### ISSUE TITLE
source contrast gives different results with fieldtrip-20180929 and fieldtrip master

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/fieldtrip#1020]
The exact same pipeline with current FT master yields this:

![image](https://user-images.githubusercontent.com/3042751/54769788-4141fd00-4c02-11e9-83ed-d1690433621c.png)

whereas 76cb0e97cb357e996903eb69e665a1f5b1231ac4 (commit picked because it was closest prior to 1-Oct-2018) yields this:

![image](https://user-images.githubusercontent.com/3042751/54770272-2ae87100-4c03-11e9-8e39-51b28251131f.png)

I don't know which of the two is "correct", but it seems they should at least be more consistent than this. (The plots of course do seem qualitatively similar.) I also don't know yet when exactly the change was introduced, but that's fairly easy to check so I'll get to that in the next couple of days.

(Data by @lindadrijvers)

**Comment by Spaak** [comment]
It appears that the issue is not in `ft_sourcegrandaverage` or `ft_sourceinterpolate`: when I do those using the current FT master, but using the individual source files computed using older FT, then the result is the same as the older one.

**Comment by schoffelen** [comment]
I'd check the default behavior of the newly introduced ft_inv, and (given that ft_sourcegrandaverage/interpolate don't have anythig to do with it) suggest to work with a single subject, rather than pushing it all the way to a figure with a group result.

**Comment by Spaak** [comment]
verified to be the same as older FT:
318e8f5ee84b714a5d2bfb168462203cb09484f6 (28 jan 2019; just before ft_inv was introduced)
83ed3e9ac9a86d1fa2f9a461bd442e324f3c1883 (30 jan 2019; first introduction of ft_inv)
cef3396f6e694e4523503816f7394d8506fe1012 (31 jan 2019; after ft_inv was added to beamformer_dics)
01281e8bdc103e72226217e16d8aae500b5eebdc (4 feb 2019)
144c461c0045fd4a55f8078263eae5f62a94e09d (6 feb 2019)

verified to be the same as newer FT:
cbc0c3159be1460d2a15c14f2420df40d853e5d3 (28 feb 2019)
a1ae21a1ebdd76434c127221be4fc66c9f916db6 (14 feb 2019)
ae0fe35c09d3ab5cbcb52cc9897904cbdfdbd582 (6 feb 2019)
f5be53c5199578162c56567f97aaa7906d702713 (6 feb 2019)

f5be53c5199578162c56567f97aaa7906d702713 is the synchronization commit
related to 144c461c0045fd4a55f8078263eae5f62a94e09d, so the actual change
in the code was made with 144c461c0045fd4a55f8078263eae5f62a94e09d

**Comment by Spaak** [comment]
I don't think I can assign issues to myself. Could @schoffelen or @robertoostenveld do so?

**Comment by schoffelen** [comment]
zoiets?

**Comment by Spaak** [comment]
```
lambda = '10%';
kappa = [];
tol = [];
invmethod = [];

x = randn(100,100) + 10;

!cd ~/repos/fieldtrip
!git checkout master
cd ~/repos/fieldtrip/inverse/private/

xinv_current = ft_inv(x, 'lambda', lambda, 'kappa', kappa, 'tolerance', tol, 'method', invmethod);

!cd ~/repos/fieldtrip
!git checkout 01281e8
cd ~/repos/fieldtrip/inverse/private/

clear ft_inv
xinv_old = ft_inv(x, 'lambda', lambda, 'kappa', kappa, 'tolerance', tol, 'method', invmethod);

isequal(xinv_current, xinv_old)
figure();
subplot(3,1,1);
imagesc(xinv_current); colorbar(); title('current');
subplot(3,1,2);
imagesc(xinv_old); colorbar(); title('old');
subplot(3,1,3);
imagesc(xinv_current-xinv_old); colorbar(); title('current - old');
```

![image](https://user-images.githubusercontent.com/3042751/54930989-8626a600-4f18-11e9-95e5-cd879a61d0e1.png)

**Comment by Spaak** [comment]
When I set `lambda` to `'0%'` then current and old are identical.

**Comment by schoffelen** [comment]
what happens with a non-zero lambda and a symmetric covariance matrix? i.e. x = randn(100); x = x*x'?

**Comment by Spaak** [comment]
![image](https://user-images.githubusercontent.com/3042751/54931552-82dfea00-4f19-11e9-8bb9-e278df3db76f.png)

**Comment by schoffelen** [comment]
nou dat gaat weer lekker.

Could you check what happens with a numeric value for lambda, not a percent?

**Comment by schoffelen** [comment]
where numeric is different from 0

**Comment by Spaak** [comment]
Same...

```
lambda = 0.1;
kappa = [];
tol = [];
invmethod = [];

x = randn(100,1);
x = x*x';
````

![image](https://user-images.githubusercontent.com/3042751/54932062-75772f80-4f1a-11e9-885c-66eba8ee65f8.png)

**Comment by schoffelen** [comment]
hmmm, the matrix you create is extremely rank deficient, so I guess that the inverse will rely on a truncation of some sort. I think that in the old style inverse, the pinv was truncated based on an implicit tolerance parameter, and the truncation was based on the singular values after diagonal loading, where currently the tolerance is computed based in the singular values before diagonal loading. Could this explain the difference?

**Comment by Spaak** [comment]
Your comment made me dig a bit further and I think now in the right place. In the new version, the svd is done on the original matrix (i.e. svd(A) [here](https://github.com/fieldtrip/fieldtrip/blob/master/inverse/private/ft_inv.m#L113)), whereas in the old version, the svd that pinv uses internally is done on the sphered (is that a word??) matrix (i.e. svd(A + lambda * eye)). So I guess we need to move the regularization up to before estimating kappa. That does mean the somewhat "neat" division there is now in ft_inv between needkappa/needlambda first, then using the parameters, is probably not sustainable.

**Comment by schoffelen** [comment]
Would it also work if lambda (if needed) is taken into account when tolerance is computed on line 176?

**Comment by schoffelen** [comment]
OK, bottom line here seems that the new ft_inv based inversion scheme is not 'worse' than before. The difference in results is therefore to be accepted. Since no resolution is to be expected anytime soon, I suggest to label this as 'wontfix', and close it.
