### ISSUE TITLE
Improve the release process and version management 

### ISSUE THREAD

**Issue by sixtyfive** [fieldtrip/fieldtrip#1026]
Would it be possible for you tag any known-good releases you make so that the Git repository could be used instead of the zip file downloads with a better conscience? :-)

**Comment by apjanke** [comment]
I read [this mailing list post](https://mailman.science.ru.nl/pipermail/fieldtrip/2010-December/003334.html) about Debian packaging and the test suite. Maybe doing some less-frequent "blessed" releases would allow time for running the complete test suite on them?

**Comment by apjanke** [comment]
BTW, it looks like the independent FieldTrip modules get tagged releases - ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/modules/ - as described in http://www.fieldtriptoolbox.org/development/module/. What's the policy for doing those?

**Comment by robertoostenveld** [comment]
Can you define a "good" release? We make changes (almost) every day, and we would not make those if we thought the changes make the code worse. So every days version is in principle better than the one of the day before ;-) 

We test a batch of approximately 600 test scripts every night, and usually have a few failing (sometimes for silly reasons). Whenever a larger number of tests fails, we typically fix it in 24 hours. So occasionally we have a "bad day" with the code, but I hardly ever get feedback on those bugs noticed by users. 

If we were to tag releases that have no known errors, we would have to hold back further updates. But nd we would have additional work. FieldTrip is not a software company, but the shared code of a (surprisingly small) group of researchers. I cannot afford to spend more time on release management than I am now doing. If you are willing to help, please let us know how you think you can contribute to tagging good releases.

PS we are working with Mathworks on https://mathworks.github.io/ci-pilot/  to get faster feedback on the results of the test batch. Furthermore, modules don't get tagged; they are simply a copy of a subset of the fieldtrip code and managed on https://github.com/fieldtrip/ (also released via ftp).

**Comment by apjanke** [comment]
> Can you define a "good" release? ... We test a batch of approximately 600 test scripts every night

Ah. I didn't realize that the test suite was running now. From that mailing list message, I thought it was disabled. That's what I'd use to define a "good" release (plus running test suites of known FieldTrip clients, if that were available).

> I cannot afford to spend more time on release management than I am now doing. If you are willing to help, please let us know how you think you can contribute to tagging good releases.

Fair enough. I've asked MathWorks to grant me access to their ci-pilot program. Maybe I can help move that along.

Is there a script to run the test suite ourselves? Just individually run all the scripts in `test/`?

**Comment by sixtyfive** [comment]
Me, I didn't even realize that you guys had a test suite. @apjanke seems to actually be following the mailing list. But yes, seconded, "has had all tests pass" would be a perfect definition of "good release".

**Comment by robertoostenveld** [comment]
@apjanke and me are working on making some improvements to the test suite, which will help us to run the relevant scripts from `fieldtrip/test` prior to a merge. In that case, we would not merge any pull request from a feature branch into the master in case it causes tests to fail. Code stability and quality is a good thing to work on, tagging specific versions is not a priority. Let me therefore close this issue.

**Comment by apjanke** [comment]
Uh, hold on one moment.

FieldTrip is effectively producing releases by rolling up "nightly" zip files and publishing them at <ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/>, with release identifiers in the form `<yyyymmdd>` embedded in the filenames.

Shouldn't we at least be tagging the git commits that were used to make these published archive files, so everyone can tell from the git history which source code version corresponds to which published nightly build version? That way when someone says e.g. "20190306" to identify which version of FieldTrip they're running, we know exactly what that means, and can easily switch local repos to that version using regular `git` commands.

Probably wouldn't be hard to do. Maybe just a couple lines of bash like `git tag "$timestamp"; git push --tags` in the nightly archive producing script.

**Comment by robertoostenveld** [comment]
I think the request was mainly about stable/good releases, not about the daily release.

Your proposal will result in 365 releases per year, corresponding to the last commit of each day (in the CET timezone). Right now people can already get the specific version of 2019-03-30 using 

    git checkout "`git rev-list master  -n 1 --first-parent --before=2019-03-31`"

But it is fine with me to tag the daily release on github. Please propose a PR to https://github.com/fieldtrip/webhook/blob/master/release-ftp.sh

**Comment by sixtyfive** [comment]
Yes, I was originally thinking about something like a tag every once in a while. But tags for the daily releases would be awesome! In that case I could ask everybody to stop downloading the zip files and instead keep FT around as a Git clone and we could all be working on the same daily release with a simple `git checkout tags/<date>`.

**Comment by robertoostenveld** [comment]
Hi @sixtyfive, following your question here, with input from @apjanke  and some internal discussions, I pondered on it for some time and figured out a way to combine it all.

Using https://github.com/fieldtrip/dashboard we run the test batch every night. Now, at the end (as the final job) of a fully successful batch, the `master` is automatically merged into the `release` branch. So the HEAD of `release` should always correspond to code without known errors, whereas the HEAD of `master` might have errors.

Using https://github.com/fieldtrip/automation and specifically with the (updated) https://github.com/fieldtrip/automation/blob/master/release-ftp.sh, whatever is the latest version will be tagged with YYYMMDD on the release branch and will be zipped and put on the ftp. The date is that of the last commit, not of the execution of the script, i.e. it will not change when re-executed but there is nothing new on the release branch. 

Yesterday evening the first combination of automated test + release ran (after quite some debugging of the dependencies). You can see the result on ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/ and on https://github.com/fieldtrip/fieldtrip/releases with version "20190611". 

I still have to document it better. And see (over time) whether it runs robustly.

**Comment by sixtyfive** [comment]
Oh sweet, and thank you so much for following up, Robert! I'll be away from home for a couple weeks more and then play around with this. For projects with more than one person contributing and where differences in FT versions might be a concern, I think the tags that are now here will be most helpful. Working on your own, the `release` branch will be real nice.

**Comment by apjanke** [comment]
This approach sounds great. Thanks!

**Comment by robertoostenveld** [comment]
I have added some documentation to the website and will close this for now.
