### ISSUE TITLE
ft_scalpcurrentdensity is not dealing with units correctly

### ISSUE THREAD

**Issue by ftadel** [fieldtrip/fieldtrip#1043]
When using `cfg.elec.unit='m'` and data units in Volts:
- the scaling of the output values is wrong for 'finite' and 'spline' options
https://github.com/fieldtrip/fieldtrip/blob/master/ft_scalpcurrentdensity.m#L255
- it selects all the electrodes as neighbors with option 'hjorth'

**Comment by schoffelen** [comment]
Can you be a  bit more specific please, with preferably some code and data to demonstrate the problem, and even better with a suggested solution? Thans.

**Comment by robertoostenveld** [comment]
agreed that something is not as expected wrt units... In general we aim to get correct values if people specify and use SI units throughout, but that only has been checked (to some extent) with MEG and source estimation, not here.

In this case the units have to be consistent between the elec (which is either from cfg.elec or from data.elec), the timeseries itself, and the cfg.conductivity. 

I propose that we aim at this function returning correct values in case everything is in SI, and otherwise it returns arbitrary units. Agreed?

**Comment by robertoostenveld** [comment]
The issue you report with hjorth seems to me due to you using ft_prepare_neighbours incorrectly.

**Comment by ftadel** [comment]
> In this case the units have to be consistent between the elec (which is either from cfg.elec or from data.elec), the timeseries itself, and the cfg.conductivity.

Here is what I pass in input:
```
cfg=
          method: 'finite'
    conductivity: 0.3300
          lambda: 1.0000e-05
           order: 4
          degree: 9

ftData = 
    dimord: 'chan_time'
     trial: {[29×206 double]}
      time: {[1×206 double]}
     label: {29×1 cell}
      elec: [1×1 struct]

ftData.elec =
      label: {1×29 cell}
       unit: 'm'
    chanpos: [29×3 double]
    elecpos: [29×3 double]
        tra: [29×29 double]

% Data amplitude in the range of 30uV (units =VOLTS).
max(abs(ftData.trial{1}(:))) 
= 2.9218e-05

% data.elec in METERS: 
ftData.elec.chanpos(1,:)
=  0.0996    0.0251    0.0210
ftData.elec.elecpos(1,:)
= 0.0996    0.0251    0.0210

% The output I get in the range of 8000 uV (assuming that units are VOLTS):
scdData = ft_scalpcurrentdensity(cfg, ftData);
max(abs(scdData.trial{1}(:)))
= 0.0087
```

Should I change something to the units of the conductivity?
Otherwise, how can we get consistent units in output? 


> The issue you report with hjorth seems to me due to you using ft_prepare_neighbours incorrectly.

Indeed... sorry, I got mixed up with all the units conversions I tried.

**Comment by ftadel** [comment]
Bonus question:
What method would you recommend using for automated processes?
and/or: What method do you think is used the most?

**Comment by schoffelen** [comment]
why do you think the units are off to begin with? A surface Laplacian is the spatial second derivative, so it's potential / distance squared.

**Comment by schoffelen** [comment]
note that if you do a cfg.method = 'finite', it's not using lambda nor conductivity

**Comment by robertoostenveld** [comment]
Parts of this code date back to 2004, i.e. FieldTrip "0.1 alpha" or so, or just some scraps from my PhD work.   

It would be good to make a test script, e.g. on basis of a simulated dipole, and then estimate the scalpcurrentdensity using the different methods and update the code to ensure that the different methods return values in consistent (and well-defined) units. Until then I would assume that the output is "arbitrary units" in most cases.  

Re bonus: on noisy (i.e. realistic) data I would personally use `spline` with some nice lambda to smooth the noise out, but have no idea what others are using. It would not surprise me that others would use the method that has the least cognitive load for them, hence the fewest cfg options, which would be `finite`. That is good if you want to reduce mental stress, not for the best results per se.

**Comment by ftadel** [comment]
> why do you think the units are off to begin with? A surface Laplacian is the spatial second derivative, so it's potential / distance squared.

I'm sorry, I don't have any notion of the amplitudes I'm supposed to get for these values.
You validate that the output of this call is expected to be: 
0.0087 V/m2 ?

My initial concern came from the fact that the range of values obtained between the options 'finite' and 'hjorth' do not match. 
With the latter, in the exact same configuration, I obtain:
```
max(abs(scdData .trial{1}(:)))
= 1.6040e-05
```

Is a factor 600 between the outputs of these two methods expected? Are these different units?

I am sorry if these are stupid questions, I think this is confusing and that the documentation of this function could need some more details regarding the input and outputs.

**Comment by robertoostenveld** [comment]
the output is arbitrary values and the scale depends on the options you specify and the data you put in. Feel free to add that to the help and send a PR.

**Comment by ftadel** [comment]
>Re bonus: on noisy (i.e. realistic) data I would personally use spline with some nice lambda to smooth the noise out, but have no idea what others are using. It would not surprise me that others would use the method that has the least cognitive load for them, hence the fewest cfg options, which would be finite. That is good if you want to reduce mental stress, not for the best results per se.

Thanks!
Any additional tip on what "some nice lambda" values could be?

**Comment by ftadel** [comment]
> the output is arbitrary values and the scale depends on the options you specify and the data you put in
Ok! it makes it a lot easier not to have to try to make sense out of these output units :)

**Comment by robertoostenveld** [comment]
I guess this has been resolved, except for the regularization. For that I would use a cross-validation approach to figure out a value that is robust but not overly smooth.
