### ISSUE TITLE
ft_test fails because test/ is not on the path by default

### ISSUE THREAD

**Issue by apjanke** [fieldtrip/fieldtrip#1047]
When I try to do `ft_test` for an individual test after configuring FieldTrip with `ft_defaults`, it fails, because `dccnpath` can't be found. It's in `test/`, which I have to add manually.

```
>> addpath ~/local/repos/fieldtrip
>> ft_defaults
>> ft_test run test_bug3192
Undefined function or variable 'dccnpath'.
Error in ft_test_run (line 56)
  hasdccnpath = exist(dccnpath('/home/common/matlab/fieldtrip/data/'), 'dir');
Error in ft_test (line 100)
    ft_test_run(varargin{:}); 
>> addpath ~/local/repos/fieldtrip/test
>> ft_test run test_bug3192
considering 1 test functions for execution
  0 scripts are excluded due to the dependencies
  1 scripts are excluded due to loading files from the DCCN path
  0 scripts are excluded due to the requirements for memory
  0 scripts are excluded due to the requirements for walltime 
executing 0 test scripts
>> which dccnpath
/Users/janke/local/repos/fieldtrip/test/dccnpath.m
>> 
```

Should `test/` be pulled in to the path by default, or when you run `ft_test`? I can understand not wanting to have all those test functions on the path by default. I see [here](https://github.com/fieldtrip/fieldtrip/blob/c0b8e5cb57ced383af130cdb9daef6a224046e3c/utilities/private/ft_test_run.m#L81) that `ft_test_run` adds `test/` to the path, but only when running all the tests.

Or maybe `dccnpath` should just be moved to `utilities/`, where `ft_test` lives, and is on the path by default?

**Comment by robertoostenveld** [comment]
There are a few more in fieldtrip/test that I suspect must be on the path when the test executes, so only moving dccnpath will not suffice.

```
constructalloptions.m
dccnpath.m
ref_datasets.m
resources.m
trialfun_affcog.m
trialfun_stimon.m
trialfun_stimon_samples.m
```

Cleaning up the test directories would be good, there are now also some tests elsewhere (plotting, spike, and some in external but those should stay there).

To start I propose to move the tests from plotting and spike to fieldtrip/test, and to use ft_hastoolbox('test', 1) inside the ft_test function.

**Comment by robertoostenveld** [comment]
oops, I thought I was working on a branch for which I could make a PR. Now I pushed it directly to master.

```
roboos@mentat001> git push upstream master
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Counting objects: 44, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (30/30), done.
Writing objects: 100% (30/30), 5.15 KiB | 0 bytes/s, done.
Total 30 (delta 23), reused 0 (delta 0)
remote: Resolving deltas: 100% (23/23), completed with 13 local objects.
To git@github.com:fieldtrip/fieldtrip.git
   059ebc4..3a7e8ec  master -> master
```

**Comment by apjanke** [comment]
Working for me now. 

```
>> addpath ~/local/repos/fieldtrip
>> ft_defaults
>> ft_test run test_bug3192
considering 1 test scripts
  0 scripts are excluded due to the dependencies
  1 scripts are excluded due to loading files from the DCCN path
  0 scripts are excluded due to the requirements for memory
[...]
```

Thanks.
