### ISSUE TITLE
ft_statistics_mvpa should not use true/false in cfg.mvpa.feedback

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1052]
the help specifies
```
cfg.mvpa.feedback         = 'yes' or 'no', whether or not to print feedback on the console (default 'yes')
```
which is consistent with FT convention, but in the code the cfg option gets converted to a boolean. Although it works (i.e. not a bug per see), it is not ideal since the output data stricture will have the boolean in output.cfg.

Better would be to only use `istrue` at the moment where it is really needed. However, I could (upon quick glance) not find where that feedback is actually dealt with...

**Comment by robertoostenveld** [comment]
I tried to assign this to @treder, but that does not work. Probably because he is not in our fieldtrip "organization" ...

**Comment by schoffelen** [comment]
That's OK. I'll change it.

**Comment by schoffelen** [comment]
Ah, I see, I think that the low-level code expects it to be a boolean... So not as straightforward to address as I thought initially.

**Comment by schoffelen** [comment]
As a clean alternative, I can only think of making a temporary copy of cfg.mvpa (e.g. as cfgmvpa) and then booleanize the cfgmvpa.feedback.

**Comment by schoffelen** [comment]
OK, fixed it.

**Comment by treder** [comment]
in MVPA-Light there's a function mv_check_inputs that's called by all major functions to perform sanity checks on the parameters, I've implemented the translation from feedback=yes/no into boolean there. So no need to deal with it any more in fieldtrip ... I've removed the corresponding code in my open pull request
