### ISSUE TITLE
Feature request: superlets

### ISSUE THREAD

**Issue by DanBenHa** [fieldtrip/fieldtrip#1055]
Hi,

I recently came upon this manuscript: https://doi.org/10.1101/583732 

Are there plans to implement this superlet decomposition in FieldTrip?

Best wishes,
Daniel

**Comment by robertoostenveld** [comment]
We have no plans for this here in Nijmegen, but we do welcome contributions from your side. 
See http://www.fieldtriptoolbox.org/contribute/#contribute-code.
