### ISSUE TITLE
Dumb question re: ft_timelockstatistics permutation test

### ISSUE THREAD

**Issue by psrdwy** [fieldtrip/fieldtrip#1087]
I was wondering if I could bother you with a dumb clarification question about the correct interpretation of the outputs of Fieldtrip’s ft_timelockstatistics function?

Online, it says:

“We use cfg.alpha to control the false alarm rate of the permutation test (the probability of falsely rejecting the null hypothesis). The value of cfg.alpha determines the critical values with which we must compare the test statistic (i.e., the maximum and the minimum cluster-level statistic). Note that if you want to run a two-sided test, you have to split the critical alpha value by setting cfg.correcttail = ‘alpha’; i.e. this sets cfg.alpha = 0.025, corresponding to a false alarm rate of 0.05 in a two-sided test. The field cfg.alpha is not crucial. This is because the output of ft_timelockstatistics (see further) contains a p-value for every cluster (calculated under the permutation distribution of the maximum/minimum cluster-level statistic). Instead of the critical values, we can also use these p-values to determine the significance of the clusters.”

I interpreted this to mean that I should double all the p-values I get in the final output, since I am running two-tailed tests.  E.g., if I specify that I want a two-tailed test in cfg.tail and if I then get an output saying:

>> stat.posclusters
ans = 
  struct with fields:
           prob: 0.0188
    clusterstat: 160.9688
         stddev: 0.0014
        cirange: 0.0027

Then I interpret it to mean that the actual two-tailed p-value is 0.0376, not 0.0188.  However, I’m having second thoughts about this, and wondering if I have this right.

I have to submit the slides soon for a talk I’m giving where we analyze data using this function, so if you have a chance to confirm whether I am interpreting this correctly or not, that would be super-appreciated!  Thanks so much.

**Comment by robertoostenveld** [comment]
Dear @psrdwy, this is not the place to ask for support on data analysis. Please ask on the http://www.fieldtriptoolbox.org/discussion_list/ instead.
