### ISSUE TITLE
 ft_freqstatistics for MEG time-frequency data

### ISSUE THREAD

**Issue by ddys0506** [fieldtrip/fieldtrip#1094]
Hello,
I'm using running the ft_freqstatistics in Brainstorm from Matlab to test if the time-frequency of two conditions differed. But I got the following error in function randomseed.m. 
![image](https://user-images.githubusercontent.com/44824787/56788359-d358a900-6831-11e9-8428-9c68953c646d.png)

Do you have any idea how can I solve this ?

Thanks in advance!

**Comment by robertoostenveld** [comment]
In general I would say: use the MATLAB debugger. E.g. `dbstup if error` and then use your MATLAB editor to figure out what is wrong.

In this case the error is in fieldtrip/utilities/private/randomseed.m at line 55
```
  if ft_platform_supports('rng')
    % Recent MATLAB versions
    s = rng;
    state = s.State;
 ```

Somehow on your MATLAB version `rng` does not return State. Are you using a compiled version of BrainStorm? If not, can you do `which png`? For me it returns

/Applications/MATLAB_R2019a.app/toolbox/matlab/randfun/rng.m

And please also report which MATLAB version you are using (e.g. do `ver` on the command line).

**Comment by ddys0506** [comment]
Thank you for your prompt reply.
I checked the path to rng.m and it returns to another toolbox (mvgc for Granger Causality). I renamed it so that the rng.m in matlab/randfun/ worked properly.
