### ISSUE TITLE
Bug in topoplot_common.m

### ISSUE THREAD

**Issue by dmatthes1982** [fieldtrip/fieldtrip#1095]
% Plot colorbar - line 751-759
if isfield(cfg, 'colorbar')
  if strcmp(cfg.colorbar, 'yes')
    c = colorbar;
  elseif ~strcmp(cfg.colorbar, 'no')
    c = colorbar('location', cfg.colorbar);
  end
  ylabel(c, cfg.colorbartext);
end

If cfg.colorbar == 'no', c will not be set and line 758 is throwing an error.

**Comment by robertoostenveld** [comment]
Sorry, I had already fixed it this morning with https://github.com/fieldtrip/fieldtrip/commit/22d8c9b8647123139c3a3359346fcd1009d3113f but forgot to push it to the release.

**Comment by robertoostenveld** [comment]
@johalgermissen I think this also solves the problem you mentioned

**Comment by johalgermissen** [comment]
Yes this was exactly it. Started writing in an open tab, but forgot to finish. Thanks for solving this!
