### ISSUE TITLE
An error of 'ns_SetLibrary' using 'mexprog'

### ISSUE THREAD

**Issue by Gery111** [fieldtrip/fieldtrip#1102]
I was using `ft_read_spike` to read Blackrock system data, I followed this code:
`spike = ft_read_spike(filename, 'spikeformat', 'neuroshare');`
and found an error that root in `ns_SetLibrary`. 
That function only use one function of 'mexprog', there are no such function but an file of 'mexprog.dll'. 
How could I use this file?
Thanks

**Comment by schoffelen** [comment]
Could you ask your question on the fieldtrip discussion list please? When doing so, please be a bit more specific. Also, you should think about whether your data is actually in the 'neuroshare' format, because as far as I know Blackrock is different from neuroshare.
