### ISSUE TITLE
Issue importing Nicolet Nervus .e file 

### ISSUE THREAD

**Issue by KASNor** [fieldtrip/fieldtrip#1105]
Hi 

Some Nicolet .e files results in an error code during import. 

Error code: 
Unable to perform assignment because the size of the left side is 324900-by-1 and the size of the right side is 295212-by-1.

Error in read_nervus_data (line 148)
        out(curIdx : end,i) = fread(h, length(out)-curIdx + 1, 'int16') * mult;

Error in ft_read_data (line 1020)
      datseg = read_nervus_data(hdr.orig,segment, range, chanindx);

Error in ft_preprocessing (line 582)
      dat = ft_read_data(cfg.datafile, 'header', hdr, 'begsample', begsample, 'endsample', endsample, 'chanindx', rawindx,
      'checkboundary', strcmp(cfg.continuous, 'no'), 'dataformat', cfg.dataformat);
 
I know Nicolet produce files that carry channels with different sampling rates. Might that be the issue ? If you have encountered this issue could you please send code that fixes the problem?

**Comment by schoffelen** [comment]
If this code were available to us, it would have been implemented in fieldtrip...
I suggest to do a bit more debugging yourself, and check the code in the github repository which is mentioned in the documentation of read_nervus_data.

**Comment by schoffelen** [comment]
Then, you can perhaps make a suggestion of how to adjust the current code to make it more robust.

**Comment by KASNor** [comment]
Unfortunately, the file format thing is a bit of a hazzle for me. The vendors often keep their proprietary file format details closed for public.

Will have someone look into it and if we figure out a solution, then I’ll email you the possible corrections.

Kind regards
Knut

**Comment by robertoostenveld** [comment]
Since you are (it seems) a customer at Nicolet - and we are not - you are in the position to ask them to provide support in FieldTrip, EEGLAB, SPM and BrainStorm (all sharing MATLAB code). You may want to inform them that they would not be the first to support their customers, BrainVision, Philips/EGI, BESA and Ricoh have all actively been engaged with open source developers to ensure that their customers can access their data in MATLAB.

**Comment by janbrogger** [comment]
I'm working on what seems a similar issue now. You could reopen the issue and assign it to me.

**Comment by schoffelen** [comment]
Thanks Jan, that would be great!

**Comment by janbrogger** [comment]
This issue might be solved by an update to the Nicolet code that I just submitted here: 
https://github.com/robertoostenveld/fieldtrip/pull/8

I got the same error that you listed here on some of my clinical EEG files (from ICU) and this fixes it.

Code is here:
https://github.com/janbrogger/fieldtrip/tree/issue302-nervusB

@KASNor  can you re-run and see if this code fixes the problem?

**Comment by KASNor** [comment]
Hi,

I’m working with a database acquired pre-2012 and when the .e files are pruned/segmented in the Nicolet reader and then saved as .e files, the previous functionality successfully reads every file.

I tried the new scripts and it produced an error and statement recognizing the files being pre-2012.

Otherwise, I might be able to get a hold of the same code used in the Nicolet reader software in C.

Kindly
Knut

**Comment by schoffelen** [comment]
Thanks @janbrogger Jan, is there a specific reason why you PR'ed this to robertoostenveld/fieldtrip, rather than to fieldtrip/fieldtrip. If not, please PR it in the fieldtrip/fieldtrip repo (master branch), we have a set of checks and balances in place before it ends up in the release branch.

**Comment by janbrogger** [comment]
@schoffelen I pushed this to robertoostenveld/fieldtrip because that's what @robertoostenveld did the last time . I thought it was standard procedure. I'll PR it to fieldtrip/fieldtrip as well.

**Comment by janbrogger** [comment]
@KASNor I just released some old code that uses Nicolet DLLs to read Nicolet data to EEGLAB. If you have access to the Nicolet DLLs, this might work: https://github.com/janbrogger/NicoletEegImportOld

**Comment by schoffelen** [comment]
@janbrogger, thanks for the clarification. Well, as far as there is any standard procedure, we typically ask contributors to PR to fieldtrip/fieldtrip. Actually, we also try and force ourselves to do so, i.e. first push to our local fork, and only then PR into fieldtrip/fieldtrip. Laziness occasionally causes @robertoostenveld and me to directly push (without PR) into fieldtrip/fieldtrip. So you may have stumbled on a rare occasion that Robert actually also tried to follow protocol :)

**Comment by schoffelen** [comment]
I believe that this can be closed. Feel free to reopen, if I am wrong
