### ISSUE TITLE
Mex file issue when attempting to compute a headmodel on macOS Mojave (version 10.14.4)

### ISSUE THREAD

**Issue by grmanxchange** [fieldtrip/fieldtrip#1107]
Hi,

when trying to compute a headmodel as follows:

cfg        = [];
cfg.method = 'singleshell';
hdm        = ft_prepare_headmodel(cfg, segmentedmri);

I get the following error messages in Matlab (version 18b):

Invalid MEX-file '/Users/darinka/Desktop/workshop-oxford/fieldtrip/external/spm8/spm_conv_vol.mexmaci64': dlopen(/Users/darinka/Desktop/workshop-oxford/fieldtrip/external/spm8/spm_conv_vol.mexmaci64, 6): Library not loaded: @loader_path/libmex.dylib
  Referenced from: /Users/darinka/Desktop/workshop-oxford/fieldtrip/external/spm8/spm_conv_vol.mexmaci64
  Reason: image not found.

Error in spm_smooth>smooth1 (line 105)
spm_conv_vol(P,Q,x,y,z,-[i,j,k]);

Error in spm_smooth (line 40)
    smooth1(P,Q,s,dtype);

Error in volumesmooth (line 18)
spm_smooth(output, output, fwhm);

Error in ft_datatype_segmentation (line 230)
          brain = volumesmooth(brain,    smooth,    'brain');

Error in prepare_mesh_segmentation (line 95)
    mri = ft_datatype_segmentation(mri, 'segmentationstyle', 'probabilistic', 'hasbrain', 'yes');

Error in ft_prepare_mesh (line 159)
    bnd = prepare_mesh_segmentation(cfg, mri);

Error in ft_prepare_headmodel (line 357)
            geometry = ft_prepare_mesh(tmpcfg, data);

Error in HandsOn_Three (line 24)
hdm        = ft_prepare_headmodel(cfg, segmentedmri);

Eelke mentioned that this might be specific to the new release of this macOS version, so it might affect other users as well. It would be great if you could look into this. 

Many thanks,
Darinka

**Comment by schoffelen** [comment]
You may want to recompile the mex files on your end.

**Comment by robertoostenveld** [comment]
Or in this case, see http://www.fieldtriptoolbox.org/faq/matlab_complains_about_a_missing_or_invalid_mex_file_what_should_i_do/#spm8-mexmaci64-mex-files-fail-on-matlab-2017-and-up

The macOS solution I use is to specify cfg.spmversion=spm12

**Comment by robertoostenveld** [comment]
we probably should change the default from spm8 (now >10 years old) to spm12.

**Comment by grmanxchange** [comment]
Ah, thanks. Specifying the spmversion does work.

**Comment by IngaKarin** [comment]
I'm facing a similar problem calling ft_write_mri. I get this error: 

Invalid MEX-file '/Users/<user>/Desktop/Diplomarbeit/Matlab/fieldtrip-20200227/external/spm8/spm_existfile.mexmaci64': dlopen(/Users/<user>/Desktop/Diplomarbeit/Matlab/fieldtrip-20200227/external/spm8/spm_existfile.mexmaci64, 6): Library not loaded: @loader_path/libmex.dylib
  Referenced from: /Users/<user>/Desktop/Diplomarbeit/Matlab/fieldtrip-20200227/external/spm8/spm_existfile.mexmaci64
  Reason: image not found.

I use Matlab 2018a on a mac os Catalina 10.15.4. I tried the cfg.spmversion = 'spm12' directly before the ft_write_mri. Was this wrong? It did not work..

**Comment by robertoostenveld** [comment]
the cfg option is not passed to `ft_write_mri`, only to the high-level FT functions (the ones with a cfg as first input). If you start a new MATLAB session that does not have spm on the path yet, you can use `ft_hastoolbox('spm12',1)` to add it to your path.  On top of that, please continue using `cfg.spmversion='spm12'`

**Comment by schoffelen** [comment]
ft_write_mri is a low-level function, that does not have the 'intelligence' to automatically deal with spm versions. Only higher level functions can do that (the functions that are in the main fieldtrip folder).

**Comment by schoffelen** [comment]
OK, simultaneous typing. Not efficient. Over and out
