### ISSUE TITLE
Status and plans wrt SLAP interpolation

### ISSUE THREAD

**Issue by sixtyfive** [fieldtrip/fieldtrip#1109]
Given [the current status](https://github.com/fieldtrip/fieldtrip/blob/master/ft_channelrepair.m#L325-L327) of [the SLAP implementation](https://github.com/fieldtrip/fieldtrip/blob/master/ft_channelrepair.m#L300-L372), I'd like to ask what the project's plans are with regard to it? Is it something that was partially implemented out of curiosity and will likely remain that way or more something that you'd like to be able to fully support at some point?

**Comment by jadref** [comment]
Hi, Yes the orginal code was written and submitted my me.  We've been using it the dondersBCI lab for the last few years without issues so have no plans to update.  Checking the code the core functionn `splint.m` and 'sphericalSplineInterpolate.m` do (mathematically) the same thing, so it would be straightforward to unify and remove one of them if someone wanted to do that.

**Comment by sixtyfive** [comment]
Hi @jadref, hi @robertoostenveld, thanks for both of your answers! I guess for me that basically means that it's good to use either one of them. That warning message felt more threatening than it would have had to, that's all I guess.
