### ISSUE TITLE
timewindow specification does not work for noise-covariance estimation in ft_timelockanalysis 

### ISSUE THREAD

**Issue by akochari** [fieldtrip/fieldtrip#1115]
I noticed what appears to be an bug when computing noise-covariance estimation using ft_timelockanalysis on MEG data. Specifically, the time-window for noise-covariance estimation that I specify does not get picked up, but instead the whole epoch is used as the time-window which is the default.

Here is the code I am using:
```
cfg = [];
cfg.covariance = 'yes';
cfg.covariancewindow = [-0.1 0];
cfg.removemean = 'no';
avg_for_nc = ft_timelockanalysis(cfg, data_nouns_filtered);
```

When looking at the cfg field of the output of this function - avg_for_nc.cfg - I see that covariancewindow = 'all' instead of [-0.1,0]. So it actually used the whole time-window instead of the one I specified.

This is an issue with the most recent version - fieldtrip-20190419 and at least also one version from February - fieldtrip-20190218.
We looked in one older version and there it worked as expected - fieldtrip-20170630. With this version, the avg_for_nc.cfg does have [-0.1 0] as the covariancewindow and also the covariance matrix is actually different from the one that we get with the most recent version.

So the problem (if we are indeed correct that it is a bug) seems to have appeared somewhere between 20170630 and 20190218.

**Comment by schoffelen** [comment]
This is not the best place to post this. Better would be the fieldtrip discussion list, or bugzilla.fieldtriptoolbox.org.

Also, I suggest to use the MATLAB debugger to step through the code line-by-line to find out where the cfg.covariancewindow gets overwritten, and to check whether the output.cfg.covariancewindow matches the window that was actually used for the covariance computation.

Also, you can investigate the history of ft_timelockanalysis on github to find the commit which introduced this (as of yet to be confirmed) inappropriate function behaviour, which will give you a handle to  suggest a fix for this.

**Comment by schoffelen** [comment]
Note that I just pushed a fix for a typo in ft_timelockanalysis, so please use the latest version from github for testing
