### ISSUE TITLE
ft_plot_layout: How to highlight some electrodes?

### ISSUE THREAD

**Issue by sixtyfive** [fieldtrip/fieldtrip#1116]
Neither `ft_prepare_layout` now `ft_plot_layout` seem to provide a way to visually highlight one or some of the channels, like for example `ft_topoplotER` does, i.e., make them a different color or so. I've read both functions' sources, but unfortunately, my Matlab-fu is not good enough to figure out how to add such a feature. First, [ft_plot_layout.m#L61](https://github.com/fieldtrip/fieldtrip/blob/master/plotting/ft_plot_layout.m#L61) stood out and when I Ctrl-F'd for that I ended up at [L118-L124](https://github.com/fieldtrip/fieldtrip/blob/master/plotting/ft_plot_layout.m#L118-L124). My hope was to be able to add something that would work similarly to `chanindx`, perhaps called `highlightindx` and then along with that, `highlightcolor`. Unfortunately I don't understand what's going on there. Could somebody explain a little and nudge me in the right direction?

**Comment by schoffelen** [comment]
The highlighting in ft_topoplotER and its colleagues is done by repeated calls to ft_plot_layout (with different inputs), in private/topoplot_common.m I suggest to check there for examples how you can repeatedly call ft_plot_layout to serve your purpose. I'd rather not adjust ft_plot_layout, to keep the functionality relatively lean.

**Comment by schoffelen** [comment]
Sorry ,didn't mean to close (yet..).

**Comment by schoffelen** [comment]
anything to follow up here @sixtyfive? Otherwise, please close

**Comment by sixtyfive** [comment]
Sorry, I've been gone for a while and without any Matlab machine close by. Anyways, I'm having trouble parsing the pragmatics of your first sentence, which contains a lot of interrelated information. Did you mean to say that (a) there is a suggestion inside of `private/topoplot_common.m` as to where to continue looking, or that (b) `private/topoplot_common.m` itself is the place where I should be looking? I grep'd through that file looking for uses of either one of `ft_topoplotER` or `ft_plot_layout` and couldn't find any. Can you clarify?

**Comment by schoffelen** [comment]
apologies for the confusion.

topoplot_common is the common underlying function that is called by ft_topoplotER/TFR/IC
the layout handling, including highlighting of channels is achieved in this function by the low-level function ft_plot_lay (sorry, I forgot about the existence of ft_plot_layout (high-level function in fieldtrip-main), and ft_plot_lay, low-level function in fieldtrip/plotting).

**Comment by sixtyfive** [comment]
Thanks, now it was easier to follow. FWIW, my current code is:

```matlab
function plot_econfigs_test(obj)    
  cfg = [];
  cfg.channel = 'all';
  cfg.headmodel = obj.headmodel;
  cfg.elec = obj.econfig.origin;
  cfg.rotate = 90;
  cfg.center = 'yes';
  cfg.skipscale = 'yes';
  cfg.skipcomnt = 'yes';
  cfg.style = 'straight_imsat'; % https://anneurai.net/2016/11/08/rasterised-topoplots-in-fieldtrip/
  
  ectype = cfg.elec.type;
  echans = num2str(length(cfg.elec.label));
  layout = ft_prepare_layout(cfg);
  
  ft_plot_layout(layout); cfg
end
```

Changing the second-to-last line to `ft_plot_lay(layout)` works just fine and results in the exact same image as when using `ft_plot_layout`. I noticed a warning caused by using `ft_plot_lay`, though. Apparently [ft_plot_lay.m](https://github.com/fieldtrip/fieldtrip/blob/master/plotting/ft_plot_lay.m) has been changed into a compatibility layer sometime in March. I can't find out what exactly `feval` returns (it doesn't seem to be a FT function, at least grepping for it yields nothing), but I'll assume it's now simply calling `ft_plot_layout`. 

In any case, `ft_plot_layout` doesn't call `ft_plot_lay` anywhere, so, well, if this were Monopoly, then "Go Back to Start, Do Not Pass Go".

Am I correct in thinking that [#L160 and #L161](https://github.com/fieldtrip/fieldtrip/blob/master/plotting/ft_plot_layout.m#L160-L161) determine the location of where to put a non-broken electrode in the image? So if I figure out how it does that, then I could use similar code to manually place my broken electrode _after_ the call to `ft_plot_layout`?

**Comment by schoffelen** [comment]
Hehe, the plot thickens... It seems that Robert renamed ft_plot_lay into ft_plot_layout, and wrote the compatibility wrapper (with the feval) in order to allow existing code that calls ft_plot_lay (instead of the now preferred ft_plot_layout) not to break.

feval is a matlab function that executes the function with the name (in the first argument), i.e. it just calls ft_plot_layout. I guess this is Robert's over-engineered way to write a generic compatibility wrapper.

Sooo, it seems that in the current codebase, all calls to ft_plot_lay need to be replaced with a call to ft_plot_layout. If you feel adventurous, feel free :).

Also, w.r.t. your question in lines 160/161; this seems just a scaling operation to me. The function is not so clever as to guess the location of missing electrodes.

**Comment by sixtyfive** [comment]
> Sooo, it seems that in the current codebase, all calls to ft_plot_lay need to be replaced with a call to ft_plot_layout. If you feel adventurous, feel free :).

That's what I've always been doing. And it produces a nice plot with all the electrodes (good as well as bad) in it. What I can't figure out is how to make the rectangle(s) with the BAD electrodes only stand out somehow.

Let me photoshop something together to explain.

So here's what the code from yesterday's comment produces:

![image](https://user-images.githubusercontent.com/192860/61186834-41ab4b80-a66a-11e9-909c-5f12c68d838a.png)

And here's what I want it to look like (let's stay with the example of `{'P4'}` being the set of bad channels):

![image](https://user-images.githubusercontent.com/192860/61186874-baaaa300-a66a-11e9-8203-56f5cb155c87.png)

Quite visible it already knows all of the electrodes' locations. It must be possible to achieve this somehow...

**Comment by schoffelen** [comment]
Top! Glad that you sorted it out. Keep up the good work
