### ISSUE TITLE
openmeeg_meg_leadfield_example.m

### ISSUE THREAD

**Issue by tmedani** [fieldtrip/fieldtrip#1122]
Hi, 
I'm trying to test the MEG leadfiled with the bem (openmeeg), using the  
openmeeg_meg_leadfield_example.m
however, it seems that this example is obsolete, since the function 
FT_PREPARE_BEMMODEL is deprecated. 

Could you please update this example with the new functions. 

Thanks 

Best regards 
Takfarinas

**Comment by schoffelen** [comment]
The idea behind the project is that you can make changes yourselves. We don't have time in the core developers team to keep track of backward incompatibilities. Please take your own responsibility here, and suggest a fix. The functionality of ft_prepare_bemmodel has been taken over by ft_prepare_headmodel, and ft_headmodel_openmeeg. Specifically, code in the 'external' folders are not developed by the core fieldtrip developers, so we take only limited responsiblity in keeping that part of the code entirely up-to-date. 

We are looking forward to a pull request on github.
