### ISSUE TITLE
ft_freqbaseline.m: baselinetype 'zscore' not properly implemented

### ISSUE THREAD

**Issue by simonruch** [fieldtrip/fieldtrip#1124]
In the description of the function ft_freqbaseline, 'zscore' is listed as possible baselinetype. However, 'zscore' is not listed as valid option in the lines that check the validity of the input. Using 'zscore' as baselinetype therefore throws an error ('the value of the option "baselinetype" is invalid').

Furthermore: 'vssum' is properly implemented (in validity check) but is not listed as valid option in the description of the function.

**Comment by schoffelen** [comment]
We are looking forward to a suggested fix as a pull request. 
Thank you.

**Comment by schoffelen** [comment]
This is followed up in PR #1125
