### ISSUE TITLE
Load already preprocessed data to fieldtrip functions

### ISSUE THREAD

**Issue by DanielStrahnen** [fieldtrip/fieldtrip#1129]
Is it possible to use the fieldtrip functions for already preprocessed data that is organized in a .mat file. The data is stored in a matrix organized as follows: Channels x samples

**Comment by schoffelen** [comment]
Dear Daniel,

Please ask this as a question on our e-mail discussion list. You can sign up following the link in the below:

http://www.fieldtriptoolbox.org/discussion_list/
