### ISSUE TITLE
add support for dipoli on windows 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1130]
it would be convenient for windows users to have `dipoli.exe` for windows. The code compiles on windows and Thom recently gave me a copy of it. 

Having `dipoli.exe` by itself is not sufficient, since the glue code between the executable and MATLAB currently involves a BASH script. For Windows we probably would need a PowerShell script, or possibly an old-fashioned DOS `.bat` file.

**Comment by robertoostenveld** [comment]
Note that this is only a starting point, hopefully a windows user can pick it up from here and implement the glue in a `.bat` file between MATLAB and dipoli.exe

**Comment by schoffelen** [comment]
I tried out a few things on a PC in the instruction room. It shouldn't be too difficult, and the issue was raised by a user on the discussion list.
