### ISSUE TITLE
Shouldn't ft_rejectcomponent always report the number of *components* kept?

### ISSUE THREAD

**Issue by ethanbb** [fieldtrip/fieldtrip#1132]
`ft_rejectcomponent` has the lines:

```
% set the rejected component amplitudes to zero
ft_info('removing %d components\n', length(reject));
if ~hasdata
  ft_info('keeping %d components\n',  ncomps-length(reject));
else
  ft_info('keeping %d components\n',  nchans-length(reject));
end
```

This means that if your total number of components is less than the number of channels in your data (e.g. if you're ignoring some channels in component analysis), the script will still report that you are "rejecting m compoents; keeping n components," where n + m = #chans. This had me worried for a minute that the function was doing something wrong, like somehow generating more components than were present in the `comp` structure. Shouldn't it always report "keeping ncomps-length(reject) components"?

**Comment by schoffelen** [comment]
Hi Ethan, sorry for the sluggish reply.
I am not sure whether you are correct in this.
That is, if MATLAB ends up in the else part of the statement, this means that the output data is constructed from the input data, by means of the projection (eye(nchan)-comp.topo(:,reject)*comp.unmixing(reject,:)). Therefore (under the assumption that the number of channels in the input data indeed correspond with the first dimension of comp.topo, and the data to be of full rank) the output data will have a rank of nchan-numel(reject).
Or not?

**Comment by ethanbb** [comment]
Hi @schoffelen,

Thanks for your response and you make an interesting point. I believe there are multiple answers depending on your assumptions about what decomposing the data into fewer components than channels is doing.

I was assuming that the input data would have a smaller rank than the # of channels, i.e. there is redundancy in the channel data, and the number of components extracted should reflect the supposed actual dimensionality of the variance. So then you would consider e.g. a 64-channel input to have maybe 20 "real" components, and if you are rejecting 1 then you are still only keeping the other 19 components among all 64 channels. This probably makes more sense in a setup where channels are spatially clustered rather than distributed, like in the LFP recordings I am working with.

If you do assume the input data is full rank and you are just extracting fewer components to avoid wasting time computing components you don't need, then I agree with your reasoning.

What if, in the case that `ncomps < nchans`, it prints something like `'keeping %d components and residual', ncomps-length(reject)` (whether or not `hasdata` is true)? I think that would make it very clear what's going on.

**Comment by schoffelen** [comment]
Well, as you say, the optimal feedback depends a bit on the situation. 

From a numerical point of view (that is, without entering a deeper discussion about what constitutes a component) I'd say that if the original channels are kind of independent (i.e. they are not re-referenced or balanced in software, or in any other way linearly combinations of each other), the numeric rank is equal to the number of channels. This would mean that nchan-length(reject) is correct, from a numerical point of view. 

Since the projection matrix by mathematical definition is of rank nchan-length(reject), would you be OK with replacing the ft_info statement after the else into:

'projecting the input data onto a subspace of at most rank %d\n', nchan-length(reject)

Alternatively, I'd vote for not giving a second line of feedback in the hasdata case.

**Comment by ethanbb** [comment]
OK. I'd be OK with either of your suggestions, although I worry a little that the "projecting onto a subspace" version could also be confusing if it makes one think that a more complex operation is being performed than really is.

(Or we could also just close this issue and forget about it, since I now somewhat understand the reasoning for how it's currently worded!)

**Comment by schoffelen** [comment]
Thanks for keeping us sharp Ethan, much appreciated. Given your opinion, I suggest to keep it like it is for now, because that constitutes the least amount of work...
