### ISSUE TITLE
Mistake in source analysis

### ISSUE THREAD

**Issue by hjzSky** [fieldtrip/fieldtrip#1133]
In the source analysis process, I want to limit the number of source locations. In function **ft_prepare_mesh** , for example, I set brain, skull, and scalp to 300, 200, and 100 respectively. Then rebuild the source, but there is a mistake when run **ft_sourceanalysis** function, part of my code is shown below:

`cfg=[];
cfg.tissue={'brain','skull','scalp'};
cfg.numvertices = [300 200 100];
bnd=ft_prepare_mesh(cfg,segmentedmri);

save bnd bnd
cfg        = [];
cfg.method ='bemcp'; % You can also specify 'openmeeg', 'bemcp', or another method.
headmodel        = ft_prepare_headmodel(cfg, bnd);

save headmodel headmodel
...
powcsd_all      = ft_freqanalysis(cfg, data_timewindow);
cfg            = [];
cfg.elec       = powcsd_all.elec;
cfg.headmodel  = headmodel;
cfg.reducerank = 3; % default is 3 for EEG, 2 for MEG
cfg.resolution = 1;   % use a 3-D grid with a 0.5 cm resolution
cfg.unit       = 'cm';
cfg.tight      = 'yes';
[grid] = ft_prepare_leadfield(cfg);

% beamform common filter
cfg                 = [];
cfg.method          = 'dics';
cfg.frequency       = 18;
cfg.grid            = grid;
cfg.headmodel       = headmodel;
cfg.senstype        = 'EEG'; % Remember this must be specified as either EEG, or MEG
cfg.dics.keepfilter = 'yes';
cfg.dics.lambda     = '15%';
source_all = ft_sourceanalysis(cfg, powcsd_all);`

**And the mistake is:**

Error using svd
Input to SVD must not contain NaN or Inf.

Error in beamformer_dics>pinv (line 667)
  [U,S,V] = svd(A,0);

Error in beamformer_dics (line 340)
        filt = pinv(lf' * invCf * lf) * lf' * invCf;              % Gross eqn. 3, use pinv/SVD to cover rank deficient leadfield

Error in ft_sourceanalysis (line 689)
          dip(i) = beamformer_dics(sourcemodel, sens, headmodel, [],  squeeze_Cf, optarg{:});

**Comment by schoffelen** [comment]
Please ask your question on the fieldtrip discussion list. If you haven't signed up yet, please refer to http://www.fieldtriptoolbox.org/discussion_list/ for more information.

**Comment by schoffelen** [comment]
I don't remember having seen your question posted on the discussion list. Is this still relevant for you? If so, this is a gentle reminder.
