### ISSUE TITLE
case 'blackrock_nsx' is present twice in ft_read_data

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1146]
One around line 440, another one around line 1451. The code is different enough that I am not sure which one to keep.

**Comment by schoffelen** [comment]
what about removing both, and see whether anybody notices :)?

**Comment by schoffelen** [comment]
I guess, that the calibration stuff is of a more recent date. So, if anything, I'd remove the shorter chunk of code.

**Comment by robertoostenveld** [comment]
that is the later piece, right? That would also be the piece that is now not being executed anyway.

**Comment by schoffelen** [comment]
yes indeed.
