### ISSUE TITLE
ft_rejectvisual does not keep channels when magnetometers and gradiometers are looked at separately

### ISSUE THREAD

**Issue by ualsbombe** [fieldtrip/fieldtrip#1152]
cfg.keepchannel doesn't work as supposed to (channels are not kept) when working on separate sensor types one after the other - see the last section. This is tested on fieldtrip pulled from git minutes ago.
In comparison, it works as supposed to using fieldtrip-20171217 (i.e. it keeps the gradiometers as supposed to)

`%% INITIALIZE

clear variables
restoredefaultpath

addpath /home/lau/matlab/fieldtrip/ % from git 15.08 June 25th 2019
% addpath /home/lau/matlab/fieldtrip-20171217/ % works fine with this
ft_defaults

%% READ IN DATA

cfg = [];
cfg.dataset = 'oddball1_mc_downsampled.fif';
cfg.trialdef.prestim        = 0.2;
cfg.trialdef.poststim       = 0.4;
cfg.trialdef.rsp_triggers   = [256 4096];
cfg.trialdef.stim_triggers  = [1 2];
cfg.trialfun                = 'trialfun_oddball_stimlocked';

cfg = ft_definetrial(cfg);

cfg.continuous    = 'yes';

data_meg = ft_preprocessing(cfg);

%% REJECT VISUAL - this works fine (i.e. when some channels are removed in 
% in the GUI they are kept for the next one

cfg = [];
cfg.method = 'summary';
cfg.keepchannel = 'yes';
cfg.channel = 'MEGMAG';

temp = ft_rejectvisual(cfg, data_meg);

cfg.channel = 'MEGMAG';

cleaned_data = ft_rejectvisual(cfg, temp);

%% REJECT VISUAL - this does not (i.e. all gradiometers disappear after first
% round

cfg = [];
cfg.method = 'summary';
cfg.keepchannel = 'yes';
cfg.channel = 'MEGMAG';

temp = ft_rejectvisual(cfg, data_meg);

cfg.channel = 'MEGGRAD';

cleaned_data = ft_rejectvisual(cfg, temp);`

**Comment by robertoostenveld** [comment]
on line 178 it does
```
selcfg = keepfields(cfg, {'trials', 'channel', 'latency', 'showcallinfo'});
data   = ft_selectdata(selcfg, data);
```
and after that the channels that are NOT in cfg.channel are gone, never to return!

Using `git blame` I see that 

```
929e750d16 ft_rejectvisual.m (Diego Lozano-Soldevilla 2018-11-06 09:31:00 +0100 178) selcfg = keepfields(cfg, {'trials', 'channel','latency', 'showcallinfo'});
b8a4495684 ft_rejectvisual.m (Jan-Mathijs Schoffelen  2018-11-21 14:16:31 +0100 179) data   = ft_selectdata(selcfg, data);
929e750d16 ft_rejectvisual.m (Diego Lozano-Soldevilla 2018-11-06 09:31:00 +0100 180) % restore the provenance information
929e750d16 ft_rejectvisual.m (Diego Lozano-Soldevilla 2018-11-06 09:31:00 +0100 181) [cfg, data] = rollback_provenance(cfg, data);
```

could you see what  happened in 929e750d16 and b8a4495684, e.g. whether they were part of an issue or pull request that was trying to resolve something?

**Comment by ualsbombe** [comment]
929e750 was part of bugfix2673  [(https://github.com/fieldtrip/fieldtrip/commit/929e750d167e3f79ce1dc354479c988c5ba77825)]

But it is not clear to me what it was trying to solve (what was done was the selection of channels was added with ft_selectdata during the "beginning" )

**Comment by robertoostenveld** [comment]
Just discussed this with @ualsbombe, he is going to send a PR

**Comment by ualsbombe** [comment]
Pull request created

**Comment by ualsbombe** [comment]
Pull request created #1281 
My apologies if I could have kept it part of the old pull request

**Comment by schoffelen** [comment]
I think that the PR looks OK, I just merged and will close this one. Thanks.
