### ISSUE TITLE
ft_componentanalysis and runica method error with random seed

### ISSUE THREAD

**Issue by rtheze** [fieldtrip/fieldtrip#1157]
Hi all, 

I have no idea how this became a problem, but when trying to run a script which worked fine a week ago, and without any update (at least that I am aware of), I ran into an error when trying to run ft_componentanalysis. 

My fieldtrip version is 20180201, I know it is not the latest but that's the version that is more compatible with other portions of my script, and I have tested ft_componentanalysis with a more recent version of FT and the error remains. 

```
    cfg                 = [];
    cfg.method          = 'runica';                                         % this is the default and uses the implementation from EEGLAB
    cfg.runica.maxsteps = 50;                                               % Limit to 50 steps to go faster (default is 512)
    cfg.numcomponent    = rank(squeeze(datads.trial{1}) * squeeze(datads.trial{1})');  
    cfg.channel         = {'all', '-audio'};

    comp                = ft_componentanalysis(cfg, datads);
```

Here datads is a downsampled version of the data I am processing. This error appeared:

> Output argument "sphere" (and maybe others) not assigned during call to "runica".
> 
> Error in ft_componentanalysis (line 515)
>     [weights, sphere] = runica(dat, optarg{:});

From what I could track down, line 513 the code in ft_componentanalysis is adding to the key-value pairs the pair "reset_randomseed" and "0"

```
    % construct key-value pairs for the optional arguments
    optarg = [ft_cfg2keyval(cfg.runica) {'reset_randomseed' 0}]; % let FieldTrip deal with the random seed handling
    [weights, sphere] = runica(dat, optarg{:});
```

But...! in the function runica this key-value pair is not recognized and (line 504 of runica.m) after trying all the known key value pairs it reaches the conclusion that it is unkown and return the function but without any output, hence the error

```
      else
         fprintf('runica(): unknown flag')
         return
      end
```

Switching 
`optarg = [ft_cfg2keyval(cfg.runica) {'reset_randomseed' 0}];
`
with 
`optarg = [ft_cfg2keyval(cfg.runica)];`

solves the problem in my case, but I have no idea what is the use for "reset_randomseed", if it is crucial somewhere or is it just a vestige of an older version. Also, my pipeline used to work fine with this version of the code (or at least I'm assuming it did), why would this be a problem now? It gives me doubt on my radical solution to removing the key-pair.

Could we change the FT code or is the problem somewhere else I could not understand?

**Comment by schoffelen** [comment]
Hi Raphael (that is: I think it's you, if not apologies for getting your name wrong),

I think that you have an issue with your matlab path. The version of runica in fieldtrip (external/eeglab) certainly supports the reset_randomseed option, which is something I seem to have implemented somewhere in 2015 :) (I needed to check it myself, because I forgot about it).
Can you confirm that your problem exists if you restart matlab, run ft_defaults from within your fieldtrip folder and then run your script?

**Comment by rtheze** [comment]
Hi Jan,
Yes it is Raphael!

So I had already tried to restart matlab and run ft_defaults from my two fieldtrip versions and the problem persisted, but now that you mention it, I see that I have multiple version of runica on my computer, and the one in external/eeglab/ has the option randomseed as you mentionned. But I also notice that despite running ft_defaults external/eeglab/ is not included in the path, which could explain why matlab is not picking the right version (but why it is not in the path I do not know). I fixed it manually and now it does work. Thank you very much for the hint!

**Comment by schoffelen** [comment]
Ah, I see. I think indeed that if you already have an instance of runica on your path, fieldtrip uses that version. Otherwise (and this is indeed not handled by ft_defaults), the call in ft_componentanalysis to ft_hastoolbox adds external/eeglab, if it cannot find runica on the matlab path.
