### ISSUE TITLE
Error in ft_senstyp for datatype "comp"

### ISSUE THREAD

**Issue by mcvinding** [fieldtrip/fieldtrip#1159]
Error in _ft_senstyp_ when reading component data, e.g. for plotting ICA components with _ft_topoplotIC_ or _ft_databrowser_. The error appears to be in reading and processing the "balance" field in the grad structure related to unmixing the components.

Error message:

```
> Error using ft_datatype_sens (line 283)
> unexpected number of coils (510) contributing to channel MEG0111 (1)
> 
> Error in undobalancing (line 58)
> sens = ft_datatype_sens(sens);
> 
> Error in ft_senstype (line 283)
>       sens = undobalancing(sens);
```

The error appeared in both my own data recorded with a Neuromag MEG and the CTF tutorial data from the FieldTrip tutorials. I have attached a grad structure from the Neuromag data.

[grad.zip](https://github.com/fieldtrip/fieldtrip/files/3350259/grad.zip)

**Comment by schoffelen** [comment]
This is probably the same issue as issue #980

**Comment by robertoostenveld** [comment]
I renamed and copied the test file to our file server

```
mac011> mv grad.mat issue1159.mat
mac011> scp issue1159.mat mentat001:/home/common/matlab/fieldtrip/data/test
```

When I try a direct replication, it now works for me

```
>> load issue1159.mat
>> ft_senstype(grad)
ans =
    'neuromag306'
```

But I think this morning you showed that after ft_componentanalysis it did not have teh `type` field (which I suppose you added by hand). The following is what works for me to reproduce the error that you report as well:


```
>> ft_senstype(rmfield(grad, 'type'))
undoing the comp balancing for the gradiometer definition
Error using ft_datatype_sens (line 283)
unexpected number of coils (510) contributing to channel MEG0111 (1)
Error in undobalancing (line 58)
sens = ft_datatype_sens(sens);
Error in ft_senstype (line 283)
      sens = undobalancing(sens); 
```

**Comment by robertoostenveld** [comment]
I made a test script  and added it to a branch on my own https://github.com/robertoostenveld/fieldtrip copy of the repository

mac011> git commit test/test_issue1159.m 
[issue1159-undobalancing 98fec29af] ENH - added test script to reproduce the problem
 1 file changed, 20 insertions(+)
 create mode 100644 test/test_issue1159.m

mac011> git push --set-upstream origin issue1159-undobalancing
Counting objects: 78, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (75/75), done.
Writing objects: 100% (78/78), 37.82 KiB | 3.44 MiB/s, done.
Total 78 (delta 39), reused 2 (delta 2)
To github.com:robertoostenveld/fieldtrip.git
 * [new branch]          issue1159-undobalancing -> issue1159-undobalancing
Branch 'issue1159-undobalancing' set up to track remote branch 'issue1159-undobalancing' from 'origin'.

**Comment by mcvinding** [comment]
You are correct; the grad type field was added manually. I have attached a new version of the grad struct that has not been altered.

[grad.zip](https://github.com/fieldtrip/fieldtrip/files/3351186/grad.zip)

**Comment by robertoostenveld** [comment]
AFAIK, this has been fixed.
