### ISSUE TITLE
implement support for .snirf files (fnirs file format)

### ISSUE THREAD

**Issue by Horschig** [fieldtrip/fieldtrip#1161]
snirf is a data format initiated by the Society for fNIRS, with the aim to have a standard data format across acqusition systems. snirf is using hdf5 definitions. The official definition can be found on the respective Github page: https://github.com/fNIRS/snirf/

There is a sample file which can be found here: https://github.com/fNIRS/snirf/pull/26
(pull request is from https://github.com/huppertt/snirf/tree/patch-2, where the file can be found as well) 

There will be official file format reading and writing MATLAB function being uploaded soon, which could be used in FT to wrap around. I'll link the files as soon as they are available.

**Comment by robertoostenveld** [comment]
FYI, I have copied the files from https://github.com/fNIRS/snirf/pull/26#commits-pushed-3ef1df8 to our test directory

```
mac011> scp -r SNIRF_example.snirf mentat001:/home/common/matlab/fieldtrip/data/test/original/nirs/snirf/
mac011> scp -r SNIRF_H5dump.txt mentat001:/home/common/matlab/fieldtrip/data/test/original/nirs/snirf/
```

Please use `dccnpath` in a test script, if the file cannot be found in `/home/common/matlab/fieldtrip/data/test/original/nirs/snirf/` but can be found in the present working directory, it will automatically return the pwd version.

**Comment by Horschig** [comment]
Just got a mail from the sfnirs people, here an excerpt relevant for this issue:

> Several people talked about a SNIRF files reader/writer. As far as Homer3 is concerned, it is available on GitHub and ready to be tested/demo'ed. I know that Ted has one and Qianqian wants to write one. If anyone would like to try the Homer3 version, a) clone the Homer3 repo (https://github.com/BUNPC/Homer3), b) follow the very brief 'getting started' instructions in the README, and c) run the demo (demo_snirf.m) which demonstrates the use of the SnirfClass reader/writer that Homer3 uses. Would love to know your thoughts.

There is thus a snirf reader implementation available at https://github.com/BUNPC/Homer3/tree/master/DataTree/AcquiredData/Snirf

I'll probably have time in September/October to check this in more detail.

**Comment by Horschig** [comment]
update: I'll probably have time in September/October 2020 to check this in more detail ;)

**Comment by robertoostenveld** [comment]
I will cover SNIRF in the BIDS lecture in the upcoming fNIRS toolkit course at the Donders. Hopefully we can get some code in place prior to that.
