### ISSUE TITLE
data2bids reading ctf crashes on line 1299

### ISSUE THREAD

**Issue by cdale8** [fieldtrip/fieldtrip#1169]
data2bids line 1299:

>> copy_ctf_files(cfg.dataset, cfg.outputfile, false)

produces a "too many input arguments" error, where copy_ctf_files.m allows only

>>copy_ctf_files(cfg.dataset, cfg.outputfile)

Does removing the third argument on that line have downstream consequences?

**Comment by schoffelen** [comment]
it looks as if copy_ctf_files is intended to behave as copy_brainvision_files, i.e. it is intended to have a third argument. Please feel free to fix copy_ctf_files according to copy_brainvision_files (both are in fieldtrip/private, and submit a PR

**Comment by schoffelen** [comment]
any update here @cdale8 ?

**Comment by robertoostenveld** [comment]
just back from holiday.

@cdale8 It should now be fixed. Please test it carefully (keeping a backup copy of your data) and let us know if you still encounter problems.
