### ISSUE TITLE
Maximum recursion limit reached

### ISSUE THREAD

**Issue by EstelleHuang666** [fieldtrip/fieldtrip#1174]
Once I imported the repository into MATLAB lib path. It would report errors like "Maximum recursion limit reached". (for version 20190527 and later versions). However,  when I used 20160303, no such errors were reported. Could you help me solve this problem? By the way, why this repo has no tag before 20190527?

**Comment by schoffelen** [comment]
I cannot help because there is insufficient information. Also it is unclear what you mean with "once I imported the repository into MATLAB lib path." I will close this issue for now.
Please formulate your question constructively when re-opening your issue.

**Comment by EstelleHuang666** [comment]
Sorry for the unclear description. I have found the solution in your [FAQs](http://www.fieldtriptoolbox.org/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path/). Thanks for your help.
