### ISSUE TITLE
ft_defaults removes isfolder in /compat/matlablt2017b from path on R2017a

### ISSUE THREAD

**Issue by bhsilverstein** [fieldtrip/fieldtrip#1179]
When running ft_defaults for the first time after starting Matlab R2017a, isfolder is removed from the path. This causes all functions that use isfolder to fail. Replacing isfolder with isdir solves the problem.

Just to clarify, only the top FieldTrip directory is in the path on Matlab startup.

**Comment by robertoostenveld** [comment]
`isfolder` was [Introduced by Mathworks](https://nl.mathworks.com/help/matlab/ref/isfolder.html#mw_c965c324-8d32-4f03-a9f1-30cb04b90118_seealso) in R2017b, which means it is not yet on the path for R2017a when you start with a clean path (e.g. with `restoredefaultpath`). Hence I don't understand how ft_defaults would remove it from the path....

The following is with MATLAB R2017a on Linux
```
>> restoredefaultpath
>> which isfolder
'isfolder' not found.
>> addpath ~/matlab/fieldtrip/
>> which isfolder
'isfolder' not found.
>> ft_defaults
>> which isfolder
/home/mrphys/roboos/matlab/fieldtrip/compat/matlablt2017b/isfolder.m
```

So running ft_defaults for the first time causes it to be **added** to the path.

**Comment by robertoostenveld** [comment]
FieldTrip code uses MATLAB functions that are not always present in older MATLAB versions. Those functions are provided in the compat/matlabltXXXX directories, where "lt" stands for less-than.  The required matlabltXXXX directories are added by ft_defaults.

See also http://www.fieldtriptoolbox.org/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path/

**Comment by robertoostenveld** [comment]
please reopen when you can make it more clear what the issue is.
