### ISSUE TITLE
ft_resampledata returns output data that is one sample short

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1184]
as reported by @ludovicbellier in the thread  https://github.com/fieldtrip/fieldtrip/commit/4a0663c7ca1d33af67ca0a177d104904fef6b932#commitcomment-34622403

```
>> 228864/12
ans =
       19072
```

**Comment by robertoostenveld** [comment]
this replicates the problem

```
function test_issue1184

% MEM 2gb
% WALLTIME 00:10:00
% DEPENDENCY ft_resampledata

data = [];
data.time{1} = (1:228864) * 1/1200;
data.trial{1}(1,:) = 1:228864;
data.label = {'time'};
data.fsample = 1200;

cfg = [];
cfg.resamplefs = 100;
resampled = ft_resampledata(cfg, data);

assert(length(resampled.time{1})==19072);
```

**Comment by robertoostenveld** [comment]
I don't know the solution immediately, but it seems that line 272

```
    % un-pad the data
    sel = nearest(newtim, oldtim(1+begpad(itr))):nearest(newtim, oldtim(end-endpad(itr)));
```
is the culprit. It not only unpads the data, but also uses nearest. And that causes the last sample to drop off.

In general this is a hard problem, since samples represent a width. E.g. at 1000 Hz one sample is 1 ms, which means that the sample that is centered at t=0 goes from -0.5 to +0.5 ms. If you resample, especially in case not with an integer multiple, the new samples don't align with the old ones, which becomes visible at the edges. 

But in this case the decimation factor is 12, so it should all align.

**Comment by ludovicbellier** [comment]
I used your function replicating the issue with a breakpoint on line 272 of ft_resampledata.m and here's what I found:
- both newtim and newdat are 1x19,072 arrays;
- `newtim(1:5)` gives -0.0083    0.0017    0.0117    0.0217    0.0317, so `nearest(newtim, 0)` returns 2;
- `newtim(end-4:end)` gives 190.6617  190.6717  190.6817  190.6917  190.7017, so `nearest(newtim, 190.72)` returns 19072, however with both values being pretty distant (190.70 vs 190.72, compared to the .01 step between adjacent values);
- hence, sel is a 1x19071 index array (2:19072).

To get newtim beginning with a positive value and ending with a value closer to 190.72 (`oldtim(end)`), I then used this quick and dirty fix: `newtim = newtim + 0.01` (0.01 being the time step in newtim), and line 272 indeed gave sel as a 1x19072 array. So it seems that the issue could be coming from just above, during the creation of newtim in lines 260 to 264.

Either not applying lines 263 and 264, or modifying line 264 by either `newtim = newtim + shift;`, `newtim = newtim + shift - 1/cfg.resamplefs`, or `newtim = newtim - shift + 1/cfg.resamplefs;` do the trick. What do you think?

**Comment by robertoostenveld** [comment]
Just to clarify (mainly for myself): samples have a width, i.e. represent a time bin. The time of a sample represents the middle of the bin. The width of the bin is 1/fsample. Subsequent time bins are flush (i.e. lined up).

In the ideal case causing the problem (1200Hz to 100Hz) the original data has 12 time bins for 1 time bin in the downsampled data. The middle of the downsampled time bin is in between bin 6 and 7 of the original data. 

But imagine that you would resample 1200Hz to 100Hz where the original data is only 11 samples. That would cause the middle of the downsampled time bin to end up centered on bin 6 of the original data.

**Comment by robertoostenveld** [comment]
this should fix it, and keep the correct behaviour for bugzilla 27 as well.

Please check out the test script.

**Comment by ludovicbellier** [comment]
Awesome, thanks Robert!
I couldn't check the whole test script as I don't have isalmostequal.m, but I can tell ft_resampledata.m works back on my data.

**Comment by robertoostenveld** [comment]
thanks. FYI, isalmostequal.m is in fieldtrip/test/private, it is available on the path if you run test scripts (also in debug mode, i.e. step by step). It is needed since once in a while there is a pesky `eps` difference.

**Comment by ludovicbellier** [comment]
Oh ok, good to know, thanks!
