### ISSUE TITLE
Warning: Colon operands must be real scalars.  When performing ft_freqstatistics

### ISSUE THREAD

**Issue by AlexChalard** [fieldtrip/fieldtrip#1187]
Hello everyone,

When I performed ft_freqstatistics whith correctm = 'cluster' on 4D array (subj_chan_freq_time), I get the following warning : "Warning: Colon operands must be real scalars. "
I try a dbstop if warning, the program in the clusterstat.m line 291, it seems that the variable "Nrndpos" % number of clusters exceeding the threshold is an uint32 empty colon vector.
Maybe even if no cluster were detected I guess that Nrndpos take 0 as value.

Any suggestion to fix this problem ? 

Kinds regards 

Alex

**Comment by robertoostenveld** [comment]
Hi @AlexChalard has this now been resolved, or did you accidentally close the issue? I don't recall ever having seen this warning. If you want to follow up: please reopen and mention the MATLAB version you are using.

**Comment by AlexChalard** [comment]
Hi @robertoostenveld, yes I resolved the isssue, I think I get this error because prior to freqanalysis I did a selectdata, and I think that a mismatch between dimord and powspctrm in freqanalysis induce this issue. 

Alex
