### ISSUE TITLE
Tutorial inconsistency:  functions icosahedron42.m is missing

### ISSUE THREAD

**Issue by Marshdweller** [fieldtrip/fieldtrip#1198]
Hello all,

Just spotted that icosahedron42.m function from [this tutorial page](http://www.fieldtriptoolbox.org/example/testing_bem_created_leadfields/)

is missing from the daily build. I am using fieldtrip-20190819. It is present in 20181231 though.
Seems that this function (and probably others) has been automatically removed as listed 
[here](http://www.fieldtriptoolbox.org/development/project/cleanup_private_functions/)

Regards,
M

**Comment by robertoostenveld** [comment]
thanks for reporting this. This is quite an old example page, and apparently broken. 

`icosahedron.m` and the various refinements were private functions, not meant to be called by users. They have been replaced by the (also private) `mesh_sphere.m`. 

I searched for similar issues and also found http://www.fieldtriptoolbox.org/example/compute_forward_simulated_data_and_apply_a_beamformer_scan/

**Comment by robertoostenveld** [comment]
this would be a piece of replacement MATLAB code to generates a sphere, without using private functions

```
[X, Y, Z] = sphere;
mesh.pos = unique([X(:) Y(:) Z(:)], 'rows');
mesh.tri = convhulln(mesh.pos);

ft_plot_mesh(mesh)
```

**Comment by robertoostenveld** [comment]
changing the construction of the gradiometer array, I run into another error that apparently has not been detected since long

```
Undefined function or variable 'lab'.
Error in channelposition (line 331)
n = size(lab,2);
Error in ft_datatype_sens (line 342)
        [chanpos, chanori, lab] = channelposition(sens);
Error in ft_datatype_sens (line 158)
    sens = ft_datatype_sens(sens, 'version', '2011v2');
Error in ft_checkconfig (line 248)
  cfg.grad = ft_datatype_sens(struct(cfg.grad));
Error in ft_preamble_trackconfig (line 34)
cfg = ft_checkconfig(cfg, 'trackconfig', 'on');
Error in ft_preamble (line 83)
evalin('caller', full_cmd);
Error in ft_dipolesimulation (line 82)
ft_preamble trackconfig 
```

**Comment by Marshdweller** [comment]
Thank you very much, Robert.

**Comment by robertoostenveld** [comment]
in commit 9b52314af I added a test script, representing the latest version of the examples

**Comment by robertoostenveld** [comment]
With https://github.com/fieldtrip/website/commit/5b01863202d85f74c5769e9b4f8f638ab903d684 I have also updated the website. It should appear online in 5 minutes or so.
