### ISSUE TITLE
Problem with xdf files

### ISSUE THREAD

**Issue by varghese-peter** [fieldtrip/fieldtrip#1200]
I am trying to analyse EEG data recorded using Lab Recorder (Lab Streaming Layer).  Whiel trying to preprocess the data using 'ft_preprocessing', I am getting the following error.

unsupported header format "sccn_xdf"

Could someone please suggest a way to fix this?

**Comment by robertoostenveld** [comment]
Hi Peter, 

you closed the issue again: does that mean that you figured out how to solve it?
