### ISSUE TITLE
'non equidistant frequency bins are not supported for method granger'

### ISSUE THREAD

**Issue by moonj94** [fieldtrip/fieldtrip#1211]
I am getting the following error:

the call to "ft_freqanalysis" took 2 seconds and required the additional allocation of an estimated 1 MB
the call to "ft_selectdata" took 0 seconds and required the additional allocation of an estimated 0 MB
Error using ft_connectivityanalysis (line 317)
non equidistant frequency bins are not supported for method granger

I do not understand why this is happening when I am applying an equidistant foi (1:60)

My input is:

freq                   = [];
freq.freqcfg           = [];
freq.freqcfg.method    = 'mtmconvol';
freq.freqcfg.taper     = 'hanning';
freq.freqcfg.output    = 'pow';
% freq.freqcfg.keeptrials= 'yes';
freq.freqcfg.foi = [1:60];
freq.freqcfg.pad='nextpow2';
freq.freqcfg.toi = [-0.2:0.01:0.9];
freq.freqcfg.t_ftimwin = ones(size(freq.freqcfg.foi))*0.1;

freq13 = ft_freqanalysis(freq.freqcfg, data13);

grangercfg=[];
grangercfg.method  = 'granger';
grangercfg.channel={'CSblue','SPblue'};
grangercfg.feedback='text';

gdata.g13_mrc = ft_connectivityanalysis(grangercfg, freq13);

**Comment by schoffelen** [comment]
Please ask this as a question on the discussion list, so that other people can think along.
