### ISSUE TITLE
laggedcoherence implementation

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1217]
Following up on bug 2951 on bugzilla.fieldtriptoolbox.org.

There is a request for a functional implementation of lagged coherence, as per Eric Maris' and Anne Fransen's 2015 paper. The code contributed by Anne in 2015 has never been functional and not in fieldtrip style.

Currently https://github.com/schoffelen/fieldtrip has a branch laggedcoherence, where an implemenation is being written.

**Comment by schoffelen** [comment]
Jan has problems with the implementation:

Hi All,

This really is quite something, you guys are really on the ball. Thanks for all of this!

I don't know where you want me to upload my data as I'm pretty sure you don't want me to push datafiles into your git branch. I've put it on dropbox for now: https://www.dropbox.com/s/k0uqd1d7csgq978/data.mat?dl=0

I went full end-user perspective and pulled Jan-Mathijs entire laggedcoherence branch and loaded it into a virginal matlab, then tried to run the laggedcoherence option of ft_connectivityanalysis. To do so, I used the exact codesegment that is on the FT ref website for the laggedcoherence option:
http://www.fieldtriptoolbox.org/reference/ft_connectivity_laggedcoherence/

Doing that, I'm getting the following error message:

Error in ft_connectivity_corr (line 182)
      p1    = reshape(input(j,powindx(:,1),:,:,:), siz(2:end));

Error in ft_connectivityanalysis (line 969)
    [datout, varout, nrpt] = ft_connectivity_corr(data.(inparam), optarg{:});


Out of curiousity, I tried running the same thing on a non-segmented dataset (which is what usually what I work with since my analysis functions continue to use continuous data after preprocessing. I don't know if the typical FT workflow is like eeglab in that it wants epoched data to ultimately derive TF parameters). I don't know if the laggedcoherence is even supposed to make sense on non-segmented, continuous data, but either way, it produces a different error message:

Error using reshape
To RESHAPE the number of elements must not change.

Error in fourierspctrm2lcrsspctrm (line 112)
    tmpfreq.lcrsspctrm = reshape(permute(tmpfreq.crsspctrm, [4 1 2 3]),[nrpt*ntime ncmb nfreq]);

Error in univariate2bivariate (line 69)
      data = fourierspctrm2lcrsspctrm(data, varargin{:});

Error in ft_connectivityanalysis (line 418)
        [data, powindx, hasrpt] = univariate2bivariate(data, 'fourierspctrm', 'lcrsspctrm', dtype, 'channelcmb', cfg.channelcmb, 'timeresolved', cfg.laggedcoherence.timeresolved, 'lags', cfg.laggedcoherence.lags);

Hope there's nothing straightforwardly dumb about what I did here. Again, I don't have any prior fieldtrip experience.

Thanks much again,

Best,
Jan

**Comment by schoffelen** [comment]
OK, I wrote a little test script, and added it to the branch. @hadrianswall I explicitly mention you here, so that you probably get notified about the existence of this issue, by e-mail.

**Comment by schoffelen** [comment]
@janwessel e-mailed the following

Sorry to communicate outside of github for now.

I can confirm that with Jan-Mathjis wrapper function, the 'laggedcoherence' option to ft_connectivityanalysis works.

The error message that I got is a result of trying to use just a single frequency as an input into ft_connectivityanalysis at a time. That issue still persists.

If I understand the original paper correctly, the idea is to use frequency-specific lags to compute lagged coherence, with the lag depending on the width of the window for a given frequency at a constant number of cycles.
To do that, one would have to run each frequency individually through the function, and that doesn't work in the current implementation.

An obvious workaround would be to use the same vector of frequencies as an input on each iteration, but cycle a for loop through the lags of interest, and store only the frequency of interest from the lagged coherence spectrum on each iteration.

But that would have to be documented somewhere if the function is to be used as currently constructed.

Jan

**Comment by schoffelen** [comment]
[jansch@mentat004 test]$ git commit test_ft_connectivity_laggedcoherence.m
[laggedcoherence 2ed6d95] ENH - added some lines to the test script to confirm a current problem with the implementation
 1 file changed, 11 insertions(+)
[jansch@mentat004 test]$ git push origin laggedcoherence
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 518 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/schoffelen/fieldtrip.git
   4475233..2ed6d95  laggedcoherence -> laggedcoherence

**Comment by schoffelen** [comment]
Error confirmed. The cause of it is most likely a non-robust conversion of the fourier data into the lagged crsspctrm in case of just a single frequency bin (possibly in combination with a single channel). The way to tackle this, is to work with the matlab debugger, and go through the code line by line. I suspect that the cause lies in fourierspctrm2lcrsspctrm

**Comment by schoffelen** [comment]
disconfirmed, it goes wrong in the call to ft_selectdata on line 568 in ft_connectivity, the output dimensionality of the lcrsspctrm should be 3x1, rather than 1x3

**Comment by schoffelen** [comment]
the problem is in line 1211 in ft_selectdata. This is a generic problem, and not related to the laggedcoherence business. Essentially, the fact that there's 2 trailing singleton dimensions in the data matrix (single frequency and single time bins) make the isvector evaluation on that line non-robust,

**Comment by schoffelen** [comment]
[jansch@mentat004 fieldtrip]$ git commit utilities/ft_selectdata.m 
[laggedcoherence 015a83a] FIX - improved logic in squeezedim subfunction for exceptional case
 1 file changed, 2 insertions(+), 2 deletions(-)
[jansch@mentat004 fieldtrip]$ git push origin laggedcoherence
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 486 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/schoffelen/fieldtrip.git
   2ed6d95..015a83a  laggedcoherence -> laggedcoherence

**Comment by schoffelen** [comment]
@robertoostenveld: on working on this, I identified an unexpected problem in ft_selectdata (subfunction 'squeezedim'). In the exceptional case that the numeric data matrix (so specifically not one of the metadata fields, such as data.freq/data.time etc) is of size 1 x N x 1 x 1 (i.e. a single 'rpt' with N channels and 1 time and frequency point) the data vector needs to be reshaped into N x 1. Previously, in case of an isvector the reshaping was never applied. Could you quickly check whether the adjusted logic would, as per 015a83a would be correct?

**Comment by schoffelen** [comment]
Eric's comment:

Dear colleagues,
 
My apologies for the late reply. Teaching preparations kept me busy …

I can confirm that with Jan-Mathjis wrapper function, the 'laggedcoherence' option to ft_connectivityanalysis works.
The error message that I got is a result of trying to use just a single frequency as an input into ft_connectivityanalysis at a time. That issue still persists.
If I understand the original paper correctly, the idea is to use frequency-specific lags to compute lagged coherence, with the lag depending on the width of the window for a given frequency at a constant number of cycles.
To do that, one would have to run each frequency individually through the function, and that doesn't work in the current implementation.
An obvious workaround would be to use the same vector of frequencies as an input on each iteration, but cycle a for loop through the lags of interest, and store only the frequency of interest from the lagged coherence spectrum on each iteration.
But that would have to be documented somewhere if the function is to be used as currently constructed.
See More
I can confirm that with Jan-Mathjis wrapper function, the 'laggedcoherence' option to ft_connectivityanalysis works.
The error message that I got is a result of trying to use just a single frequency as an input into ft_connectivityanalysis at a time. That issue still persists.
If I understand the original paper correctly, the idea is to use frequency-specific lags to compute lagged coherence, with the lag depending on the width of the window for a given frequency at a constant number of cycles.
To do that, one would have to run each frequency individually through the function, and that doesn't work in the current implementation.
An obvious workaround would be to use the same vector of frequencies as an input on each iteration, but cycle a for loop through the lags of interest, and store only the frequency of interest from the lagged coherence spectrum on each iteration.
But that would have to be documented somewhere if the function is to be used as currently constructed.

You are right, Jan. For lagged coherence to make sense, the time windows for which the conjugate-multiplied Fourier coefficients are calculated must be non-overlapping. For the implementation to be user-friendly, we should allow the user to specify the lags-of-interest (next to the channels-of-interest and the frequencies-of-interest) and to let the function determine the appropriate cfg.toi (times-of-interest) and cfg.timwin (time windows of interest) such that there is no overlap between the time windows for which the Fourier coefficients are calculated. In order for the function to determine this appropriate cfg.toi and cfg.timwin, the user should specify the number of cycles of the Fourier basis function that a time window must contain. I would advise to build a helper function that takes as its input the time axis of the preprocessed data and the user-specified desided number of cycles per time window, and calculates the appropriate cfg.toi and cfg.timwin.
 
I’m happy to receive your comments.  I’m also happy to do some coding, but I think that we should first decide on the desired functionality.
 
Best,
Eric

**Comment by schoffelen** [comment]
A few quick comments on the automatic determination of the correct time steps for a given frequency bin:
- Fieldtrip does not know about the t_ftimwin used, unless it explicitly check in the cfg of the freq structure outputted by ft_freqanalysis. This is in general something that we would like to avoid.
- In case of frequency bin specific t_ftimwins (and possibly subsequent frequency bin specific selection of time steps): how does one deal with the differences in the bias of the coherence estimate, due to the different number of observations per frequency? @hadrianswall I mention you explicitly here, hoping that this would result in you receiving this by e-mail. Can you confirm? I'd like to move the discussion to this location, rather than keeping it in a more volatile e-mail thread.

**Comment by schoffelen** [comment]
@janwessel @hadrianswall. Hi both, Eric and I have now created a functional (we think) version of ft_laggedcoherence. For now, my work is done. I think that the implementation needs some testing with a few proper test scenarios, to be implemented in the test/test_laggedcoherence function. Now the test case just checks whether it runs through without error.

**Comment by schoffelen** [comment]
I will merge this branch into fieldtrip once we have tested a bit more, and provide some documentation on the fieldtrip wiki (e.g. as an example script), so that people can find some more information about how to use this function.

**Comment by robertoostenveld** [comment]
Following up on 
http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2951

This has now been addressed with 
https://github.com/fieldtrip/fieldtrip/pull/1233
https://github.com/fieldtrip/fieldtrip/pull/1259
and merged in the release.
