### ISSUE TITLE
ft_inside_headmodel and ft_headmodeltype not compatible with EEG shell headmodels

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1220]
headmodel = load('-mat', 'standard_singleshell.mat');
ft_headmodeltype(headmodel)

Unknown

Should be an easy fix. A fix to ft_inside_headmodel would also be great.

Arno

**Comment by arnodelorme** [comment]
Code to add to ft_inside_headmodel

inside = bounding_mesh(dippos, headmodel.vol.bnd(end).pnt, headmodel.vol.bnd(end).tri);

**Comment by robertoostenveld** [comment]
by reading it as 
```
var = load(file)
```
you are putting the struct `vol` that is contained in the file into `var.vol`.

The structure `var` is not recognized, but `vol` is. The following works:

```
load('-mat', 'standard_singleshell.mat'); % this loads vol
ft_headmodeltype(vol)
```

**Comment by robertoostenveld** [comment]
this is quite a common nuisance. To remedy this (partially) we have ft_read_xx functions for some of the structures that are often contained in mat files.  In this case the clean solution would be

```
>> headmodel = ft_read_headmodel('standard_singleshell.mat');
reading 'headmodel' from file 'standard_singleshell.mat'
>> ft_headmodeltype(headmodel)
ans =
    'singleshell' 
```

We also have the `fieldtrip/private/loadvar` and `savevar` functions to deal with these situations, but those are only for internal use. For HCP we had functions `hcp_read_ascii` and `hcp_read_matlab`. Now with BIDS I am more working with json and tsv files. I am therefore again  considering making a bunch of generic (and public) functions to read and write single variables/arrays/structs  from and to files. The representation in MATLAB memory and on disk are similar enough not to worry about the specific file format, as long as the assumption holds that one file contains one variable. This might also deal with Numpy npy and openjdata. 

But I think that is out of scope for the issue you reported.

**Comment by arnodelorme** [comment]
Thank you Robert. That makes sense and it is good to know for the future that you assume people load files directly in the workspace.

Arno
