### ISSUE TITLE
Segmentation fault with nanmean/nansum/nanstd/nanvar and no input

### ISSUE THREAD

**Issue by gllmflndn** [fieldtrip/fieldtrip#1227]
`prhs[0]`is used before the check that an input is provided so callling a `nan*` function without any input results in a segmentation fault.
https://github.com/fieldtrip/fieldtrip/blob/2239ff8f3169bc0169bf4d07ab76cfaaceeb2d0e/src/nansum.c#L36

**Comment by robertoostenveld** [comment]
triggered by #1246 I had a look at the Makefile that @nno made, and now realize that the message

> xcrun: error: SDK "macosx10.14.6" cannot be located

is actually not an error, but a warning, and that compilation continues nevertheless.

Furthermore https://github.com/fieldtrip/fieldtrip/commit/eb2b2ab51eb3ef8c0711701027eb7191746035f3 actually also includes the recompiled mexmaci64 files.

However, they still seem to crash.

**Comment by gllmflndn** [comment]
Thanks @robertoostenveld, I don't observe any more segfault after I recompiled them.

While we are looking at these functions, there is one warning during compilation:
```
nanstd.c: In function ‘mexFunction’:
nanstd.c:342:41: warning: passing argument 4 of ‘mexCallMATLAB’ from incompatible pointer type [-Wincompatible-pointer-types]
         mexCallMATLAB(nlhs, plhs, nrhs, prhs, "std");
                                         ^~~~
```
would it possible to therefore use `(mxArray **)prhs` instead?
