### ISSUE TITLE
`optopos` and `fiberpos` (and label) should be named consistently 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1235]
@helenacockx discovered that the artinis code uses one, whereas field trip main uses the other.

@Horschig is there a reason to deviate from the [initial design](http://www.fieldtriptoolbox.org/development/project/nirs/#layouts)?

**Comment by robertoostenveld** [comment]
Hi @Horschig, do you want me to fix this in the Artinis code?

**Comment by helenacockx** [comment]
I've noticed that **opto2lay** (from **ft_prepare_layout**) is also asking for `opto.fiberlabel`, so this should maybe be implemented too?

**Comment by robertoostenveld** [comment]
I see that the code that uses `fibers` in ft_nirs_prepare_ODtransformation dates back to 2016-10-07, which might very well be prior to us settling on the documented opto definition.

**Comment by robertoostenveld** [comment]
this has been resolved with #1245
