### ISSUE TITLE
ft_plot_sens plotting CTF sensors in a rotated coordinate system

### ISSUE THREAD

**Issue by solleo** [fieldtrip/fieldtrip#1237]
Dear FT community,

Is there a specific reason behind `plotting/ft_plot_sens.m` plotting CTF (or any non-neuromag MEG systems) sensor in a rotated (along the Z-axis by 90 deg) space?

- The channel positions and orientations are in ALS coordinates for the CTF system. So currently, it plots sensors in ALS space, not in RAS space. When I use it with coregistered MRI data (and source spaces from it), it looks pretty funny as if the subject is wearing the MEG helmet in such a way a juvenile who is highly inspired by popular North American cultures would do.
- Anyway, I think we could simply read `.coordsys` field from the `sens` structure, and just rotate the `pos` and `ori` by 90 deg when the system is not neuromag. I just wonder if there is any particular reason for not doing this?

**Comment by schoffelen** [comment]
Please ask your question on the fieldtrip discussion list if you'd like to get feedback from the community. These issues are not widely read.

See http://www.fieldtriptoolbox.org/discussion_list/ for instructions to sign up.

PS: CTF's convention for the coordinate axes to be ALS is as valid a convention as neuromag's RAS. They are rotated with respect to one another indeed, but this shouldn't be a problem.
