### ISSUE TITLE
undo electrode assignment in ft_electrodeplacement for cfg.method='headshape'

### ISSUE THREAD

**Issue by helenacockx** [fieldtrip/fieldtrip#1242]
For` cfg.method = 'volume'`, **ft_electrodeplacements** allows to undo an electrode assignment by clicking on the same label again. When trying this for the `cfg.method = 'headshape' `option this does not seem to work. Is it possible to make this option available for this (and other methods) too? An example can be found in the fieldtrip "Localizing electrodes using a 3D scanner" .(http://www.fieldtriptoolbox.org/tutorial/electrode/) 
By running following lines on the attached 3D-scan.
```
head_surface = ft_read_headshape('3D-Scan/3D-Scan/Model/Model.obj');
cfg=[];
cfg.method = 'headshape';
elec = ft_electrodeplacement(cfg, head_surface);
```

[3D-Scan.zip](https://github.com/fieldtrip/fieldtrip/files/3750393/3D-Scan.zip)

_Windows10 - MATLABR2019a_

**Comment by StolkArjen** [comment]
Quick reply: can you try and port some of the functionality from the volume-based approach to the surface-based approach? It probably involves removing the re-clicked electrodes from a list.

**Comment by robertoostenveld** [comment]
I went through the code yesterday and figured it out: you have to double-click, i.e. click twice on the label to erase it again. 

I have added it to the help as 
```
% In the interactive 'headshape' and 'volume' methods you can click once on an
% already assigned electrode to jump to that electrode position and you can click
% twice to remove the assigned electrode position.
```

Please check and re-open this issue if it does not work for you.
