### ISSUE TITLE
Makefile issues for Octave/Linux

### ISSUE THREAD

**Issue by Andesha** [fieldtrip/fieldtrip#1246]
Hi there,

Currently when invoking the make file via ``make mex OCTAVE=`which octave` `` on Linux platforms, there's an error. It reports that there is no target for `engine/private`.

As a workaround I simply create the directory in the terminal with `mkdir -p engine/private` and rerun the make command and everything compiles great after that.

Thanks! :)

**Comment by Andesha** [comment]
The only file I have inside of `engine/private` is `ft_getopt.mex`

Just so you know: I'm calling these functions via DipFit. DipFit is sitting at version 3.2 and FieldTrip is at lite20190922. I got this particular version of DipFit by default as it's a submodule in the current versions of EEGLAB. When I went to do an actual dipole fit, FieldTrip-lite20190922 was downloaded automatically via DipFit.

Here's the error I get without manually creating the `engine/private` folder:
```
[tk11br@gra-login2 Fieldtrip-lite20190922]$ make mex OCTAVE=`which octave`
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/octave/4.4.1/bin/octave --eval "[pth,nm,ext]=fileparts('src/det2x2.c');cd(pth);succes=false;try,succes=~mex([nm,ext]);catch,end;exit(~succes);"
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
cp src/det2x2.mex  connectivity/private/det2x2.mex
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/octave/4.4.1/bin/octave --eval "[pth,nm,ext]=fileparts('src/ft_getopt.c');cd(pth);succes=false;try,succes=~mex([nm,ext]);catch,end;exit(~succes);"
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
cp src/ft_getopt.mex  connectivity/private/ft_getopt.mex
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/octave/4.4.1/bin/octave --eval "[pth,nm,ext]=fileparts('src/inv2x2.c');cd(pth);succes=false;try,succes=~mex([nm,ext]);catch,end;exit(~succes);"
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
cp src/inv2x2.mex  connectivity/private/inv2x2.mex
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/octave/4.4.1/bin/octave --eval "[pth,nm,ext]=fileparts('src/mtimes2x2.c');cd(pth);succes=false;try,succes=~mex([nm,ext]);catch,end;exit(~succes);"
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
cp src/mtimes2x2.mex  connectivity/private/mtimes2x2.mex
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/octave/4.4.1/bin/octave --eval "[pth,nm,ext]=fileparts('src/sandwich2x2.c');cd(pth);succes=false;try,succes=~mex([nm,ext]);catch,end;exit(~succes);"
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
cp src/sandwich2x2.mex  connectivity/private/sandwich2x2.mex
cp src/ft_getopt.mex  engine/private/ft_getopt.mex
cp: cannot create regular file 'engine/private/ft_getopt.mex': No such file or directory
make: *** [Makefile:167: engine/private/ft_getopt.mex] Error 1
```

**Comment by robertoostenveld** [comment]
ah, that you have the 'lite' version explains it. When zipping it for release on the ftp server, some folders/files are excluded. I will update the filter for the exclusion and will also remove the `src` directory and `Makefile`. I regretfully cannot support  compiling mex files in the lite version, compiling the mex files in the regular version is already hard enough to maintain.

Furthermore, I will add a sentence to the documentation on http://www.fieldtriptoolbox.org/faq/compile/

If you would share your mex file compiled on octave with other users (eg through a github repo under your account), I would be happy to point to that.
