### ISSUE TITLE
zucht

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1253]
the units of the grad-array returned by ft_read_sens depends on the order of the input arguments:

if I do:

grad = ft_read_sens(filename, 'fileformat', 'neuromag_mne_grad', 'coilaccuracy', 0);

I get the grad in 'cm'

if I do:

grad = ft_read_sens(filename, 'coilaccuracy', 0, 'fileformat', 'neuromag_mne_grad');
 
I get the grad in 'm'

Strange. Scaling of the tra seems to be according to the units.

**Comment by schoffelen** [comment]
false alarm. User error: typo.

**Comment by StolkArjen** [comment]
asjemenou :/
