### ISSUE TITLE
warning and error message in head model creation

### ISSUE THREAD

**Issue by dwleeibru** [fieldtrip/fieldtrip#1256]
Hi there, I'm new to fieldtrip. While running head model using ft_prepare_headmodel, I encounter an error message that appeared once before: https://mailman.science.ru.nl/pipermail/fieldtrip/2016-July/023564.html

I’d highly appreciate if anybody may have a quick look. Thank you very much in advance, Jimmy ~

FYI, I just download fieldtrip and am using the most updated version. My matlab is R2014b. The MRI is provided by fiedltrip. The command ft_defaults is used in the beginning. The code (from tutorial) and error message (the program aborts) are as follows:

 %%%%%%%
% the code
%%%%%%%

cfg        = [];
cfg.method ='simbio';
cfg.conductivity = [0.33 0.14 1.79 0.01 0.43];   % order follows mesh.tissyelabel
vol        = ft_prepare_headmodel(cfg, mesh); % I’ve constructed a mesh following tutorial

 %%%%%%%%%%%%%%%%%%
% warning and error message
%%%%%%%%%%%%%%%%%%
Warning: could not determine dimord of "tissue"
in:
             hex: [4253860x8 double]
            pos: [4354472x3 double]
         tissue: [4253860x1 double]
    tissuelabel: {1x5 cell}
           unit: 'mm'
       coordsys: 'ctf'
            cfg: [1x1 struct]
         inside: [4354472x1 logical]

 In getdimord>warning_dimord_could_not_be_determined at line 681
In getdimord at line 631
In getdatfield at line 45
In ft_datatype_source at line 232
In ft_datatype_parcellation at line 178
In ft_checkdata at line 280
In ft_prepare_headmodel at line 210
 
Warning: could not determine dimord of
"tissue" in:
             hex: [4253860x8 double]
           pos: [4354472x3 double]
         tissue: [4253860x1 double]
    tissuelabel: {1x5 cell}
           unit: 'mm'
       coordsys: 'ctf'
            cfg: [1x1 struct]
         inside: [4354472x1 logical]
 
Warning: adding
D:\XXX\fieldtrip-20191028\external\simbio
toolbox to your MATLAB path
Warning: could not determine dimord of
"tissue" in:
             hex: [4253860x8 double]
            pos: [4354472x3 double]
         tissue: [4253860x1 double]
    tissuelabel: {1x5 cell}
           unit: 'mm'
       coordsys: 'ctf'
            cfg: [1x1 struct]
         inside: [4354472x1 logical]
 
In getdimord>warning_dimord_could_not_be_determined at line 681
In getdimord at line 631
In getdatfield at line 45
In ft_datatype_source at line 232
In ft_datatype_parcellation at line 178
In ft_headmodel_simbio at line 46
In ft_prepare_headmodel at line 467
 
Warning: could not determine dimord of
"tissue" in:
             hex: [4253860x8 double]
            pos: [4354472x3 double]
         tissue: [4253860x1 double]
    tissuelabel: {1x5 cell}
           unit: 'mm'
       coordsys: 'ctf'
            cfg: [1x1 struct]
         inside: [4354472x1 logical]
 
In getdimord>warning_dimord_could_not_be_determined at line 681
In getdimord at line 631
In ft_datatype_source at line 234
In ft_datatype_parcellation at line 178
In ft_headmodel_simbio at line 46
In ft_prepare_headmodel at line 467
 
Error using sb_calc_stiff (line 89)
Error executing mex-file. Microsoft Visual C++
2008 Redistributables and Intel Visual Fortran
Redistributables are required.
Error in ft_headmodel_simbio (line 90)
headmodel.stiff = sb_calc_stiff(headmodel);
 Error in ft_prepare_headmodel (line 467)
    headmodel = ft_headmodel_simbio(geometry,
    'conductivity', cfg.conductivity);

**Comment by schoffelen** [comment]
This is not the best place to ask this type of questions. Please sign up on the e-mail discussion list, and ask your question there.

http://www.fieldtriptoolbox.org/discussion_list/
