### ISSUE TITLE
ft_convert_coordsys fails when spm is not on the path

### ISSUE THREAD

**Issue by StolkArjen** [fieldtrip/fieldtrip#1257]
The error msg is quite self-explanatory, with function 'spm' not found when spm is not on the path. This can be easily fixed by a prior call to ft_hastoolbox (eg ft_hastoolbox('spm12',1)), but do we want this to be checked someplace downstream too? For instance, we could add a call to ft_hastoolbox in align_ctf2acpc.

Error msg:

ct_acpc = ft_convert_coordsys(ct_ctf, 'acpc');
converting the coordinate system from ctf to acpc
Undefined function or variable 'spm'.

Error in align_ctf2acpc (line 137)
  switch lower(spm('ver'))

Error in ft_convert_coordsys (line 104)
            obj = align_ctf2acpc(obj, method);

**Comment by robertoostenveld** [comment]
I added a call, but in such a way that it only gives a (meaningful) error. Deciding on the SPM version cannot be done this far down in the code.

**Comment by StolkArjen** [comment]
Great, thanks. Should we maybe also have ft_determine_coordsys check
whether spm's on the path?

**Comment by robertoostenveld** [comment]
AFAIK that function does not reply on SPM. It only makes a figue and asks some questions.

**Comment by StolkArjen** [comment]
Well, it calls that align function still, which relies on spm

**Comment by robertoostenveld** [comment]
> Well, it calls that align function still, which relies on spm

which align function?

**Comment by StolkArjen** [comment]
I am sorry, I meant to say ft_convert_coordsys, not ft_determine_coordsys,
which calls align_ctf2acpc

**Comment by robertoostenveld** [comment]
the low-level function now has the explicit detection opf SPM and the informative error, so no reason to also add it to the high level function.

**Comment by StolkArjen** [comment]
Ok, agreed
