### ISSUE TITLE
ft_datatype_sens stopped rescaling distance

### ISSUE THREAD

**Issue by vlitvak** [fieldtrip/fieldtrip#1263]
This line

 sens = ft_datatype_sens(sens, 'amplitude', 'V', 'distance', 'm');

stopped working after the switch to v2019 because you don't pass additional arguments in the recursive call.

**Comment by robertoostenveld** [comment]
can you send a PR to fix it?

**Comment by vlitvak** [comment]
Is there an elegant way to get all the arguments except 'version'?

**Comment by vlitvak** [comment]
Maybe not the most elegant but works:

around line 162:

new_argin = ft_setopt(varargin, 'version', '2016');
sens      = ft_datatype_sens(sens, new_argin{:});

I can't do a PR before Monday because my git stopped working and I can't update it myself. For us it's a critical fix because it breaks all our source analyses and Guillaume was just about to make an external release. I've checked in this fix into SPM already but of you can make either this or a better fix ASAP, that'd be great.
