### ISSUE TITLE
ft_senslabel returns incorrect labels for Neuromag 306 magnetometers

### ISSUE THREAD

**Issue by rbruna** [fieldtrip/fieldtrip#1264]
In function ft_senslabel, for Neuromag 306, the labels are defined:
{ GRAD2 GRAD3 MAG GRADCOMB }

In line 1628 the code takes the first column for magnetometers, instead of the third one:

      neuromag306_mag      = label(:,1);

The fix is simple:

      neuromag306_mag      = label(:,3);

This error only appears when the channel selection is performed through ft_senslabel, so maybe it has passed unnoticed until now (the last update of the file is from 2 years ago).

Thank you,
Ricardo Bruña

**Comment by robertoostenveld** [comment]
thanks for spotting this! I realize that @schoffelen mentioned something related to this, although I don't think it was the same issue but rather something with the template layouts.

**Comment by robertoostenveld** [comment]
I have made the change to the master branch, and hope to have it in the release soon as well. 

We currently have a minor issue in an unrelated function that is blocking the (automatic) release. See http://www.fieldtriptoolbox.org/development/dashboard/ for a description how that works.

**Comment by schoffelen** [comment]
We could consider renaming the test function for lagged coherence to failed, until it is looked into/resolved by the primary stakeholders?
