### ISSUE TITLE
eeglab2fieldtrip not working for componentanalysis

### ISSUE THREAD

**Issue by hydera2** [fieldtrip/fieldtrip#1266]
Hi, 
I did all my preprocessing in EEGlab and ERPlab and wanted to put in my ERP files into fieldtrip to do the cluster permutation analysis on my ERPs. I tried using the function eeglab2fieldtrip as specified in the following link: https://mailman.science.ru.nl/pipermail/fieldtrip/2006-March/000441.html
I used the 'component analysis' option eg: comp = eeglab2fieldtrip(ERP, 'componentanalysis').
However, I get the following error: 
Reference to non-existent field 'icachansind'.
Error in eeglab2fieldtrip (line 54)
 header.label   = { tmpchanlocs(EEG.icachansind).labels };

When I comment out these lines I run into another error:
Reference to non-existent field 'icaact'.

Error in eeglab2fieldtrip (line 119)
        if isempty(EEG.icaact)

It seems that this function requires ICA information in the EEGLAB ERP file, which isnt stored in the way that it is called. Can someone take a look into the function? Do I have to get the ERPs again in fieldtrip?

**Comment by schoffelen** [comment]
This has been taken up on the discussion list, which indeed is a more appropriate locaation
