### ISSUE TITLE
creating sensitivity maps à la MNE-python

### ISSUE THREAD

**Issue by dnacombo** [fieldtrip/fieldtrip#1273]
Trying to create a ft_sensitivitymap function, translating [python code](https://github.com/mne-tools/mne-python/blob/master/mne/proj.py#L331-L453) from MNE. 

Started a [branch](https://github.com/dnacombo/fieldtrip/blob/feature/sensitivitymap/forward/ft_sensitivitymap.m). Code is more like a draft right now. Options are not implemented.

Testing it with the practicalMEEG dataset and copied bits of pipeline_sourceanalysis. The file sensitivity map that I get seems off.

Can you provide guidance?

**Comment by robertoostenveld** [comment]
first step (I would say) is to figure out how this would be used by FT users. Could you write a (pseudo) script that demonstrates how the user would call this?

E.g. 

```
cfg = ...
sourcemodel = ft_prepare_leadfield(cfg)

cfg = ...
sensitivitymap = ft_sensitivitymap(cfg)

cfg = ...
ft_sourceplot(cfg, sensitivitymap)
```

This helps to define the input and output data structure, and the options. You can call the script `inspect_ft_sensitivitymap.m` and put it in fieldtrip/text (in your branch).

**Comment by dnacombo** [comment]
I would use it like this:

```
%% compute the forward model
cfg             = [];
cfg.channel     = label;
cfg.grad        = grad;
cfg.sourcemodel = sourcemodel;
cfg.headmodel   = headmodel;
cfg.method      = 'singleshell';
leadfield_meg   = ft_prepare_leadfield(cfg); % NOTE: input of the whitened data ensures the correct sensor definition to be used

%% sensitivity map
cfg             = [];
cfg.mode        = 'fixed'; % not sure what these different "modes" refer to in 
%                        the original MNE doc.
cfg.ch_type     = 'megplanar';
cfg.excludelist = badchannels;

leadfield_meg.smap = ft_sensitivitymap([],leadfield_meg);

%% plot on a mesh
figure;
ft_plot_mesh(sourcemodel,'vertexcolor',leadfield_meg.smap')
```

A real example is in [inspect_sensitivitymap](https://github.com/dnacombo/fieldtrip/blob/feature/sensitivitymap/test/inspect_ft_sensitivitymap.m) using the tutorial BIDS data from practicalMEEG

Eventually the sensitivity map could be returned by `ft_prepare_leadfield`...

**Comment by schoffelen** [comment]
@dnacombo Hi Max, How would you propose to progress here?
Besides creating a new function, there might be a possibility to consider adding this as diagnostic output to ft_prepare_leadfield

**Comment by schoffelen** [comment]
@dnacombo, is there any progress on this?

**Comment by dnacombo** [comment]
Not at the moment. I don't need this feature at the moment. Will look into it next time I need it.
