### ISSUE TITLE
(inconsistent) artefacts and errors in ft_volumesegment with spm12 old/new

### ISSUE THREAD

**Issue by vitpia** [fieldtrip/fieldtrip#1286]
Hi all, and in particular @mcvinding @robertoostenveld 

Here is a more thorough description of the issues I am encountering when using various options for ft_volumesegment of (maybe not so great quality) MRIs.

I've done several checks now, with permutations of 
1) coordsys ctf or acpc for ft_volumerealign
2) either with or without ft_volumereslice
3) spm8, and spm12 with either 'old' or 'new'

[Code](https://github.com/fieldtrip/fieldtrip/files/4080719/code.txt) attached, but the basics are:
```
mri = ft_read_mri([dirmri f(isub).name]);
cfg                     = [];
cfg.method              = 'interactive';
cfg.coordsys            = 'ctf';
mri_aligned_ctf         = ft_volumerealign(cfg,mri);
mri_reslice             = ft_volumereslice([], mri_aligned_ctf); 

% Segment anatomy
cfg                 	= [];
cfg.spmversion          = 'spm8';
cfg.output              = {'brain' 'scalp' 'skull'};
cfg.coordsyst               = 'ctf';
mri_segment_reslice_ctf_8   = ft_volumesegment(cfg, mri_reslice_ctf);
```
I've tried so many things that I don't even know anymore where/why artefacts are introduced, and which pipeline I should go for. The issue is the following:
ACPC with spm8, with or without reslicing seems fine
![image](https://user-images.githubusercontent.com/34679762/72663200-f7779e00-39ef-11ea-800c-efe6199e7e35.png)

CTF wiht spm8, artefact is introduced. I don't think it can be due to my placement of the fiducials, I've always done it this way but never saw this issue before.
![image](https://user-images.githubusercontent.com/34679762/72663137-3ce79b80-39ef-11ea-8503-9abc9b3d4d8b.png)

The artefact is more prominent with CTF but maybe because of some skull stripping with SPM12_old that is different for ACPC/CTF?
![image](https://user-images.githubusercontent.com/34679762/72664251-d6b54580-39fb-11ea-899f-3d466678fe91.png)

Finally, SPM12_new
![image](https://user-images.githubusercontent.com/34679762/72664254-e0d74400-39fb-11ea-9bde-0e1660377045.png)

SPM12 new is nicely segmenting the tumour in this case, better than SPM12 old, which is a good thing. But I still seem to have some artefacts (see picture above, the light blue pixels in the red box.
![image](https://user-images.githubusercontent.com/34679762/72664268-1845f080-39fc-11ea-96ec-cd6871f6f08b.png)

I've tried so many things by now that I'm a bit lost and don't know what is a real artefact, what I can ignore, which pipeline I should use, and whether this is an issue I should be reporting at all :)
But I promised @mcvinding I would do that, so here is the complete picture.

**Comment by schoffelen** [comment]
@vitpia what is the status of this? Do you still feel it is an issue that needs to be looked into? What are the next steps to take?

**Comment by vitpia** [comment]
This is how far I came in figuring out what the best option is, posting here for completeness. I did not continue these analyses, so for me the issue can be closed, but the question is whether it is worth looking at how spm12 old/new is being used by different functions. Shall I close the issue?
(All trials now using the current version of FT on the DCCN cluster)

Either aligning with acpc of ctf yield the same output with spmmethod = ‘new’ even if I don’t use any explicit template:
Original MRI
![origMRI](https://user-images.githubusercontent.com/34679762/76944010-92adc680-6900-11ea-93a2-4fe2e67468eb.jpg)

`cfg                     = [];`
`cfg.method              = 'interactive';`
`cfg.coordsys            = 'ctf';`
`mri_aligned             = ft_volumerealign(cfg,mri); % patient’s original MRI`
`mri_reslice             = ft_volumereslice([], mri_aligned);`
 
`cfg                     = [];`
`cfg.coordsyst           = 'ctf';`
`cfg.spmversion = 'spm12';`
`cfg.spmmethod      = 'new';`
`cfg.output              = {'brain' 'scalp' 'skull'};`
`mri_segment           = ft_volumesegment(cfg, mri_reslice);`
![segmentation](https://user-images.githubusercontent.com/34679762/76944084-b244ef00-6900-11ea-972f-6b9f82003bfe.png)

If I default back to spmmethod = ‘old’ but still ‘spm12’ I see one artefact in the brain compartment:
![seg2](https://user-images.githubusercontent.com/34679762/76944281-051ea680-6901-11ea-8a18-0c1480fd1fae.png)

The same 'spm12 new' gives bad results when used for the segmentation, but to create the sourcemodel (ft_prepare_sourcemodel), 'spm12 new' is giving a better output (see below), which had failed entirely with 'spm12 old'.
![sourcemodel](https://user-images.githubusercontent.com/34679762/76944486-5e86d580-6901-11ea-9f36-9a09fc458b92.png)

So for now what seems to work best is 'spm12 old' for segmenting, then 'spm12 new' for ft_prepare_sourcemodel.

**Comment by schoffelen** [comment]
I think it may be worthwile to look into the difference, but given the information posted above, it is still rather anecdotal (i.e. given the specific example MRI). Besides, somebody needs to spend some time to try and understand what is happening, and if you (or someone from your group) is not going to do it, I am not sure whether this will ever happen. 

From what I can take home from this, it seems a subtle interaction between the different versions of the segmentation, the coordinate system of the input MRI, reslicing yes or no, (have we already considered bias correction of the input images?) etc. Also, it is somewhat worrisome that the segmentation step works best with a different version of SPM than the sourcemodel creation (although I don't understand what spm12 does when creating the sourcemodel).

Would it be possible to extract some generic recommendations from all this, that can be made into a FAQ? For instance: what is the best strategy for anatomical segmentation if my anatomical MRI is of poor quality?

PS: have you tried the 5 tissue type segmentation from mrtrix?

**Comment by vitpia** [comment]
I did try different coordinate systems and reslicing options, what made the difference was the spm12 version (old/new) in interaction with segmentation vs sourcemodel, not the other steps. 
I'm not sure I have general recommendations for now. As you point out, these clinical MRIs may be causing the issue, which most people will never encounter. 
In thinking ahead, though, we are working on FEM for MEG, and that is also failing as soon as there's a slightly bad feature in the segmentation, which would go unproblematic for the 'singleshell'. So I will continue looking into this issue. 
I have great segmentations from mrtrix, I will work on getting those into Matlab-FT compatible and how to proceed with the forward model from there. I think only then I can make recommendations!
I'm closing the issue for now and will write a FAQ once I have a good-enough suggestion/solution.

**Comment by schoffelen** [comment]
OK, just as a follow up: fieldtrip supports the mrtrix image format, so getting in the segmentations is really straightforward. We'd only need some glue code to label the individual volumes according to the individual tissue types, and probably need some code in ft_prepare_headmodel to deal with it appropriately.
