### ISSUE TITLE
Overlapping warning too noisy in ft_fetch_data

### ISSUE THREAD

**Issue by rbruna** [fieldtrip/fieldtrip#1292]
Hello,

I have a small suggestion to reduce the on-screen noise when re-segmenting overlapping data. With the current configuration, it complains when 'allowoverlap' is set to true, either if the overlapping data is identical or not, but it does not complain when it is set to false if the data is indeed identical. 

In my opinion, ft_fetch_data should only complain with a warning when data is overlapping and different in different appearances, as otherwise there is absolutely no issue (as indicates the fact that, when no overlap is allowed, it does not pose a problem).

Thank you!

**Comment by robertoostenveld** [comment]
Hi Ricardo,

FIeldTrip is indeed not very consistent with the amount of information/warning/debug statements printed on screen. I suspect that the one you are seeing is  
```
      ft_warning('samples present in multiple trials, using only the last occurence of each sample')
``` 
on line 171 in ft_fetch_data.

Can you first try whether 
```
ft_warning off
``` 
solves it? You can also switch specific warnings off. Please see the help of ft_warning. 

best regards,
Robert

**Comment by rbruna** [comment]
Hello, Robert,

Indeed, that was the warning I was referring to. And, as you indicate, the use of

`ft_warning off`

removes the warning. However, I am worried I miss some important warning, and this specific warning does not have an identifier (so I cannot turn only it off).

In any case, I still think that the warning should only appear when samples are different (and there is indeed a possible issue), but is is only my opinion.

Thank you for your help!

Best,
Ricardo

**Comment by robertoostenveld** [comment]
every ft_warning automatically gets an identifier (based on the string). Could you see whether you can switch it off specifically? Would be interesting whether it is clear for you, or whether more documentation/explanation is needed.

**Comment by rbruna** [comment]
Hello again,

When setting the `verbose` mode to `on`, I get:

<pre>Type "ft_warning off FieldTrip:ft_fetch_data:line171" to suppress this message.</pre>

Using this effectively removes the warning, but it is, in my opinion, strongly dependent on the FieldTrip version.

Maybe a method based on the string itself (for example its MD5 hash) could be more appropriate? It would be more stable across FieldTrip versions, and it would remove any appearance of the string in other functions.

**Comment by robertoostenveld** [comment]
cool, so that works for you! That in itself is already useful for us to know, since this feature has not been so widely discussed/tested yet.

it would not depend *stongly* on the FT version, since in most code the line numbers don't change that often. And if they do, the warnings would re-appear. That would be annoying, but still a safe option. 

The warning strings themselves are not that unique, so an md5-hash would not be unique either. 

But let's try not to digress: there is now one work-around confirmed to work. However, we still might want to make the "information" (error/warning/notice/info/debug) more appropriate. 

In this case (on line 171) I would say that the warning is not needed in case the samples have the same value. Just like the error a few lines up being conditional on them having the same value.

So should it not be something like

```
if any(count>1)
  % detect whether the overlapping samples are identical
  ... 

  if isidentical
     % no worries
  elseif ~isidentical && allowoverlap
    % print warning 
  elseif ~isidentical && ~allowoverlap
    % give error
  end
end
```

**Comment by robertoostenveld** [comment]
I tried the following
```
function test_issue1292


%% This one has identical overlap

data1 = [];
data1.label = {'1'};
data1.trial{1} = 1*ones(1,100);
data1.trial{2} = 1*ones(1,100);
data1.time{1} = 1:100;
data1.time{2} = 1:100;
data1.sampleinfo = [
  1 100
  91 190
  ];

%% This one has non-identical overlap

data2 = [];
data2.label = {'1'};
data2.trial{1} = 1*ones(1,100);
data2.trial{2} = 2*ones(1,100); % NOTE HERE
data2.time{1} = 1:100;
data2.time{2} = 1:100;
data2.sampleinfo = [
  1 100
  91 190
  ];

%%

dat1a = ft_fetch_data(data1, 'begsample', 1, 'endsample', 190);

%%

dat1b = ft_fetch_data(data1, 'begsample', 1, 'endsample', 190, 'allowoverlap', true);

%%

dat2a = ft_fetch_data(data2, 'begsample', 1, 'endsample', 190);

%%

dat2b = ft_fetch_data(data2, 'begsample', 1, 'endsample', 190, 'allowoverlap', true);
```

and see that `dat1a` is silent, `dat1b` gives a warning (not needed), `dat2a` gives error (correct), and `dat2b` gives warning (which I consider appropriate).

Do you agree with this analysis? If so, could you propose a change to the warning generating section (as outlined in my previous comment) and send that as pull request? See http://www.fieldtriptoolbox.org/development/git/ if you have never done this before. Or (simpler) go to https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_fetch_data.m and click on the pencil (edit this file) in the upper right corner.

**Comment by rbruna** [comment]
Hello, Robert,

exactly my thought. If samples are identical, no problem either if the overlap is allowed or not (in my opinion, at least), and if they are not, the warning or error should appear.

The code is already in the _error_ option (i.e. no overlap allowed):

<pre>
    if ~allowoverlap
      % ft_error('some of the requested samples occur twice in the data');
      % this  can be considered OK if the overlap has exactly identical values
      sel = find(count>1); % must be row vector
      for smplop=sel
        % find in which trials the sample occurs
        seltrl = find(smplop>=trl(:,1) + 1 - begsample & ... 
                      smplop<=trl(:,2) + 1 - begsample);  % which trials, requires the adjustment with begsample, if different from 1, JM 20180116
        selsmp = smplop - trl(seltrl,1) + begsample; % which sample in each of the trials, requires the adjustment with begsample, rather than 1
        for i=2:length(seltrl)
          % compare all occurences to the first one
          % consider also mutual occurring NaNs as equal values
          if ~all(isequaln(data.trial{seltrl(i)}(:,selsmp(i)), data.trial{seltrl(1)}(:,selsmp(1))))
            ft_error('some of the requested samples occur twice in the data and have conflicting values');
          end
        end
      end
    else
      ft_warning('samples present in multiple trials, using only the last occurence of each sample')
    end
</pre>

So it would only require to put the conditional inside the block, instead of on a higher level:

<pre>
    allequal = true;
    sel = find(count>1); % must be row vector
    for smplop=sel
      % find in which trials the sample occurs
      seltrl = find(smplop>=trl(:,1) + 1 - begsample & ... 
                    smplop<=trl(:,2) + 1 - begsample);  % which trials, requires the adjustment with begsample, if different from 1, JM 20180116
      selsmp = smplop - trl(seltrl,1) + begsample; % which sample in each of the trials, requires the adjustment with begsample, rather than 1
      for i=2:length(seltrl)
        % compare all occurences to the first one
        % consider also mutual occurring NaNs as equal values
        if ~all(isequaln(data.trial{seltrl(i)}(:,selsmp(i)), data.trial{seltrl(1)}(:,selsmp(1))))
          allequal = false;
          break;
        end
      end
      if ~allequal, break, end
    end
    if ~allequal
      if allowoverlap
        ft_warning('some of the requested samples occur twice in the data and have conflicting values; using only the last occurrence of each sample');
      else
        ft_error('some of the requested samples occur twice in the data and have conflicting values');
      end
    end
</pre>

**Comment by rbruna** [comment]
Robert, your analysis seems correct.

Silencing the warning, as expected, removed both the undesired and the correct warnings.

> Do you agree with this analysis? If so, could you propose a change to the warning generating section (as outlined in my previous comment) and send that as pull request?

I will get to it right now.

Thanks!

**Comment by robertoostenveld** [comment]
the test script as a whole failed, which was not good. In that case new versions of fieldtrip cannot be released. 

I changed it such that it checks for the (expected) error, and if so, it passes. If the error does not happen, it fails.

**Comment by schoffelen** [comment]
Thanks. my thinking was to pull it in and indeed fix it should it cause problems. It's a bit much of a hassle to try and pull the PR locally in order to test before merging. Next time, just assign to me

**Comment by rbruna** [comment]
Hello,

I am sorry, I did not think of this issue. Of course, the code should get an error, but I did not know this was not allowed in test functions.

Thank you very much for the fix!
