### ISSUE TITLE
Issue with non-param CBPT plot

### ISSUE THREAD

**Issue by josejperez** [fieldtrip/fieldtrip#1298]
I was checking the ["Parametric and non-param stats..."](http://www.fieldtriptoolbox.org/tutorial/eventrelatedstatistics/) tutorial with the exact same example data (ERF_orig.m) that is suggested. The "issue" arose when computing the non-parametric test with cluster-based multiple comparison correction. In the tutorial figure: ![tutorial figure](http://www.fieldtriptoolbox.org/assets/img/tutorial/eventrelatedstatistics/figure7.png) appears to be 2 clusters, left and right lateralized. Whereas in the figure I get ![figure I get](https://user-images.githubusercontent.com/29755416/74044918-cc1b1a00-49c3-11ea-95f2-432dda5ed1d2.png) only the bigger cluster appears, left lateralized. I wonder if it has anything to do with a new cluster-formation or MC criteria, since I'm in the latest version (fieldtrip-20200130) of fieldtrip.
Thank you!

**Comment by robertoostenveld** [comment]
I had also noticed this. I suspect the figure was made with slightly different settings of the script, and the text (and settings) of the tutorial were updated later; It is hard to keep them all in sync. 

Your figure is exactly when following the tutorial? If so, could you recreate the figures, copy them to (your clone of) https://github.com/fieldtrip/website/tree/master/assets/img/tutorial/eventrelatedstatistics and make a pull request? See the [git tutorial](http://www.fieldtriptoolbox.org/development/git/) if needed.

**Comment by robertoostenveld** [comment]
oh, and this issue (and especially the PR) should be discussed in http://github.com/fieldtrip/website and not here, since there is not an issue with the code AFAIK.

**Comment by josejperez** [comment]
Thank you for your answer!

I just made the pull request for that figure, I hope it helps.

**Comment by schoffelen** [comment]
This has been properly addressed by now, and merged (in the website repo)
