### ISSUE TITLE
 .c3d files not readable with ft_read_header for Windows computer

### ISSUE THREAD

**Issue by helenacockx** [fieldtrip/fieldtrip#1303]
When trying to read a c3d-file on my Windows computer using ft_read_header, I got following error:

_Warning: cannot determine whether the EZC3D toolbox is present 
Warning: adding C:\Users\helen\Documents\MATLAB\matlab_toolboxes\fieldtrip\external\ezc3d toolbox to
your MATLAB path 
Undefined function or variable 'ezc3dRead'._

_Error in motion_c3d (line 57)
  c3d = ezc3dRead(fullname);_

_Error in ft_read_header (line 2595)
      hdr = feval(headerformat, filename);_
 
Apparently this error is Windows specific, which is not able to use the function 'ezc3dRead' of the added toolbox.
(sorry, .c3d-files are not supported to add in this issue report...)

@robertoostenveld

**Comment by robertoostenveld** [comment]
it is because the mex file is not compiled for windows. I will have to download https://github.com/pyomeca/ezc3d again on a windows computer to compile it.
