### ISSUE TITLE
ft_datatype_sens renames NIRS opto fields, but other code expects old fieldnames

### ISSUE THREAD

**Issue by Horschig** [fieldtrip/fieldtrip#1309]
In line 166 ff, ft_dataytpe_sens renames some fields in data.opto, especially opto.transceiver to opto.transmits. Code in other functions, however, like ft_nirs_transform_ODs, do access opto.transceiver.

Proposed fix: 
As discussed a couple of months ago, change the fieldnames in all functions.

**Comment by robertoostenveld** [comment]
Please send a pull-request, since it mainly affects the artinis code (including p-files).

**Comment by Horschig** [comment]
changed and tested (using own test scripts and data and tutorial scripts).

Please see https://github.com/fieldtrip/fieldtrip/pull/1208
