### ISSUE TITLE
 [ft_definetrial] remove cfg.event from output cfg

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/fieldtrip#1310]
cfg.event is not required anymore after running ft_definetrial (the relevant information is present in cfg.trl). Therefore remove it from the output cfg.

@Spaak @robertoostenveld @schoffelen

**Comment by robertoostenveld** [comment]
searching through the code, I only see `cfg.event` used in ft_definetrial (as expected) and ft_databrowser. In the latter, there is this


    cfg.event           = ft_getopt(cfg, 'event');                       % this only exists for backward compatibility and should not be documented

which looks good to us (i.e. indicating deprecated use), but also some potentially problematic use later in the code around [here](https://github.com/fieldtrip/fieldtrip/blob/71472af4bf6c158c7caba42df535dff8d7977320/ft_databrowser.m#L1029) which results in [this line](https://github.com/fieldtrip/fieldtrip/blob/71472af4bf6c158c7caba42df535dff8d7977320/ft_databrowser.m#L795) where a modified version of `opt.event` is returned.

this relates to some (to be obscure) `cfg.selectmode` behaviour. Searching for it returns actual results from 2013, but not later. See http://www.fieldtriptoolbox.org/search_results/?q=cfg.selectmode

**Comment by robertoostenveld** [comment]
there is also `test_issue1067` and `test_issue789` that use it.

**Comment by robertoostenveld** [comment]
there is also `ft_fetch_event`, which gets it from `data.cfg.previous.previous.event`.

The way that ft_databrowser gets the events from `data.cfg.event` (only one level deep, as per http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2501) is not so flexible as the way from ft_fetch_event, but ft_databrowser has this additional check on `origfs` to figure out whether the events are still applicable to the data (which is not the case after resampling).

A first step would be to merge the ft_databrowser code with that of ft_fetch_event. That could then also be extended to allow `data.event` to be specified, just like `data.hdr`, to add the events to the data.

**Comment by matsvanes** [comment]
See #1317

**Comment by robertoostenveld** [comment]
this code uses `ft_findcfg`. I propose to rename that to `findfield`, in line with `keepfields` etc.

**Comment by matsvanes** [comment]
Instead of removing 'event' from output-cfg in all cases, for reproducescript I remove it manually in #1359
