### ISSUE TITLE
[reproducescript] issue with comment "new input file"

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/fieldtrip#1312]
If reproducescript writes a cfg-field to disk, which is used by a next fieldtrip call, a comment is written in the generated script, indicating that is a new file that enters the pipeline. This should be removed. The comment should only be written when there is a change to the data outside of fieldtrip @Spaak.

**Comment by Spaak** [comment]
Feel free to assign to me (or give me permissions to assign issues?)

**Comment by robertoostenveld** [comment]
@Spaak I don't really understand how the roles work in general (*), nor specific w.r.t. permissions of assigning people. But I tried to update the roles and permissions. Could you try whether you now can change the assignees? 

*) github seems to be updating the features related to this continuously

**Comment by Spaak** [comment]
I was able to **un**assign myself, but I don't think I can re-assign myself now. There is this page: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

Maybe I need 'Triage' permissions?

**Comment by robertoostenveld** [comment]
that would make sense. However, I cannot find it anywhere in the settings. Let's not waste time on it now. Better sit together at a later time and have a joint look at the management options.

**Comment by Spaak** [comment]
See #1330
