### ISSUE TITLE
prepare_mesh_hexahedral.m does not require simbio toolbox

### ISSUE THREAD

**Issue by ftadel** [fieldtrip/fieldtrip#1318]
The function prepare_mesh_hexahedral.m requests the simbio toolbox:
https://github.com/fieldtrip/fieldtrip/blob/f67c00431828af4777ac27b464d6adfd9d4ac884/private/prepare_mesh_hexahedral.m#L145

But works well without it (ie. with the fieldtrip-lite distribution).
Maybe this statement could be removed...

**Comment by robertoostenveld** [comment]
agreed, that seems to be an outdated requirement. I'll remove it. 

thanks
