### ISSUE TITLE
Atlas VTPM not correct

### ISSUE THREAD

**Issue by yingjoeyzhou** [fieldtrip/fieldtrip#1319]
`load ([ftpath,'/template/atlas/vtpm/vtpm.mat'], 'vtpm');`

Note here ftpath is the path in DCCN cluster, which i would assume to have the most updated version of fieldtrip.

While `numel( vtpm.tissuelabel ) = 50`, `max( vtpm.tissue(:) ) = 25` and `min( vtpm.tissue(:) ) = 0`.

Needs to be fixed.

**Comment by schoffelen** [comment]
Please go ahead and fix it. I don't know about this atlas, perhaps you could first check what the expected number of parcels is, and whether the tissuelabel is consistent with this number, or whether the values in tissue are consistent with this label. Then, you can try and find out why one of the two is inconsistent. Next, we can try and find a way to make the atlas consistent (and/or update the reading code so that all is aligned again.)

**Comment by yingjoeyzhou** [comment]
ok, I will try to fix it. I will label it as work in progress.

**Comment by schoffelen** [comment]
One obvious cause of a mismatch could be that the tissuelabel distinguishes the left and right hemispheres, while the tissue-field does not.

**Comment by schoffelen** [comment]
Note: if that is true, it is straightforward to fix, but don't forget to update the description on the website

**Comment by schoffelen** [comment]
Please confirm that the vtpm.mat consists of a blend of the original maxprob volumes lh/rh, as present in the Probatlas_v4/subj_vol_all. To me this means that the volumetric data is consistent with the distributed maxprob atlas, only the indices are not consistent with the labels, and as of yet the labels do not distinguish left from right it seems.

**Comment by schoffelen** [comment]
Also, the tissuelabel is a row vector as of yet, should be column vector.

**Comment by yingjoeyzhou** [comment]
I am currently working on it ~ I will send you the updated atlas and the
code to make it by the end of today.

**Comment by schoffelen** [comment]
I suggest at minimum to update the template/atlas/vtpm/vtpm.mat file to be internally consistent.
Probably in terms of file size it might be good to consider to keep  the tissue field in int8.

Starting from the original volumetric maxprob files:

x = ft_read_mri('maxprob_vol_lh.nii.gz');
y = ft_read_mri('maxprob_vol_rh.nii.gz');

z = rmfield(z,'anatomy');
y.anatomy(y.anatomy~=0) = y.anatomy(y.anatomy~=0)+25;
z.tissue = x.anatomy+y.anatomy;

z.tissuelabel = vtpm.tissuelabel(:);
for k = 1:25
z.tissuelabel{k} = {z.tissuelabel{k},'_lh'};
z.tissuelabel{k+25} = {z.tissuelabel{k+25},'_rh'};
end
vtpm = z;

**Comment by yingjoeyzhou** [comment]
[vtpm.zip](https://github.com/fieldtrip/fieldtrip/files/4244827/vtpm.zip)

**Comment by yingjoeyzhou** [comment]
see above for code and the updated vtpm fieldtrip-friendly atlas.

**Comment by schoffelen** [comment]
thanks. I checked the code+file, changed the tissuelabel into a column vector and pushed the updated file to the fieldtrip master branch. If the testing framework runs through, it will be in the release version, and on /home/common as of tomorrow.

Now the only thing that is left, is to update the documentation (i.e. describe that it's the combined lh/rh maxprob image, where the lh indices are the +25 version of the original) + figure needs an update.

**Comment by schoffelen** [comment]
I also found this: https://mailman.science.ru.nl/pipermail/fieldtrip/2017-July/011681.html

Although it seems from the e-mail correspondence that there might be something fundamentally wrong with the maxprob based atlases that have been contributed by the original contributors, if you care a lot about this particular atlas, it might be worth looking into

**Comment by yingjoeyzhou** [comment]
The maxprob map is indeed problematic. 

I am creating the masks for each ROI myself now :) 

Intuitively, I just read in the probabilistic map (e.g., that of V1v) from the original resource (i.e., Kastner lab), and set a threshold for my ROI mask. For example, only take voxels with probabilities >= 0,5. This allows much better voxel selection especially for higher level areas which, across subjects, have a high variance in the MNI coordinates.

Maybe I can share my experience in the tutorial afterwards?

**Comment by schoffelen** [comment]
what is the status of this?
If it's worthwile to share the probabilistic maps, and a corresponding recipe to create the ROIs based on probabilistic thresholding, then please create a corresponding file + the added documentation. My suggestion would be to create a 4D niftifile + a list of labels, with the left and right hemispheric areas separately represented as a volume. The original data is very poorly documented, and there does not seem to be much incentive to maintain it on their end.

Also, please check whether the missing area (right IPS I believe) is absent from the probabilistic maps. It seems to be missing from the maxprob volume

**Comment by yingjoeyzhou** [comment]
I have all the ingredients (i.e., the atlas based on maxprob, and the
probabilistic maps of each ROI) and I am currently using it for my
analyses. Just need to find time (later this week or next) to document it.

**Comment by schoffelen** [comment]
What is needed from me to finalize this?

**Comment by yingjoeyzhou** [comment]
nothing :)

**Comment by schoffelen** [comment]
Is this ever going to be finished? If not, I will close this issue.

**Comment by yingjoeyzhou** [comment]
sorry for the confusion - yes please close this issue. i think the vtpm
template in the master is already updated.

**Comment by schoffelen** [comment]
Indeed the template has been updated, but I was waiting (and hoping for) a contribution from your end, kind of as a reward for the time I spent on this. You mentioned a strategy to convert the probabilistic images more flexibly into a set of ROIs description.

**Comment by yingjoeyzhou** [comment]
ah that's what you were looking for! now i see the point. maybe i can share
this knowledge as a faq page on the website.
