### ISSUE TITLE
edf channel selection bug

### ISSUE THREAD

**Issue by jdien07** [fieldtrip/fieldtrip#1320]
The edf reader has some rather complicated rules for dealing with heterogeneous channel sampling rates, so it's my preference to just pull out the channels one at a time.  In the present case, the edf file has a number of EEG channels with a sampling rate of 256Hz but also several non-EEG channels (also desired) that have other sampling rates.  I would like to be able to extract the non-EEG channels as well.  However, it is not currently possible (fieldtrip-20200224) to select out the channels with divergent sampling rates.  chanData=ft_read_data(fileName,'dataformat',fileFormat,'headerformat',fileFormat,'chanindx',2);
results in an error message, which happens because it calls ft_read_header which then sets a 'chansel' field to 2 and then read_edf attempts to read a second number from this field, which doesn't exist:

  elseif ~isempty(chanindx) &&  isfield(EDF, 'chansel')
    % a subset of channels should been selected from the predefined list
    chanindx = EDF.chansel(chanindx);

Index exceeds the number of array elements (1).

Error in read_edf (line 345)
    chanindx = EDF.chansel(chanindx);

Error in ft_read_data (line 731)
    dat = read_edf(filename, hdr, begsample, endsample, chanindx);
 
in other words, the channel selection is happening twice, first via chansel and then a second time via chanindx.  Alternatively, one can use the command: 
chanData=ft_read_data(fileName,'dataformat',fileFormat,'headerformat',fileFormat,'chanindx',2,'header',hdr);
In this case, there is no 'chansel' field in the header but hdr itself prunes itself of all the channels with divergent sampling rates, in which case the channel that results is the second of the remaining channels, not necessarily the desired one.

I'm a little hesitant to muck with this code as it would likely break things for other users since it is quite complicated and I'm not exactly sure why things are the way they are.  I'm thinking a possible way forward would be for there to be two channel selection fields in hdr.orig, the existing chansel one that would be used for user specified channel selection and a second one that would only be used for the kind of automatic channel selection performed by the edf reader.  That way read_edf could know not to apply the user specified channel selection redundantly.  How does this sound?

**Comment by jdien07** [comment]
[000810000.230120.122109.Signals.Raw.edf.zip](https://github.com/fieldtrip/fieldtrip/files/4252571/000810000.230120.122109.Signals.Raw.edf.zip)

**Comment by schoffelen** [comment]
Hi Joe,

Thanks for your message. I am  not so familiar with this file format, but reading your detailed diagnostic description, and quickly checking the code I would think that a principled solution should be possible. 

I guess that it eventually should work robustly, both when attempting to read a specified channel using ft_preprocessing, and when reading in at the level of ft_read_data, both with and without a pre-loaded header.

Right now, there seems to be an unpredictable interaction between the header reading bit and the presence of a user-defined chanindx. 

Right now, ft_read_data reads in the header on the fly, which is done incorrectly in the presence of a chanindx (possbly a vector), since ft_read_header (called by ft_read_data) always uses chanindx = 1 in this case (line 815 in ft_read_header).

Next, indeed as identified by @jdien07 a preselection of channels using the complicated heuristic as outlined in the help of read_edf yields the chansel field in hdr.orig, which would then require an update to the chanindx.

**Comment by robertoostenveld** [comment]
I realize that the reading of channels from files with multiple sample rates (not only EDF) is messy. 

I have copied the test file to our internal file server as `/home/common/matlab/fieldtrip/data/test/issue1320/000810000.230120.122109.Signals.Raw.edf`

The next would be to implement a `test_issue1320.m` script (or function) that demonstrates the intended usage and that (right now) gives an error. Then the FT code should be updated to make the specific error disappear, without introducing any (regression) errors in the other test scripts.

However ... I am not sure whether code changes are needed. Have you checked `edf2fieldtrip`? Please try the following

```
filename = dccnpath('/home/common/matlab/fieldtrip/data/test/issue1320/000810000.230120.122109.Signals.Raw.edf');

hdr = ft_read_header(filename);
orig = hdr.orig;

hdr = {};
for i=1:orig.NS
  hdr{i} = ft_read_header(filename, 'chanindx', i);
end

dat = {};
for i=1:orig.NS
  dat{i} = ft_read_data(filename, 'header', hdr{i}, 'chanindx', 1, 'begsample', 1, 'endsample', hdr{i}.Fs);
end
```

**Comment by robertoostenveld** [comment]
in the previous example, each of the 31 headers represents one specific channel from the original EDF file. Using those in ft_read_data, and telling that it should read the 1st (and only) channel from that header specification, you can read all channels.

**Comment by jdien07** [comment]
Ah, very good!  Yes, this suggested approach is working for me.  I didn't know about edf2fieldtrip.  Perhaps it should go into the fileio directory?  Anyway, since there is a workaround, doesn't seem worth the work to address the issue as long as folks can find edf2fieldtrip.  Thanks!

**Comment by robertoostenveld** [comment]
the xxx2fieldtrip functions typically return a high-level FT data structure, not a chansXtime matrix, that is why they are in the top level directory.
