### ISSUE TITLE
problem reading the data (EGI mff.format)

### ISSUE THREAD

**Issue by SayaKidby** [fieldtrip/fieldtrip#1321]
This is my first time to use Field trip. I was simply trying to read the data, with the code of; 

FTDat_ABP04_Aacc = ft_read_data('AB_P04_A-correct.mff');

and then I got this error message popping up ;
"ft_getopt.mexmaci64" cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

I'm using the MacBook Air 2018, OS Catalina 10.15.13. 

Sorry for the trouble - thank you for your help in advance.

<img width="411" alt="Screenshot 2020-02-28 at 21 37 27" src="https://user-images.githubusercontent.com/61603836/75589972-2152c480-5a74-11ea-92e0-5660c25d4290.png">

**Comment by schoffelen** [comment]
Please subscribe to, and check the fieldtrip discussion list. There is a recent thread which addresses this.

**Comment by schoffelen** [comment]
http://www.fieldtriptoolbox.org/discussion_list/
