### ISSUE TITLE
print volume of different compartments following segmentation 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1328]
following discussion with @mcpiastra, we think it would have a lot of diagnostic value to print the volume (in milliliter) of the different tissue types. Preferably this would be printed in a function that is called often (e.g. checkdata) and not only immediately following segmentation.

**Comment by schoffelen** [comment]
See also: http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3272

**Comment by schoffelen** [comment]
with the issue pointing to the bugzilla bug and vice versa, we have created an endless loop...loop...loop

**Comment by schoffelen** [comment]
What about adding this to ft_datatype_segmentation?
