### ISSUE TITLE
Cluster-Based Permutation Test Tutorial

### ISSUE THREAD

**Issue by rpriefer** [fieldtrip/fieldtrip#1332]
Hello,

I work as a Lab Coordinator for the Neurocognition of Communication Disorders Lab at Adelphi University, New York. We are looking to perform a cluster-based permutation test on our EEG data but have some questions as we are quite unfamiliar with how to apply it to this data in particular, and neither of us are too familiar with Matlab code.

We have attempted to utilize the bountiful tutorials FieldTrip provides on their website and YouTube channel to no avail. We are simply not savvy enough with Matlab code, and would really appreciate if someone could provide some clarity on the process.

We collect our EEG data using a 128-HydroCel Geodesic Sensor Net from EGI/Philips, and therefore we have used NetStation to do most of our processing in the past. Anyway, that is our setup.

Some initial questions:
1. I am assuming all of this analysis could be one on an averaged EEG file - but what file type works best? The default for EGI is .mff, but we could use .raw, .mat, .txt, and so on...
2. If not, should we be doing our processing entirely within FieldTrip? That's what the [tutorial online](http://www.fieldtriptoolbox.org/tutorial/cluster_permutation_timelock/) suggests. We are familiar with EEGLAB which we understand may work in tandem with FT.

Other than this, we have very little knowledge and understanding of how to proceed within FieldTrip. The coding seems straightforward enough but we still can't seem to progress very far. I think it is just a fundamental misunderstanding on our parts.

Please advise as to what to do, or what further information you'd like from us.

Thank you,

**Comment by schoffelen** [comment]
I suggest that you ask this on our discussino forum: see http://www.fieldtriptoolbox.org/discussion_list/
for instructions to subscribe etc.
Also, see http://www.fieldtriptoolbox.org/faq/how_to_ask_good_questions_to_the_community/
to sharpen your questions (that is: beyond the questions 1 and 2 it is unclear what the 'misunderstanding' is about).

**Comment by schoffelen** [comment]
To clarify: The discussion list is read by a large sample of the fieldtrip community, which represents a good deal of practical know-how. The github issues are not directly linked from anywhere, so only few people are aware that they exist, thus it provides a narrow base for knowledge transfer.
