### ISSUE TITLE
selection of reference channels failed for combined MEG-EEG data

### ISSUE THREAD

**Issue by awollbrink** [fieldtrip/fieldtrip#1334]
for a combined MEG-EEG dataset recorded with the CTF 275 sensor system the channel selection for extracting the reference channels fails.
Applying ft_preprocessing with cfg.channel = {'megref'} results in a data structure containg the 29 reference sensors plus some EEG sensors which channel labels start with the letter 'P'.
I am using Fieldtrip revision 93dd0f61b on a Ubuntu 18.04 system.
For further verification attached you can find an tar archive containing a data .mat file and a matlab script.
[IBB-MEEG.zip](https://github.com/fieldtrip/fieldtrip/files/4324224/IBB-MEEG.zip)

**Comment by schoffelen** [comment]
Thanks Andreas,
We'll check whether we can confirm the issue with a more recent version of the code :)

**Comment by schoffelen** [comment]
OK, confirmed.

**Comment by schoffelen** [comment]
selection fails in ft_selectdata, line 651, where ft_channelselection is called

**Comment by schoffelen** [comment]
I notice that the logic is not fully robust to begin with, because ft_selectdata makes an exclusive selection of going into the 'grad' or 'elec' mode, whereas both a 'grad' and 'elec' could be present in the data. 
Yet, in addition, apparently the automatic selection of the megref labels from a list of labels that contain, besides the ctf sensor names EEG channel labels is insufficiently robust in ft_channelselection

**Comment by schoffelen** [comment]
Ah, I think that this is caused by the EEG channels in your data to have 'proper names' rather than the generic EEG123 labels.

in case of ctf data, fieldtrip identifies all channelnames that start with P as reference

**Comment by schoffelen** [comment]
Ah, I think that this is caused by the EEG channels in your data to have 'proper names' rather than the generic EEG123 labels.

in case of ctf data, fieldtrip accepts all channels that start with 'P' as meg reference channel

**Comment by schoffelen** [comment]
https://youtu.be/gg0I9rskXTk

**Comment by schoffelen** [comment]
I see two things that can be improved:
* make ft_channelselection a bit smarter with a hard coded list of reference channel names
* make the handling of the selection in ft_selectdata more robust, i.e. treat both grad and elec as a separate case (operating on the subset of channels in the varargin.label that are of generic meg or eeg chantype.

@robertoostenveld, any quick thoughts?

**Comment by robertoostenveld** [comment]
the selection should preferably be done with a combination of chantype (which for CTF is based on the res4 header details)  and label. But right now `ft_channelselection` does not know about chantype at al (because its implementation predates the introduction of chantype).

**Comment by schoffelen** [comment]
http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2028

**Comment by schoffelen** [comment]
PR #1342 fixes this, @awollbrink please confirm this, and feel free to reopen this if needed.

**Comment by awollbrink** [comment]
confirmed

**Comment by schoffelen** [comment]
Thanks and take care.
