### ISSUE TITLE
ft_prepare_layout does not convert 3D optode positions into 2D layout

### ISSUE THREAD

**Issue by helenacockx** [fieldtrip/fieldtrip#1335]
When creating a layout for nirs optodes based on their 3D optode positions, you got the following error: 
> Unable to perform assignment because the size of the left side is 1-by-3 and the size of the right side is 1-by-2.
> Error in ft_prepare_layout (line 1122)
>     layout.pos(end+1,:) = [min(pos(:,1))-width/2 min(pos(:,2))-height/2];

This is because 3D positions are not converted to 2D positions prior to generating a layout. 
You can find an example file here: 
[opto.zip](https://github.com/fieldtrip/fieldtrip/files/4324247/opto.zip)

**Comment by robertoostenveld** [comment]
I see in http://www.fieldtriptoolbox.org/tutorial/nirs_multichannel/ (search for ft_layoutplot) that it is used differently. When specifying the oxy3 file, ft_read_sens returns positions (from the xml file?) that are 2d. This apparently never has worked for a 3D optode specification.

**Comment by robertoostenveld** [comment]
Please see the new test script. 

I can explain the extra options (projection, viewpoint) later in person, or see http://www.fieldtriptoolbox.org/tutorial/layout/#creating-a-layout-from-sensor-positions for an example on a MEG sensor array and http://www.fieldtriptoolbox.org/tutorial/human_ecog/ for an ECoG example (see figure following step 49). I don't think that they are very relevant right now, but might be with a bilateral optode array that is very low (e.g. over temporal) and hence not rendered optimally if you project it pancake style along the z-axis.
