### ISSUE TITLE
Link to data in dipole fitting example broken

### ISSUE THREAD

**Issue by britta-wstnr** [fieldtrip/fieldtrip#1338]
I lately wanted to check out something in this tutorial:
http://www.fieldtriptoolbox.org/workshop/natmeg/dipolefitting/

and noticed that the link to `dicom.zip` does not exist on the FTP server anymore (the folder it links to is not there: `server-address/workshop/natmeg/dicom.zip` ).

I know the example is from a quite old workshop but I wonder if it can be fixed/if the data just got moved and is still on the server, so could be re-linked.

**Comment by robertoostenveld** [comment]
I have moved the issue over to the website repository
