### ISSUE TITLE
ADC channels are detected as trigger channels in .oxy3 files

### ISSUE THREAD

**Issue by helenacockx** [fieldtrip/fieldtrip#1341]
When selecting events from an .oxy3 file with ft_read_event, ADC channels are selected as trigger channels resulting in very long computation times (for example for my dataset, this means that fieldtrip unnecessary needs to go over the loop in line 2141-2160 61192 times). Maybe it is possible to change something in read_trigger line 82-89 (see code below) to better detect when ADC channels are no trigger channels? Or else to have an option in cfg.chanindex of ft_read_event to prevent ADC channels from being selected?
I also added an example data file (having 2x4 ADC channels)
[sub-01.zip](https://github.com/fieldtrip/fieldtrip/files/4330115/sub-01.zip)
.
```
% Detect situations where the channel value changes almost at every time
% step which are likely to be noise
if denoise
  for i=1:length(chanindx)
    if (sum(diff(find(diff(dat(i,:))~=0)) == 1)/length(dat(i,:))) > 0.8
      ft_warning(['trigger channel ' hdr.label{chanindx(i)} ' looks like noise and will be ignored']);
      dat(i,:) = 0;
    end
  end
end
```

**Comment by robertoostenveld** [comment]
also pinging @Horschig on this

any exceptions should be implemented in the fixartinis section. But given the flexible use of these channels, it might be hard to autodetect whether it is analog TTL values (which are noisy) or accelerometer values. It is clearly not a good design of the Artinis system that channels with the same name can contain very different stuff.

**Comment by robertoostenveld** [comment]
can you try to use the `chanindx` option on line https://github.com/fieldtrip/fieldtrip/blob/d9be660553a894921ec2eba09188dd1c5c138cdd/fileio/ft_read_event.m#L2175

**Comment by robertoostenveld** [comment]
so rather than the previous autodetected chanindx, you specify it as option to ft_read_event

**Comment by helenacockx** [comment]
Yes, that was my suggestion. But when specifying chanindx, it looks like you cannot specify an empty matrix or cell array (this will still result in autodetection of the channels)? And if for example passing [0] or string 'none', you got an error because this channel is not present in the data.  I also don't want to select a random channel, because then it will loop over all the data points of this channel...

**Comment by robertoostenveld** [comment]
ehm, if you don't want to read triggers from _any_ channel, why do you call ft_read_event?

**Comment by robertoostenveld** [comment]
let me answer myself... presumably because you expect the incoming LSL marker events to show up? However, I don't see any code in ft_read_event or underlying functions that suggests that LSL markers are supported.

**Comment by helenacockx** [comment]
Because this was the way it used to work... If for example using this oxy3-file, it correctly detects the events (including the ADC channels).  Nevertheless it is also still not clear to me where in the code the event strings (type 'event') are generated...
[190820_midline_Janne.zip](https://github.com/fieldtrip/fieldtrip/files/4330328/190820_midline_Janne.zip)
.

**Comment by helenacockx** [comment]
Oh it is generated in line 2130: 
` event = read_artinis_oxy3(filename, true);`
By using this line instead, we can surpass the problem. (However, we can't use this trick then anymore...:
`cfg=[];
cfg.dataset=filename;
cfg.trialdef = [];
cfg.trialdef.eventtype = '?';
ft_definetrial(cfg);
`

**Comment by robertoostenveld** [comment]
yes, I also just traced it there. And then later the ADC events are added, using read_trigger.

So there is a good reason to allow the specification of `chanindx` in ft_read_event such that it does not try reading them. What about  specifying chanindx=-1, or nan, or another number that is not in 1:nChan? And when specified like this, skip the read_trigger call?

**Comment by helenacockx** [comment]
For now this doesn't work (or it is seen as an empty matrix and autodetect ADC channels, or it gives an error because the channel doesn't exist in the data). But if we can update the code such that this becomes a valid option, that would be a good solution.

**Comment by robertoostenveld** [comment]
have a look at https://github.com/fieldtrip/fieldtrip/commit/48e7f809f8f94fec40deef00abaf0b02ace95bed to see how I fixed it.
