### ISSUE TITLE
Startup issues

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1344]
1- Made a clean clone of Fieldtrip code March 16, 2020
2- Typed ft_defaults

ft_defaults
Undefined function or variable 'ft_warning'.

Error in ft_defaults (line 146)
  ft_warning('FieldTrip is not yet on your MATLAB path, adding %s', strrep(ftPath, '\\', '\'));

3- Added folders with recursion

ft_defaults
Out of memory. The likely cause is an infinite recursion within the program.

Error in fileparts (line 40)
elseif ~isrow(file)

**Comment by robertoostenveld** [comment]
could you check why line 79 is not executed?

```
% ft_warning is located in fieldtrip/utilities, which may not be on the path yet
if ~exist('ft_warning', 'file')
  ft_warning = @warning;
end
```

**Comment by arnodelorme** [comment]
It was because another version of Fieldtrip from 2 months ago was in the path. I always start Matlab with a clean path (no addition) but somehow some path was saved. Sorry about that.
