### ISSUE TITLE
Problems reading ascii stl

### ISSUE THREAD

**Issue by jdue** [fieldtrip/fieldtrip#1352]
Hi

When I try to read an ascii stl file using `ft_read_headshape` I get an empty struct

```
>> ft_read_headshape(f)

ans = 

    pos: [0x3 double]
    tri: [0x3 double]
```

I believe the arguments to `contains` have been swapped in the following line https://github.com/fieldtrip/fieldtrip/blob/e23031c0f1266f8eed9f0ad41a3fa34fcdc796c0/fileio/private/read_stl.m#L58 as the documentation says that the input arguments are `contains(str, pattern)`. Swapping the two arguments results in

```
>> ft_read_headshape(f)

ans = 

     pos: [36x3 double]
     tri: [12x3 double]
    unit: 'mm'
```

(I am actually using `fieldtrip\compat\matlablt2016b\contains.m` but that should not matter in this particular case).

Best,
Jesper

**Comment by robertoostenveld** [comment]
thanks for reporting in this detail. It is interesting, I am sure this has worked on other STL files in the past. But probably those have an exact match for `str` and `pattern`, which causes them to match, and in your case the match is not exact.

I will fix it.

**Comment by robertoostenveld** [comment]
I merged the fix with the master branch. It will take until tomorrow for it to be in the release branch, and in the release zip file (assuming all tests pass). See http://www.fieldtriptoolbox.org/development/dashboard/
