### ISSUE TITLE
ERROR_Invalid MEX-file_combineClusters.mexw64

### ISSUE THREAD

**Issue by fabiopadova** [fieldtrip/fieldtrip#1355]
Hi all,

I'm facing a problem when I try to run the function ft_freqstatistics from Brainstorm.
This is the error:

Error: [process_ft_freqstatistics]  Test > FieldTrip: ft_freqstatistics
** Line 107: Invalid MEX-file 'C:\Program Files\brainstorm_200203\brainstorm3\external\fieldtrip-20161013\private\combineClusters.mexw64': Impossibile trovare il modulo specificato.

Same problem when I tried with other Fieldtrip versions (fieldtrip-20170824; fieldtrip-20200315; fieldtrip-20190109).

How could I fix it? 

Thanks,

Fabio

fieldtrip-20161013, Matlab R2019b, Windows 10 v1903 (OS Builds 18362.720)

**Comment by schoffelen** [comment]
Please ask your question on the fieldtrip discussion list.
Also, we don't maintain brainstorm, so if your question pertains to that package, please ask your question there.

**Comment by robertoostenveld** [comment]
There is probably some dll file missing on your computer.

Please search for "dependency walker" on the the [fieldtriptoolbox website](http://www.fieldtriptoolbox.org/search_results/?q=dependency%20walker) and mailing list and see http://www.dependencywalker.com.

**Comment by schoffelen** [comment]
I didn't know that @robertoostenveld spoke Italian :)

**Comment by schoffelen** [comment]
@fabiopadova I might have missed this, but have you asked your question on the discussion list, and has your issue been solved for you?

**Comment by fabiopadova** [comment]
Hi, thanks for your suggestion. Yes, I do. 
I asked my question on the fieldtrip discussion list and I hope someone can help me.
