### ISSUE TITLE
[reproducescript] ft_prepare_sourcemodel can't handle char in cfg.sourcemodel

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/fieldtrip#1361]
ft_prepare_sourcemodel can handle a cfg that contains the fields 'mri' and 'sourcemodel', but not when cfg.sourcemodel is a string (these are hard-coded to be mutually exclusive, line 254). This causes an error when cfg.sourcemodel is a file on disk, created by reproducescript.

**Comment by robertoostenveld** [comment]
if cfg.sourcemodel points to a file, then cfg.mri should not point to a file as well, right?

**Comment by robertoostenveld** [comment]
I propose you suggest a fix in a PR

**Comment by matsvanes** [comment]
correction: cfg.mri is empty, but cfg.headmodel is not (basedonvol is true), causing the same issue
