### ISSUE TITLE
[reproducescript] error saving figure when not started with empty figure

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/fieldtrip#1369]
When plotting functions are run with reproducescript enabled, the corresponding line in the standerdized script (script.m) can produce an error (something about a corrupt file). This can occur when the plotting function plots in a figure that was not cleared before the function was ran.

**Comment by matsvanes** [comment]
I propose to let reproducescript.m explitictly write `figure;` in script.m before any plotting function.
For example

```
if outputcfg
  % this is for ft_definetrial, ft_artifact_zvalue, etc.
  fprintf(fid, 'cfg = %s(cfg);\n\n', highest_ft);
else
  if isplottingfunction(highest_ft) % this statement is my proposition
    fprintf(fid, 'figure; \n');
  end
  fprintf(fid, '%s(cfg);\n\n', highest_ft);
end
```

Now my question is if there already exists a function or list that I can use to check whether a FieldTrip function is a plotting function @robertoostenveld @schoffelen @Spaak? Also I realize that this problem might not occur with a plotting functions, since some of them automatically open a new figure (e.g. ft_sourceplot), but this is more a note about the consistency in plotting functions.

**Comment by Spaak** [comment]
My hunch is you could do a simple check whether `highest_ft` contains the substring `plot`*. But of course that is not a very clean approach, and would still be best handled in a helper function like the `isplottingfunction` you propose (then we can always update the heuristics later on).

(* exception I immediately can think of: `ft_sourcemovie`.)

**Comment by matsvanes** [comment]
See #1371
