### ISSUE TITLE
tutorial data beamformer is not in sync with tutorial page

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1383]
as identified by @tiborauer the data on the ftp for the beamformer tutorial contains the data_FIC variable, but the current version of the online tutorial does not have this anymore (these days working with data_all). This needs to be updated.

**Comment by robertoostenveld** [comment]
I recomputed the following files and copied them to /home/common/matlab/fieldtrip/data/ftp/tutorial/beamformer (and removed the old ones)

They will be on the ftp server in 30 minutes.

```
mac036-lan> ll
total 678224
-rw-r--r--  1 roboos  staff   22150073 Apr 22 10:13 dataPost.mat
-rw-r--r--  1 roboos  staff   22147190 Apr 22 10:13 dataPre.mat
-rw-r--r--  1 roboos  staff  234342745 Apr 22 10:13 data_all.mat
-rw-r--r--  1 roboos  staff   25819954 Apr 22 10:13 freqPost.mat
-rw-r--r--  1 roboos  staff   25819843 Apr 22 10:13 freqPre.mat
-rw-r--r--  1 roboos  staff     242133 Apr 22 10:13 headmodel.mat
-rw-r--r--  1 roboos  staff    6505711 Apr 22 10:13 segmentedmri.mat
-rw-r--r--  1 roboos  staff   10203226 Apr 22 10:13 sourcemodel.mat
```
