### ISSUE TITLE
default spmversion in ft_prepare_mesh

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1384]
ft_prepare_mesh still has 'spm8' as default version. 
Why?
we noticed at the toolkit significant mex-file problems with spm_conv_vol for spm8, not for spm12 (presumably mostly by people with matlab versions >=2019a). Possibly other mex-files are affected as well.

**Comment by schoffelen** [comment]
Shall we just change the default throughout, and see what happens?

Also, we may need to revamp the documentation on: http://www.fieldtriptoolbox.org/getting_started/spm/, which describes spm8 as state of the art

**Comment by robertoostenveld** [comment]
I recall that all functions were modified to have a consistent default, and a consistent way of overruling the default (was not always possible in the past, in some places of the code 8 or 12 would be hard-coded). And that default is now spm8

```
mac036-lan> grep 'spmversion.*spmversion.*spm8' *.m */*.m */*/*.m
ft_prepare_mesh.m:cfg.spmversion  = ft_getopt(cfg, 'spmversion', 'spm8');
ft_prepare_sourcemodel.m:cfg.spmversion        = ft_getopt(cfg, 'spmversion', 'spm8');
ft_volumedownsample.m:cfg.spmversion = ft_getopt(cfg, 'spmversion', 'spm8');
ft_volumenormalise.m:cfg.spmversion       = ft_getopt(cfg, 'spmversion',       'spm8');
ft_volumerealign.m:cfg.spmversion    = ft_getopt(cfg, 'spmversion', 'spm8');
private/clusterstat.m:cfg.spmversion   = ft_getopt(cfg, 'spmversion', 'spm8');
private/prepare_mesh_segmentation.m:cfg.spmversion    = ft_getopt(cfg, 'spmversion', 'spm8');
```

although ...

```
mac036-lan> grep 'spmversion.*spmversion.*spm12' *.m */*.m */*/*.m
ft_volumebiascorrect.m:cfg.spmversion       = ft_getopt(cfg, 'spmversion',       'spm12');
ft_volumesegment.m:cfg.spmversion       = ft_getopt(cfg, 'spmversion',     'spm12');
```

I am fine with changing the default everywhere to spm12, but that should be communicated to the mailing list.

**Comment by schoffelen** [comment]
OK, I merged #1394 (and a related PR on the website). I will wait now with communicating this to the FT list once the test results come in (i.e. if a new release will be created based on the test batch running through fine).

**Comment by robertoostenveld** [comment]
I propose to also make a short news item on the home page (can be the same as the text in the email). That one remains visible for a longer time.

**Comment by schoffelen** [comment]
news item has been created, and e-mail has been sent. Nothing to be done.
