### ISSUE TITLE
ft_read_event breaks when thresholding events on multiple channels

### ISSUE THREAD

**Issue by iandol** [fieldtrip/fieldtrip#1387]
I am loading an EDF file (Test_4.edf attached) that has two EEG channels (1:2), and 8 analog continuous trigger channels (3:8) -- the 8 event triggers are 8 bits that I want to decode to strobed words so I can define my trials. I use a threshold set to `4*nanmedian`.

[Test_4.zip](https://github.com/fieldtrip/fieldtrip/files/4528504/Test_4.zip)

I thought I could do this all in one go with ft_read_event:

```matlab
fileName = 'Test_4.edf';
triggerchannels = 3:8;
cfg				= [];
cfg.dataset 	= fileName;
cfg.header		= ft_read_header(cfg.dataset);
labels			= cfg.header.label(3:end);
data_events		= ft_read_event(cfg.dataset,'header',cfg.header,...
	'detectflank','up','chanindx', triggerchannels, 'threshold', '4*nanmedian');
```

The result is incorrect (see the markers I draw for each event channel don't align with channels, in fact markers from one channel are found on another and some events are unmarked):
![test](https://user-images.githubusercontent.com/153905/80207649-1c1f8980-8661-11ea-97b6-3c575ffd4261.png)
full code to reproduce: https://gist.github.com/iandol/118a3aeb6820ab8d7edd48fe2791774e

Step debugging through I found that the problem is on line 181 of read_trigger.m:

```matlab
if ~isempty(threshold)
  % the trigger channels contain an analog (and hence noisy) TTL signal and should be thresholded
  if ischar(threshold) % evaluate string (e.g., threshold = 'nanmedian')
    threshold = eval([threshold '(dat)']);
  end
  % discretize the signal
  dat(dat<threshold) = 0;
  dat(dat>=threshold) = 1;
end
```

With a single channel there is no problem with this eval: dat is 1xN then `eval(['4*nanmean(dat)'])` gives the correct single threshold value, but when dat is more than one channel (M channels x N) then this breaks (wrong dimension used); simple test code shows this:

```
>> dat = [0 0 0 0 10 0]

dat =

     0     0     0     0    10     0

>> eval(['4*nanmedian' '(dat)'])

ans =

     0 


>> dat = [0 0 0 0 10 0;0 0 10 0 0 0]

dat =

     0     0     0     0    10     0
     0     0    10     0     0     0

>> eval(['4*nanmedian' '(dat)'])

ans =

     0     0    10     0    10     0 
```

I assume this function is supposed to be able to handle multiple channels? It just needs some logic to do this per data channel.

**Comment by iandol** [comment]
If I change the code to something like:

```matlab
if ~isempty(threshold)
	% the trigger channels contain an analog (and hence noisy) TTL signal and should be thresholded
	if ischar(threshold) % evaluate string (e.g., threshold = 'nanmedian') per channel
		for i = 1:size(dat,1)
			tval(i) = eval([threshold '(dat(i,:))']);
			% discretize the signal
			dat(i,dat(i,:)<tval(i)) = 0;
			dat(i,dat(i,:)>=tval(i)) = 1;
		end
	else
		% discretize the signal
		dat(dat<threshold) = 0;
		dat(dat>=threshold) = 1;
	end
end
```

...then multiple channels work fine:
![triggers](https://user-images.githubusercontent.com/153905/80296738-1b493d80-87b0-11ea-85df-5e66a505749e.png)

**Comment by schoffelen** [comment]
Thanks for reporting this.
The full example does not run for me because my matlabversion does not have the tiledlayout functionality. Your suggested fix makes sense, alternatively we could ad a ',2' to the string to be evaluated, but this depends of course on the thresholding function.

Would you mind making a PR out of this? Perhaps consider not making tval a vector, because it is not kept in the output. Also, please use the convention of 2 spaces per tab.

**Comment by iandol** [comment]
Yes, I will do this tomorrow.

**Comment by iandol** [comment]
@schoffelen -- I've created a pull and added a test though I was unsure exactly how to format the test in terms of paths for source data etc.
