### ISSUE TITLE
ft_rejectvisual with summary mode rejects wrong channel if cfg.channel is set

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/fieldtrip#1391]
See the following snippet. When executing `ft_rejectvisual`, select the second channel in the display (label 'c', values 3). I'd expect `datout` to have channel labels 'a' and 'd' ('b' no longer there because it was not selected in `cfg.channel`, 'c' no longer there because it was toggled in the GUI). Instead, channels 'a' and 'c' are present! Thus channel d was removed.

```
%% create data

data = [];
data.label = {'a' 'b' 'c' 'd'}';

% ensure the channels are distinguishable by their data (helps in the
% GUI)
dat = ones(4,1000);
dat(2,:) = 2*dat(2,:);
dat(3,:) = 3*dat(3,:);
dat(4,:) = 4*dat(4,:);

data.trial = {dat dat};
data.time = {1:1000 1:1000};

%% check it

cfg = [];
cfg.channel = {'a' 'c' 'd'};
cfg.method = 'summary';
cfg.metric = 'max';
datout = ft_rejectvisual(cfg, data);

% Now I select the second channel to reject, which corresponds to channel
% label 'c' (due to the selection above). Weirdly, datout now has channels
% a and c, so channel d was removed!
```

**Comment by Spaak** [comment]
Happy to work on a fix myself, so feel free to assign to me. Also, @robertoostenveld, what is the best practice here for submitting the above as a test script? It involves a manual action to reproduce the bug (but the result can be checked automatically).

**Comment by robertoostenveld** [comment]
You can put the code to test (and instructions) in an `inspect_issue1391.m` file. We don't often look at those inspect-scripts, but it does facilitate to revisit/retest the issue later.

**Comment by Spaak** [comment]
Note that this is a pretty severe bug, I think, and also applies to `cfg.trials`, and also to `rejectvisual_trial` and `rejectvisual_channel` (not just summary mode). The selection of channels due to `cfg.channel` is made here: https://github.com/fieldtrip/fieldtrip/blob/d8662e204096419b2bfafcc64910e12665368209/ft_rejectvisual.m#L191 and the implementation functions (`rejectvisual_summary`/`_trial`/`_channel`) subsequently work on `tmpdata`. Channel removal feedback in the command window after GUI interaction is based on this:
https://github.com/fieldtrip/fieldtrip/blob/d8662e204096419b2bfafcc64910e12665368209/ft_rejectvisual.m#L234 so based on the `chansel` output argument of the implementation function, which is created based on the channels in `tmpdata` (and *not* in `data`). This does not raise an error because it's converted to integer indices using `find` (using the logical `chansel` itself would have raised a dimension mismatch error). Analogously, the actual removal is done like so: https://github.com/fieldtrip/fieldtrip/blob/d8662e204096419b2bfafcc64910e12665368209/ft_rejectvisual.m#L328-L334 so almost guaranteed to be wrong if a channel was removed using `cfg.channel` that was not at the end of the channel list.

The issue is easy to fix (simply translate `chansel`/`trlsel` back to original indices; will send PR soon) but may have affected many people if they rely on the `cfg.channel` or `cfg.trials` input to `ft_rejectvisual`. The result would be no error message, but good channels/trials removed, artifactual channels/trials retained.

**Comment by Spaak** [comment]
Incidentally, the issue also occurs if you don't select any channel at all in the GUI interface. If you do not interact with the GUI and press 'quit' immediately, you will get back channels `1:n` from the original data where `n` is the number of channels you selected using `cfg.channel`, irrespective of which those channels were.
