### ISSUE TITLE
dimensions issue between cfg.t_ftimwin and cfg.toi in ft_mvaranalysis

### ISSUE THREAD

**Issue by yukoka** [fieldtrip/fieldtrip#1393]
This issue was discussed in the mailing list, 2018 as follow.
I have the same problem now. so... unsolved yet??

---
Dear Manuela,

This looks like a typo in the code, which I will fix (and once fixed will become available in the daily release version of the code). To give myself some time: probably not tonight, but perhaps after the weekend :). However, the fact that this part of the code clearly doesn’t work, I am not entirely sure whether the rest will work smoothly as well, as soon as the current hurdle is fixed. But let’s see

Best wishes,
Jan-Mathijs

On 29 Aug 2018, at 13:34, Manuela Costa <manuela.costa at ctb.upm.es<mailto:manuela.costa at ctb.upm.es>> wrote:

Dear community,

I'm planning to do granger causality analysis on human iEEG data. I'm using ft_mvaranalysis to get time-dependent coefficient sets based on a sliding window, but I get an error.

The data is downsampled at 250 Hz. The fields of my data structure are fsample, trial, time, label and cfg. The size of preprocessing_emotional_Rem_ds{1}.trial{1} is 3x3751 (channels, data points). Below is the configuration structure and the error message. The ft_mvaranalysis function works if I do not use the sliding window approach. I tried to use different cfg.toi and cfg.t_ftimwin but I could not find a solution. I hope you can help me.

Best wishes,

Manuela Costa

Configuration structure:

cfg = [];
    cfg.toolbox = 'bsmart';
    cfg.order   = 10;
    cfg.toi       = -0.5:0.01:3; %% the time points at which the windows are centered
    cfg.t_ftimwin = 0.25; %% length of time window in second
    mdata_emotional_Rem{subj} = ft_mvaranalysis(cfg, preprocessing_emotional_Rem_ds{subj});

Error message:

Matrix dimensions must agree.

Error in ft_mvaranalysis (line 185)
latency(k,:) = cfg.toi + cfg.t_ftimwin.*[-0.5 0.5];

Error in Step2_Calculate_Granger_time_freq(line 108)
    mdata_emotional_Rem{subj} = ft_mvaranalysis(cfg,preprocessing_emotional_Rem_ds{subj});

**Comment by schoffelen** [comment]
Can you please be a bit more specific? We will not be able to look into this (or be inclined to spend time on this) without any additional information. Please report the error you get, upload some data+code that can be used to reproduce your problem. Check whether you use a recent version of fieldtrip, report the matlab version etc.

**Comment by yukoka** [comment]
Hi Jan-Mathijs,

Thank you for your prompt response.
The error message is bellow in Japanese. In English "Matrix dimensions must agree."  
I use relatively new FT which I download on Apr.23, 2020. And Matlab ver. is 2019b

Please find the attached code and preprocessed the data.
I reduced the trial number and resampled from 5000 to 500 to upload the file here.
[codeAndData.zip](https://github.com/fieldtrip/fieldtrip/files/4574234/codeAndData.zip)


Error Message...-----------------------------------------------------------
185 		latency(k,:) = cfg.toi + cfg.t_ftimwin.*[-0.5 0.5];
行列の次元は一致しなければなりません。(Matrix dimensions must agree.)

エラー: ft_mvaranalysis (line 185)
		latency(k,:) = cfg.toi + cfg.t_ftimwin.*[-0.5 0.5];
--------------------------------------------------------------

**Comment by schoffelen** [comment]
Do you know how to operate the matlab debugger? Please try and find out yourself what might be going wrong. The error is an matrix size allocation problem, so that would mean that the expected dimensions don't match. In particular, you should be able to investigate what the dimension is of the 'latency' variable, the cfg.toi and the cfg.t_ftimwin. 

By the way, I don't know what version of fieldtrip you downloaded on april 23 2020, but the most recent version of the code looks different than the line 185 you pasted in your reply. So, again, please get yourself a as recent version as possible of the fieldtrip code. If you look on github, and investigate the revision history of ft_mvaranalysis, you will see that the code has been updated as recently as end of March 2020, and that the respective line '185' now has cfg.toi indexed with k.

**Comment by yukoka** [comment]
Ahh, it was fixed. I downloaded the newest version and it works.
Sorry for bothering you and thank you!
yuka
