### ISSUE TITLE
ft_selectdata averages fields the shouldn't be averaged: sampleinfo, trialinfo and time

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1400]
Hi,

I came across this bug when using ft_rejectvisual in summary mode, with a data structure that has a table in trialinfo. When selecting a trial to plot in the GUI, ft_selectdata is called (rejectvisual_summary lines 634-638):
```
cfg_sd = [];
cfg_sd.trials = trls(n);
cfg_sd.avgoverrpt = 'yes';
cfg_sd.keeprpt = 'no';
tmpdata = ft_selectdata(cfg_sd, info.data);
```
line 311 in ft_selectdata is the problematic one:
`if fieldhasrpt,     varargin{i} = makeselection(varargin{i}, datfield{j}, dimtok, rptdim{i},                                selrpt{i},     avgoverrpt,      'intersect', average); end`
If trialinfo is a table, this will result in an error, because cellmatmean which is called be makeselection expects cell or matrix datfields. trialinfo, time and sampleinfo are all defined as datfields and not removed by lines 160-172 that clean the datfield. sampleinfo is used later (lines 364-374) while I think trialinfo is not used. time is used.

Solving the averaging of sampleinfo and trialinfo is possible by moving lines 402-406 to after line 250 and apply them on datfield rather than keepfield (if they don't make sense in the output, I guess they shouldn't be kept in the input too?):
```
if avgoverrpt
  datfield = setdiff(datfield, {'cumsumcnt' 'cumtapcnt' 'trialinfo' 'sampleinfo'});
end
```

This solved my specific problem for ft_rejectvisual, but I don't know if it's a good idea, and it doesn't change the fact that ft_selectdata will still average the time field.

Any suggestions for a better fix?

**Comment by schoffelen** [comment]
Although in itself this might be a valid issue, I don't understand why rejectvisual_summary has functionality that averages across observations. Does this have anything to do with the (on-the-fly) visualization of the artifactual trials? If so, why would it make sense to average across trials ti inspec the morphology of an artifact?

Besides this, could you please create a test script that, in combination with some problematic data demonstrates the issue. I would say that a call to ft_selectdata (+data) would be sufficient to highlight the issue.

Then, you can submit the test code and the fix as a PR to the fieldtrip github repo, and send your data (please make it as small as possible), so that we can document it, and put the data as test data on our filesystem.

**Comment by NirOfir** [comment]
So there are actually 2 issues here:
1. ft_selectdata averages over fields it shouldn't.
2. reject visual averages over trials selected for artifact visualization.

**Issue 1**
I'll create a test script and update when it's ready.

**Issue 2**
yes, ft_selectdata is called for artifact visualization. It is called because ft_multiplotER fails to do the data selection itself (explained in bugzilla [bug 2978](http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2978)). I don't know why it was set to averaging over trials, but removing
```
cfg_sd.avgoverrpt = 'yes';
cfg_sd.keeprpt = 'no';
```
fixes the issue in rejectvisual_summary without having to change the code in ft_selectdata (I checked using the newest version of ft_selectdata available on github). If you choose multiple trials for plotting, it will plot each in a separate figure which is the reasonable behavior.
I feel like this should actually be a separate issue, right? If so, I'll open one and make a PR.

**Comment by robertoostenveld** [comment]
regarding `ft_selectdata` averaging, I suspect that `cfg.avgoverxxx` is the only way to activate the `cfg.keepxxx` option where in this case `xxx=rpt`. The default assumption in FT is that if there is a dimension (such as trials, or time, or freq) there are multiple observations along that dimension. What happens here is (I think) correct, cfg.trials=x selects one (or multiple), avgoverrpt=yes averages, and keeprpt=yes squeezes it and thereby removes the singleton dimension from the data structure. 

The observation that removing avgoverrpt=yes and keeprpt=no in ft_selectdata is interesting: in that case the averaging is simply done one step later (in ft_multiplotER). That is an efficient work-around and I would welcome a pull request that implements that. However, the bug that ft_selectdata fails to data where trialinfo is a table remains, for that it would be good to have an as simple as possible test script.

**Comment by NirOfir** [comment]
I'll make a PR for rejectvisual_summary. Did I understand correctly that ft_selectdata selects a single trial and submits it ft_multiplotER which averages the single trial to remove singleton dimensions?

This is the test code I came up with for the averaging issue:
```
function inspect_issue1400

ntrial = 2;

data = [];
data.label = {'1'};
for i=1:ntrial
  t = (1:1000)/1000 + i; % time vectors are unaligned to show the error
  s = sin(i*2*pi*t); % make a sine with 1, 2, 3, ... Hz
  data.time{i} = t;
  data.trial{i}(1,:) = s;  % insert it in the first channel
end

disp('Demonstrate averaging over time:')
disp('Averaging trials 1, 2')
cfg = [];
cfg.trials = [1,2];
cfg.avgoverrpt = 'yes';
cfg.keeprpt = 'no';
cfg.verbosity = 'off';
tmpdata = ft_selectdata(cfg, data);

% disp(['trialinfo(1, 1) = ', num2str(tmpdata.trialinfo(1,1))])
disp(['trial 1 time = ', regexprep(num2str(data.time{1}(1:5)),'\s+',', ')])
disp(['trial 2 time = ', regexprep(num2str(data.time{2}(1:5)),'\s+',', ')])
disp(['average time = ', regexprep(num2str(tmpdata.time{1}(1:5)),'\s+',', ')])

disp('Demonstrate averaging over trialinfo:')
for i = 1:ntrial
    data.trialinfo(i, 1) = i;
end
data.trialinfo = array2table(data.trialinfo);
disp(['trialinfo class is: ', class(data.trialinfo)])

% This will return an error in ft_selectdata, because it's trying to
% average a table variable
disp('Averaging trials 1, 2')
cfg = [];
cfg.trials = [1,2];
cfg.avgoverrpt = 'yes';
cfg.keeprpt = 'no';
cfg.verbosity = 'off';
tmpdata = ft_selectdata(cfg, data);
end
```

**Comment by robertoostenveld** [comment]
could you try it with this in `ft_selectdata` ? 

```
function x = cellmatmean(x, seldim, average)
if iscell(x)
  if seldim==1
    for i=2:numel(x)
      x{1} = x{1} + x{i};
    end
    x = {x{1}/numel(x)};
  else
    for i=1:numel(x)
      x{i} = average(x{i}, seldim-1);
    end % for
  end
elseif istable(x)
  try
    % try to convert to an array, depending on the table content this might fail
    x = average(table2array(x), seldim);
  catch
    % construct an appropriately sized array with NaN values
    s = size(x);
    s(seldim) = 1;
    x = nan(s);
  end
  % convert back to table
  x = array2table(x);
else
  x = average(x, seldim);
end
end % function cellmatmean
```

if this works, it is a general solution and other changes are not needed. 

What happens, in this case, is that the table is first averaged, and later it figures out that trialinfo should not be kept anyway and therefore it is discarded any way.

**Comment by robertoostenveld** [comment]
oh, using the test script I was able to confirm the bug.

**Comment by NirOfir** [comment]
This fix works! I updated the test script to show that this fix can also handle table with non-numeric variables:
```
function inspect_issue1400

ntrial = 2;

data = [];
data.label = {'1'};
for i=1:ntrial
  t = (1:1000)/1000 + i; % time vectors are unaligned to show the error
  s = sin(i*2*pi*t); % make a sine with 1, 2, 3, ... Hz
  data.time{i} = t;
  data.trial{i}(1,:) = s;  % insert it in the first channel
end

disp('Demonstrate averaging over time:')
disp('Averaging trials 1, 2')
cfg = [];
cfg.trials = [1,2];
cfg.avgoverrpt = 'yes';
cfg.keeprpt = 'no';
cfg.verbosity = 'off';
tmpdata = ft_selectdata(cfg, data);

% disp(['trialinfo(1, 1) = ', num2str(tmpdata.trialinfo(1,1))])
disp(['trial 1 time = ', regexprep(num2str(data.time{1}(1:5)),'\s+',', ')])
disp(['trial 2 time = ', regexprep(num2str(data.time{2}(1:5)),'\s+',', ')])
disp(['average time = ', regexprep(num2str(tmpdata.time{1}(1:5)),'\s+',', ')])

disp('Demonstrate averaging over trialinfo:')
data.trialinfo = table([1;2],{'1'; '2'});
disp(['trialinfo class is: ', class(data.trialinfo)])

% This will return an error in ft_selectdata, because it's trying to
% average a table variable
disp('Averaging trials 1, 2')
cfg = [];
cfg.trials = [1,2];
cfg.avgoverrpt = 'yes';
cfg.keeprpt = 'no';
cfg.verbosity = 'off';
tmpdata = ft_selectdata(cfg, data);
end
```
