### ISSUE TITLE
Issue with ft_fetch_header 

### ISSUE THREAD

**Issue by marziehba** [fieldtrip/fieldtrip#1402]
I've been using ft-version 2017 and I changed it recently to 2020, apparently, the function ft_fetch_header is not compatible with the old version. 
In the field structure in the header, there is no field called label.
ft_fetch_header from 2017 does not have this line to look for the field 'label' in the header too.

I get continuously error in 'ft_redefinetrial': 

**Reference to non-existent field 'label'.

Error in ft_fetch_header (line 55)
  [datindx, hdrindx] = match_str(data.label, data.hdr.label);

Error in ft_redefinetrial (line 252)
  hdr = ft_fetch_header(dataold);**

**Comment by schoffelen** [comment]
I recommend you to write a little test script that, more clearly than in your initial report, demonstrates the issue. What is the input data into the function. Are you using pure fieldtrip data structures, or did you handcraft something yourself.

Which 'label' is missing, data.label, or data.hdr.label?

Also, you can use the MATLAB debugger to see what is going on within the function.

**Comment by marziehba** [comment]
Sorry for this confusion, indeed the header information in my data was coming from an external function and of course did not have the label information.
