### ISSUE TITLE
improve ft_rejectvisual to prevent plotting/scaling errors when the metric is all-zero  

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1404]
This relates to https://github.com/Spaak/fieldtrip/pull/1#issuecomment-629991293, where @Spaak noticed that the plotting failed when the min and max axis limits are the same, i.e. when the values are all similar. 

Rather than solving it along with #1392, I propose to keep it separate.

**Comment by Spaak** [comment]
> Rather than solving it along with #1392, I propose to keep it separate.

Agreed. (But notice that the issue was *introduced* by #1392, perhaps good to keep in mind when searching for a fix.)

**Comment by robertoostenveld** [comment]
I recently implemented a fix for this, using the `fixrange` function in https://github.com/fieldtrip/fieldtrip/blob/1c0e81a25ddd22cd4cfca03f28c51037502bbf41/private/rejectvisual_summary.m#L676

Just now I used the following code to test. Only kurtosis fails to plot nicely because that returns all NaNs. But after clicking kurtosis, you can still move on to the other options so it does not break the actual functionality of the GUI.  

```
%% create data

numtrl = 52;
numchan = 26;

data = [];
for chanlop=1:numchan
  data.label{chanlop} = char(96+chanlop); % a = 97
end
data.trialinfo = (1:numtrl)';

for trlop=1:numtrl
  data.trial{trlop} = zeros(numchan,1000);
end

data.time = repmat({1:1000}, 1, numtrl);

%%

cfg = [];
cfg.method = 'summary';
ft_rejectvisual(cfg, data);

```
