### ISSUE TITLE
Qsubcellfun doesn't run jobs in parallel

### ISSUE THREAD

**Issue by yundumbledore** [fieldtrip/fieldtrip#1414]
Hello there,
I use fieldtrip doing a MEG processing task. I've built a customized analysis pipeline with some ft functions. There is no problem in my analysis pipeline since it works well sequentially. Currently, I use qsubcellfun with my analysis pipeline. 

The remote server is slurm system. I apply for an interactive session with --ntasks=8 --mem=160gb since I would like to run 8 qsub jobs in parallel. I plug some arguments in function qsubcellfun like: 
y=qsubcellfun(@myfname, cond, 'timreq', 2*1800 ,'memreq', 20*1024^3,'backend', 'slurm', 'StopOnError', false, 'matlabcmd', 'matlab', 'options', '--ntasks=1'). I assume there're 8 qsub jobs running at the same time, each qsub job uses 1 processing element.

But things are not what I expect. qsubcellfun submits jobs sequentially still. It submits a new qsub job right after the previous one is finished. 

Could you guys help me with this issue? Is there anything I did wrong? :( Thanks a lot.

Rowen

**Comment by robertoostenveld** [comment]
Hi Rowen,

We don't use SLURM ourselves, so I cannot check what is going wrong. I suspect there to be more expertise on SLURM on the http://fieldtriptoolbox.org/discussion_list/. But you write that you apply for an interactive session with 8 tasks and that you want to run 8 jobs. That is not how it works. The idea is that you start a single-task interactive session, execute `qsubcellfun` for a batch with N jobs, which then in turn queues N additional (and non-interactive) jobs. 

See http://www.fieldtriptoolbox.org/faq/how_to_get_started_with_distributed_computing_using_qsub/

I suggest you use the MATLAB debugger to set a breakpoint on [this line](https://github.com/fieldtrip/fieldtrip/blob/99cd897831df2caf6ab0159818ae7da4e53420e9/qsub/qsubfeval.m#L264) and that you follow what happens. At that moment the input mat file has just been written to the shared filesystem (line 180) and it starts a single MATLAB that reads the mat file, executes the code, and writes the output mat file. 

For N jobs in `qsubcellfun`, the call to `qsubfeval` is made N times.

**Comment by yundumbledore** [comment]
Hi, 

Just a follow-up in case other users may have this problem.

I solved this problem but with minor issues. In qsubfeval.m, if you are using slurm cluster, you might like to add 'nohup' to the front of the line with 'srun'. I can run my experiments in parallel by doing so. The issue is I have to manually terminate the process when it finishes. Just check the output files. You may need to add a flag in your processing pipeline code indicating a process finishes. Looks like the processing info hardly returns to qsubfeval.m.

Cheers,
Rowen

**Comment by schoffelen** [comment]
Hi Rowen, as indicated by Robert, we don't have access to a SLURM cluster, so we cannot test any proposed fixes ourselves. If you think that other users will benefit from your changes, I suggest (and gently recommend) to create a Pull Request with the incorporated changes, so that it will end up un the code base. Looking forward to it, and thanks for your contribution.

**Comment by schoffelen** [comment]
Closing, since I don't know how to take this further, and required input for this from @yundumbledore is lacking. Feel free to reopen
