### ISSUE TITLE
binica.sc looking for ica_linux in the wrong folder

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1415]
**Describe the bug**
I'm analyzing EEG data on CenotOS 7, and I wanted to try binica to see if it can make things quicker. Running the following code:
```
cfg = [];
cfg.numcomponent = 65;
cfg.method = 'binica';
cfg.channel = 'all';
comp  = ft_componentanalysis(cfg, clean_data);
```
Returned this error:
binica: using source file '/mnt/raid0/CPC_vis_EEG_v2/fieldtrip-20200508/external/eeglab/binica.sc'
binica(): ica binary 'functions/resources/ica_linux' is not in your Matlab path, check

ica_linux is in /external/eeglab, together with binica.sc. I tried creating /functions/resources/ under eeglab, and moving ica_linux there, but it didn't work.

**Environment and versions (please complete the following information):**
 - Operating System: CentOS 7
 - MATLAB version R2018b
 - FieldTrip version 20200508

**Comment by robertoostenveld** [comment]
Am I correct that this is an error when `binica.m` is trying to execute the binary, i.e. around line [310]( https://github.com/fieldtrip/fieldtrip/blob/f13cdb92c6f3da95dd2422412a061ce9cc15ee05/external/eeglab/binica.m#L310)? 

If so, it is an bug in EEGLAB and you should report it there. We are ourselves not maintaining the code  in fieldtrip/external.

**Comment by schoffelen** [comment]
I can confirm the issue. It is due to some clunky programming in icadefs.

If I change in fieldtrip/external/eeglab/icadefs the lines 149/150 into:
   
   %eeglab_p = fileparts(which('eeglab'));
    %ICABINARY = fullfile(eeglab_p, 'functions', 'resources', 'ica_linux'); 
    eeglab_p = fileparts(which('binica'));
    ICABINARY = fullfile(eeglab_p, 'ica_linux');

I can get it to work. Note that this is a hack that works only for linux, because ica_linux is the only compiled version that is shipped in FT at the moment.

**Comment by NirOfir** [comment]
Thanks for the quick responses! That does fix it. However, binica apparently can't use multithreading, which means it is much slower than runica, at least for me. So I guess that without adding an option to use cudaica to ft_componentanalysis, there's not much to do, correct? 
Since modern computers are usually (or always?) multithreaded, what's the use case for binica now?

**Comment by schoffelen** [comment]
I don't know. Ask the eeglab folks.

**Comment by NirOfir** [comment]
Thanks, will do.
