### ISSUE TITLE
reading the NWB file format fails

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1421]
The NWB file format should be tested, see #1419. After that, the `inspect_xxx` script should be renamed to `test_xxx`

**Comment by robertoostenveld** [comment]
My first attempt at running the test fails. I downloaded the latest release, added it to my path, generated the core (whatever that means) and tried with one of the test files suggested in the script. The other 10GB test file is still downloading, the ETA is in 3 hours from now...

```
>> addpath(genpath('/Users/roboos/matlab/matnwb-2.2.5.0/'))
>> generateCore()
>> ft_read_header('P9HMH_NOID5.nwb')
Warning: Something might not be alright with your MatNWB path. Will try anyways. 
Unable to resolve the name types.core.VectorData.
Error in io.parseDataset (line 72)
    parsed = eval([Type.typename '(kwargs{:})']);
Error in io.parseGroup (line 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath, Blacklist);
Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);
Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);
Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);
Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
Error in ft_read_header (line 2312)
    tmp = nwbRead(filename); % is lazy, so should not be too costly 
```

The `P9HMH_NOID5.nwb` test file is fine, it is not too large for inclusion in the daily batch. The 10GB file is too large, and for manual inspection too slow to download. I also found this test data `https://drive.google.com/drive/folders/1g1CpnoMd9s9L-sHBWVyklp3-xJcLGeFt`. That is small and better for testing.

However, it fails with the same error in the `matnwb` toolbox

```
>> ft_read_header('v2.0.1/test_LFP.nwb')
Warning: Something might not be alright with your MatNWB path. Will try anyways. 
Unable to resolve the name types.core.DynamicTableRegion.
Error in io.parseDataset (line 72)
    parsed = eval([Type.typename '(kwargs{:})']);
Error in io.parseGroup (line 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath, Blacklist);
Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);
Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);
Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);
Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
Error in ft_read_header (line 2312)
    tmp = nwbRead(filename); % is lazy, so should not be too costly 
```

**Comment by robertoostenveld** [comment]
I tried to also assign this to @sbuergers, but somehow that is not possible. I suspect that has to do with not yet having interacted with the fieldtrip repository enough. But please do feel welcome to help out here!

**Comment by jens-k** [comment]
The error comes from the file having a different schema version than the one installed on your system. This happens particularly with rather old files, younger data will have the schema embedded in the file, preventing that error. There should have been a more informative error message, will try to fix that.

We will come up with a lightweight test file using the latest schema and will change the code accordingly.

**Comment by robertoostenveld** [comment]
@sbuergers sent me a file, and with that, it works:

```
>> hdr = ft_read_header('ANM255201_20141125_trimmed.nwb')
Warning: Something might not be alright with your MatNWB path. Will try anyways. 

hdr = 
  struct with fields:

       nSamples: 100
             Fs: 200
    nSamplesPre: 0
        nTrials: 1
          label: {32×1 cell}
         nChans: 32
       chanunit: {32×1 cell}
           orig: [1×1 struct]
       chantype: {32×1 cell}
```

also `ft_read_data` and `ft_preprocessing` works. The warning seems not to indicate a big problem. The `ft_read_event` does not support the nwb format, as I think is to be expected at the moment.

**Comment by robertoostenveld** [comment]
I renamed the test script to `test_pull1419` and it will be added to the regular tests as documented on http://www.fieldtriptoolbox.org/development/dashboard/

Feel free to send PRs for further extensions of the test script.

**Comment by jens-k** [comment]
Robert, just out of interest: Could you find out what triggered that warning?

It is thrown by these lines of code in ft_read_header:
```
    try
        c = load('namespaces/core.mat');
        nwb_version = c.version;
        nwb_fileversion = util.getSchemaVersion(filename);
        if ~strcmp(nwb_version, nwb_fileversion)
            warning(['Installed NWB:N schema version (' nwb_version ') does not match the file''s schema (' nwb_fileversion{1} '). This might result in an error. If so, try to install the matching schema from here: https://github.com/NeurodataWithoutBorders/nwb-schema/releases'])
        end
    catch
        warning('Something might not be alright with your MatNWB path. Will try anyways.')
    end
```

...so I assume, this is the part that fails: load('namespaces/core.mat');

That folder and that file should however be in your path (after addpath(genpath(**matnwb path**));. Could you tell me whether this is indeed the line responsible for the warning and whether that folder is in your path? Thanks!

**Comment by robertoostenveld** [comment]
I recall that the warning was because `nwb_fileversion` was not a cell-array, so the inclusion of `nwb_fileversion{1}` in the first to-be-printed warning string failed.  That was caught, causing the 2nd warning to be printed.
