### ISSUE TITLE
EDF+ Annotation timestamps missing submillisecond accuracy

### ISSUE THREAD

**Issue by greydongilmore** [fieldtrip/fieldtrip#1425]
This bug was previously found in [MNE-python](https://github.com/mne-tools/mne-python/issues/7872#issue-632648353). EDF files do not allow for millisecond accuracy in recording starttime but EDF+ files do. When loading EDF+ files into FieldTrip, the TAL channel within the first block contains the millisecond aspect to the recording starttime. The current behavior of FieldTrip includes this millisecond value in all annotation timestamps but it should be subtracted.

I will include the information provided on the MNE bug report for completeness.

**To Reproduce**

This is the [EDF+ file](https://drive.google.com/file/d/1yql0bMGcXXrEZr1At_Cp-eMi6rTKSr_F/view?usp=sharing) to reproduce this behavior.

**Expected behavior**

If the EDF+ file is brought into [EDFbrowser](https://www.teuniz.net/edfbrowser/) it will be noticed that the millisecond aspect of the start time is displayed in the Start field:

![thumbnail_Outlook-ibjnd242](https://user-images.githubusercontent.com/26314366/83948860-4c288380-a7ee-11ea-8f98-9f95026da92d.png)

For instance, this results in the annotation timestamps being:

![thumbnail_Outlook-of2qriv1](https://user-images.githubusercontent.com/26314366/83948874-68c4bb80-a7ee-11ea-8e9f-6cd5969134cf.png)

**Actual Behavior**

When loading the data into FieldTrip the annotation timestamps return:

![Selection_231](https://user-images.githubusercontent.com/26314366/84077948-13330f00-a9a6-11ea-96d4-3a7d8c7fb890.png)

If you take the difference between the FieldTrip timestamp and the EDFbrowser timestamp it is equal to the submillisecond portion of the recording start time.

**Environment and versions (please complete the following information):**
 - Operating System: Ubuntu 20.04 LTS
 - MATLAB version: R2019b
 - FieldTrip version: most recent master branch from GitHub

**Additional context**

I reached out to Teunis van Beelen, the developer of [EDFbrowser](https://www.teuniz.net/edfbrowser/), to get an explanation. The explanation provided was as follows:

> EDF does not have support for subsecond precision of the starttime but EDF+ does. Because EDF+ needed to be backwards compatible with EDF and EDF doesn't have the possibility to write subsecond precision for the starttime into the header, the subsecond part of the starttime is written outside of the EDF header. The way the subsecond part of the starttime is stored in EDF+ is described here: https://www.edfplus.info/specs/edfplus.html#timekeeping

Teunis van Beelen provided a quote from the EDF specs:

> "The startdate/time of a file is specified in the EDF+ header fields 'startdate of recording' and 'starttime of recording'. These fields must indicate the absolute second in which the start of the first data record falls. So, the first TAL in the first data record always starts with +0.X2020, indicating that the first data record starts a fraction, X, of a second after the startdate/time that is specified in the EDF+ header. If X=0, then the .X may be omitted."

In other words, the subsecond part of the starttime is written in the EDF Annotations "signal".

**Comment by schoffelen** [comment]
Thanks for the diagnostics and the notification. I see that a similar issue is open on the EEG github repo. It would be good to make a principled solution which addresses this issue in both toolboxes. How would you like to proceed from here? As you know, we welcome Pull Requests with code changes. Also, it will be necessary to have some test data and some test code in order to demonstrate the issue. As it seems to have been solved for MNE python, please provide us with data, test code and ideally a fix for this.

**Comment by schoffelen** [comment]
Thanks for your contribution!
