### ISSUE TITLE
ft_read_header, ft_read_data are not on Matlab path and ft_hastoolbox has a bug

### ISSUE THREAD

**Issue by jiecui** [fieldtrip/fieldtrip#1429]
**Describe the bug**
at HEAD **a3fa0f3cc**
After run `ft_defaults`, the functions `ft_read_header` and `ft_read_data` cannot be found on Matlab path.  ft_hastoolbox produced an error.

**To Reproduce**
1. Go to the root folder of fieldtrip
2. run `ft_defaults`
3. run `which ft_read_header` and get ```'ft_read_header' not found.```
4. run `which ft_read_data` and get ```'ft_read_data' not found.```
5. run `ft_hastoolbox('mayo_mef',1)` and get
```Error: File: ft_hastoolbox.m Line: 171 Column: 3```
```Invalid expression. When calling a function or indexing a variable, use parentheses. Otherwise, check for mismatched delimiters. ```

**Comment by robertoostenveld** [comment]
thanks for reporting

```
K>> ft_hastoolbox('fileio', 1, 1);
Error: File: ft_hastoolbox.m Line: 171 Column: 3
Invalid expression. When calling a function or indexing a variable, use
parentheses. Otherwise, check for mismatched delimiters. 
```
there was an extra `};` at the end of the list

**Comment by robertoostenveld** [comment]
it works again:

```
>> cd ~/matlab/fieldtrip
>> ft_version
This is FieldTrip, revision 10fb923dc.

>> restoredefaultpath

>> ft_defaults
Warning: FieldTrip is not yet on your MATLAB path, adding
/Users/roboos/matlab/fieldtrip 
> In ft_defaults (line 155) 

>> which ft_read_header
/Users/roboos/matlab/fieldtrip/fileio/ft_read_header.m
```
