### ISSUE TITLE
Speeding up ft_freqanalysis by chagning exist(x , 'var') to ~isempty(x)

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1441]
I noticed that almost 40% of the computation time of ft_freqanalysis (fft with hanning window, nextpow2 padding, all frequencies, on ~800 trials, 67 channels, ~1500 samples each trial) is by line 708:
```
if exist('trlcnt', 'var')
```
Apparently, exist var takes a lot of time to run. I made the following change (to be made into PR soon):
add before the cfg.method switch (line 504):
```
trlcnt = [];
```
Change line 708 to:
```
if ~isempty('trlcnt', 'var')
```

**Comment by robertoostenveld** [comment]
This is a good suggestion. I don't like the use `exist(...)` to check for a variable ad in conditional code execution anyway. 

One thing though is that the replacing line 708 should be 

    if ~isempty(trlcnt)

Looking forward to the PR!

**Comment by robertoostenveld** [comment]
thanks
