### ISSUE TITLE
ft_sourceplot cannot plot sourcemodel defined using vertices depicting a volume with holes

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1455]
Some source models are only defined as a list of vertices inside a 3-D volume. The coordinates are regularly spaced and defined in MNI space. It is possible to use ft_sourceanalysis using such source models. 

However, it is not possible to use ft_sourceplot to plot the solution because this function requires a volume. Below is a piece of code that will convert this list of vertices into a volume with "inside" and "transform" fields so ft_sourceplot can plot these source models as well.

```
sourceProjtmp = load('-mat', 'mni_vertices.mat');
xl = [min(sourceProjtmp.Vertices(:,1)) max(sourceProjtmp.Vertices(:,1)) ];
yl = [min(sourceProjtmp.Vertices(:,2)) max(sourceProjtmp.Vertices(:,2)) ];
zl = [min(sourceProjtmp.Vertices(:,3)) max(sourceProjtmp.Vertices(:,3)) ];
volMat = ones(diff(xl)/5+1, diff(yl)/5+1, diff(zl)/5+1);
clear sourcemodelout;
sourcemodelout.dim = size(volMat);
[r,c,v] = ind2sub(size(volMat),find(volMat));
sourcemodelout.pos = [r,c,v];
sourcemodelout.inside    = zeros(size(sourcemodelout.pos,1),1);
sourcemodelout.unit      = 'mm';
%sourcemodelout.transform = traditionaldipfit([xl(1)-5 yl(1)-5 zl(1)-5 0 0 0 5 5 5]);
sourcemodelout.transform = [5 0 0 -75;0 5 0 -105;0 0 5 -45;0 0 0 1]; % 5mm grid
allInds = zeros(size(sourceProjtmp.Vertices));
for iVert = 1:length(sourceProjtmp.Vertices)
    xVal = (sourceProjtmp.Vertices(iVert,1)-xl(1))/5+1;
    yVal = (sourceProjtmp.Vertices(iVert,2)-yl(1))/5+1;
    zVal = (sourceProjtmp.Vertices(iVert,3)-zl(1))/5+1;
    ind = sub2ind(size(volMat), xVal, yVal, zVal);
    allInds(iVert,:) = [xVal yVal zVal];
    sourcemodelout.inside(ind) = true;
end

% check transformation
allInds2 = [ allInds ones(size(allInds,1),1) ];
allInds3 = H*allInds2';
allInds3(4,:) =[];
allInds3 = allInds3';
if ~isequal(allInds3, sourceProjtmp.Vertices)
    error('Issue with transformation');
end
```

**Comment by arnodelorme** [comment]
Example of result

<img width="533" alt="Screen Shot 2020-06-19 at 1 57 56 PM" src="https://user-images.githubusercontent.com/1872705/85172120-0a5bfc00-b236-11ea-8137-521b3064f792.png">

**Comment by robertoostenveld** [comment]
what is precisely the issue that is to be resolved? What is the input, what is the output, and what are the results that you are now getting that you consider to be incorrect? If you share a FieldTrip data structure and a cfg in a mat file, it will be easier to figure out what the issue is.

**Comment by arnodelorme** [comment]
The issue is that when a source model is defined as list of vertices (with holes in the volume) - not a full volume, it cannot be plotted by ft_sourceplot.

Code that crashes.

```
load('dataPre_and_vol.mat');

sourceProjtmp = load('-mat', 'tmp_sourcemodel.mat');

% ----- Create leadfield

cfg            = [];
cfg.elec       = dataPre.elec;
cfg.headmodel  = vol.vol;
cfg.channel    = { 'all' };
**cfg.sourcemodel.pos = sourceProjtmp.Vertices;**
[sourcemodel] = ft_prepare_leadfield(cfg);

% ----- Compute spectrum

cfg1 = [];
cfg1.length  = 1;
cfg1.overlap = 0;
dataPreEpochs    = ft_redefinetrial(cfg1, dataPre); % slice data

% Compute spectrum
cfg                  = [];
cfg.output  = 'fourier';
cfg.channel = 'all';
cfg.method  = 'mtmfft';
cfg.taper   = 'boxcar';
dataFreq = ft_freqanalysis(cfg, dataPreEpochs);
freqs1 = dataFreq.freq;

nTrials = size(dataFreq.fourierspctrm,1);
dataFreq.freq = [1:nTrials];
dataFreq.fourierspctrm = permute(dataFreq.fourierspctrm, [3 2 1]);
dataFreq.cumsumcnt = ones(1, size(dataFreq.fourierspctrm,1))*nTrials;
dataFreq.cumtapcnt = ones(1, size(dataFreq.fourierspctrm,1));

% source reconstruction
cfg             = [];
cfg.method      = 'eloreta';
cfg.sourcemodel = sourcemodel;
cfg.headmodel   = vol.vol;
sourceFreq      = ft_sourceanalysis(cfg, dataFreq);  % compute the source model
sourceFreq.time = freqs1;
sourceFreq = rmfield(sourceFreq, 'freq');

cfg = [];
cfg.projectmom = 'yes';
cfg.flipori = 'yes';
sourceProj = ft_sourcedescriptives(cfg, sourceFreq);
 
cfg = [];
cfg.parameter = 'mom';
cfg.operation = 'abs';
sourceProj = ft_math(cfg, sourceProj);

cfg              = [];
cfg.method       = 'ortho';
cfg.funparameter = 'mom';
ft_sourceplot(cfg, sourceProj);

```

Modified code (in Bold the only line modified when calling Fieldtrip) that works.


```
load('dataPre_and_vol.mat');

sourceProjtmp = load('-mat', 'tmp_sourcemodel.mat');
xl = [min(sourceProjtmp.Vertices(:,1)) max(sourceProjtmp.Vertices(:,1)) ];
yl = [min(sourceProjtmp.Vertices(:,2)) max(sourceProjtmp.Vertices(:,2)) ];
zl = [min(sourceProjtmp.Vertices(:,3)) max(sourceProjtmp.Vertices(:,3)) ];
volMat = ones(diff(xl)/5+1, diff(yl)/5+1, diff(zl)/5+1);
clear sourcemodelout;
sourcemodelout.dim = size(volMat);
[r,c,v] = ind2sub(size(volMat),find(volMat));
sourcemodelout.pos = [r,c,v];
sourcemodelout.inside    = zeros(size(sourcemodelout.pos,1),1);
sourcemodelout.unit      = 'mm';
%sourcemodelout.transform = traditionaldipfit([xl(1)-5 yl(1)-5 zl(1)-5 0 0 0 5 5 5]);
sourcemodelout.transform = [5 0 0 -75;0 5 0 -105;0 0 5 -45;0 0 0 1]; % 5mm grid
allInds = zeros(size(sourceProjtmp.Vertices));
allIndVolume = zeros(length(sourceProjtmp.Vertices),1);
for iVert = 1:length(sourceProjtmp.Vertices)
    xVal = (sourceProjtmp.Vertices(iVert,1)-xl(1))/5+1;
    yVal = (sourceProjtmp.Vertices(iVert,2)-yl(1))/5+1;
    zVal = (sourceProjtmp.Vertices(iVert,3)-zl(1))/5+1;
    ind = sub2ind(size(volMat), xVal, yVal, zVal);
    allIndVolume(iVert) = ind;
    allInds(iVert,:) = [xVal yVal zVal];
    sourcemodelout.inside(ind) = true;
end

allInds2 = [ allInds ones(size(allInds,1),1) ];
allInds3 = sourcemodelout.transform*allInds2';
allInds3(4,:) =[];
allInds3 = allInds3';
if ~isequal(allInds3, sourceProjtmp.Vertices)
    error('Issue with transformation');
end

% ----- Create leadfield

cfg            = [];
cfg.elec       = dataPre.elec;
cfg.headmodel  = vol.vol;
cfg.channel    = { 'all' };
cfg.sourcemodel = sourcemodelout;
%cfg.sourcemodel.pos = tmp.Vertices;
[sourcemodel] = ft_prepare_leadfield(cfg);

% ----- Compute spectrum

cfg1 = [];
cfg1.length  = 1;
cfg1.overlap = 0;
dataPreEpochs    = ft_redefinetrial(cfg1, dataPre); % slice data

% Compute spectrum
cfg                  = [];
cfg.output  = 'fourier';
cfg.channel = 'all';
cfg.method  = 'mtmfft';
cfg.taper   = 'boxcar';
dataFreq = ft_freqanalysis(cfg, dataPreEpochs);
freqs1 = dataFreq.freq;

nTrials = size(dataFreq.fourierspctrm,1);
dataFreq.freq = [1:nTrials];
dataFreq.fourierspctrm = permute(dataFreq.fourierspctrm, [3 2 1]);
dataFreq.cumsumcnt = ones(1, size(dataFreq.fourierspctrm,1))*nTrials;
dataFreq.cumtapcnt = ones(1, size(dataFreq.fourierspctrm,1));

% source reconstruction
cfg             = [];
cfg.method      = 'eloreta';
cfg.sourcemodel = sourcemodel;
cfg.headmodel   = vol.vol;
sourceFreq      = ft_sourceanalysis(cfg, dataFreq);  % compute the source model
sourceFreq.time = freqs1;
sourceFreq = rmfield(sourceFreq, 'freq');

cfg = [];
cfg.projectmom = 'yes';
cfg.flipori = 'yes';
sourceProj = ft_sourcedescriptives(cfg, sourceFreq);
 
cfg = [];
cfg.parameter = 'mom';
cfg.operation = 'abs';
sourceProj = ft_math(cfg, sourceProj);

cfg              = [];
cfg.method       = 'ortho';
cfg.funparameter = 'mom';
ft_sourceplot(cfg, sourceProj);

```

**Comment by arnodelorme** [comment]
Data to run the script

[tmp_sourcemodel.mat.zip](https://github.com/fieldtrip/fieldtrip/files/4806542/tmp_sourcemodel.mat.zip)
[dataPre_and_vol.mat.zip](https://github.com/fieldtrip/fieldtrip/files/4806544/dataPre_and_vol.mat.zip)

**Comment by robertoostenveld** [comment]
thanks for sharing the code and data

```

cfg              = [];
cfg.method       = 'ortho';
cfg.funparameter = 'mom';
ft_sourceplot(cfg, sourceProj);
```
fails with

```
Index exceeds the number of array elements (2).
Error in ft_sourceplot (line 986)
    zi = round(zi); zi = max(zi, 1); zi = min(zi, dim(3)); 
```

because 
```
sourceProj = 
  struct with fields:

       pos: [6896×3 double]
      time: [1×65 double]
       mom: {6896×1 cell}
    inside: [6896×1 logical]
       cfg: [1×1 struct]
```
is not a structure that can be reshaped in a [nx, ny, nz] shape. In the title you call it a "volume with holes", I would rather call it "not a volume but rather a collection of random dipole positions".

**Comment by robertoostenveld** [comment]
it will now give the error

```
>> ft_sourceplot(cfg, sourceProj);
the input is source data with 6896 brainordinates
the call to "ft_selectdata" took 0 seconds and required the additional allocation of an estimated 2 MB
not plotting anatomy
not using an atlas
not using a region-of-interest

Error using ft_sourceplot (line 985)
the input source structure cannot be reshaped into a volumetric 3D representation 
```

**Comment by robertoostenveld** [comment]
I do not see a method by which the code of ft_sourceplot would be able to figure out how to make a full 3D grid out of the input that you provide. The idea is (as you already figured out yourself) to specify a 3D array of dipole positions, together with the logical `inside` field to mark which positions are inside the source model (brain) and which ones outside. That allows reshaping the data back-and-forth.

If you can come up with something, we would welcome a pull request. You might want to look at https://github.com/fieldtrip/fieldtrip/blob/master/private/pos2dim3d.m for inspiration.

**Comment by arnodelorme** [comment]
Hi Robert, I provide the code in the issue report to convert 3D grid out of the input that I provided, and it works for me. It recomputes the volume, the inside field and the transform field (assuming the 3-D positions are already in MNI space). It is unclear if having a collection of random locations as I have here is a common occurrence or not (for example the Loreta Key source model depicting voxel locations is in this format), but it is a convenient function nevertheless that you might consider including, and the reverse transformation to get the 3-D vertices of the source model in MNI space is relatively trivial.

pos = cfg.transform*[cfg.pos(cfg.inside) ones(length(cfg.pos(cfg.inside)),1)]';
pos(4,:) = [];
pos = pos';

Happy to assist if you judge this time worthy.

**Comment by schoffelen** [comment]
Hi Arno, The code that you wrote is doing more or less what is done  in ft_source2full. This is a historically very old function, so it might not work flawlessly these days. We have discussed this issue in our local user meeting, and the general consensus was that this is to be solved at the level of the user. Your specific scenario might be well-behaved in terms of dipole positions (i.e. the positions are a subset of a regular 3D grid, where the (x,y,z) triplets nicely correspond with the cardinal axes of the coordinate system. This is not generally to be assumed, so it will be almost impossible to provide a generic solution to the 'filling of holes' procedure. We'd therefore rather leave it the responsibility of the user, or to the people who maintain the official sLORETA template, to make the implicit metadata (i.e. which locations are missing from the 3D grid) explicit to the user.
