### ISSUE TITLE
Error in dipole simulation with OpenMEEG

### ISSUE THREAD

**Issue by oO0oO0oO0o0o00** [fieldtrip/fieldtrip#1467]
**Describe the bug**
I have prepared the head model without problem according to [this tutorial](http://www.fieldtriptoolbox.org/tutorial/headmodel_eeg_bem/) using MRI and electrodes template referenced in the tutorial. The method being used is 'openmeeg'. `ft_prepare_sourcemodel` and `ft_prepare_leadfield` worked fine, but when calls `ft_dipolesimulation` it gives the following error:

> 错误使用  * 
> (Error about matrix multiply with mismatch dimensions, in our local language)
> 
> 出错 ft_compute_leadfield (line 494)
>     lf = sens.tra*lf;
> 
> 出错 ft_dipolesimulation (line 226)
>     lf = ft_compute_leadfield(dippos{trial}, sens, headmodel);

I found that the variable of leadfield in `ft_compute_leadfield.m`, `lf` is `[]`, which caused the problem. The reason is at line 267:

```matlab
    case 'openmeeg'
        % OpenMEEG lead field already computed in ft_prepare_leadfield;
        % load here so any post-processing options (e.g. normalization) may
        % be applied
        lf = ft_getopt(varargin, 'lf');
```

Argument `varargin` is not set at all, line 226, `ft_dipolesimulation.m`:
```matlab
lf = ft_compute_leadfield(dippos{trial}, sens, headmodel);
```

**That's it.**

**To Reproduce**
1. Install OpenMEEG, setup PATH and restart MATLAB.
2. Prepare head model in FieldTrip like this (not the full code):
```matlab
cfg        = [];
cfg.method ='openmeeg';
vol        = ft_prepare_headmodel(cfg, bnd);
```
3. Align electrodes to avoid confusion with other potential problems (optional).
4. Test out `ft_dipolesimulation`:
```matlab
cfg.dip.pos = [0 0.5 0.3];
cfg.dip.mom = [1 0 0]';
cfg.fsample = 250;
% cfg.dip.signal = {sim_brain_act(cfg.fsample*5)}
% in case you don't have `sim_brain_act.m` use sin or cosin.
```
5. Got the error message pasted ahead.

**Expected behavior**
To get the correct result, what else^_^

**Environment and versions (please complete the following information):**
 - Operating System: [Windows 10 x64]
 - MATLAB version [R2019b]
 - FieldTrip version [20200310]

**Comment by robertoostenveld** [comment]
This is a long-standing bug that we were aware of. @sarangnemo implemented the openMEEG leadfield computation for scanning on a pre-defined grid, but back then did not consider dipole fitting. @schoffelen has very recently fixed this in https://github.com/fieldtrip/fieldtrip/pull/1452

Please upgrade to the latest fieldtrip release version and try again. I would love to hear whether it now works for you.

**Comment by oO0oO0oO0o0o00** [comment]
Thanks it's fixed in version 20200623 downloaded from the release page (not available through FTP yet).

It is still needed to `addpath [some folder]\fieldtrip-20200623\external\openmeeg` or an error would pop out about function `ft_sensinterp_openmeeg` not defined. You may want to improve this before the next release. Meow~

**Comment by schoffelen** [comment]
can you specify the stack trace of this error, i.e. which line in which fieldtrip function throws this error?

**Comment by oO0oO0oO0o0o00** [comment]
> can you specify the stack trace of this error, i.e. which line in which fieldtrip function throws this error?

ft_compute_leadfield (line 436)  
`[h2sens,ds2sens] = ft_sensinterp_openmeeg(dippos, headmodel, sens);`

**Comment by schoffelen** [comment]
OK, thanks for reporting. I have now added an explicit check of the path, when openmeeg is required in ft_compute_leadfield. This should take care of the residual error, since it adds openmeeg automatically to the path if needed

1064 $ git commit ft_compute_leadfield.m
[master 663863c] ENH - added check for openmeeg if needed
 1 file changed, 4 insertions(+)
jansch@mentat002:~/matlab/fieldtrip/forward
1065 $ git push upstream master
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 435 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/fieldtrip/fieldtrip.git
   0757282..663863c  master -> master
