### ISSUE TITLE
merge conflict in external npmk code

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1469]
https://github.com/fieldtrip/fieldtrip/blob/04c904d98533ee9dac0a50f41f1fc4a850c8f968/external/npmk/NTrode%20Utilities/splitNEVNTrode.m#L46

**Comment by schoffelen** [comment]
@robertoostenveld how did you come across this? Was it flagged by git? I didn't notice it before. Shall I just resolve it?

**Comment by schoffelen** [comment]
OK, updated in external. I didn't check whether this is present in the official toolbox as well, but frankly I don't care
