### ISSUE TITLE
Enquiry about how to apply the mask parameter in the function 'ft_connectivityplot'.

### ISSUE THREAD

**Issue by luzhuoen123** [fieldtrip/fieldtrip#1478]
Hello,

I am conducting a project about analysing the dynamic functional connectivity based on EEG data from Open Ephys. I have finished the analysis of the dynamic connectivity using ft_connectivityanalysis. I plotted the connectivity figure using ft_connectivityplot as well. Some effects can be detected in the figure. In order to quantify these effects in a systematic way, I considered implementing some statistical testing with the connectivity. Initially I followed the example of the official tutorial and successfully finished the statistical testing with the power spectrum. The result looks good. 

Now I need to implement the test to the 'cohspectrm' from 'ft_connectivityanalysis' in the same way. I know the visualisation of the statistical testing is to plot the parameter with the logical mask from 'ft_freqstatistics'. However, it seems that the plotting function 'ft_connectivityplot' does not have the option about applying the mask parameter in the plotting. 

Therefore, I would like to seek for the guidance about how to achieve the visualisation of the result from statistical testing with the connectivity parameter using 'ft_connectivityplot' or any other function. 

Thank you so much!

Johnny
01/07/2020

**Comment by robertoostenveld** [comment]
Hi Johnny,

This is not the place to ask questions about the use of the FieldTrip toolbox. Please head over to http://www.fieldtriptoolbox.org/support/ and click on the link to the email discussion list. 

best regards,
Robert
