### ISSUE TITLE
Support for jackknife

### ISSUE THREAD

**Issue by noushinquazi** [fieldtrip/fieldtrip#1481]
I would like to use jackknife in conjunction with phase-slope index using ft_connectivityanalysis. Looking through the code, I see that ft_selectdata is invoked with the jackknife option, but it doesn't look like ft_selectdata actually supports it. Is there actually support for jackknife that I missed?

**Comment by robertoostenveld** [comment]
Dear Noushin,

This is not the place to ask for support on *using FieldTrip*, but rather to discuss development. Please head over to http://www.fieldtriptoolbox.org/support/ and from there over to the email discussion list where you can ask your question.

best regards,
Robert
