### ISSUE TITLE
ft_singleplotER - redundant input arguments

### ISSUE THREAD

**Issue by tiborauer** [fieldtrip/fieldtrip#1485]
**Describe the bug**
`ft_singleplotER` calls `ft_plot_vector `with multiple `linewidth` argument: https://github.com/fieldtrip/fieldtrip/blob/1e6c05a048b4c3f36ca6d632c9e6450275ae4e0a/ft_singleplotER.m#L464
https://github.com/fieldtrip/fieldtrip/blob/1e6c05a048b4c3f36ca6d632c9e6450275ae4e0a/ft_singleplotER.m#L468

which generate an error (see below)

**To Reproduce**
1. Load a timelock data with channel "Fz"
2. ft_singleplotER(struct('channel','Fz'), data)
3. See error:
```
Error using ft_getopt (line 92)
multiple input arguments with the same name

Error in ft_plot_vector (line 124)
linewidth       = ft_getopt(varargin, 'linewidth', 0.5);

Error in ft_singleplotER (line 468)
    ft_plot_vector(xval, yval(i,:), 'color', linecolor(i,:), 'linewidth', cfg.linewidth, 'style', cfg.linestyle{i}, 'highlight', mask,
    'highlightstyle', cfg.maskstyle, 'linewidth', cfg.linewidth, 'hlim', [xmin xmax], 'vlim', [ymin ymax], 'facealpha', cfg.maskfacealpha);
```
 
**Expected behavior**
plotting ER for a single channel without error

**Environment and versions (please complete the following information):**
 - Operating System: CentOS7
 - MATLAB version: R2019b
 - FieldTrip version: revision 1e6c05a

**Additional context**
none

**Comment by tiborauer** [comment]
I am happy to submit a PR, but I wanted to confirm first, whether it is intentional and why it did not raise an issue before.

**Comment by tiborauer** [comment]
Sorry, I have realized it was my SPM in the path, which caused the issue.

**Comment by robertoostenveld** [comment]
but the error still applies, right? The option `'linewidth', cfg.linewidth` is double:

```
mac036-lan> grep linewidth.*linewidth.*linewidth *.m
ft_singleplotER.m:  ft_plot_vector(xval, yval, 'color', linecolor, 'linewidth', cfg.linewidth, 'style', cfg.linestyle{1}, 'linewidth', cfg.linewidth, 'highlight', mask, 'highlightstyle', cfg.maskstyle, 'hlim', [xmin xmax], 'vlim', [ymin ymax], 'facealpha', cfg.maskfacealpha);
ft_singleplotER.m:    ft_plot_vector(xval, yval(i,:), 'color', linecolor(i,:), 'linewidth', cfg.linewidth, 'style', cfg.linestyle{i}, 'highlight', mask, 'highlightstyle', cfg.maskstyle, 'linewidth', cfg.linewidth, 'hlim', [xmin xmax], 'vlim', [ymin ymax], 'facealpha', cfg.maskfacealpha);
```

a PR is appreciated!

**Comment by tiborauer** [comment]
The error appear only if SPM is also in the path, and its version of `ft_getopt` cannot handle the redundancy. I assume your version of `ft_getopt` can.

**Comment by robertoostenveld** [comment]
I fixed it anyway, thanks for spotting this.
