### ISSUE TITLE
Issue with infinite recursion?

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1487]
Seems like on some occasion Fieldtrip can create infinite recursions because of overloaded Matlab functions.

https://www.mathworks.com/matlabcentral/answers/466693-out-of-memory-the-likely-cause-is-an-infinite-recursion-within-the-program

I have experienced myself infinite recursion when compiling some functions although I am not sure yet Fieldtrip is at fault.

**Comment by arnodelorme** [comment]
The infinite recursion problem I had myself was with Fieldtrip/compat/matlablt2016b/startsWith.m and ispc.m (matlab function which calls that function). Apparently, somewhere inside startsWith.m, the ispc function is called indirectly. I did not add the path myself but somehow the Matlab compiler must have found that function.

**Comment by robertoostenveld** [comment]
it is `ft_defaults` that adds the compat directories around line https://github.com/fieldtrip/fieldtrip/blob/266e2aec5cfadfc102d9873125f7ee5960a644f9/ft_defaults.m#L226 

Furthermore, there is https://github.com/fieldtrip/fieldtrip/blob/266e2aec5cfadfc102d9873125f7ee5960a644f9/ft_defaults.m#L130 which checks whether https://github.com/fieldtrip/fieldtrip/tree/master/compat/incorrect is on the path (which should never be the case). 

I don't think there is anything I can do at the moment. Perhaps specifically for compiling you might want to delete the `compat` directories altogether, to prevent them from automatically being added to the path by your compile script.

**Comment by arnodelorme** [comment]
Somehow the compiler scans and add all folders and subfolders even though they might not be in the path. I just deleted all these folders and it compiles and runs fine now.

**Comment by arnodelorme** [comment]
One way to fix this issue is to for each of these functions to see if it is overloading a Matlab function (at runtime). I am not sured path to compiled function can be removed at runtime though. Let's close this issue since I resolved it on my side.

**Comment by robertoostenveld** [comment]
the functions are actually checking at runtime whether they overload a MATLAB function, see the cryptical code in https://github.com/fieldtrip/fieldtrip/blob/master/compat/matlablt2016b/startsWith.m 

that is thanks to @gllmflndn 

So there are now three lines of defense
1. carefully add them to the path in ft_defaults.
2. give warning in ft_defaults if the user did it wrong.
3. give warning in the function itself if the user did it wrong.
