### ISSUE TITLE
Error with compiled code

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1488]
ft_version (fieldtrip version lite20200703) does not return a value when called from a compiled Fieldtrip functions. This makes these compiled function crash. Last version of Fieldtrip I was able to compile successfully with EEGLAB was "fieldtrip-lite20180627".

**Comment by arnodelorme** [comment]
Saw there was a fix already. That was quick. I have implemented another fix for Fieldtrip-lite (and it actually works for the compile version). I have issued a pull request.

**Comment by robertoostenveld** [comment]
this has been solved with PR #1489 right? If so, please close this issue/

**Comment by arnodelorme** [comment]
Yes, although I have added some code in my pull request to handle Fieldtrip-lite - and the code also provides the correct version to the compiled version.
