### ISSUE TITLE
hexahedral and tetrahedral meshes are not aligned with the segmentation

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1492]
**Describe the bug**

I added some visual feedback to the test script https://github.com/fieldtrip/fieldtrip/blob/master/test/test_pull1427.m which reveals that the meshes are not aligned with the segmented volume. Furthermore, the tetrahedral mesh has some unusual and irregular refinement on one side.

**To Reproduce**

Run https://github.com/fieldtrip/fieldtrip/blob/master/test/test_pull1427.m

This starts with a regular 10x10x10 segmentation that is centered on head-coordinate position `[5.5 5.5 5.5]`.

<img width="672" alt="Screenshot 2020-07-08 at 11 10 50" src="https://user-images.githubusercontent.com/899043/86900651-e17ba800-c10b-11ea-8ecc-bd65512aab98.png">

From the segmentation a hexahedral mesh is made, which is shifted.

<img width="672" alt="Screenshot 2020-07-08 at 11 11 17" src="https://user-images.githubusercontent.com/899043/86900782-10921980-c10c-11ea-9116-03ccd0bdbc66.png">

From the segmentation a tetrahedral mesh is made, which is shifted AND which has some irregular refinements.

<img width="672" alt="Screenshot 2020-07-08 at 11 11 25" src="https://user-images.githubusercontent.com/899043/86900804-1687fa80-c10c-11ea-810b-32c554a6e838.png">

**Expected behavior**

Both meshes should be aligned and centered on the volume. Since the first voxel is on `[1 1 1]` and the last one on `[10 10 10]`, the center should be in `[5.5 5.5 5.5]` and not like this:

```
>> mean(mesh_vol_hex.pos)
ans =
    5.0000    5.0000    5.0000
```

Furthermore, I would expect the tetrahedral mesh for such a simple segmentation to be nicely behaved.

**Environment and versions (please complete the following information):**

MATLAB 2020a on macOS Mojave
 
latest master, which corresponds to https://github.com/fieldtrip/fieldtrip/commit/54636d667dca8442fefce969e2ef1f84752e5200

**Comment by robertoostenveld** [comment]
please note that in the first ft_sourceplot the crosshair lines are at `[6 6 6]` and not at `[5.5 5.5 5.5]` in the middle because that function insists on intersecting the slices precisely at a voxel. Had it been a 11x11x11 volume, it would have been in the center.

**Comment by schoffelen** [comment]
it seems that #1516 fixes the strange shape of the tetrahedral mesh. 

The hexahedral mesh misalignment stays a bit elusive. I tried to understand prepare_mesh_hexahedral, which I found quite difficult to parse, with the many subfunctions etc. Also, when trying to fix the example in the test function (where I suspected a 0.5 voxel offset issue), I noticed that the misalignment also depends on the specified cfg.resolution (and possibly -> not checked <- on the resolution of the input MRI).

**Comment by schoffelen** [comment]
Update: prepare_mesh_hexahedral relies internally on ft_volumereslice if cfg.resolution ~= 1. 
The mesh seems to align well with the resliced volume, which suggests some unanticipated shift in coordinates between the resliced and non resliced volumes... :(

**Comment by schoffelen** [comment]
OK, test_pull1427 now has some test cases built in to check the hexahedral mesh alignment to the volumetric data. There's still something off.
