### ISSUE TITLE
data2bids discards all marker data in the *.vmrk-file when method=='convert'

### ISSUE THREAD

**Issue by marcelzwiers** [fieldtrip/fieldtrip#1494]
When I convert my eeg-data to BIDS using data2bids and cfg.method='convert' then I only get the header, e.g. like this:
```
Brain Vision Data Exchange Marker File, Version 1.0

[Common Infos]
Codepage=UTF-8
DataFile=sub-POM1FM0023671_task-rest_eeg.eeg

[Marker Infos]
; Each entry: Mk<Marker number>=<Type>,<Description>,<Position in data points>,
; <Size in data points>, <Channel number (0 = marker is related to all channels)>
; Fields are delimited by commas, some fields might be omitted (empty).
; Commas in type or description text are coded as "".
```

However, when I use cfg.method='copy' I get all the info, e.g. like this:
```
Brain Vision Data Exchange Marker File, Version 1.0

[Common Infos]
Codepage=UTF-8
DataFile=sub-POM1FM0023671_task-rest_eeg.eeg

[Marker Infos]
; Each entry: Mk<Marker number>=<Type>,<Description>,<Position in data points>,
; <Size in data points>, <Channel number (0 = marker is related to all channels)>
; Fields are delimited by commas, some fields might be omitted (empty).
; Commas in type or description text are coded as "\1".
Mk1=New Segment,,1,1,0,20190428185532568118
Mk2=SyncStatus,Sync On,1,1,0
Mk3=SyncStatus,Sync On,4501,1,0
Mk4=SyncStatus,Sync On,9501,1,0
Mk5=SyncStatus,Sync On,14501,1,0
Mk6=SyncStatus,Sync On,19501,1,0
Mk7=SyncStatus,Sync On,24501,1,0
Mk8=SyncStatus,Sync On,29501,1,0
Mk9=SyncStatus,Sync On,34501,1,0
[...]
```

Here is some example code to reproduce the problem (I can give you access to the data if you like, just ask me for it):

```matlab
function test_data2bids(method)

if nargin<1 || isempty(method)
    method = 'convert';
end

assert(any(strcmp(method, {'copy', 'convert'})), '"method" can be "copy" or "convert", see data2bids')

% Set the input filename and the (empty) output directory
sourcepath = '/home/mrphys/marzwi/pom/tmp/marcel/data2bids/raw';
targetpath = '/home/mrphys/marzwi/pom/tmp/marcel/data2bids/bids';
sub        = 'POM1FM0023671';
filename   = fullfile(sourcepath, ['sub-' sub], 'ses-mri01', 'emg', [sub '_rest1.vhdr']);
delete(fullfile(targetpath, ['sub-' sub], 'eeg', '*'))

% Set a minimal cfg
cfg          = [];
cfg.method   = method;
cfg.bidsroot = targetpath;
cfg.sub      = sub;
cfg.datatype = 'eeg';
cfg.task     = 'rest';

% Either copy or convert the data to BIDS
if strcmp(cfg.method, 'copy')
    cfg.dataset = filename;
    data2bids(cfg);
else
    % Change channel names
    cfg_                  = [];
    cfg_.dataset          = filename;
    cfg_.montage.labelold = {'1', '2', '3', '4', '9', '10', '11', '12', '13'};
    cfg_.montage.labelnew = {'extensor_right_arm', 'flexor_right_arm', 'extensor_left_arm', 'flexor_left_arm', 'pulse_sensor', 'respiration_sensor', 'accelerometer_x', 'accelerometer_y', 'accelerometer_z'}';
    cfg_.montage.tra      = eye(numel(cfg_.montage.labelold));
    data                  = ft_preprocessing(cfg_);
    data2bids(cfg, data);
end
```

 - Operating System: CENTOS
 - MATLAB version: 2020a
 - FieldTrip version: revision b81c606 (=most recent master branch from github)

**Comment by marcelzwiers** [comment]
Is there any missing information that I can provide that may help?

**Comment by schoffelen** [comment]
I don't know

**Comment by schoffelen** [comment]
Have you read the code? I don't know too much about data2bids myself but reading the code, I see:  

if nargin>1
  % input data was specified
  varargin{1} = ft_checkdata(varargin{1}, 'datatype', {'raw', 'volume'});
  typ = ft_datatype(varargin{1});
elseif ~isempty(cfg.dataset)
  % data should be read from disk
  cfg = ft_checkconfig(cfg, 'dataset2files', 'yes');
  if isfield(cfg, 'headerfile')
    typ = ft_filetype(cfg.headerfile);
  else
    typ = ft_filetype(cfg.presentationfile);
  end
else
  typ = 'unknown';
end 

(line 675 and beyond)

this means that the variable 'typ' is created, conditional on whether you input a data argument, or not (as per the snippet of pasted code of your test function).

**Comment by schoffelen** [comment]
As a consequence the data object that is created as per ft_preprocessing, using cfg_ would need to contain the marker information if it is to be converted into bids format. Most likely, this was not the case, since the only thing that was done in the ft_preprocessing step was the reading in of the data + the renaming if the EMG channels. I am not sure whether a trace of the marker data is saved in the output data object of ft_preprocessing. If this happened to be the case, then it could be that data2bids does not find it, but at the moment I would not rely on your assumption (that the marker data is there to begin with) to be valid.

**Comment by schoffelen** [comment]
Zo, koffiepauze is voorbij, terug aan het werk.

**Comment by marcelzwiers** [comment]
Since I know too little of fieldtrip to make a proper change, I do see this when I change line 679 from:
```matlab
K>> typ = ft_datatype(varargin{1})
typ =
    'raw'
```
to:
```matlab
K>> typ = ft_filetype(varargin{1}.cfg.dataset)
typ =
    'brainvision_vhdr'
```
Is that a change that should be made to the code?

**Comment by schoffelen** [comment]
Can you try whether this works for you:

in the else...end chunk of your test function do:

event = ft_read_event(filename);

and then add the event structure to the cfg that you pass into data2bids?
cfg.event = event;

**Comment by schoffelen** [comment]
sorry, this is not going to work

**Comment by schoffelen** [comment]
Probably it will work, if you pass event to cfg_, or (less elegantly) add event to data.cfg

**Comment by marcelzwiers** [comment]
Yes, passing that event to `cgf_` seems to work! Kuddos for you JM :-)

**Comment by schoffelen** [comment]
I guess the idea is either to pass a data structure that contains all the info that needs to be converted, in which case it should also explicitly contain the events, or to pass the filename/foldername for the data-on-disk that needs to be converted. A hybrid input (e.g. data with changed labels + event data to be read from disk) is probably not a good idea.

Glad to be of help. 

Closing time?

**Comment by schoffelen** [comment]
sure thing, that's what I guessed from the context. Never trust a neurologist.
