### ISSUE TITLE
ft_statfun_cohensd

### ISSUE THREAD

**Issue by as049** [fieldtrip/fieldtrip#1496]
**Describe the bug**
There are minor issues in ft_statfun_cohensd occurring when running it on unpaired data:
Line 73: To perform elementwise matrix powers, use '.^'.
Line 74: To perform elementwise matrix divisions, use './'.
Line 101 and 103 need to be exchanged in order to match with the if-condition (Line 103 is the action to be taken in case cfg.uvar is empty, i.e. in case of unpaired data).

**Environment and versions:**
 - FieldTrip version 20200607

**Comment by schoffelen** [comment]
Hi Antje,
Since you seem to have found your way to github, could you make the code changes in your own version of the repository, and submit them as a Pull Request? Thanks in advance

**Comment by schoffelen** [comment]
fixed with #1498
