### ISSUE TITLE
Speeding up rejectvisual_channel

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1499]
Hi,

I find the rejectvisual_channel function very useful, but it's quite slow. I think this comes from the fact that after each interaction with the GUI, the entire graphics is plotted again (by the redraw subfunction). This means that each time the user marks a trial to exclude by clicking on it, or each time the user moves to a new channel, all graphics are recreated, and the GUI takes several seconds to become responsive again (obviously this becomes worse with more trials). The solution I thought about is this:

Create the entire graphical layout once at the beginning. In the trial plotting loop, get the handles of individual lines from ft_plot_vector, and assign them as children to the figure. When an object is interacted with, change the properties of only that object when those are interacted with. When the user moves to a different channel, loop and change only the YData property of all trials (the layout and excluded trials remain the same, so this should be simple enough).

I wanted to check with you whether it makes sense before submitting a PR. If it does make sense, I think the same logic applies to rejectvisual_trial.

**Comment by schoffelen** [comment]
Go for it! It's been a while that I used this functionality myself, but if I recall well, not all trials/channels might fit into one figure, right? I guess then that the redraw stil needs to recreate handles etc. when this happens

**Comment by NirOfir** [comment]
Great, I'll start working on the code and hopefully make a PR soon. As to your question, right now only one figure is created, regardless of the number of trials. The way the code is structured now, with uiwait, I don't think can be extended to more than one figure. I don't see any reason that this code won't work without uiwait, but that will take more work to do. Anyway, theoretically, what I would do if we want multiple figures is to create them in a loop and make sure that the assignments happen within the loop. The rest should "take care of itself" as long as the handles are in the right place.

**Comment by schoffelen** [comment]
sorry for the confusion, i did not suggest that more than one figure should be created, I just (wrongly) thought that this was the case.

**Comment by NirOfir** [comment]
Oh ok, no problem. I've starting fixing the code, and this is what I've fixed so far:

1. There's a redundant condition in the while loop that maintains focus on the GUI ('interactive' is set to 1 before the loop but nothing else ever touches it, so it's a condition that can't fail).
2. During redraw, tmin (min timepoint for all trials), tmax (max timepoint for all trials) and amax (maximum amplitude, later ymin and ymax are calculated and used) are calculated but not used.
3. All subfunctions had varargout that weren't set.
4. There were redundant conditions making sure that users weren't moving beyond the first or last channels using keyboard arrows. This was tested both in the key() subfunction and in the next() and prev() subfunctions. 
5. Command output was "at last channel" if the user tried to go back from the first channel.
6. I made the implementation of next(), next10(), prev() and prev10() consistent w.r.t checking that the user isn't going beyond the first or last channels.

Right now, if the user clicks the close button of the figure at the top right rather than the quit button that is created for the GUI, any choices that he made are discarded. Is that the intended behavior? That's easy to fix by modifying closeRequestFcn.

I found another error, that blocks my progress here in ft_plot_vector (#1500, PR coming soon). I'll continue working on the current PR once ft_plot_vector is fixed.

**Comment by NirOfir** [comment]
One more thing I found: There was some field in info (the guidata struct), which held the index of the previous selected channel. It was used only once in a redundant if check, so I removed it.

**Comment by NirOfir** [comment]
One last thing that I don't know how to solve, but I came across also in the old version of the code: Any use of any of the GUI buttons disables the keyboard input to the GUI for some reason. More mysteriously, if you go back to the first channel in the bunch, the GUI is suddenly willing again to accept keyboard input...
