### ISSUE TITLE
ft_dipolesimulation is not accepting cfg.dip for phase, frequency or amplitude

### ISSUE THREAD

**Issue by Richter2552** [fieldtrip/fieldtrip#1505]
When cfg settings are provided for cfg.dip.phase / frequency / amplitude, FT ignores them

Simple fix: on line 169 - 171 FT is searching cfg, not cfg.dip for these settings, it doesn't find any, so it goes to default.

Best,

C .

**Comment by schoffelen** [comment]
@Richter2552 could you follow up on this and make a pull request that contains the fix that you propose?

**Comment by schoffelen** [comment]
This has been fixed by a  recent PR from @Richter2552
