### ISSUE TITLE
Small issues with rejectvisual_summary

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1509]
**Describe the bug**

1. Until recently, when a channel was excluded in summary mode, the text field showed the label along with the (less informative) number in parentheses. I think that PR #1405 broke that (relevant lines are around 330), and now only the number is shown.
2. Another thing that changed recently (less than two months) is that editable text fields for channels and trials used to keep the choice after the user pressed enter, which was comfortable, because it allowed quickly toggling back and forth to see the effect of removing the channel/trial on the maximum value of the statistic. Now, when the user presses enter, the editable fields are cleaned.
3. One last thing actually changed to the better, but can be improved, is that the text fields for rejected trials channels are slightly too large, and spill outside the figure. For both, their position is in normalized units, the left edge is 0.795 and the width is 0.21, so the right edge is 1.05.

I hope to get around to fixing these small things myself soon.

**Comment by schoffelen** [comment]
I remember that the PR you refer to was quite some work (both conceptually and in terms of code overhaul), so it could be indeed that some of the old behavior (i.e. in terms of feedback in the gui) might have been lost. I don't know whether that was on purpose, or not. This specifically refers to your point 1., but it could well be that this was by accident. Points 2 and 3 seem fine to address (although I don't fully understand 2).

**Comment by NirOfir** [comment]
Thanks for the response!
1. Here are the relevant lines:
 ```
 if ~all(info.chansel)
   if false % isfield(info.data, 'label')
     excludechantxt = sprintf('%s, ', info.data.label{~info.chansel});
   else
     excludechantxt = sprintf('%d, ', find(~info.chansel));
   end
   excludechantxt = excludechantxt(1:end-2);
   set(info.excludechantxt, 'String', excludechantxt, 'FontAngle', 'normal');
 else
   set(info.excludechantxt, 'String', 'No channels to exclude', 'FontAngle', 'italic');
 end
 ```
The first indented if statement will always be false, meaning that only the second option, comma separated channel numbers, is used. I couldn't a find a comment as to why the first option was set to false, which looks a bit like a placeholder. If you have any more info about this, I'd be happy to know.

2. I'll try to clarify: When the user inserts a channel or trial using the editable text box and presses enter, the selection is excluded, and the editable text box is cleaned. This makes sense generally, but I found that the advantage of keeping the selection in the box is that you could repeatedly toggle the channel/trial on and off, which helps see the effect it has (how many channels are affected in a suspect trial / how many trials are affected by a suspect channel). This was changed and explicitly mentioned in commit de54a16a093c5a1828c034988004d3db5557bcc6, so I don't want to change it without clearly discussing it first :)

**Comment by schoffelen** [comment]
I am not sure, but rejectvisual_summary has changed a bit in the meantime, with the 'GUI' a bit improved hopefully, and the functionality that toggling channels/trials back and forth is facilitated (now by clicking on the list, rather than keeping it 'active' in the selection window). I have the feeling that the concerns raised in this issue therefore have been addressed, and I like to close the issue. Feel free to reopen, or file a new issue if you feel we should still do some work on this @NirOfir
