### ISSUE TITLE
Error: ft_filetype() at line 176

### ISSUE THREAD

**Issue by mellingerjess** [fieldtrip/fieldtrip#1515]
**Describe the bug**

When I attempt to run dipfit using the following code, or through the gui, I get an error related to fieldtrip:

EEG = pop_multifit(EEG, [1:numChannels] ,'threshold',15,'rmout','on','plotopt',{'normlen' 'on'});

The error reads:

"EEGLAB error in function ft_filetype() at line 176:
Undefined function 'filetype_check_extension' for input arguments of type 'char'.
This is a problem with FIELDTRIP. The Fieldtrip version you downloaded is corrupted. Please manually replace Fieldtrip with an earlier version and/or email the Fieldtrip developers so they can fix the issue."

**To Reproduce**

Either use the Autofit option in the eeglab gui or this code:

EEG = pop_multifit(EEG, [1:numChannels] ,'threshold',15,'rmout','on','plotopt',{'normlen' 'on'});

**Expected behavior**

I expect pop_multifit() to run successfully.

**Environment and versions (please complete the following information):**

 - Operating System: Windows 10
 - MATLAB version: R2019a update 1
 - FieldTrip version: Fieldtrip-lite20200709

**Comment by robertoostenveld** [comment]
the function `filetype_check_extension.m` should be present in fileio/private. Can you check whether you have it there?  See also https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/filetype_check_extension.m

**Comment by mellingerjess** [comment]
Hello,

Yes, I see the function in that folder. I checked and I do have it.

Thanks,
Jess

**Comment by robertoostenveld** [comment]
then it means that you don't have the FieldTrip path set up correctly. You write that you use Fieldtrip-lite20200709, however, the error is at line 176 of `ft_filetype`. When I look at that function from the 20200709 I see that line does not call `filetype_check_extension`. You can check yourself, see https://github.com/fieldtrip/fieldtrip/blob/20200709/fileio/ft_filetype.m which is the 20200709 version.

Please check that you don't use different versions of fieldtrip on your path. E.g. do 
```
which ft_filetype
```
and
```
which ft_defaults
```
to see which FieldTrip version is being used.

**Comment by mellingerjess** [comment]
That was the problem. I had downloaded fieldtrip into the eeglab plugins
folder, but there was already a separate folder in there called Fileio with
an ft_filetype, and also a Fieldtrip-8e24be2 in the institution's MATLAB
add-ons.

which ft_filetype indicated that I was using ft_filetype from the other
Fileio and which ft_defaults indicated ft_defaults was set to the add-ons
folder.

Thank you!
