### ISSUE TITLE
error using ft_preprocessing

### ISSUE THREAD

**Issue by fleur-jacobs5** [fieldtrip/fieldtrip#1517]
When I attempt to apply a low pass filter by running ft_preprocessing using the following code,  I get an error related to fieldtrip:

%low pass filter  to get rid of electrical noise
cfg                = [];
cfg.lpfilter       = 'yes';        % enable low-pass filtering
cfg.lpfreq         = 150;          % set up the frequency for low-pass filter
cfg.dftfilter      = 'yes';        % enable notch filtering to eliminate power line noise
cfg.dftfreq        = [50 100 150]; % set up the frequencies for notch filtering
data               = ft_preprocessing(cfg,data);
%data               = ft_preprocessing(cfg,eeg_data);

The error reads:

_"Error using butter (line 83)
butter: critical frequencies must be in (0 1)

Error in ft_preproc_lowpassfilter (line 151)
    [B, A] = butter(N, max(Flp)/Fn);

Error in preproc (line 343)
  if strcmp(cfg.lpfilter, 'yes'),     dat = ft_preproc_lowpassfilter(dat, fsample, cfg.lpfreq,
  cfg.lpfiltord, cfg.lpfilttype, cfg.lpfiltdir, cfg.lpinstabilityfix, cfg.lpfiltdf,
  cfg.lpfiltwintype, cfg.lpfiltdev, cfg.plotfiltresp, cfg.usefftfilt); end

Error in ft_preprocessing (line 368)
    [dataout.trial{i}, dataout.label, dataout.time{i}, cfg] = preproc(data.trial{i}, data.label,
    data.time{i}, cfg, begpadding, endpadding);."_

To Reproduce
Use the code above. 

Expected behavior
I expect this code to run successfully since this was before. 

Environment and versions (please complete the following information):

Operating System: Windows 10
MATLAB version: R2019b update 1
FieldTrip version: Fieldtrip-lite20200305

**Comment by schoffelen** [comment]
This is not the right place to ask this question. Please join the fieldtrip discussion list, and ask your question there. Also, it may help to browse the documentation a bit, as well as the discussion list's archive, because this question might have been asked before.
