### ISSUE TITLE
method = 'svd' not implemented correctly in ft_combineplanar

### ISSUE THREAD

**Issue by yingjoeyzhou** [fieldtrip/fieldtrip#1521]
**Describe the bug**
Implemented the pipeline described here (https://mailman.science.ru.nl/pipermail/fieldtrip/2013-January/031961.html) by Jan-Mathijs. Matlab showed error msg 
_Error using reshape 
To RESHAPE the number of elements must not change. 
Error in ft_combineplanar (line 187) 
dum = reshape(dum(1,:),[Ntim Nrpt]);_

**To Reproduce**
See the described pipeline in the above link.

**Expected behavior**

**Screenshots**
NA.

**Environment and versions (please complete the following information):**
 - Operating System: Linux (DCCN cluster)
 - MATLAB version R2018b
 - FieldTrip version in _.../common/matlab/fieldtrip_

**Additional context**
Proposed fix: name the second output of line 184 `[loading, dum,  ori, sin_val] = svdfft(dum(:,timbin),2,data.cumtapcnt);` (i.e., variable `dum` differently should solve the issue.

**Comment by robertoostenveld** [comment]
can you share a `freqplanar.mat` file such that I can reproduce the code snippet

```
cfg = [];
cfg.method = 'svd'; % which is equivalent to PCA
freqcombined = ft_combineplanar(cfg, freqplanar);
```
?

**Comment by yingjoeyzhou** [comment]
sure. here it is. data from 10 trials. 

it's in _.../common/temporary/4Robert_ in the home drive.

**Comment by robertoostenveld** [comment]
thanks.

for reference, I have copied it to the location with files for the test batch.

```
cp freqplanar.mat /home/common/matlab/fieldtrip/data/test/issue1521.mat
```

**Comment by robertoostenveld** [comment]
I was able to reproduce. the error is specific for time-frequency data where the Fourier spectrum contains NaNs at the edges for the lower frequencies (which is quite common).
