### ISSUE TITLE
A possible bug in ft_version.m in fieldtrip-20200607

### ISSUE THREAD

**Issue by HeidiYan** [fieldtrip/fieldtrip#1524]
**Describe the bug**
When I was using fieldtrip tool from brainstorm, an error appeared in **line 148** in ft_version.m

```else
  a = ver(ftpath);
  ftver = a.Version;
```

I found this function would return the version info of fieldtrip, and my  fieldtrip file (fieldtrip-20200607)should have been matched to the condition
 
```
elseif isequal(regexp(ftpath, ['.*' filesep 'fieldtrip-20[0-9]{6}']), 1)     
% this corresponds with the daily version from the ftp server 
% which results in a ftpath like /Users/robert/matlab/fieldtrip-20160317
  ftver = ftpath(end-7:end);
```
but it failed to match the regexp, that's why the program runned into the error sentence.
 After examing the regexp, I found that the filesep of my system was '\\', which was a special character (escape character), and if I want to match the character'\\', another '\\' has to be added before the '\\'.
Thus, I edited the sentence
```
elseif isequal(regexp(ftpath, ['.*' filesep 'fieldtrip-20[0-9]{6}']), 1)  
```   
as
```
elseif isequal(regexp(ftpath, ['.*\' filesep 'fieldtrip-20[0-9]{6}']), 1)  
```

**My question is**
Is there  a bug in the ft_version.m as I  described?
If so, is my edition right?

**Comment by robertoostenveld** [comment]
Thanks for reporting in detail. You seem to be right about this. We have many windows users,  so I wonder why nobody ever noticed this before.

I don't have a windows computer myself, and (still) working from how it is more difficult to test the ft_version function as a whole on the computer of a colleague. 

But I can test the small part that you drilled down to: on linux and macOS the string is `.*/fieldtrip-20[0-9]{6}` and on windows it is now `.*\fieldtrip-20[0-9]{6}` 

```
>> regexp('/a/b/c/fieldtrip-20200202', '.*/fieldtrip-20[0-9]{6}') % macOS now
ans =
     1
>> regexp('/a/b/c/fieldtrip-20200202', '.*\/fieldtrip-20[0-9]{6}' )% macOS with extra \
ans =
     1
>> regexp('\a\b\c\fieldtrip-20200202', '.*\\fieldtrip-20[0-9]{6}') % Windows with extra \
ans =
     1
```

your suggested edit therefore seems correct, both for windows and macOS/linux.

Do you want to submit it yourself as a pull request? In that case you will be recognized and listed as a contributor. We have a full tutorial for that, see http://www.fieldtriptoolbox.org/development/git

Of course I could also do this small edit for you, whatever you prefer.

**Comment by HeidiYan** [comment]
Thanks for your quick reply!    
It's a small edition, please just do it for me. :)
@robertoostenveld

**Comment by robertoostenveld** [comment]
I have made the edit, it will be in the upcoming release version.
