### ISSUE TITLE
Undefined function 'isfolder' for input arguments of type 'char'

### ISSUE THREAD

**Issue by bell-star** [fieldtrip/fieldtrip#1527]
When I called it in the EEGLAB toolbox, the following problems occurred.
Warning: removing "D:\Program\MATLAB\R2013b\eeglab2019_1\plugins\Fieldtrip-lite20200811\compat\matlablt2016b"
from your path, see http://bit.ly/2SPPjUS 
Warning: removing "D:\Program\MATLAB\R2013b\eeglab2019_1\plugins\Fieldtrip-lite20200811\compat\matlablt2017b"
from your path, see http://bit.ly/2SPPjUS 
Error using feval
Undefined function 'isfolder' for input arguments of type 'char'.

Error in isfolder (line 34)
    [varargout{1:nargout}] = feval(mfilename, varargin{:});

Error in ft_version (line 78)
  issvn = isfolder(fullfile(ftpath, '.svn'));

Error in ft_preamble_init (line 50)
[FjmoT6aA_ft_ver, FjmoT6aA_ft_path] = ft_version;

Error in ft_preamble (line 83)
evalin('caller', full_cmd);

Error in ft_timelockanalysis (line 89)
ft_preamble init

**Comment by robertoostenveld** [comment]
the first message indicates that you added **all** subdirectories of fieldtrip to your path, which you should not do (see http://bit.ly/2SPPjUS).

As a consequence also the `matlablt2017b`folder is removed from your path, along with all other `compat` subfolders. Since you are using a MATLAB version older than 2017b, the function `isfolder` is not supported in your MATLAB version itself, and cannot be found any more in `matlablt2017b`.

Please set up your path correctly following the instructions here http://www.fieldtriptoolbox.org/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path/. The `matlablt2017b` directory, including the `isfolder` function will be added automatically for your MATLAB version.

**Comment by AmirAvnit** [comment]
These issues may also occur if the FieldTrip main folder is a subdirectory of the MATLAB folder, resulting from the way FieldTrip examines whether the required .m file exists in MATLAB's subdirectories.

Thus, when relevant, moving FieldTrip outside of the MATLAB directory (and removing previous paths), and then following the instructions in http://bit.ly/2SPPjUS may be the solution.

**Comment by robertoostenveld** [comment]
Hi @AmirAvnit 

To follow this up: what do you mean with "if FieldTrip ... is a subdirectory of the MATLAB folder"? 

The reason for asking is that there might be perfectly sane MATLAB use-patterns that I am not aware of, e.g. for people on Windows computers. We might want to update the documentation a bit to explain the challenges with path settings for those use patterns better.

**Comment by AmirAvnit** [comment]
Hi @robertoostenveld,

I mean that the fieldtrip directory is located inside the MATLAB folder; for example:
C:\Program Files\MATLAB\R2017a\toolbox\fieldtrip-20201023

This causes Fieldtrip to erroneously remove folders in fieldtrip-20201023\compat from the user's path, although they include functions which are required by Fieldtrip and do not exist in the user's Matlab version, as indicated by the "Warning: removing..." messages.
This results in missing functions, as indicated by the "Undefined function 'isfolder'..." error message.

Moving the fieldtrip folder to a location not inside the MATLAB folder solved this issue for me, as the required folders were not removed from path.

**Comment by robertoostenveld** [comment]
ah, that explains it!

Most functions in `compat` include some code that tries to detect that people have done `addpath(genpath(...))` and fix it automatically. That fails in your case.

**Comment by robertoostenveld** [comment]
future fieldtrip releases will not do the checking for incorrect `compat` directories in case fieldtrip is installed under the MATLAB root directory
