### ISSUE TITLE
rename NIRS oxygenated, deoxygenated and total haemoglobin into HbO/HbR/HbT

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1532]
**Is your feature request related to a problem? Please describe.**

In line with nomenclature that is used by other NIRS researchers, I propose that the naming of oxygenated, deoxygenated and total haemoglobin are changed to converge and facilitate knowledge accumulation and transfer. 

Specifically this relates to `ft_nirs_transform_ODs` 

```
%   cfg.target             = Mx1 cell-array, can be 'O2Hb' (oxygenated hemo-
%                            globin), 'HHb' de-oxygenated hemoglobin') or
%                            'tHb' (total hemoglobin), or a combination of
%                            those (default: {'O2Hb', 'HHb'})
```

and `ft_nirs_prepare_ODtransformation`, but there are also some documentation and test scripts that need changes.  

**Describe the solution you'd like**

Search and replace (in the code and cocumentation)  O2Hb -> HbO, HHb -> HbR, and  tHb -> HbT. 

**Describe alternatives you've considered**

We could keep it like this. In that case, when adding more code and more examples, we will diverge more from other toolboxes.  

**Additional context**

- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3263786
- https://neuroimage.usc.edu/brainstorm/Tutorials/NIRSFingerTapping 
- https://mne.tools/dev/auto_tutorials/preprocessing/plot_70_fnirs_processing.html
- http://homer-fnirs.org/faq/#concentration%20overlay
- Ted Huppert's NIRS toolbox [here](https://bitbucket.org/huppertt/nirs-toolbox/src/f9f3d407a73d470c8210c2b185f0912625023ae2/demos/Examples/Example_Adding_HbT.m?at=master#Example_Adding_HbT.m-29,35,39,72,77) although that seems to use both HbO and HbO2.

**Comment by robertoostenveld** [comment]
I would like to get the opinion of @Horschig @marcvanwanrooij @jannystapel @helenacockx and other researchers working on NIRS.

**Comment by Horschig** [comment]
Those terms are mainly used because the Homer community is using those. According to Willy it is simple:
HbO2 and HHb are correct, and HbO  and HbR are incorrect. Oxygen is O2, which already indicates that oxygenated hemoglobin means O2 bound to hemoglobin, not O. HbR is supposed to stand for "reduced hemoglobin" Some evidence that this is wrong or outdated can be found on https://en.wikipedia.org/wiki/CO-oximeter:
"but normal hemoglobin (HHb) (formerly, but incorrectly, referred to as 'reduced' hemoglobin),"

FieldTrip could use the outdated / wrong nomenclature, but that would in my opinion send the wrong message to the community (namely: it is okay to use what is wrong, just because it is convention by some people).

**Comment by jannystapel** [comment]
Maybe good to know: SNIRF uses HbO, HbR and HbT: https://github.com/fNIRS/snirf/blob/master/snirf_specification.md
But indeed, that might be because the Homer community uses these terms.

**Comment by robertoostenveld** [comment]
Language is subject to change given its use and more often strictly technical incorrect. E.g. we refer to an individual piece of music as a  "song", even if it is instrumental (i.e. there is no singing involved).

Which terms are used in the software and documentation of other companies? And which terms are mostly used in literature and by the NIRS society? Are there NIRS guidelines or best practice papers that use either term?

**Comment by robertoostenveld** [comment]
> Maybe good to know: SNIRF uses HbO, HbR and HbT ...

indeed, it is part of a controlled vocabulary in this [table](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#supported-measurementlistkdatatypelabel-values-in-datatimeseries). That makes it likely that these terms will also be adopted in BIDS.

**Comment by robertoostenveld** [comment]
@helenacockx brought up in https://github.com/fieldtrip/fieldtrip/pull/1540#issuecomment-688318973 that

> Regarding the label field: could it be a solution to represent the Tx and Rx (transmitters and receivers) in FT as source (S) and detector (D) too? It would make the FT format also more consistent with the snirf format that way.

I think that is a good suggestion, especially since that we'll be aligning more with SNIRF.

**Comment by robertoostenveld** [comment]
Since this pertains to the code in `fieldtrip/external/artinis`, and @Horschig and Willie don't like the idea, I don't think there is a reason to keep this issue open.
