### ISSUE TITLE
regression error due to change in denoising of STIM channel 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1535]
**Describe the bug**

The reading of events from a fif file seems to be broken due to #1534

```
Reading 111000 ... 278999  =    444.000 ...  1115.996 secs... [done]
Reading 111000 ... 278999  =    444.000 ...  1115.996 secs... [done]
Error using read_trigger (line 261)
Index exceeds the number of array elements (0).
Error in ft_read_event (line 1616)
Error in test_bug2170 (line 18)
Error in ft_test_run (line 212)
Error in ft_test (line 118)
Error in test_DjZR1mfw (line 20)
=== test_bug2170 FAILED in 14 seconds
```

**To Reproduce**

Execute test_bug2170 on compute cluster with the latest master branch of FIeldTrip.
 
**Expected behavior**

The test script should pass without errors. 

**Additional context**

The older neuromag fif files would have STIM channels with a noisy  ~5V stim channel representing TTL pulses.

**Comment by robertoostenveld** [comment]
there appear to be more regression errors due to merging #1533 and #1534 

```
mentat001> grep FAILED *.txt
test_artinis_oxy.txt:=== test_artinis_oxy FAILED in 52 seconds
test_bug1306.txt:=== test_bug1306 FAILED in 68 seconds
test_bug2170.txt:=== test_bug2170 FAILED in 14 seconds
test_bug2220.txt:=== test_bug2220 FAILED in 66 seconds
test_ft_preprocessing.txt:=== test_ft_preprocessing FAILED in 105 seconds
test_issue1387.txt:=== test_issue1387 FAILED in 2 seconds
test_issue1438.txt:=== test_issue1438 FAILED in 1 seconds
```

**Comment by schoffelen** [comment]
This can be closed @robertoostenveld , right?

**Comment by robertoostenveld** [comment]
oh yes, this has been resolved with https://github.com/fieldtrip/fieldtrip/commit/5b82f4bd82e20e587a276b664ebb1ffc5cf93b75
