### ISSUE TITLE
Computation of an interaction using EEGLAB's Fieldtrip-lite20200816 plugin

### ISSUE THREAD

**Issue by CorentinWicht** [fieldtrip/fieldtrip#1536]
Dear Dr. Oostenveld,

after raising an issue on the [EEGLAB's github webpage](https://github.com/sccn/eeglab/issues/202), I was wondering whether it is now possible to  **compute the interaction of a 2x2 mixed ANOVA** using ```non-parametric Monte-Carlo permutations``` with multiple comparisons correction set up to ```Max```?

Many thanks and best regards,

Corentin Wicht

**Comment by schoffelen** [comment]
Hi Corentin,

Questions of this type are best asked on our discussion list:
http://www.fieldtriptoolbox.org/discussion_list/

Note that this particular question, about non-parametric testing of interaction effects pops up now and then, and has been discussed on various occasions, both on the discussion list, and on the fieldtrip website. My suggestion is to start from the mailing list's archive (which is searchable):

Some relevant links (but there may be others):

http://www.fieldtriptoolbox.org/faq/how_can_i_test_an_interaction_effect_using_cluster-based_permutation_tests/

https://mailman.science.ru.nl/pipermail/fieldtrip/2018-September/025238.html
