### ISSUE TITLE
short channels in the Artinis NIRS system result in messed-up 2D positions

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1539]
The channels load fine in FieldTrip, but the `opto` structure (based on the optodetemplate.xml) might be wrong. Helena reported that this results in receivers being represented twice. Furthermore, when using `oxysoft2matlab`  the resulting Homer `.nirs` file or SNIRF file contains positions that are inconsistent. 

This needs to be tested and further clarified. Perhaps it is required to implement something to update the positions in the SNIRF file, e.g. based on a Polhemus or Structuresensor measurement of the actual positions.

This will also require input from @Horschig

**Comment by robertoostenveld** [comment]
perhaps this requires writing the correct positions to the `_optodes.tsv`

**Comment by robertoostenveld** [comment]
I am not sure how to reproduce this any more. 

@helenacockx do you know what this was about? If you don't know either, I propose to close it as unresolved.

**Comment by Horschig** [comment]
Sorry, really hard to explain this without going into a lot of detail....

**Comment by helenacockx** [comment]
Yes, that was indeed the issue. Might be good to explain this to people designing the optode templates :)

**Comment by Horschig** [comment]
Yea, we're working on that... ;) and sorry for taking about a year to respond to this.

**Comment by robertoostenveld** [comment]
I think that right now we don't want to continue on this in FieldTrip code our documentation, right? 

If this would be followed up in Artinis software and/or documentation, perhaps in due time it could be mentioned on https://www.fieldtriptoolbox.org/getting_started/artinis/

Let me close this issue.
