### ISSUE TITLE
read channels, electrodes, optodes and events.tsv from BIDS datasets

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1545]
Datasets organized according to BIDS (see https://bids-specification.readthedocs.io/en/stable/) have additional human- and machine-readable metadata in so-called sidecar files. This includes the JSON files and also the `channels.tsv`, `electrodes.tsv`, `events.tsv` and for the coming BEP030 `optodes.tsv`. 

These  are located next to the original (binary) data files. Their purpose is to allow querying, but they also allow the user to overrule (or correct) and to extend the information in the original binary headers. E.g., when two EEG channels are swapped on the amplifier but not specified correctly in the acquisition software (and hence not in the header), or when electrode positions are measured with an external device that is not integrated with the EEG system.

In case these sidecar files are available, FieldTrip should read them and use the information in them as intended by BIDS, i.e. to extend and.or overrule the information from the binary files.

I propose to extend `ft_read_header`, `ft_read_event` and `ft_read_sens`. These return structured information that directly relates to the sidecar files. 

I don't think that `ft_read_data` or `ft_read_headshape` need to be extended in any major way, proabbly only some minor changes to pass options to `ft_read_header`. 

I am not sure yet if `ft_read_mri` needs to be extended. There is information in the JSON sidecar that accompanies the nifti file, but that does not directly overrule the nifti file and would not be used to interpret the MRI.

**Comment by schoffelen** [comment]
I think that ft_read_event is already capable of reading in BIDS event.tsv files, 'eventformat', 'bids_tsv' takes care of this.

**Comment by robertoostenveld** [comment]
yes it does, but only if you specify the `_events.tsv` as filename. 

I have now changed it (not yet committed) such that ft_read_event checks that the input file is an EEG, MEG, iEEG or NIRS data (i.e. starts with `sub-xx`, ends with the datatype as suffix) file in BIDS standard, and if so, it switches to reading the corresponding `events.tsv` rather than reading the native triggers/events.  It then uses the existing code. For reading the native events, you can specify the option `readbids=false` (default is `true`)

**Comment by robertoostenveld** [comment]
The new code has an interesting consequence for @helenacockx. If you use `data2bids` to convert Artinis data to BIDS and snirf, the Rx/Tx labels end up in the `channels.tsv` (as discussed yesterday). If you would read the snirf file as is (ignoring the `channels.tsv`), it will have channels S/D.  If you now read it with the new code, it will first read the header info from the snirf file, but then overrule that with the Rx/Tx channel names from the BIDS `channels.tsv`. So the data in BIDS/snirf format still adheres to Artinis channel names. 

The new code also supports [inheritance](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#the-inheritance-principle), so there can be a single channels.tsv at the top level which can be used for all snirf files.

**Comment by robertoostenveld** [comment]
this has been implemented about a month ago with fed1e6575db5a604aed1d9b83503ea872991311e (and some commits around it)
