### ISSUE TITLE
Nicolet .e file format error

### ISSUE THREAD

**Issue by janbrogger** [fieldtrip/fieldtrip#1548]
### Description
Some Nicolet .e  files fail reading because of a file format problem. Could be related to #1357 

<br>
#### Steps to Reproduce

1.  `pop_fileio('a_failing_file.e')`
```
Reading data ...
Unable to perform assignment because the size of the left side is 1854834-by-1 and the size of the right side is
983352-by-1.
```

Error in read_nervus_data (line 148)
        out(curIdx : end,i) = fread(h, length(out)-curIdx + 1, 'int16') * mult;[*First Step*]

<br>
#### Expected behavior:
No error. File is just read.

<br>
#### Actual behavior:
See above

<br>
#### Versions
|   |   |
|----| ---- | 
| OS version     | Windows 10. |
| Matlab version | 9.5.0.1067069 (R2018b) Update 4 |
| EEGLAB version | EEGLAB is from up-to-date develop branch at https://github.com/sccn/eeglab/tree/73165f45dadb424b8906f99e53774caf8e56d965
 |

**Comment by janbrogger** [comment]
I can't share the data, since it's clinical.

**Comment by schoffelen** [comment]
OK, how do you propose to proceed? You are clearly the expert on this file format :)... is 'a_failing_file.e' a member of a family of failing files, or a one-off failure?

Also, I wouldn't rely on the version in EEGLAB, because this seems to be an older version of the code. The fieldtrip version of read_nervus_data is different, i.e. around line 148 or so there's the following code chunk:

if length(useSections) > 1
    % Full Segments
    for j = 2: (length(useSections)-1)
      curSec = nrvHdr.MainIndex(useSections(j));
      fseek(h, curSec.offset,'bof');
      
      out(curIdx : (curIdx + useSectionL(j) - 1),i) = ...
        fread(h, useSectionL(j), 'int16') * mult;
      curIdx = curIdx +  useSectionL(j);
    end
    
    % Final Partial Segment
    curSec = nrvHdr.MainIndex(useSections(end));
    fseek(h, curSec.offset,'bof');
    %Sometimes there is less data available in the file.
    %So we calculate the wanted lastReadLength,
    %but assign in the data array the actualReadLength
    lastReadLength = length(out)-curIdx+1;
    %disp(['LastReadLength: ' num2str(lastReadLength)]);
    lastData = fread(h, lastReadLength, 'int16');
    actualReadLength = length(lastData);
    %if (actualReadLength <lastReadLength)
    %  warning('Some data not found');
    %disp(['ActualLastReadLength: ' num2str(lastReadLength)]);    
    out(curIdx : (curIdx+actualReadLength-1),i) = lastData * mult;
  end

**Comment by janbrogger** [comment]
Yeah, I noticed now that the EEGLAB code is old. This issue is actually already fixed. Sorry!

**Comment by schoffelen** [comment]
No problem, feel free to close this issue and ping @arnodelorme that it might be worthwhile to upgrade the fileio module in eeglab

**Comment by janbrogger** [comment]
Thanks! Posted the issue to EEGLAB here https://github.com/sccn/eeglab/issues/208
