### ISSUE TITLE
offline .oxy3 file is refering to non-existing template ID in optodetemplate.xml?

### ISSUE THREAD

**Issue by helenacockx** [fieldtrip/fieldtrip#1550]
When reading in an offline .oxy3 file with the following lines of code, a warning `Warning: optode template not found in optodetemplate.xml`  and error `Error using read_oxy3_header. could not find corresponding optode template` is given. Here you can find an example datafile: [https://surfdrive.surf.nl/files/index.php/f/7924505585](https://surfdrive.surf.nl/files/index.php/f/7924505585) 

```
cfg=[];
cfg.dataset='22-11-2019-10_28_55_Dev24065.oxy3';
data=ft_preprocessing(cfg);
```

It is hard to fix this bug because the read_oxy3_header is private, but when using the function `oxysoft2matlab` I am encountering similar problems. On line 501 of oxysoft2matlab `arrangeoxy3optodes` is generating a variable  `metaInfo`  which holds a field `metaInfo.OptodeTemplateID` and is 100 in this case. When comparing this to the optodetemplates.xml file, I cannot find a template with ID 100, so possibly this is causing the error. 

Is it possible to add an option to provide `read_artinis_oxy3` to specify the template ID for example? 

I am working on Windows 10, the most recent master branch from github and Matlab R2019a.

**Comment by helenacockx** [comment]
@Horschig, maybe you can have a look at this?

**Comment by robertoostenveld** [comment]
Hi @helenacockx I cannot access the file on surfdrive: "You don't have permissions to access this file/folder - Please contact the owner to share it with you." Can you have a look at the sharing settings?

**Comment by helenacockx** [comment]
I am sorry. Here is the correct link: [https://surfdrive.surf.nl/files/index.php/s/TU7jiXPaqF0rhaL](https://surfdrive.surf.nl/files/index.php/s/TU7jiXPaqF0rhaL)

**Comment by helenacockx** [comment]
In oxysoft2matlab you can specify metaProj (including metaProj.optodeTemplateID), so this already helps to import the offline measurements with the right template. It would be great if such an option would also exist for the read_artinis_oxy3 and related functions.

**Comment by Horschig** [comment]
Hey, yes, the problem is that the optodetemplates.xml has all the info on the optode layout, and it is needed to read in the data. You apparently have used a custom optodetemplates.xml during recording of the measurement. You to have the exact same optodetemplates.xml when reading the data into matlab also. So, you need to copy over the optodetemplates.xml from the measurement PC to your analysis PC. This is, unfortunately, not a bug, but a feature. (One that we will fix soon, so that all measurement meta data is finally kept within the oxy-file.)

**Comment by robertoostenveld** [comment]
but the `optodetemplates.xml` that we use (from the measurement PC) does not have the template ID 100 in it. Should it?

**Comment by robertoostenveld** [comment]
can you share an `optodetemplates.xml` that contains ID 100?

**Comment by helenacockx** [comment]
Hi Jörn, I am using the same optodetemplates.xml during measuring and during reading into matlab (with a custom optodetemplates.xml), so that is not really the problem. However, if I am reading in a file that was recorded on the device itself (offline), then it does not know which template it should use, so it would be great if I can provide the function with the optodetemplateID so it can look it up into the customized optodetemplates.xml

**Comment by helenacockx** [comment]
Yes, indeed! I solved this by "read in data with the readoxy3file.m and arrangeoxy3optodes.m from the oxysoft2matlab toolbox, where we manually adjust the metaInfo (with the correct OptodeTemplateID) and input it to the arrangeoxy3optodes.m."

see also: https://docs.google.com/document/d/1Jsxkf8c74taL1pfYe_QuwhViotgG7awIMUEEss5Evj8/edit#
