### ISSUE TITLE
Appreciable slowdown of code performance with both grad and elec field in datastructure

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1551]
I am wondering about the following thing:

Currently, it seems that potentially a lot of 'computation time' is spent doing low-level data-structure bookkeeping operations (ft_senstype related), when a MEG raw data structure contains both a grad and elec field. This is mostly due to the fact that the persistent variable trick in the lower-level utility functions does not work, because the slightly higher-level low level functions alternate between using grad and elec as input. 
If I encounter this slowdown (and get annoyed by it), I usually ditch the elec field, and then I am happy again.

Would it be worthwile to consider making it a standard feature of the code, to ditch elec/grad, conditional on the data.label?

**Comment by robertoostenveld** [comment]
so the idea would be (in pseudo code) like this

```
if ~any(ismember(data.grad.label, data.label))
  data = rmfield(data, 'grad')
end
```

and idem for elec (and opto)?

**Comment by schoffelen** [comment]
Yes indeed, and then not only in case

if isequal(user, 'jansch')

**Comment by robertoostenveld** [comment]
that could work. 

But in general, I am more worried about the increasing cost of checking everything all the time and everywhere. Could we come up with a strategy to prevent some checks from happening multiple times other than using a persistent variable?

**Comment by schoffelen** [comment]
Good point. I guess there's a trade off between administration time, and speed. Probably, at the moment, many people won't notice any slowdown, since my specific issue occurs when a high level function is repeatedly called (with the call to ft_checkdata/ft_selectdata each time). 
I guess it will be hard to come up with anything foolproof that can toggle on/off the checking, e.g. as per a set of (hidden) skipcheck flags associated with a data structure, which switch on once a check has been performed, and switch off again if the content of the previously checked field has changed. This would probably require a new object, i.e. a fieldtrip datastructure... forget it.

**Comment by robertoostenveld** [comment]
I was thinking in the direction of a global "hash"-table that keeps track of which objects have been checked and which not. A bit like the handling of previous warnings in `ft_warning` etc

**Comment by schoffelen** [comment]
That will be one flag per object, then?

**Comment by robertoostenveld** [comment]
yes. E.g. `ft_default.(hash).checked = true` where hash is some string that is constructed from the object.

**Comment by robertoostenveld** [comment]
it basically boils down to moving the information from a (single) persistent variable to a global variable (which can hold more info)

**Comment by schoffelen** [comment]
but what would happen if a user changes the object in the mean time?

**Comment by robertoostenveld** [comment]
that is why the hash (e.g. a MD5) of the object is used. When the object changes, the hash changes.

**Comment by schoffelen** [comment]
but is the hash (once computed) added to the data structure as well? Otherwise, I can imagine that the computation of the hash is time consuming, in which case it defies the purpose, provided it needs to be computed many times.

**Comment by robertoostenveld** [comment]
yes indeed, and yes I can also imagine that it won't work efficiently.

**Comment by robertoostenveld** [comment]
I also ran into this while running the nightly ft_qualitycheck. A lot of time was spent in ft_redefinetrial -> ft_datatype_sens -> ft_chantype.
