### ISSUE TITLE
Add .amplitude field to ft_spike_maketrials for segmentation into trials, and overwrite .samples field in new trial dimension

### ISSUE THREAD

**Issue by stephenwhitmarsh** [fieldtrip/fieldtrip#1554]
I'd like ft_spike_maketrials to also segment an additional amplitude field - when present - into trials.

Currently there are some try-catch statements that add a .waveform, .unit or .fourierspctrm field to the spike structure by ft_spike_maketrials. It would be easy to add an .amplitude field here.

Additionally, these trial-based fields currently overwrite existing 'raw' fields in the spike structure. However, .samples field stays in the original dimension, i.e. does not get segmented. 

The most consistent to me would be to create a trial-based .samples field, and overwrite the existing one. Then also segment into trials any other fields that have the same dimensions as the input raw structure. This would make the dimensions of the data consistent within a single data structure. 

Currently fields to be segmented are hard-coded. I am unsure / have no opinion about what would be a better. Hardcoded is easy (already done on my side). But I can make a PR of either.

**Comment by stephenwhitmarsh** [comment]
To clarify further - an unusual aspect of the current output is that the total number of indices in the trial segmented fields have a different number of elements than the remaining .samples field (i.e. when not all spikes are selected, or trials overlap), which then becomes orphaned, i.e. cannot be indexed in any meaning way anymore.

**Comment by robertoostenveld** [comment]
can you explain how `amplitude` relates to the existing fields as documented/defined in https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_datatype_spike.m

I think (recall) that the spike data structures predate the more explicit definition of the dimord. Although the dimord is in general not present explicitly, we have the function https://github.com/fieldtrip/fieldtrip/blob/master/private/getdimord.m. It would be good to have clear what the dimord is of each of the fields in the `spike` data structure.

**Comment by stephenwhitmarsh** [comment]
Amplitude would describe the amplitude of a spike, either real (in uV) or e.g. normalized to a template, and will have the same dimensions as e.g. the `time`, `trial `or `timestamp`. These would all have a `dimord `of "{chan}_spike". Of the remaining fields, we have `trialtime `and `sampleinfo`, both "rpt", and `waveform`, which is already described in ft_datatype_spike as "{chan}_lead_time_spike"

**Comment by robertoostenveld** [comment]
so it is a scalar (but not integer) field. In that sense it is similar to `spike.unit` and `spike.timestamp`, right? Those are used in https://github.com/fieldtrip/fieldtrip/blob/master/fileio/ft_read_spike.m.

**Comment by stephenwhitmarsh** [comment]
Indeed, a scalar. It _could_ be expressed as an integer in combination with a scaling factor - that is how it is stored on disk, but it is converted when reading data.

**Comment by robertoostenveld** [comment]
could you make a test_issue1554 script that demonstrates the desired use in high-level FT functions? Initially, it is fine to have the script fail; it still shows how it is meant to work. 

You could start the script by hand-crafting a spike structure, that might be easier than sharing a dataset in a file. See also the `*_spike_*` scripts in the fieldtrip/test directory.

**Comment by stephenwhitmarsh** [comment]
I'm on it, sorry for the delay

**Comment by stephenwhitmarsh** [comment]
bump - anything else I can do?

**Comment by robertoostenveld** [comment]
can you point me to the test_issue1554 script? If you want, you can just paste it here, or share it as a gist on https://gist.github.com

**Comment by stephenwhitmarsh** [comment]
Dear Robert,

Please find the PR for the test script here:
https://github.com/fieldtrip/fieldtrip/pull/1610

Cheers,
Stephen

Op vr 4 dec. 2020 om 12:57 schreef Robert Oostenveld <
notifications@github.com>:
