### ISSUE TITLE
Change of ft_transform_geometry breaks SPM code

### ISSUE THREAD

**Issue by vlitvak** [fieldtrip/fieldtrip#1555]
After the latest update ft_transform_geometry gives and error around line 65 related to the new check that the transform is uniform on all axes. This is not the case in some SPM applications where we transform the template head to individual head. I suppose FT users might also want to do something similar from time to time so I'm not sure this limitation is necessary (perhaps just change to a warning?).

**Comment by robertoostenveld** [comment]
what does `ft_datatype` on line https://github.com/fieldtrip/fieldtrip/blob/a2b192030722dc90cb1d73fb65f8273fe2e2ab85/utilities/ft_transform_geometry.m#L61 think that the object is?

should this be added to https://github.com/fieldtrip/fieldtrip/blob/master/test/test_spm_ft_integration.m and the corresponding mat file?

**Comment by vlitvak** [comment]
It's just an inner skull mesh. The code thinks it's 'source+mesh'
[ft_transform_geometry_error_l65.zip](https://github.com/fieldtrip/fieldtrip/files/5327343/ft_transform_geometry_error_l65.zip)

**Comment by schoffelen** [comment]
Sorry to pick this up only now. It seems indeed that the with a more explicit checking of what is and is not allowed, the error has surfaced. (i.e. initially the error checking was somewhat sloppy, so your user scenario pulled through).

We'll look into this. Things to do:
- revamp the help section, being explicit about what is allowed and what not
- update the code.

stay tuned!

**Comment by schoffelen** [comment]
The original PR #1609 was messed up, I recreated a PR that contains the relevant changes to the code
