### ISSUE TITLE
Issues with Biopack .acq files, possibly new file format

### ISSUE THREAD

**Issue by mcvinding** [fieldtrip/fieldtrip#1557]
We have encountered issued with reading data stored in Biopack's .acq file format into FieldTrip. It seems that Biopack has updated how the data is saved in the files and the new file format is no longer compatible with the way FieldTripe read the data. FieldTrip can read the data, but the channel names and `chantyp` is wrong, and it cannot detect triggers in the trigger channel.

I have looked into the issue and it seems that the error might be because the first data channel in the raw files has a negative index. I am however not familiar enough with Biopack's file format, so now I am opening it as an issue instead.

FieldTrip uses an external file `read_acq `from Mathworks Fileexchange to read .acq files (https://se.mathworks.com/matlabcentral/fileexchange/14562-load-biopac-acq-acqknowledge-for-pc-data). Several have reported a similar issue there, but the suggestions also seems to be implemented in the version of `read_acq` that FieldTrip uses. The last edit was also in 2018, so I suspect my current issue is a new one.

I found this toolbox that can convert the raw acq files to Matlab but is written in Python. It is possible to get the data into FieldTrip using that tool and then manually arranging the data as a FieldTrip structure.

**Comment by robertoostenveld** [comment]
Looking at https://www.biopac.com/product/api-biopac-file-formats/ it seems there are indeed different sub-formats to the `.acq` files, since their own API (win32 dll) is also limited in what it can read. Being able to better detect which sub-format a file is would be a good first step.

**Comment by robertoostenveld** [comment]
At the DCCN we don't use Biopac systems, so expertise from somewhere else is needed to address this.

**Comment by schoffelen** [comment]
Hey Mikkel, how is this coming along? Have you found some partners in crime to push this forward?

**Comment by mcvinding** [comment]
Hello. We have not gone further with a low-level solution to this issue. We needed the project to move forward, so the solution for our dataset was to import and export with Biopacks own software and then import with ft_preprocessing. @m-topor has been responsible for implementing the data processing pipeline.

**Comment by schoffelen** [comment]
OK, may I then suggest to close this for now? Feel free to re-open if something needs/can be done on the FieldTrip end.
