### ISSUE TITLE
improve representation/documentation of channel-specific artifacts

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1564]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: It would be more efficient if [...], or I would like to do [...] to analyze my data.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. How can you contribute to the implementation of your preferred solution?

**Describe alternatives you've considered**

**Additional context**

**Comment by robertoostenveld** [comment]
bummer! I used the back button in the browser and lost my description.

**Comment by robertoostenveld** [comment]
Let me start again... We have good support for dealing with bad segments, and with bad channels, but not so much for short-lived artifacts that are confined to a single channel. 

For artifacts we use a Nx2 matrix with begin- and end-sample, for trials we use a Nx3 matrix with also the offset.  For the `trl` array we also support additional columns with trigger codes, but as array they have to be numeric. To allow for string-valued trial info, we also allow `trl` to be a MATLAB table where the 4th and subsequent columns can be non-numeric. 

I am proposing to extend the Nx2 artifact description so that it cal also be a table. One of the additional columns can then code for the channel in which the artifact was detected. 

This could already be used in `ft_artifact_clip`, `ft_artifact_threshold`, `ft_artifact_jump`. Furthermore, I am thinking of implementing an `ft_artifact_nbcorr` to replace the existing `ft_nirs_scalpcouplingindex`. The SCI method is based on correlations between NIRS channels at different wavelengths, but `nbcorr` can also be used for other types of data (like MEG).

The downstream consequence is that functions that can work with the Nx2 `artifact` array need to be updated to deal with it optionally being a table. Specifically, `ft_rejectartifact` with method=nan should be updated to only insert nans in the affected channels rather than in all channels.

**Comment by schoffelen** [comment]
I'd say: go for it :)!

I guess that in case the artifact is Nx2-matrix, or when it's a 2 column table, it's assumed that all channels are affected?

Also, w.r.t. nbcorr functionality, we have an ft_denoise_sns, that does 'sensor-level noise suppression', based on a neighbour correlation heuristic. Perhaps it can be looked into in order not to duplicate code.

**Comment by robertoostenveld** [comment]
... imagine `ft_artifact_clip` on a bunch of TTL channels (like Neuromag STI00x)  instead of `ft_definetrial`, and then subsequently using the artifact definition in `ft_preprocessing`. Alternatively `ft_artifact_threshold` should also do that trick.

**Comment by robertoostenveld** [comment]
ft_artifact_zvalue has this

% If you specify cfg.artfctdef.zvalue.artfctpeak='yes', the maximum value of the
% artifact within its range will be found and saved into cfg.artfctdef.zvalue.peaks.

Following discussion with @schoffelen, this is better saved in an additional column in the artifact table, rather than somewhere hidden in the output cfg.
