### ISSUE TITLE
cfg.normalize in ft_regressconfound

### ISSUE THREAD

**Issue by ruiliu-psy** [fieldtrip/fieldtrip#1578]
I'm writing to report a discrepancy between the description and exact algorithm in ft_regressconfound.m.

The instruction of the function and script comment in line 127 indicated specifying the configuration cfg.normalize = 'yes' (by default) for "normalization to make the confounds orthogonal". The actual algorithm (line 127~142) indeed normalizes the regressors by taking the z-scores of each (scaling the vectors), but doesn't do anything for orthogonalization (not rotating the vectors). In case a prove is required, it can be tested by taking dot products of the 'normalized' repressors, and to see if the results are (super closed to) zeros.

I have collinear regressors, so would like to orthogonalize them. As the order of iteration matters, I decide it based on the correlation among the regerssors, from high to low. Of course, this can be achieved within the analysis pipeline without touching the original ft function. I just found the discerption of the function is a bit confusing.

**Comment by schoffelen** [comment]
I agree that the documentation in the function is incorrect. Could you fix this in the documentation, and make a PR?
