### ISSUE TITLE
Remove default invalid fields in cfg.channels for data2bids function

### ISSUE THREAD

**Issue by DidiLamers** [fieldtrip/fieldtrip#1580]
**Describe the bug**

cfg.channels = struct2table(cfg.channels) does not work, since fields in cfg.channels that are left empty by the user, are added anyway. This creates fields containing one scalar, and they cannot be transformed into a table with the other fields of cfg.channels since they of a different size (row vector with a length of channel number).  

**Solution**
In data2bids at line 1245: 
```
  if isstruct(cfg.channels)
    fn = fieldnames(cfg.channels);
    for i=1:numel(fn)
        if isequaln(cfg.channels.(fn{i}), nan)
            % this was set as default, it is not informative
            cfg.channels = rmfield(cfg.channels, fn{i});
        end
    end
    try
      cfg.channels = struct2table(cfg.channels);
    catch
      ft_error('incorrect specification of cfg.channels');
    end
  end
```

**Comment by robertoostenveld** [comment]
I added your suggestion to the code of https://github.com/fieldtrip/fieldtrip/blob/master/data2bids.m

It is now still in the master branch. After testing it will become part of the release, which is also available as zip files hete on github and on the FTP server. However, I recommend that while developing your analysis scripts, in general you work with the latest master, and once you are ready to run your scripts for "production" (i.e. once again on all the data, ensuring that everything is cnosistent and reproducible) that you switch to an explicit release and at that moment document the FieldTirp release version  that you used.
