### ISSUE TITLE
Potential issue with exporting BIDS data

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1584]
In this repository

https://openneuro.org/datasets/ds001810/versions/1.1.0

The vhdr file mentions that the files were exported with Fieldtrip. The vhdr also contains the wrong name for the marker file and binary file. See for example

sub-01/ses-01/eeg/sub-01_ses-anodalpost_eeg_sub-01_ses-anodalpost_task-attentionalblink_eeg.vhdr

**Comment by robertoostenveld** [comment]
That the file mentions it was exported with FieldTrip is not a problem, right? 
You might also see in files like this that they have been written by BrainVision Recorder (the acquisition software) or BrainVision Analyzer (if some processing had been done on them).

**Comment by robertoostenveld** [comment]
I downloaded the data from one subject and one session using Cyberduck using these settings

<img width="522" alt="image" src="https://user-images.githubusercontent.com/899043/98249281-5ce44d80-1f76-11eb-80d0-a9286ba231b7.png">

and looked ad `sub-01_ses-anodalpost_task-attentionalblink_eeg.vmrk`

It starts with 

```
Brain Vision Data Exchange Header File Version 1.0
; Data created by FieldTrip

[Common Infos]
DataFile=sub-01_ses-anodalpost_task-attentionalblink_eeg.eeg
MarkerFile=sub-01_ses-anodalpost_task-attentionalblink_eeg.vmrk
DataFormat=BINARY
DataOrientation=MULTIPLEXED
NumberOfChannels=73
SamplingInterval=1.953125e+03

[Binary Infos]
BinaryFormat=IEEE_FLOAT_32

[Channel Infos]
Ch1=Fp1,,1
Ch2=AF7,,1
Ch3=AF3,,1
...
```

I do not see anything wrong with this. 

However, when I download the vhdr file by clicking in the web browser (on macOS, using both Chrome and Safari), I get a local file with the name `sub-01-ses-anodalpost-eeg-sub-01_ses-anodalpost_task-attentionalblink_eeg.vhdr`. That is clearly incorrect. I suggest you report the issue on https://github.com/OpenNeuroOrg/openneuro

**Comment by arnodelorme** [comment]
Good point. I downloaded with the AWS OpenNeuro command line tool and got this problem.
Not sure why it is different with Cyberduck. I will report to OpenNeuro
