### ISSUE TITLE
FIF file import issue from BIDS dataset

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1585]
Import works with FileIO from Jan 30, 2020 but failed with FileIO from Nov 3rd, 2020. Note that it might be because the more recent version finds the matching sidecar files while the old version ignores them.

The file in question is the first FIF file of the Henson Wakeman release on OpenNeuro

sub-01_ses-meg_task-facerecognition_run-01_meg.fif

https://openneuro.org/datasets/ds000117/versions/1.0.3

found matching BIDS sidecar '/expanse/projects/nemar/openneuro/ds000117/task-facerecognition_meg.json'
found matching BIDS sidecar '/expanse/projects/nemar/openneuro/ds000117/task-facerecognition_channels.tsv'
	Read a total of 8 projection items:
		mag_ssp_upright.fif : PCA-mags-v1 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v2 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v3 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v4 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v5 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v1 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v2 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v3 (1 x 306) idle
	306 MEG channel locations transformed
Reading sub-01_ses-meg_task-facerecognition_run-01_meg.fif ...
	Read a total of 8 projection items:
		mag_ssp_upright.fif : PCA-mags-v1 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v2 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v3 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v4 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v5 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v1 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v2 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v3 (1 x 306) idle
Opening raw data file sub-01_ses-meg_task-facerecognition_run-01_meg.fif...
	Read a total of 8 projection items:
		mag_ssp_upright.fif : PCA-mags-v1 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v2 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v3 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v4 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v5 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v1 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v2 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v3 (1 x 306) idle
	Range : 248600 ... 788699  =    226.000 ...   716.999 secs
Ready.
Warning: assuming that the default scaling should be amplitude/distance rather than amplitude 

Reading data ...
Forcing EEG channel units to 'uV' ...... 
Reading 248600 ... 788699  =    226.000 ...   716.999 secs... [done]
Error using ft_notification (line 350)
the number of channel units is inconsistent with the number of channels

Error in ft_error (line 39)
  ft_notification(varargin{:});

Error in ft_read_data (line 1656)
    ft_error('the number of channel units is inconsistent with the number of channels');

**Comment by schoffelen** [comment]
OK, I can more or less confirm that (with the current code version) something is amiss.

doing something like:
cfg = [];
cfg.dataset = 'sub-01_.....fif'
cfg.trl = [1000 10000 0];
data = ft_preprocessing(cfg)

leads to an error in ft_read_data, which is the result (I think) of a mismatch between hdr.label (404 entries), and hdr.nChans = 395

**Comment by schoffelen** [comment]
It goes wrong in ft_read_header, around line 2820: hdr.label is overwritten with the information from the channel_tsv, as is chantype and chanunit. Yet, nChans is not updated.

**Comment by schoffelen** [comment]
updating the nChans is not going to work (I checked) because the fif-readers complain that there are only 395 channels in the data.

**Comment by schoffelen** [comment]
In other words: 'overruling' the information returned by the header-reader with the info in the channels.tsv does not guarantee success in this case. Pinging @robertoostenveld

**Comment by robertoostenveld** [comment]
Am I correct to summarize this as: the fif file specifies a different number of channels than the number of rows in channels.tsv? That is annoying. 

I feel tempted to say that this dataset does not comply with the BIDS standard, i.e. the dataset is corrupt (internally inconsistent). But one could also say that the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#channels-description-_channelstsv) its not explicit that the number of channels should match. 

See also https://github.com/mne-tools/mne-python/issues/8312#issuecomment-730210350 and the rest of that thread. 

Now imagine that the number does not match the binary header AND that the channel names do not match those of the binary header...

**Comment by schoffelen** [comment]
Well, I guess that a principled solution would be that - in case of a situation where bids_info is to be added - some checks are done w.r.t. the number of channels + their labels, and an informative error is thrown.

**Comment by robertoostenveld** [comment]
that is also what I tend to. Rather than an error we could also do a warning if it fails and fall back to the binary header details. But that more or less means that the option

```
%   'readbids'       = boolean, whether to read information from the BIDS sidecar files (default = true)
```

would be extended to 'yes', 'no', 'ifpossible' and that `ifpossible` would have to be the default. I rather not make these types of heuristics in the code, since it is hard to maintain. In the specific case reported in this issue, @arnodelorme could  already proceed with readbids=no, and could even make that the default in the file plugin. So the work-around is already implemented. 

More informative error messages and better checks on known exceptions in the code are always good.

**Comment by schoffelen** [comment]
or should it be called 'ifmakessense'?

**Comment by robertoostenveld** [comment]
hmm, yes. That is something we already have elsewhere. Let me have a look at the code and see whether `ifmakessense` makes sense as the default.

**Comment by robertoostenveld** [comment]
the "smart" stuff now happens on line https://github.com/fieldtrip/fieldtrip/blob/e538d1e70987a466c2bee97db1e47082bdcf90b5/fileio/ft_read_header.m#L2833

and by default it should now not give an error but a warning for this dataset.
