### ISSUE TITLE
FIF file empty room import issue

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1590]
Using ds000117 on OpenNeuro

Opening raw data file /expanse/projects/nemar/openneuro/ds000117/sub-emptyroom/ses-20090511/meg/sub-emptyroom_ses-20090511_task-noise_meg.fif...
	Read a total of 8 projection items:
		mag_ssp_upright.fif : PCA-mags-v1 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v2 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v3 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v4 (1 x 306) idle
		mag_ssp_upright.fif : PCA-mags-v5 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v1 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v2 (1 x 306) idle
		grad_ssp_upright.fif : PCA-grad-v3 (1 x 306) idle

--------
WARNING: This file contains raw Internal Active Shielding data. It may be distorted.
Elekta recommends it be run through MaxFilter to produce reliable results.
Consider closing the file and running MaxFilter on the data.
--------

	Range : 95000 ... 401999  =     95.000 ...   401.999 secs
Ready.
Error using error
The field "stack" must be an m-by-1 array.

Error in ft_notification (line 350)
          error(state);

Error in ft_error (line 39)
  ft_notification(varargin{:});

Error in ft_read_header (line 1926)
          ft_error('Maxshield data should be corrected using Maxfilter prior to importing in FieldTrip.');

**Comment by schoffelen** [comment]
Hi Arno,
Indeed I can confirm that - using default settings - the reading fails. This can be overcome by specifying cfg.checkmaxfilter = false; in the higher level call to ft_preprocessing, or to specify the key-value pair 'checkmaxfilter', false when using ft_read_data/ft_read_header directly.
