### ISSUE TITLE
Issues with estimated computing time for finding dipole positions in headmodel

### ISSUE THREAD

**Issue by kenzo0619** [fieldtrip/fieldtrip#1591]
**Issue with estimated computing time**
**Describe the bug:**
As you can see from row number 186 in the original code file:   _**fieldtrip/forward/ft_inside_headmodel.m**_ , the number of estimated seconds is calculated by **`round(numdip*t)`**. The variable **`numdip`** was defined at row 133:   **` numdip = size(dippos,1);`** . However, the size of the variable **`dippos`** has changed at row 178:    **`dippos = dippos(insidedip,:);`** for further computation with only inside dipoles but the printed estimated time still uses the size of the original **`dippos`** variable. This issue causes a different estimated running time for this process. 

**To Reproduce:**
1. Row number 133, 178, and 186.

**Expected behavior:**
The number of the total numbers of finding the nearest vertex for each of the dipoles should be updated before printing it.

**Environment and versions (please complete the following information):**
 - Operating System: linux
 - MATLAB version: R2017b
 - FieldTrip version: most recent master branch from github

**Comment by schoffelen** [comment]
Can you make a suggestion as to how the code needs to be changed, and file this as a PR, please?

**Comment by kenzo0619** [comment]
> Can you make a suggestion as to how the code needs to be changed, and file this as a PR, please?

After the content of  `dippos` at Row 178 has been changed, the variable `numdip` at Row 185 should be updated as well, otherwise, the printed string is a wrong estimated at Row 185. This can be fixed simply by assigning the new size value to the variable `numdip` before it being printed out. Thanks


https://github.com/fieldtrip/fieldtrip/blob/ea6897bb7d1079f8ed685efa8074ca3fb30508b6/forward/ft_inside_headmodel.m#L178-L185

**Comment by schoffelen** [comment]
In my previous comment I asked for a PR.
 
Right now you provide textual feedback with what needs to be changed (for the second time), which is double work: you spend time on writing what needs to be changed, and somebody else needs to spend time in making the actual change.

For now, I have made the code change for you, next time please file  a PR.
