### ISSUE TITLE
Suggestion regarding to slow performance in finding the nearest vertex position

### ISSUE THREAD

**Issue by kenzo0619** [fieldtrip/fieldtrip#1592]
**Is your feature request related to a problem? Please describe.**
My suggestion is related to the script **_fieldtrip/forward/ft_inside_headmodel.m_** from number **180-186** . In the recent version of Fieldtrip(including the latest), the method for finding the nearest vertex for each of the dipoles is MATLAB function **`dsearchn`**. As I'm now working with FEM headmodel and high-density EEG data(256 channels, downsampled to 128Hz, 1 min recording, 1 trial only, the performance is rather slow (approximately a few hours with my data), I found the other searching function **`knnsearch`** in MATLAB, which gives the same result verified by **`isequal`** function but done the job in 4 seconds. 

**Describe the solution you'd like**
I hope you can test and verify the function **`knnsearch`**, if it's all good, the function **`dsearchn`** can be replaced then.

**Additional context**
Please use a large dataset when comparing the performance between **`knnsearch`** and **`dsearchn`**. Thank you.

**Environment and versions (please complete the following information):**
Operating System: linux
MATLAB version: R2017b
FieldTrip version: most recent master branch from github

**Comment by schoffelen** [comment]
The 'problem' with knnsearch would be that it is part of the 'stats'-toolbox, which not all users may have a license for. Ideally, we'd work without legacy toolbox functions as much as possible, so we'd need a strategy to fallback to the slower version. Or write a fast implementation of dsearchn

**Comment by robertoostenveld** [comment]
@mcpiastra this relates to https://github.com/fieldtrip/fieldtrip/blob/34332821c9e8d9d6bf02103d34071d2784e909b3/forward/ft_inside_headmodel.m#L181 which is a piece of code that you contributed. Do you have an idea about this?

**Comment by schoffelen** [comment]
I have looked a bit more into this, and can confirm the slow behavior. I wrote a test function: test_pull1604, which is in #1604 
I could not confirm that it took a few hours, but using a segmented mri (3 tissue types, 1 mm) and a sourcemodel with ~5800 dipole positions, the use of dsearchn takes 10-15 minutes on my end, while knnsearch takes indeed only a few seconds. I wrote a drop in replacement for dsearchn (which is a subfunction in ft_inside_headmodel) which takes about 50 seconds for the sketched test. This is to service the users that don't have the stats toolbox. Note that in my proposed changes knnsearch will be used, if available. I checked that the output of my_dsearchn is the same as dsearchn (using the anecdotal test). @mcpiastra could you confirm that this change is OK with you, in which case I will merge the PR

**Comment by mcpiastra** [comment]
I successfully run the test function @schoffelen wrote (test_pull1604). I had the following timings:
dsearchn took 317.82 seconds
native use of my_dsearchn took 61.95 seconds
my_dsearchn took 4.26 seconds
knnsearchn took 3.59 seconds
ft_inside_headmodel took 46.69 seconds
so a great speed-up!

**Comment by schoffelen** [comment]
OK, I'll merge. Thanks for testing. I am surprised that the ft_inside_headmodel still took so long, I'd expect it to take in the range of ~10 s, but perhaps some other parts of the code took more time for some reason

**Comment by schoffelen** [comment]
or did the code not end up in knnsearch, when running ft_inside_headmodel?

**Comment by mcpiastra** [comment]
in the subfunction my_dsearchn in ft_inside_headmodel there is no check for knnsearchn, these lines are possibly missing?
if flag && exist('knnsearch', 'file')
  % use much faster knnsearch if available on the path
  indx = knnsearch(pos1, pos2);
  return;
end
and flag should be an additional input..or I am missing something?

**Comment by schoffelen** [comment]
well, that's taken care of in line 257-259, flag will be set to true

**Comment by mcpiastra** [comment]
you are right, I was looking/using an older version of ft_inside_headmodel. now I get:
ft_inside_headmodel took 4.99 seconds
as you expected.

**Comment by schoffelen** [comment]
Nice. Thanks for checking. Merging time.
