### ISSUE TITLE
FIF file limits channel names to 15 Characters

### ISSUE THREAD

**Issue by bloyl** [fieldtrip/fieldtrip#1596]
FIF files currently limit channel names to 15 Characters which can restrict its use for some applications, particularly clinical eeg.

There is an MNE-python PR which solves this issue by shortening channel names and storing a renaming map so that during reading the shorten names are expanded to their original channel names.
See mne-tools/mne-python#8312 (comment) and mne-tools/mne-python#8348

We plan for a similar PR for MNE-matlab but before we move much farther we'd like to ensure that these files won't cause any issues with brainstorm or fieldtrip.

So I have 2 questions:

1) would the proposed change cause any fundamental problems for fif support within fieldtrip?
2) would a PR to MNE-matlab be sufficient to support these files in brainstorm or are changes also needed within fieldtrip code?

CC @larsoner @robertoostenveld

**Comment by robertoostenveld** [comment]
Hi Luke, 

When properly implemented in mne-matlab, I don't directly see how this would break anything on the FT side. Of course we would have to update the copy of MNE-matlab that we include in fieldtrip/external. Also, when people were to change MEG channel names, our template layouts would not match any more, as they have the default names.  But that would be their problem, and is easy to resolve.

The relevant code is here https://github.com/fieldtrip/fieldtrip/blob/34332821c9e8d9d6bf02103d34071d2784e909b3/fileio/ft_read_header.m#L1881

One think that might have to be looked at in the FIF format in detail is whether the channel names (for the sampled timeseries) and the names of the magnetometer/gradiometer sensor desciptions are stored separately. I am thinking of the code here https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/mne2grad.m which subsequently reads https://github.com/fieldtrip/fieldtrip/blob/master/external/mne/coil_def.dat. But I don't see a problem yet, just something to keep in mind when someone were to change the MEG channel names.

**Comment by bloyl** [comment]
Thanks Robert,

I don't see this being used for standard eeg/meg since for the most part those channel names already meet the 15 char limit. Similarly channel definitions and the `coil_def.dat` file are indexed by FIFF constants so should be fine.

I'll let you know once there is a PR available for MNE-matlab to test against.

Thanks,
Luke

**Comment by schoffelen** [comment]
Hi @bloyl I am going over issues which have been silent for a while. Is ther anything that needs to be done here, or can it be closed?

**Comment by bloyl** [comment]
I believe these changes have been made for a while now, without complaint.

I am fine with closing this ticket.
