### ISSUE TITLE
ft_appendsource: missing argument in the call of checkpos.m line 101

### ISSUE THREAD

**Issue by LucaLaFisca** [fieldtrip/fieldtrip#1605]
**Describe the bug**
checkpos.m function requires the argument "tol" to be passed as last argument. In the line 101 of ft_appendsource.m, this argument is missing. Could you add it?

**To Reproduce**
cfg = [];
cfg.parameter = 'mom';
combined_source = ft_appendsource(cfg,source1,source2);

**Comment by schoffelen** [comment]
Hi Luca,

I assume that you get an error? If so, could you paste some code and upload ideally some small snippet of data for easy reproduction?

**Comment by schoffelen** [comment]
PS I noticed that you have a repository in which you are working on interfacing fieldtrip with LIMO. I am pinging @robertoostenveld and @cpernet who might be interested in hearing about this.

**Comment by LucaLaFisca** [comment]
Hi Jan-Mathijs,

Here is the corresponding piece of code:
`conditions = unique(eeg.trialinfo.condition);
nb_conditions = nnz(conditions(~isnan(conditions)));
source_all_cond = cell(1,nb_conditions);

% select target ROIs
roi_mat = {[3,5];[4,6];[7,9];[8,10];[11,13,15];[12,14,16];61;62;63;64;65;66;67;68;31;32;[83,87];[84,88];85;86};
[roi_atlas] = select_roi(sourcemodel_atlas,roi_mat);

for i = 1:nb_conditions
    cfg = [];
    cfg.trials = find(eeg.trialinfo.condition == i)';
    eeg_single_cond = ft_preprocessing(cfg,eeg);
    
    cfg                     = [];
    cfg.method              = 'mne';                    %specify minimum norm estimate as method
    cfg.sourcemodel         = sourcemodel_and_leadfield;%the precomputed leadfield
    cfg.headmodel           = vol;                      %the head model
    cfg.elec                = eeg.elec;                 %the electrodes
    cfg.channel             = eeg.label;                %the targeted channels
    cfg.mne.prewhiten       = 'yes';                    %prewhiten data
    cfg.mne.lambda          = 0.01;                     %regularisation parameter
    cfg.rawtrial            = 'yes';                    %apply single trial reconstruction
    cfg.keeptrials          = 'yes';                    %keep trial information
    source_dipole = ft_sourceanalysis(cfg, eeg_single_cond);

    % Compute ROI-by-ROI source activity
    source_roi = dipole2roi(source_dipole,roi_atlas);
    source_all_cond{i} = source_roi;
end
    
% Gather source data for all conditions together
cfg = [];
cfg.parameter = 'mom';
source_roi = ft_appendsource(cfg,source_all_cond{:});`

The error:
    Output argument "boolval" (and maybe others) not assigned during call to "checkpos".

    Error in ft_appendsource (line 101)
          boolval1 = checkpos(varargin{:}, 'identical');

Note: "select_roi.m" and "dipole2roi" are personal functions, I attach them here.

I also attach some needed structures. Unfortunately, "vol" and "sourcemodel_and_leadfield" are too big to be attached, but you can reproduce the result with another head model I guess.

Anyway, thanks for the contact. I'm already in touch with them.

[Issue_needed_info.zip](https://github.com/fieldtrip/fieldtrip/files/5615628/Issue_needed_info.zip)

**Comment by CPernet** [comment]
YES we are, @robertoostenveld already had a chat with @LucaLaFisca trying to get the code generic enough and tidy - FYI the main bit for us is [limo_import_data](https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/LIMO_FT_integration/limo_batch_import_data.m) which deals for now with ERP and sources (well sources hopefully once this issue is resolved) -- if you want to have a quick look too that would be fab.

**Comment by LucaLaFisca** [comment]
[UPDATE]
I've just detected an error in the previous data.
Here are the right ones:
[Issue_needed_info.zip](https://github.com/fieldtrip/fieldtrip/files/5617200/Issue_needed_info.zip)

**Comment by schoffelen** [comment]
OK, I just fixed it, without trying to reproduce. It seems too obvious. Note @LucaLaFisca that the reported line number of the error (101) does not match the line number in the current version of the code (which is 100)

**Comment by LucaLaFisca** [comment]
Hi Jan-Mathijs,

Thank you for this rapid fix.

Regards,

*Luca La Fisca*
*PhD Student*
Service d'Information, Signal et Intelligence Artificielle

Boulevard Dolez, 31

7000 Mons

+32 (0)65/37.40.83

*Luca.LAFISCA@umons.ac.be <Luca.LAFISCA@umons.ac.be>*
