### ISSUE TITLE
Use of varargout in ft_warning

### ISSUE THREAD

**Issue by gllmflndn** [fieldtrip/fieldtrip#1607]
Shouldn't this line:
https://github.com/fieldtrip/fieldtrip/blob/f0ae33ee9edc1b863c4151338fdaecce0845c66a/utilities/ft_warning.m#L58
be using `[varargout{1:nargout}]` ?

**Comment by schoffelen** [comment]
Hi Guillaume, could be. 
Do you get an error otherwise?

**Comment by gllmflndn** [comment]
Hi Jan-Mathijs, sorry for the short comment. It doesn't work with Octave:
````
error: invalid dimension inquiry of a non-existent value
error: called from
    ft_warning at line 58 column 16
````
and I am actually surprised this syntax works with MATLAB.

**Comment by robertoostenveld** [comment]
I would not mind changing it, but then we should also do it elsewhere (i.e. search for it in the code) and document the principle. The documentation could go here https://www.fieldtriptoolbox.org/development/guideline/code/#ensure-that-it-runs-on-older-matlab-versions and we might want to make an octave section to collect the compatibility considerations.

**Comment by robertoostenveld** [comment]
this should also work, right?

```
[varargout{:}]
```

**Comment by schoffelen** [comment]
Hi, in order to clean up a bunch of longstanding open issues, I took the challenge and installed octave on my laptop. I can confirm that Guillaume's @gllmflndn works, but not Robert's @robertoostenveld solution, i.e. Octave needs [varargout{1:nargout}]

**Comment by schoffelen** [comment]
I am not sure whether there are any costs in changing this throughout the code base, w.r.t. to the plain matlab users. I think it can be changed transparently, with the benefit of improving octave support. @robertoostenveld what do you think?

**Comment by gllmflndn** [comment]
I think this is the appropriate syntax for both Matlab and Octave, as the size of the output variable has to be defined. See this syntax being used in [Matlab documentation](https://www.mathworks.com/help/matlab/ref/varargout.html#d123e1463970).
