### ISSUE TITLE
visualisation problem with ft_rejectvisual

### ISSUE THREAD

**Issue by elshafeh** [fieldtrip/fieldtrip#1615]
I tried using ft_rejectvisual on CTF275 data with the following parameters:

cfg.method                          = 'trial';
cfg.preproc.demean           = 'yes';
cfg.megscale                       = 1;

The function plots the first trial i.e. I can see the signal on each channel , but when I scroll through the next trial there is nothing. This problem also persisted when I toggle **cfg.preproc.demean** , **cfg.megscale** and **cfg.ylim** .. I used the most recent version github branch of fieldtrip on both MacOS bigSur (matlab 2018b) and Windows 10 (matlab 2019b).

I'm attaching some screenshots for this bug :) 

<img width="1399" alt="Screenshot 2020-12-09 at 10 40 31" src="https://user-images.githubusercontent.com/15911215/101612668-31d49a00-3a0b-11eb-9c53-a9636a23fece.png">
<img width="1408" alt="Screenshot 2020-12-09 at 10 40 16" src="https://user-images.githubusercontent.com/15911215/101612675-339e5d80-3a0b-11eb-9421-cb1f6c6441cf.png">
<img width="1366" alt="Screenshot 2020-12-09 at 10 40 05" src="https://user-images.githubusercontent.com/15911215/101612678-3436f400-3a0b-11eb-80ed-828f2e6652b8.png">

**Comment by schoffelen** [comment]
Hi Hesham,
I can confirm your issue. Something seems to be wrong with the scaling of the signals upon plotting new trials. Have you gotten any further solving this?

**Comment by benjybarnett** [comment]
Hey I'm having the exactly the same issue. I just downloaded the most recent fieldtrip-master from github and the same issue is happening, even with your #1645 fix. 

The only way I can seem to fix it is through specifying cfg.ylim = [-1 1]. But, obviously, this messes up the scaling so is useless. Using cfg.ylim = [-1 1e-12] works too, but cfg.ylim = [-1e-12 1e-12] does not. I have no idea why!

Here's my configuration:

```
cfg          = [];
%cfg.ylim = [ -1   1 ]; %adding in this line fixes error but messes up scaling

cfg.method   = 'trial';
cfg.channel  = 'MEGGRAD';
cfg.keepchannel = 'yes';

clean_data        = ft_rejectvisual(cfg,data);
```
