### ISSUE TITLE
[reproducescript] manual data manipulation does not print "new input variable has entered the pipeline"

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/fieldtrip#1617]
**Describe the bug**
When using reproducescript and manually manipulating the data in the original script (e.g. changing units by multiplying the data with a conversion factor), does not print the "new input variable has entered the pipeline.." text in the reproduced script. E.g. example 1 on https://github.com/matsvanes/reproducescript
Note that when running example 2, this line does appear in the reproduced script of the group analysis (in which the individual subject data are entering the pipeline).

**Environment and versions (please complete the following information):**
 - Operating System: MacOS 10.15.7
 - MATLAB version 2020b
 - FieldTrip version b626fbc5f

**Comment by matsvanes** [comment]
It seems I cannot assign issues. But @Spaak will look at this.

**Comment by Spaak** [comment]
Can confirm on DCCN cluster, Matlab R2017b.

**Comment by Spaak** [comment]
> Note that when running example 2, this line does appear in the reproduced script of the group analysis (in which the individual subject data are entering the pipeline).

See my PR #1623: because in your example 2 you did not pass a trailing slash to `cfg.reproducescript`, there the functionality still worked.

**Comment by matsvanes** [comment]
@Spaak This fix introduces a new issue: two identical files are treated as being different (they appear as different files in the reproduced script, with "% a new input variable is entering the pipeline here:" being inserted as well). 

```
% enable reproducescript
ft_default.reproducescript = 'reproduce/';

data_dir = '../rawdata/';
results_dir = 'analysis/';

% extract epochs
cfg = [];
cfg.dataset = fullfile(data_dir, 'Subject01.ds');
cfg.trialfun = 'ft_trialfun_general';
cfg.trialdef.eventtype = 'backpanel trigger';
cfg.trialdef.eventvalue = 3;
cfg.trialdef.prestim = 1;
cfg.trialdef.poststim = 2;
cfg = ft_definetrial(cfg);

% loading data and basic preprocessing
cfg.channel = {'MEG' 'EOG'};
cfg.continuous = 'yes';
dataFIC = ft_preprocessing(cfg);

% time-lock analysis
cfg = [];
avgFIC = ft_timelockanalysis(cfg, dataFIC);
```

This results in the following (from ft_preprocessing onwards):

```
cfg.outputfile = { 'reproduce/20210106T122014_ft_preprocessing_output_data.mat' };
cfg.channel = { 'MEG', 'EOG' };
cfg.continuous = 'yes';
ft_preprocessing(cfg);

%%

% a new input variable is entering the pipeline here: 20210106T122016_ft_timelockanalysis_input_data.mat

cfg = [];
cfg.tracktimeinfo = 'yes';
cfg.trackmeminfo = 'yes';
cfg.inputfile = { 'reproduce/20210106T122016_ft_timelockanalysis_input_data.mat' };
cfg.outputfile = { 'reproduce/20210106T122020_ft_timelockanalysis_output_timelock.mat' };
ft_timelockanalysis(cfg);
```

where the output file from ft_preprocessing, and the inputfile from ft_timelockanalysis are identical (asserted with matlab isequal).

**Comment by Spaak** [comment]
Hmm I think this is a separate issue. The flagging of "a new input variable..." is done by string comparisons between the already-generated script and the cfg of the to-be-written step. In this case, the `cfg.inputfile` of `ft_timelockanalysis` should have been set to `reproduce/20210106T122014_ft_preprocessing_output_data.mat`, but it incorrectly is not (and hence the flagging code correctly detects it as new).

This is probably due to some (related or not?) bug in `make_or_fetch_inputfile`. I'll have a look.

**Comment by Spaak** [comment]
@matsvanes I cannot reproduce this. Executing your example code:

```matlab
global ft_default

% enable reproducescript
ft_default.reproducescript = 'reproduce/';

data_dir = '/home/common/matlab/fieldtrip/data/';
results_dir = 'analysis/';

% extract epochs
cfg = [];
cfg.dataset = fullfile(data_dir, 'Subject01.ds');
cfg.trialfun = 'ft_trialfun_general';
cfg.trialdef.eventtype = 'backpanel trigger';
cfg.trialdef.eventvalue = 3;
cfg.trialdef.prestim = 1;
cfg.trialdef.poststim = 2;
cfg = ft_definetrial(cfg);

% loading data and basic preprocessing
cfg.channel = {'MEG' 'EOG'};
cfg.continuous = 'yes';
dataFIC = ft_preprocessing(cfg);

% time-lock analysis
cfg = [];
avgFIC = ft_timelockanalysis(cfg, dataFIC);
```

correctly results in the following `script.m` (same snippet as you posted):

```matlab
...
cfg.outputfile = { 'reproduce/20210111T145115_ft_preprocessing_output_data.mat' };
cfg.channel = { 'MEG', 'EOG' };
cfg.continuous = 'yes';
ft_preprocessing(cfg);

%%

cfg = [];
cfg.tracktimeinfo = 'yes';
cfg.trackmeminfo = 'yes';
cfg.inputfile = { 'reproduce/20210111T145115_ft_preprocessing_output_data.mat' };
cfg.outputfile = { 'reproduce/20210111T145122_ft_timelockanalysis_output_timelock.mat' };
ft_timelockanalysis(cfg);
```

This is on Matlab R2017b on Linux 64 bit, DCCN cluster. Can you try again to see whether you're sure the issue persists? If so, maybe it's due to some hashing differences between different Matlab versions? Let me know.

**Comment by matsvanes** [comment]
@Spaak I verified this on the DCCN cluster myself, and I get the same (correct) results as you for both matlab versions 2017b and 2020b, using the latest FT. Oddly, I get the incorrect behavior on my local machine using matlab 2020b and the latest FT. Will try to find the root of this.

**Comment by Spaak** [comment]
Thanks, let me know. The first place I'd look is the hashing in `ft_hash` used by `make_or_fetch_inputfile`--this, I think, depends on mex-files, which might behave differently across different platforms (and FT macOS mex files are notorious).

**Comment by matsvanes** [comment]
I found the culprit. I was using a faulty version of `CalcMD5`, which is used in `ft_hash`. This file was residing in fieldtrip/utilities/private, and probably wasn't deleted in a github pull. It returned NaNs for all input. I deleted this file from my local FT and now I get the results as expected 👍
