### ISSUE TITLE
ft_prepare_neighbours: variable 'sens' not set

### ISSUE THREAD

**Issue by typically** [fieldtrip/fieldtrip#1620]
**Describe the bug**
On line 231 of ft_prepare_neighbours:

`sens = ft_checkdata(sens, 'hasunit', 'yes');`

The variable `sens` may not have been set at this point. This produces an "undefined function or variable 'sens'" error.

**To Reproduce**
`cfg_nbr = [];`
 `cfg_nbr.method = 'distance';`
 `cfg_nbr.layout = 'biosemi64.lay';`
 `cfg_nbr.channel = ft.label;`
    
 `cfg.neighbours = ft_prepare_neighbours(cfg_nbr);`

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10
 - MATLAB version R2020b
 - FieldTrip version 20191206
 - Issue is not present in 20190419, and appears to have been introduced in [this commit](https://github.com/fieldtrip/fieldtrip/commit/40de8cd483a3cceef5a97399f5cedfd7c81c39c0#diff-06dba900db60aae8e2c4716f9465c980eb8998e59ccdb152f5633b46315dd3a8), corresponding to release 20190527.

**Comment by robertoostenveld** [comment]
I can confirm the error. The distance method is mainly useful for 3D positions, hence (I suspect) that this combination of input options was never tested. Accidentally, I was working with @DidiLamers on an 32-channel EEG layout and neighbour structure and already considered to make an example script for the website. I will combine that with fixing this issue.

**Comment by robertoostenveld** [comment]
Hi Andrew,

Could you check out the branch https://github.com/robertoostenveld/fieldtrip/tree/neighbours that I just made for pull request #1621  and test it? This is linked to the new page https://www.fieldtriptoolbox.org/example/neighbours/ that I just added to the website, which also explains some things better.

**Comment by typically** [comment]
Hi Robert,

It looks like this has resolved the issue, thanks!
