### ISSUE TITLE
estimating cross-channel cross-frequency coupling

### ISSUE THREAD

**Issue by tiborauer** [fieldtrip/fieldtrip#1627]
I understand that estimating cross-channel CPC has been removed with [this commit](https://github.com/fieldtrip/fieldtrip/commit/a33f57599fcfde15248609dc6925c676743596e8); however, I am not sure why. Would it be possible to re-implement, or is it about something more fundamental issue with cross-channel CPC? 

[PACTools for EEGLAB](https://github.com/sccn/PACTools) and [the Pythonic pactools](https://pactools.github.io/index.html), for example, have implemented similar approaches to estimate coupling, and both of them allow independent channel selection.

**Comment by schoffelen** [comment]
I don't think that the functionality has been removed, but the documentation has been updated to get the expectations right.
Feel free to improve the implementation to allow for cross channel stuff. Looking forward to a PR.

**Comment by tiborauer** [comment]
#1628
