### ISSUE TITLE
Mismatch in documentation and code in ft_preproc_dftfilter.m prevents spectrum interpolation

### ISSUE THREAD

**Issue by lussanet** [fieldtrip/fieldtrip#1634]
**Describe the bug**
According to the documentation of ft_preproc_dftfilter (line 51-55), the spectrum interpolation method (Leske & Dalal 2017) is run when the argument key-value pair: 'Flreplace', 'neighbour' is inserted. However  the  code (line  89-92) defaults  to:

% defaults
Flreplace  = ft_getopt(varargin,'dftreplace','zero');
Flwidth    = ft_getopt(varargin, 'dftbandwidth', [1 2 3]);
Neighwidth = ft_getopt(varargin, 'dftneighbourwidth', [2 2 2]);

so the  spectrum interpolation method will only be called with the key-value pair: 'dftreplace', 'neighbour'. Similarly, the  two other key-value pairs are defined wrongly. 

Bad programming of ft_getopt is part of the problem (see below)

% Additional input arguments come as key-value pairs:
%
%   Flreplace       'zero' or 'neighbour', method used to reduce line noise, 'zero' implies DFT filter, 'neighbour' implies spectrum interpolation
%   Flwidth         bandwidth of line noise frequencies, applies to spectrum interpolation, in Hz
%   Neighwidth      width of frequencies neighbouring line noise frequencies, applies to spectrum interpolation (Flreplace = 'neighbour'), in Hz

**To Reproduce**
Call the function with 

DataSI = ft_preproc_dftfilter(DataHum, Freq, [50 100 150], ...
            'Flreplace','neighbour', 'Flwidth',[1 1 1], 'Neighwidth',[2 2 2]);

and set a break point at line 111, demonstrates that strcmp(Flreplace,'zero') ==1  so spectrum  interpolation is not reached.

**Expected behavior**
strcmp(Flreplace,'zero') should be 'neighbour'

**Screenshots**

**Environment and versions (please complete the following information):**
 - Operating System: [e.g. Windows 10]
 - MATLAB version [e.g. R2019b, type `ver`]
 - FieldTrip version [e.g. 2020312, or "most recent master branch from github", type `ft_version`]

**Additional context**
The correction is straightforward, however the coding of 
function ft_getopt() 
is insecure, because the user will usually not notice that the desired setting is not implemented. It  would be desirable if ft_getopt checks the entry against valid entries and warns if the entry is not  member of the valid list.

**Comment by schoffelen** [comment]
![image](https://user-images.githubusercontent.com/1517611/104564184-e4230100-564a-11eb-82d2-ce6f2c5aa15f.jpeg)

**Comment by schoffelen** [comment]
please file a PR fixing it in ft_preproc_dftfilter

ft_getopt is a low level function that on purpose has no knowledge about allowed cfg.arguments, because these depend on the caller function. 

If anything ft_checkconfig should be used for this. See the documentation and the code of this function to see how it can be used to protect users against themselves. 

Feel free to go through the entire codebase and add to each of the main fieldtrip functions a code section that exhaustively goes through all permitted cfg arguments for the respective function.  At the moment we do not have the resources to do this.

**Comment by lussanet** [comment]
I commented on ft_getopt, because it is also attached into the file ft_preproc_dftfilter.m. Possibly a different  function should be called here. I only found out by coincidence that the function is not behaving as it should! This is  quite serious, because this issue has remained unnoticed  for several years  now, and I hardly think that I am the first one to use the spectrum interpolation method. So, probably lots of studies have now been performed who accidentally  and unknowingly used a wrong method!

Het gaat hier dus niet om goederen over de  schutting werpen!

**Comment by lussanet** [comment]
Thanks a lot for rapid reply

**Comment by robertoostenveld** [comment]
is there any high-level documentation on the fieldtrip website that could be improved to increase the chances that people perform the analysis by specifying the right cfg options to the high-level functions, and the right key-val pairs to the low-level functions?
