### ISSUE TITLE
reading BrainVision timestamps gives error

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1644]
**Describe the bug**

Reading BrainVision timestamps gives an error due to the changes introduced by @nbeliy in #1625

**To Reproduce**

This was detected in the `fieldtrip/test/test_bug2482.m` script, with the file `/home/common/matlab/fieldtrip/data/test/bug2482/001 P11 M1 004_Seg_fs6.vhdr`

**Expected behavior**

The existing test scripts should never start failing, since that would also mean that existing scripts on the computer of FT users might fail. 

**Screenshots**

```
Error using datetime.datetime (line 635)
Unable to convert '00000000000106774000' to datetime using the format 'yyyyMMddHHmmssSSSSSS'.
Error in ft_read_event (line 528)
Error in ft_trialfun_brainvision_segmented (line 48)
Error in ft_definetrial (line 181)
Error in test_bug2482 (line 17)
```

**Comment by nbeliy** [comment]
the timestamp in the log `00000000000106774000` looks weird (anonymised?)

BV gives it's timestamps [explicetly as](https://www.brainproducts.com/files/public/products/more/BrainVisionCoreDataFormat_1-0.pdf) 
```
Date Example19990311140312003012means 11 March 1999, 14:03:12.003012
```

**Comment by robertoostenveld** [comment]
yes, but the one you give is explicitly an example and might be the ideal case, whereas in reality they can be more variable. The file I have is one from an actual experiment and seems to be generated by BrainVision Analyzer. So files like these are out and about.

This is the start of the vhdr:
```
 Brain Vision Data Exchange Header File Version 2.0
; Data created from history path: 001 P11 M1 004/Raw Data/InitChans_electrodepos_256/new_positions/Filters_0.1-80Hz/without_channels_cheek/ICA/Inverse ICA/Raw Data Inspection/interpol_39,81,90132,144/new_Ref_linked_Mastoid/Filters_1-20Hz/Seg_fs6

[Common Infos]
Codepage=UTF-8
DataFile=001 P11 M1 004_Seg_fs6.eeg
MarkerFile=001 P11 M1 004_Seg_fs6.vmrk
DataFormat=BINARY
; Data orientation: VECTORIZED=ch1,pt1, ch1,pt2..., MULTIPLEXED=ch1,pt1, ch2,pt1 ...
DataOrientation=MULTIPLEXED
DataType=TIMEDOMAIN
NumberOfChannels=204
DataPoints=37050
; Sampling interval in microseconds if time domain (convert to Hertz:
; 1000000 / SamplingInterval) or in Hertz if frequency domain:
SamplingInterval=2000
SegmentationType=MARKERBASED
SegmentDataPoints=650

[User Infos]
; Each entry: Prop<Number>=<Type>,<Name>,<Value>,<Value2>,...,<ValueN>
; Property number must be unique. Types can be int, single, string, bool, byte, double, uint
; or arrays of those, indicated int-array etc
; Array types have more than one value, number of values determines size of array.
; Fields are delimited by commas, commas in strings are written \1

[Binary Infos]
BinaryFormat=IEEE_FLOAT_32

[Channel Infos]
; Each entry: Ch<Channel number>=<Name>,<Reference channel name>,
; <Resolution in "Unit">,<Unit>, Future extensions...
; Fields are delimited by commas, some fields might be omitted (empty).
; Commas in channel names are coded as "\1".
Ch1=E1,Mastoid_Ref,,µV
Ch2=E2,Mastoid_Ref,,µV
...
```

and this is in the vmrk
```
Brain Vision Data Exchange Marker File, Version 2.0
; Data created from history path: 001 P11 M1 004/Raw Data/InitChans_electrodepos_256/new_positions/Filters_0.1-80Hz/without_channels_cheek/ICA/Inverse ICA/Raw Data Inspection/interpol_39,81,90132,144/new_Ref_linked_Mastoid/Filters_1-20Hz/Seg_fs6
; The channel numbers are related to the channels in the exported file.

[Common Infos]
Codepage=UTF-8
DataFile=001 P11 M1 004_Seg_fs6.eeg

[Marker Infos]
; Each entry: Mk<Marker number>=<Type>,<Description>,<Position in data points>,
; <Size in data points>, <Channel number (0 = marker is related to all channels)>,
; <Date (YYYYMMDDhhmmssuuuuuu)>, Visible
; Fields are delimited by commas, some fields may be omitted (empty).
; Commas in type or description text are coded as "\1".
Mk1=New Segment,,1,1,0,00000000000106774000
Mk2=Time 0,,51,1,0
Mk3=Stimulus,DIN6,51,1,0
Mk4=Stimulus,DIN9,410,1,0
Mk5=New Segment,,651,1,0,00000000000109504000
Mk6=Time 0,,701,1,0
Mk7=Stimulus,DIN6,701,1,0
Mk8=Stimulus,DIN9,1055,1,0
Mk9=New Segment,,1301,1,0,00000000000207644000
Mk10=Time 0,,1351,1,0
Mk11=Stimulus,DIN6,1351,1,0
Mk12=Stimulus,DIN9,1678,1,0
Mk13=New Segment,,1951,1,0,00000000000217668000
Mk14=Time 0,,2001,1,0
Mk15=Stimulus,DIN6,2001,1,0
Mk16=Stimulus,DIN9,2367,1,0
Mk17=New Segment,,2601,1,0,00000000000226150000
Mk18=Time 0,,2651,1,0
Mk19=Stimulus,DIN6,2651,1,0
Mk20=Stimulus,DIN9,2979,1,0
Mk21=New Segment,,3251,1,0,00000000000246124000
Mk22=Time 0,,3301,1,0
Mk23=Stimulus,DIN6,3301,1,0
Mk24=Stimulus,DIN9,3801,1,0
Mk25=New Segment,,3901,1,0,00000000000330218000
Mk26=Stimulus,DIN6,3951,1,0
Mk27=Time 0,,3951,1,0
Mk28=Stimulus,DIN9,4296,1,0
Mk29=New Segment,,4551,1,0,00000000000335824000
Mk30=Time 0,,4601,1,0
Mk31=Stimulus,DIN6,4601,1,0
...
```

The provenance I have of this file (which btw is not my own) is that it mentions "bug 2482" which means that it relates somehow to http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2482. So the file is apparently from someone who attended a FT workshop in Zurich.

**Comment by robertoostenveld** [comment]
the current implementation should be made more robust, such that FT does not give errors on files that other researchers have.

**Comment by nbeliy** [comment]
I have little experience with Matlab and with BV, so I have little judgment of robustness.

In this particular case the problem comes from  `0000000000` in the beginning of timestamps (the day 00 have no sense). For me it is the problem of data file (it doesn't follow data format description), probably result of anonymisation, which replaces the true date with invalid one. It can be the that BV authorise it, but I don't see in the docs.

The most robust but slow way is to enclose datetime in try/catch statements.
Another solution is to check if string starts with `0000`, but it can fail if times are anonymised in different way.

**Comment by robertoostenveld** [comment]
I had a look at the MATLAB [datetime](https://nl.mathworks.com/help/matlab/ref/datetime.html) function, which I never  used myself before. It indeed makes some "sane" assumptions on the format, which are broken here. 

Since we don't know in which ways the datetime in the BV files can be "corrupt" (from the MATLAB perspective), I think safest is to do a try-catch and not try to implement heuristics for specific cases (like "starting with 0000").

I will add something to the code for this.

**Comment by robertoostenveld** [comment]
I added a try-catch and reorganized the code a bit. 

This night the whole batch of test script will again run, and check whether the function gives the expected output on the test datasets. If that passes, it will be included in the next release.

**Comment by nbeliy** [comment]
Sorry for re-opening issue,

There can be a lot of `New segment` markers, and in the current implementation it will create a warning at each occurrence.
It could be better to show the warning once, for ex.:

```
readTime = ft_platform_supports('datetime')

% in loop:
if numel(tok)>5 && readTime;
  try
            event(end).timestamp = datetime(tok{6}, 'InputFormat', 'yyyyMMddHHmmssSSSSSS');
  catch
            ft_warning('skipping invalid datetime in BrainVision marker file');
            readTime = false;
   end
```

**Comment by robertoostenveld** [comment]
sure, that would be a further improvement. Can you make it and send a PR?

**Comment by nbeliy** [comment]
For sure

**Comment by nbeliy** [comment]
Made request #1646
