### ISSUE TITLE
speed up ft_qualitycheck

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1650]
While implementing #1649 and checking with the MATLAB profiler, I noticed that reading and parsing a CTF header from the res4 file takes a lot of time. Inside `ft_qualitycheck` this is done repeatedly, since the data is read and analyzed in 10-second chunks.  So for a 1 hour recording (or 3600 seconds), the header is parsed 360 times. 

I think that could be made more efficient, thereby allowing https://github.com/Donders-Institute/meg_quality to run more efficiently.

**Comment by schoffelen** [comment]
This has been adressed by #1649, true?

**Comment by robertoostenveld** [comment]
Yes, correct. 

Additional speedups in the `ft_qualitycheck` function itself would be possible, but I don't consider them needed. They would only reduce the nightly quality check computation somewhat, but otherwise not have impact on other FT functions. So this can be closed.
