### ISSUE TITLE
converting ODs to concentrations won't work for ICA components

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1653]
https://github.com/fieldtrip/fieldtrip/blob/3ba8125c1e809a8a9e6ed4f6f286b8fb3357d28a/external/artinis/ft_nirs_transform_ODs.m#L11

If PCA or ICA component analysis has been done on data that represents ODs, the output will contain data that is mixed between opcodes and wavelengths. This cannot be simply converted to concentrations. I therefore believe that the support (both in the help and in the code) for component data should be removed.

**Comment by Horschig** [comment]
Good point.
