### ISSUE TITLE
[ENH]raw data and cfg.method='corr' with ft_connectivityanalysis

### ISSUE THREAD

**Issue by ruiliu-psy** [fieldtrip/fieldtrip#1656]
I'd like to report two issues with ft_connectivityanalysis in computing correlation among channels (no fancy stuff, just Pearson correlaiton).

1) ft_connectivityanalysis didn't compute covariance for raw data as documented in the help, hence turned error in later steps (line 600).
```
  cfg         = [];
  cfg.method  = 'corr';
  data_cor    = ft_connectivityanalysis(cfg, data_raw);
```
_Reference to non-existent field 'cov'.
Error in ft_connectivityanalysis (line 600)
    data.(inparam) = reshape(data.(inparam), [1 size(data.(inparam))]);_

2) I then tried time-locked data provided by the aftermentioned raw data and also chose the method 'corr' to compute Pearson correlation among channels. However, the output was still covariance instead of correlation coefficients.
 ```
% compute covariance
  cfg            = [];
  cfg.covariance = 'yes';
  data_tlk       = ft_timelockanalysis(cfg, data_raw);
% compute correlation
  cfg            = [];
  cfg.method     = 'corr';
  data_cor       = ft_connectivityanalysis(cfg, data_tlk);
```

For now, I just took the covariance matrix from the ft_timelockanalysis and hand-coded the correlation.

**Comment by robertoostenveld** [comment]
I had expected on basis of the help from ft_connectivityanalysis and from the comments around line 277 that it computes the covariance on the fly, since raw data is allowed as input. But apparently not. 

Could you look in a bit more detail in the code and come with a suggestion to fix it?

**Comment by schoffelen** [comment]
Naively, I would say that using ft_connectivityanalysis to compute a correlation coefficient is a total overkill. Yet, nobless oblige, and if the documentation of the function hints at the fact that it should be possible with 'raw' data, then the function should work.

**Comment by ruiliu-psy** [comment]
Yes, I checked the code and the function indeed does not compute covariance matrix for raw data. It's possible somehow the part of code got lost during the development. 
The output given the time-locked data was not correlation either, but covariance, which was computed with the lower-function ft_connectivity_corr (line 231). Maybe, you guys did it for more general purposes.
```
c = outsum./outcnt;
```

As for my solution, I computed it manually, fitted to my own purpose, but maybe not suitable for others. 
```
refchan = 'left_eye';

% compute covariance
cfg            = [];
cfg.covariance = 'yes';
data           = ft_timelockanalysis(cfg, data); 

% compute correlation manually
data_cor.dimord = 'chan';
data_cor.label = data.label;
covxy = data.cov(strcmp(data.label, refchan),:)';
stdx  = sqrt(diag(data.cov,0));
stdy  = sqrt(covxy(strcmp(data.label, refchan)));
data_cor.corr = covxy ./ (stdx * stdy);

% plot corr map
figure;
cfg            = [];
cfg.parameter  = 'corr';
cfg.layout     = 'CTF275.lay';
cfg.commentpos = 'middlebottom';
cfg.zlim       = [-1 1];
cfg.comment    = sprintf('\n\n\nleft eye\nr = [%.2f %.2f]', min(data_cor.corr), max(data_cor.corr));
subplot(1,3,1); ft_topoplotER(cfg, data_cor)
```

I'm not sure if it is a common practice to compute correlation with ft_connectivityanalysis. Perhaps not, seen JM's reply. Could you suggest a more elegant approach? I created three virtual channels approximate to the eyes (right, left and between) using lcmv beamformer. However, activities of the two eyes are correlated that may hamper the estimation of spatial filter, so I'm checking correlation between the virtual channels of the eyes and the raw sensor-level data to get an idea of the spatial distribution, like:
![eyecorr](https://user-images.githubusercontent.com/71086397/105840228-f6018e00-5fd2-11eb-8ed1-c40d2473d25c.PNG)

1) Do you think this is a effective check?
2) If not, what I should do to ensure that I get appropriate proxy of the eye movements (we didn't recruit the EOGs and eye-tracker, unfortunately)?
