### ISSUE TITLE
Unable to run any ft_ functions in real and sample data (from FieldTrip Tutorials) - error message on Mac 

### ISSUE THREAD

**Issue by KLanovyk** [fieldtrip/fieldtrip#1660]
Hi, I am having issues with running any analysis on my Mac (iOS 10.15.7) when using any ft_ functions. I have the latest version of FieldTrip and a new user. I am planning on working on preprocessed EEG data to run time-frequency analysis. I have managed to install the toolbox and run the toolbox in MATLAB fine. I have also managed to load my preprocessed data files in FieldTrip. 

When I was following the tutorials for Time-Frequency Analysis I (https://www.fieldtriptoolbox.org/tutorial/timefrequencyanalysis/#time-frequency-analysis-i), I used the provided sample data (datFIC) to load it into FieldTrip. Once loaded I tried to run the "Hanning taper, fixed window length" analysis using the script copied and pasted into the MATLAB's command window directly from the tutorial. I do not get any output and I get an error message:

"Invalid MEX-file '/Users/katerynalanovyk/Desktop/fieldtrip-20210122/utilities/ft_getopt.mexmaci64':
dlopen(/Users/katerynalanovyk/Desktop/fieldtrip-20210122/utilities/ft_getopt.mexmaci64, 6): no suitable
image found.  Did find:
	/Users/katerynalanovyk/Desktop/fieldtrip-20210122/utilities/ft_getopt.mexmaci64: code signature in
        (/Users/katerynalanovyk/Desktop/fieldtrip-20210122/utilities/ft_getopt.mexmaci64) not valid for use
        in process using Library Validation: library load disallowed by system policy

Error in removefields (line 36)
recursive = ft_getopt(varargin, 'recursive', false);

Error in ft_preamble_provenance (line 51)
cfg.callinfo.usercfg = removefields(cfg, ignorefields('provenance'));

Error in ft_preamble (line 83)
evalin('caller', full_cmd);

Error in ft_freqanalysis (line 196)
ft_preamble provenance data" 

Aswell as this error message in my command window in MATLAB, I also get a warning pop up on my screen.
 "ft_getopt.mexmaci64" cannot be opened because the developer cannot be vertified. macOS cannot verify that this app is free from malware. Firefox downloaded this file on 24 January 2021 from ftp.fieldtriptoolbox.org" and two options "Move to Bin" or "Cancel". 

Exact same message comes up when I was trying to visualise/display my real data using ft_databrowser function. 
This error also occured in earlier versions of FieldTrip (from 2020). 

Is anyone aware of this error and how to overcome it? Thank you. 
Kateryna.

**Comment by robertoostenveld** [comment]
Have you read the documentation on the website (searching on “mex”)?
https://www.fieldtriptoolbox.org/search_results/?q=mex

**Comment by KLanovyk** [comment]
Hi robertoostenveld, no I have not but I will check it out now! Thank you.

**Comment by robertoostenveld** [comment]
since there has not been further activity on this, I will close the issue.
