### ISSUE TITLE
ft_connectivity_wpli: missing abs() for numerator in formula

### ISSUE THREAD

**Issue by ojoenlanuca** [fieldtrip/fieldtrip#1661]
Just a little implementation error.
In Vinck et al. the wpli is defined as:
wpli = | E{ | Im(X) | * sgn(Im(X)) | / E{ | Im(X) | }

In your implementation the abs() for the numerator is missing, causing a wrong value range of [-1, 1] instead of [0, 1].

**Comment by dieloz** [comment]
My first hunch is that the absence of abs() is intended in order to provide directionality. Please correct me in case I´m wrong

**Comment by ojoenlanuca** [comment]
I have not enough theoretical background about providing directionality. I just look at the paper reference form Vinck et al. 2011, which defines the WPLI like above.

**Comment by schoffelen** [comment]
'your' implementation is the one supplied by Martin by the way. How would you suggest to proceed. Perhaps a github issue is not the right place.

**Comment by ojoenlanuca** [comment]
Because it is not a real bug, I think we can close the issue. I just wanted to make you aware of this difference and find out why it was implemented in this way.
