### ISSUE TITLE
ft_write_sens "bioimage_mgrid" bug

### ISSUE THREAD

**Issue by CarinaFo** [fieldtrip/fieldtrip#1662]
Hey FT community,

there is no determine_griddim function executing the following:
I just defined them on my own but I guess this is a bug:

ft_write_sens(filename, elec_xyz, 'format', 'bioimage_mgrid');
Unrecognized function or variable 'determine_griddim'.

Error in write_bioimage_mgrid (line 85)
  GridDim = determine_griddim(elec_g);

Error in ft_write_sens (line 55)
    write_bioimage_mgrid(filename, sens);

thanks for the great toolbox.

Carina

**Comment by StolkArjen** [comment]
Hi Carina,

You may want to have look at the relevant high-level functionality,
*fieldtrip2bis.m* (see doc
<https://www.fieldtriptoolbox.org/getting_started/bioimage/>). It does a
couple of things prior to calling to ft_write_sens to safeguard the
consistency of the data between fieldtrip and bioimagesuite. This should
also resolve that "bug", but let us know if not (*determine_griddim.m* is
located in the private directory, btw).

Best,
Arjen

**Comment by schoffelen** [comment]
what's the status of this?
