### ISSUE TITLE
ft_megplanar should transparently pass through non-MEG channels

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/fieldtrip#1671]
If we have an axial gradient MEG data structure with some added (e.g. reference or EMG) channel, `ft_megplanar` now throws away those channels in the output (i.e. it *only* returns the computed planar gradient channels). We could consider passing through any extra non-MEG channels unchanged.

If you agree, I could file a PR for this.

**Comment by robertoostenveld** [comment]
that surprises me, I thought that 

https://github.com/fieldtrip/fieldtrip/blob/565b9f12dfd465ff16b699238cda7f834ec9ccaf/ft_megplanar.m#L319

would keep all non-MEG channels.

**Comment by robertoostenveld** [comment]
when you are going to look at it in more detail, please also check `ft_megrealign.m`. Once upon a time these two functions were combined in a single function, so I expect them to behave (or misbehave) similarly.

**Comment by Spaak** [comment]
Minimal example showing this issue:

```
% loads a data struct that has an extra channel 'EMGlft'
load /home/common/matlab/fieldtrip/data/ftp/tutorial/connectivity/data.mat;

cfg = [];
cfg.method = 'template';
cfg.template = 'ctf151_neighb.mat';
neighb = ft_prepare_neighbours(cfg);

cfg = [];
cfg.method = 'sincos';
cfg.neighbours = neighb;
datplan = ft_megplanar(cfg, data);

disp(any(strcmp(data.label, 'EMGlft')));
disp(any(strcmp(datplan.label, 'EMGlft')));
```

shows:

```
>> disp(any(strcmp(data.label, 'EMGlft')));
   1

>> disp(any(strcmp(datplan.label, 'EMGlft')));
   0
```
