### ISSUE TITLE
ft_checkdata (sometimes) does not correctly recognize planar gradient data, while ft_senstype does

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/fieldtrip#1673]
I have the following data structure (see [corrdat.zip](https://github.com/fieldtrip/fieldtrip/files/6011081/corrdat.zip)):
```
>> corrdat

corrdat = 

  struct with fields:

     label: {538x1 cell}
      time: [0 1]
       avg: [538x2 double]
    dimord: 'chan_time'
```

which results in an error from `ft_checkdata` (ran into it while calling `ft_combineplanar`):

```
>> ft_checkdata(corrdat, 'datatype', {'raw', 'freq', 'timelock'}, 'feedback', 'yes', 'senstype', {'ctf275_planar'});
the input is timelock data with 538 channels and 2 timebins
Error using ft_checkdata (line 573)
This function requires data with an ctf275_planar sensor array.
```

However, `ft_senstype` recognizes it correctly:

```
>> ft_senstype(corrdat)

ans =

    'ctf275_planar'
```

Am I missing some magic aspect of how planar gradient data structures are recognized by `ft_checkdata`, or should this just work as it is?

**Comment by robertoostenveld** [comment]
my first idea is that the type of sensor-array and the type of the data are two separate things. So `data.label` and `data.trial` might be all EEG channels, whereas data also could contain the `grad` field... Or as in your case: just the other way around, your data.label suggests that it is planar CTF data, but there is no `grad` . 

In this case you are enforcing with `ft_checkdata` that `corrdat` contains a `sens` or `grad` structure that is of type `ctf275_planar`. And that is why it gives the error.
