### ISSUE TITLE
BUG: neuromag122_neighb.mat has 306 entries

### ISSUE THREAD

**Issue by larsoner** [fieldtrip/fieldtrip#1676]
I think an issue from [~8 years ago](https://mailman.science.ru.nl/pipermail/fieldtrip/2013-May/019387.html) is unresolved:

> it seems to me that this template contains labels form the neuromag306 system.  Is it right? And can I find the template somewhere?

Locally `load neuromag122_neighb.mat` shows:
```
>> neighbours

neighbours = 

  1×306 struct array with fields:

    label
    neighblabel
```
So this still seems to be an issue.

Apologies if this file is no longer used -- we use it in MNE-Python as a definition for neighbors and [a user hit this issue](https://github.com/mne-tools/mne-python/issues/8890). If it's not used anymore by FieldTrip, another option would be for us to stop using the file and use a Delaunay triangulation instead at the MNE end.

**Comment by schoffelen** [comment]
Hi Eric,

Ouch! This indeed is not correct. As it stands currently, the file cannot be used anyhow, so I don't see a problem in falling back to a Delaunay triangulation. If you want, I can search some dusty disks to see whether a correct file existed at some remote past, and upload it.

**Comment by schoffelen** [comment]
The oldest FT-copy I could lay hands on - and which contains a neuromag122_neighb.mat file - also has 306 channels.

I think it would be best to not use the file. We will get rid of it on our end, and indeed rely on ft_prepare_neighbours (which by default does a distnace based neighbour definition (but can also do a triangulation)).

**Comment by robertoostenveld** [comment]
I think this goes back to http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=800 and https://www.fieldtriptoolbox.org/development/project/neighbourtemplates/ 

which led me to http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=1135 where some content is discussed and which links to https://www.fieldtriptoolbox.org/faq/why_are_there_multiple_neighbour_templates_for_the_neuromag306_system/.

However, I think that the important issue not discussed in those old issues is how to define neighbours of planar channels in a meaningful fashion. E.g. should channels with a horizontal sensitivity be neighbours of channels with a vertical sensitivity?

**Comment by schoffelen** [comment]
So, in other words, we could drop in a neuromag122cmb_neighb.mat file, where the neighbours are defined on the 61 'channel' locations, to be used spatial clustering of 'combined planar gradients'.

**Comment by robertoostenveld** [comment]
or we could delete it and leave it to whomever still wants to analyze a neuromag122 dataset. I am not aware whether any of those systems is still operational, and I am also not aware of any shared data from those systems. 

I prefer to play it safe and keep expectations low, i.e. remove the file. 

If we keep the file and update it, we are responsible to use the most optimal way to make the neighbours. Nowadays that probably would be with [ft_prepare_neighbours.m](https://github.com/fieldtrip/fieldtrip/blob/master/ft_prepare_neighbours.m) with method=triangulation and compress=yes, to ensure that we cross both diagonals in square arrangements (which I consider more appropriate than only taking a single diagonal, as with a default Delaunay triangulation)

**Comment by larsoner** [comment]
> I prefer to play it safe and keep expectations low, i.e. remove the file... [and] ensure that we cross both diagonals in square arrangements

Agreed this seems safest. I'll check to see what we do in MNE-Python, I can't recall how careful we are about this...
