### ISSUE TITLE
ft_virtualchannel help not consistent with options

### ISSUE THREAD

**Issue by mcvinding** [fieldtrip/fieldtrip#1682]
I have noticed an inconsistency in the help documentation for the function `ft_virtualchannel`. The documentation mentions the following methods:

   'mean'      compute the mean
   'median'    compute the median (unsupported for fields that are represented in a cell-array)
   'eig'       compute the largest eigenvector
   'min'       take the minimal value
   'max'       take the maximal value
   'maxabs'    take the signed maxabs value
   'std'       take the standard deviation

However, none of these methods are part of the options from what I can read in the function.  In the function, `cfg.method` has the option "svd" (default), "None", or compmethods = {'pca' 'runica' 'fastica' 'dss'} - which is what the function choose between in the switch at line 271. It is also not specified that the method should be declared with `cfg.method` (I assume).

**Comment by schoffelen** [comment]
Well spotted Mikkel. I suspect that this is a remnant from the documentation that is in ft_sourceparcellate. I think I overlooked this section when rewriting the docstring to match the ft_virtualchannel function.

**Comment by schoffelen** [comment]
I have updated the documentation
