### ISSUE TITLE
Octave 6.1 compatibily

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1692]
startsWith function not defined. 
It is there though

fieldtrip/compat/matlablt2016b/

Should be added if Octave is detected.

**Comment by robertoostenveld** [comment]
Thanks. 

I added it to `compat/octave`. However, I do not have an easy way of checking whether `compat/octave` is automatically added to the path, so you should check yourself that it now works.

**Comment by arnodelorme** [comment]
OK, I will check that out. Thanks Robert.
