### ISSUE TITLE
ft_info and other notification functions slow down many FieldTrip functions

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1701]
**Describe the bug**

When looking at `ft_databrowser` with the MATLAB profiler, I noticed that quite some time was spent on `ft_info`.  We have replaced many occurrences of `fprintf` with that, and also use the same underlying code for `ft_warning` and `ft_error`. However, I do worry that the sophistication that we rely on for e.g. "warning once" slows down FT in general.

**To Reproduce**

```
n = 1000;

stopwatch = tic;
for i=1:n
  fprintf('hello\n');
end
t1 = toc(stopwatch);

stopwatch = tic;
for i=1:n
  ft_info hello
end
t2 = toc(stopwatch);

t1
t2
```

gives me this

```
t1 =
    0.0107
t2 =
    1.3086
```

So ft_info is more than 100 times slower.

**Expected behavior**

I don't see a fundamental reason why it would be 100x so slow.

**Environment and versions (please complete the following information):**
 - Operating System: macOS
 - MATLAB version: R2020b
 - FieldTrip version: latest master

**Comment by schoffelen** [comment]
hehe, if I run it, it takes > 4 seconds. Half of the time seems to be spent on the line (in ft_notification) p = fileparts(which('ft_defaults')), which is I guess needed to get ft_path

**Comment by robertoostenveld** [comment]
I see it varying quite a bit over repeated calls, sometimes it is a factor 100x, sometimes 250x.

**Comment by robertoostenveld** [comment]
replacing that line with 
```
[v, p] = ft_version;
```
already speeds it up quite a bit.

**Comment by schoffelen** [comment]
It's actually an interesting profiling exercise. I notice that fileparts in itself is quite 'slow' when it evaluates ispc: I wonder if it's worthwhile to overload it, and use a persistent variable (or input flag to denote pc'ness)

Might be something to consider in general for own FT-code that calls ispc often

**Comment by schoffelen** [comment]
Not sure, but the repeated evaluation ismember(<something>, {s.identifier}) might be speeded up, if the {s.identifier} is created once as a temporary variable, which removes the need of doing the { } expansion multiple times per call to ft_notification

**Comment by robertoostenveld** [comment]
I made a `test_issue1701.m` script and made `ft_version` a bit faster by beter use of the persistent variables, resulting in `fileparts` only being called once. I also made some other changes in the commit 13a0700 that I just merged with master. 

I suspect there is further room for improvement.
