### ISSUE TITLE
statfun_correlationT not using correlation type for cluster critval 

### ISSUE THREAD

**Issue by stephenwhitmarsh** [fieldtrip/fieldtrip#1713]
Hi there. I might have stumbled on a bug; 

When montecarlo clustering correction is used in conjuction with statfun_correlationT, the cluster critval is retrieved in ft_stastistics_montecarlo (line 239) using ft_statfun_correlationT.

In ft_statfun_correlationT (line 62), the correlation type is determined using:

`cfg.type  = ft_getopt(cfg, 'type', 'Pearson'); % 'Pearson', 'Kendall' or 'Spearman'`

However, ft_statistcs_montecarlo does not pass cfg.type to ft_statfun_correlationT (see tmpcfg above line 239 in ft_stastistics_montecarlo).

This is not the case when using statful_correlationT in conjuction with ft_statistic_analytic, because the latter passes the whole cfg on.

Now, it is possible that the critval is independent of correlation type, and that always using Pearson is fine, but it looks suspicious to me. 

A solution would be adding 
`tmpcfg.type = cfg.type (~ line 234 in ft_stastistics_montecarlo)`

What do you think?
Stephen

**Comment by schoffelen** [comment]
Hi Stephen, well caught. I think that adding the 'type' field to the tmpcfg would work for this function, but not in general. There might be statfuns which have other non-standard fields in their cfg that would then also need to be added, which is not maintainable (although I doubt whether there are many non-standard statfuns that allow for critical values to be computed, but that's a different story...). 
Interestingly, the tmpcfg is only used when computing the critical value for thresholding, but in the actualy computation of the observed test statistic the 'full' cfg is used (line 264).
I think that this can be addressed in a rather straightforward way: at the moment I have a work-in-progress PR #1709 that involves an overhaul of ft_statistics_montecarlo, shall I just take this issue along in it? I worry that - if we fix the current issue in a PR that is merged more rapidly than my PR - I need to fix merge conflicts along the way, which I'd rather avoid.

**Comment by stephenwhitmarsh** [comment]
Hi JM,

Thanks for confirming. Adding it to your overhaul would be great. In the
meantime I'll just add the line in my local repo.

Best wishes,
Stephen

**Comment by schoffelen** [comment]
The corresponding PR has been merged. The fix will appear in the new release
