### ISSUE TITLE
ft_nirs_transformODs gives error about the montage

### ISSUE THREAD

**Issue by jannystapel** [fieldtrip/fieldtrip#1718]
**Describe the bug**
If I run ft_nirs_transformODs then I get an error that 'not all output channels of the montage are unique'

**To Reproduce**
[montage_error.zip](https://github.com/fieldtrip/fieldtrip/files/6172705/montage_error.zip)
1. Read in the attached file called montage_error.mat
2. Run the following line: dataout = ft_apply_montage(data, montage, 'keepunused', 'yes');

The problem is independent of whether you keep or do not keep the unused parts.

**Expected behavior**
I expected no error.

**Comment by robertoostenveld** [comment]
I renamed the file and executed the following 

```
function test_issue1718

% WALLTIME 00:10:00
% MEM 2gb
% DEPENDENCY ft_apply_montage

load(dccnpath('/home/common/matlab/fieldtrip/data/test/issue1718.mat'));

%% this caused the error
ft_apply_montage(data, montage, 'keepunused', 'yes');

%% this shoul also work
ft_apply_montage(data, montage, 'keepunused', 'no');

```

the error is in the montage.
