### ISSUE TITLE
read_oxy3_header prints a lot of imaginary numbers to the screen

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1720]
**Describe the bug**
read_oxy3_header.p prints a lot of imaginary numbers to the screen, probably due to a trailing 'i' or 'j' in the function's code

**To Reproduce**
1. run the test function test_tutorial_nirs_multichannel20191023 (which is a currently failing test function for some reason).

**Expected behavior**
informative text feedback to the screen

**Screenshots**
a lot of ans = 0.0000 + 1.0000i

**Environment and versions (please complete the following information):**
 - Operating System: linux
 - MATLAB version: R2018b
 - FieldTrip version: master branch

**Additional context**
no hurry but perhaps @Horschig can have a look at some point.

**Comment by robertoostenveld** [comment]
I changed something to `ft_nirs_prepare_ODtransformation` last week and wonder whether that might be related...

**Comment by robertoostenveld** [comment]
It is not related to `ft_nirs_prepare_ODtransformation` but it happens in the Artinis p-code. This is something only @Horschig can fix.
