### ISSUE TITLE
Feature request: Getting topography plots for ML purposes

### ISSUE THREAD

**Issue by ShiriMakov** [fieldtrip/fieldtrip#1723]
Hi,
I wish to run ML models on topography plots.
For that aim, I'm preparing the plots using `ft_topoplotER`.
I would like to suggest 2 features that would allow getting the image (matrix of values) properly:

1. Have `ft_topoplotER` and `topoplot_common` return `h` all the way back to the main script. 
Here are the necessary changes:
```matlab
    % ft_topopltER: 
    % line 1:     function [cfg,h] = ft_topoplotER(cfg, varargin)
    % line 212:   [cfg,h] = topoplot_common(cfg, varargin{:});
    % topoplot_common: 
    % line 1:     function [cfg,h] = topoplot_common(cfg, varargin)
    % line 687:   h = ft_plot_topo(chanX, chanY, dat, opt{:});
```

2. Allow running ft_topoplotER without actually plotting, for this makes the process very slow.

**Comment by schoffelen** [comment]
it's unclear what you want. why using a plotting function if the purpose is not to plot anything? Do you need the interpolated surface matrix that is generated in ft_plot_topo?

**Comment by ShiriMakov** [comment]
Exactly :)
Is there an easier way for getting it?

**Comment by robertoostenveld** [comment]
you can do the following

```
cfg = [];
cfg.layout = layout;
ft_topoplotER(cfg, timelock1);

ans = 
  13×1 graphics array:

  Text       (25-Mar-2021, time=[0.002 1], avg=[-0.0801…)
  Line
  Line
  Line
  Line
  Line
  Line
  Contour
  Line
  Line
  Line
  Line
  Surface

>> ans(end)
ans = 
  Surface with properties:

       EdgeColor: 'none'
       LineStyle: '-'
       FaceColor: 'flat'
    FaceLighting: 'flat'
       FaceAlpha: 1
           XData: [67×67 double]
           YData: [67×67 double]
           ZData: [67×67 double]
           CData: [67×67 double]
```

so with this

```
>> h = get(gca, 'Children');
>> h(end).CData
```

you get the data you want. If you want to control the figure handle, you can do

```
myfigure = figure;
cfg = [];
cfg.layout = layout;
cfg.figure = myfigure;
ft_topoplotER(cfg, timelock1);
```
and use the `myfigure` handle.

If you want to speed it up, I recommend that you look at `ft_plot_topo` and call that directly, or even use the low-level  [griddata](https://nl.mathworks.com/help/matlab/ref/griddata.html) or [scatteredinterpolant](https://nl.mathworks.com/help/matlab/ref/scatteredinterpolant.html) rather than the high-level `ft_topoplotER`

**Comment by schoffelen** [comment]
But the question remains: What's an "ML purpose"?

**Comment by robertoostenveld** [comment]
> But the question remains: What's an "ML purpose"?

I guess the machine will tell us when it has leaned its purpose... it might be 42.

**Comment by ShiriMakov** [comment]
I meant that my purpose was to use it for ML.
Excuse my English.
Glad you had a good laugh, it's good for your health.

**Comment by schoffelen** [comment]
Note that we were not laughing about you, we're laughing with you. You know how to move forward now I hope?
