### ISSUE TITLE
make cfg.channels forbidden

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1729]
**Is your feature request related to a problem? Please describe.**

I noticed a user to specify `cfg.channels` rather than `cfg.channel`, where the channel selection was subsequently ignored. This lead to unexpected results further down in the analysis. 

**Describe the solution you'd like**

Using ft_checkconfig we could make cfg.channels forbidden in all high-level functions.

**Describe alternatives you've considered**

We could also make use the ft_checkconfig  `renamed` option and rename channels into channel. Since channels was never used, I am not in favor of that.

**Comment by schoffelen** [comment]
I agree. Better make the user aware of the fact that they should pay attention to the proper spelling of options, rather than automatic fixes for often unintended typos

**Comment by robertoostenveld** [comment]
The same thing just happened for `cfg.method` rather than `cfg.interpmethod` in ft_sourceinterpolate.

**Comment by schoffelen** [comment]
regarding <something>method: there's also a cfg.planarmethod :).  Would it not make sense to revert those instances back to plain cfg.method? in case the function does not have different <something>methods as option, it would streamline the option naming scheme in general.

**Comment by schoffelen** [comment]
BTW, regarding channels vs. channel: why is it called cfg.trials, and not cfg.trial?

**Comment by robertoostenveld** [comment]
there is also invmethod, pairmethod, mvarmethod, submethod, refmethod, cohmethod, powmethod, supmethod, fwhmmethod, projmethod, spmmethod, and others.

For some it is a sub-specification, for others it is the consequence of code refactoring in the past, e.g. ft_megplanar was once part of the same high-level function as ft_meginterpolate. 

For functions that have a single unambiguous method, like ft_sourceinterpolate, I do prefer `cfg.method` over the peculiar methods that are now used.

**Comment by schoffelen** [comment]
pairmethod?

**Comment by robertoostenveld** [comment]
regarding interpmethod: I see in ft_sourceplot that when cfg.method=surface  you can specify cfg.projmethod, which later in the code is translated into tmpcfg.interpmethod.

I think that is too big to be solved together with this issue. We can keep it in mind for later.
