### ISSUE TITLE
cfg.clusteralpha not used properly

### ISSUE THREAD

**Issue by yingjoeyzhou** [fieldtrip/fieldtrip#1731]
From my understanding, `cfg.clusteralpha` should be used to set the critical T-value for clustering. For example, if `cfg.clusteralpha = 0.01`, then the cluster should only include voxels whose T-values fall outside 99% tail(s); whereas if set to 0.025, then the voxels included would correspond to those outside 97.5% tail(s).

However, this doesn't seem to be the case. Instead of using `cfg.clusteralpha` to set the critical T-value, the statfun uses `cfg.alpha` to do so. Which in principle is something users can easily get around with by `cfg.alpha = cfg.clusteralpha`, but then `cfg.clusteralpha` would be meaningless.  

Example code included. 

`load ERF_orig;

Nsubj  = 10;
design = zeros(2, Nsubj*2);
design(1,:) = [1:Nsubj 1:Nsubj];
design(2,:) = [ones(1,Nsubj) ones(1,Nsubj)*2];

%% traditional cluster-based permutation test
cfg                  = [];
cfg.design           = design;
cfg.uvar             = 1;
cfg.ivar             = 2;
cfg.channel          = {'MLT12'};
cfg.latency          = [0 1];
cfg.method           = 'montecarlo';
cfg.numrandomization = 500;
cfg.statistic        = 'depsamplesT';
cfg.correctm         = 'cluster';
cfg.clusteralpha     = 0.01;
cfg.clusterstatistic = 'maxsum';
cfg.clustertail      = 0;
cfg.tail             = 0;
cfg.alpha            = cfg.clusteralpha;
stat01 = ft_timelockstatistics(cfg, allsubjFIC{:}, allsubjFC{:});

`

**Comment by schoffelen** [comment]
Hi Joey, could you add some information that allows for easy appreciation of the issue, i.e. perhaps add some different scenarios (2x2) with different clusteralpha/alpha, and then some figures that show why it doesn't work. Perhaps also check how the options are handled within the caller functions, <something>statistics, and ft_statistics_montecarlo?

**Comment by yingjoeyzhou** [comment]
Yes. I'm currently making some screenshots for how I trace down and spot
this.

**Comment by schoffelen** [comment]
I guess that you need to scrutinize the way in which the critical values are computed. If a parametric threshold is employed (as I suspect in your use case), this means that the statfun is called once in ft_statistics_montecarlo, in order to compute the cfg.clustercritval. I would think that the cfg.clusteralpha should be transferred to the (temporary) cfg that serves as cfg for th statfun, but it should be renamed into cfg.alpha (again: temporarily) in order to work well.

**Comment by schoffelen** [comment]
Recently, some small changes were made in ft_statistics_montecarlo in this department, based on an issue detected by @stephenwhitmarsh . I suggest you look into the history of the changes to ft_statistics_montecarlo

**Comment by yingjoeyzhou** [comment]
You are 100% correct. The issue stems exactly from that `cfg.clusteralpha` was not passed into `cfg.alpha` (temporarily).

**Comment by yingjoeyzhou** [comment]
relevant output field:
![image](https://user-images.githubusercontent.com/31690290/114152310-6c4d3580-991e-11eb-91f2-4360437ad9c1.png)




`if isempty(which('ft_defaults')) %when fieldtrip is not yet in the path
    addpath('/home/common/matlab/fieldtrip');
    ft_defaults;
end

load ERF_orig;


Nsubj  = 10;
design = zeros(2, Nsubj*2);
design(1,:) = [1:Nsubj 1:Nsubj];
design(2,:) = [ones(1,Nsubj) ones(1,Nsubj)*2];


%% traditional cluster-based permutation test
cfg                  = [];
cfg.design           = design;
cfg.uvar             = 1;
cfg.ivar             = 2;
cfg.channel          = {'MLT12'};
cfg.latency          = [0 1];
cfg.method           = 'montecarlo';
cfg.numrandomization = 500;
cfg.statistic        = 'depsamplesT';
cfg.correctm         = 'cluster';
cfg.clusteralpha     = 0.01;
cfg.clusterstatistic = 'maxsum';
cfg.clustertail      = 0;
cfg.tail             = 0;
cfg.alpha            = 0.025; %cfg.clusteralpha;
stat01 = ft_timelockstatistics(cfg, allsubjFIC{:}, allsubjFC{:});


cfg.clusteralpha     = 0.05;
cfg.clusterstatistic = 'maxsum';
cfg.clustertail      = 0;
cfg.tail             = 0;
cfg.alpha            = 0.025; %cfg.clusteralpha;
stat05 = ft_timelockstatistics(cfg, allsubjFIC{:}, allsubjFC{:});


%% 
figure(1), clf, hold on, 
set(gcf, 'units','centimeters','position',[0 0 10 18] );

subplot(2,1,1), hold on,
title( 'clusteralpha = .01' );
plot( stat01.time, stat01.stat, 'k');
plot( stat01.time(stat01.mask), 7.5*ones(sum(stat01.mask),1), 'k', 'linewidth',2 );
ylabel( 't-value' );
ylim( [-3, 8] );
set(gca, 'TickDir','out' );

subplot(2,1,2), hold on,
title( 'clusteralpha = .05' );
plot( stat05.time, stat05.stat, 'k');
plot( stat05.time(stat05.mask), 7.5*ones(sum(stat05.mask),1), 'k', 'linewidth',2 );
ylabel( 't-value' );
ylim( [-3, 8] );
set(gca, 'TickDir','out' );
`

**Comment by yingjoeyzhou** [comment]
![demo_issue1731](https://user-images.githubusercontent.com/31690290/114152484-a6b6d280-991e-11eb-80ba-173b643058ca.png)


horizontal bars highlight the identified clusters.

**Comment by schoffelen** [comment]
I have fixed this (I think) and created a PR. I will merge this into the master branch in a minute. Could you please test it off the master branch whether it now behaves as expected?

**Comment by schoffelen** [comment]
To document: functionality of cfg.clusteralpha was incorrect for ft_statistics_montercarlo in the releases that were released between March 25 and March 30, 2021. The result was that - for the parametric critical value computation for test statistics - the cfg.alpha was used. If a user uncoupled the two (i.e. specified by hand a cfg.clusteralpha that was different from the cfg.alpha), the results might have been not according to what was to be expected. This has been fixed by PR 1733
