### ISSUE TITLE
add a template layout file for the yokogawa160 MEG system

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1737]
We don't have a template layout file for the yokogawa160 system. I propose to make one, starting from a data set shared by @Herminepsy

It would use ft_read_sens, ft_prepare_layout, and some additional tweaking to make it fit the sphere better.

**Comment by robertoostenveld** [comment]
this is also relevant for @grahamflick

What I did so far was this
 
```
grad = ft_read_sens('subject2_block1.con');
ft_plot_sens(grad)

%%

cfg = [];
cfg.grad = grad;
layout = ft_prepare_layout(cfg);

sel = 1:(length(layout.label)-2); % the last two are COMNT and SCALE
layout.pos(sel,:) = layout.pos(sel,:) *1.05;
layout.pos(sel,2) = layout.pos(sel,2) * 1.08 + 0.02;


%%


load ~/matlab/fieldtrip/template/layout/CTF151_helmet.mat
ctf151 = lay;
clear lay

%%
layout.outline = ctf151.outline;
layout.mask = ctf151.mask;

ft_plot_layout(layout, 'box', 1);

```
<img width="672" alt="Screenshot 2021-04-20 at 15 41 35" src="https://user-images.githubusercontent.com/899043/115405840-e5863b80-a1ee-11eb-851a-000719791f05.png">

it looks ok at first glance, but I noticed that it is not perfectly symmetric

**Comment by robertoostenveld** [comment]
@grahamflick and I discussed this in detail. The different "yokogawa160" systems in different labs do not have precisely the same layout, hence adding a single template would not be wise. Instead, we will add a section to the http://fieldtriptoolbox.org/getting_started/yokogawa/ page instead.

**Comment by Herminepsy** [comment]
@robertoostenveld thank you so much for looking into it. I also got a layout for my data based on your advice from yesterday. I guess adding a section is a very good solution for helping people to get started with yokogawa data.

**Comment by schoffelen** [comment]
I think that this has been addressed, right? Please feel free to close the issue @Herminepsy or @grahamflick

**Comment by grahamflick** [comment]
@schoffelen yes, done. Though I don't seem to be able to close the issue on my end...

**Comment by schoffelen** [comment]
no worries. Thanks for your contributions and we're looking forward to more !

**Comment by Herminepsy** [comment]
@schoffelen indeed, sorry I was not able to close the issue either. Me and @grahamflick will continue contributing to this in future.
