### ISSUE TITLE
add support for the polhemus 3D motion tracker file formats from kinemagic 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1746]
Following discussion with @ruiliu-psy we identified that  the [kinemagic](https://github.com/lennartverhagen/kinemagic) toolbox from @lennartverhagen can read and process data from the Polhemus Liberty 3D tracker in the DCCN behavioral lab. It would be nice to have that functionality also in FieldTrip. 

This will allow to convert the data to BIDS using `data2bids` just like here https://www.fieldtriptoolbox.org/example/bids_motion/. 

Note that we **do not aim** to replace the existing motion processing that kinemagic can do, just the minimal preprocessing. Following data actual processing in kinemagic, we might want to implement a `kinemagic2fieldtrip` function for follow-up analysis, but that would be for a separate issue.

Specifically it pertains to this function https://github.com/lennartverhagen/kinemagic/blob/master/proc/read/km_read_polhemus.m.

**Comment by robertoostenveld** [comment]
@ruiliu-psy can you send me an example data file? You can send it through `/home/common/temporary` or email.

**Comment by ruiliu-psy** [comment]
> @ruiliu-psy can you send me an example data file? You can send it through `/home/common/temporary` or email.

Hi, Robert! I uploaded the data onto '/home/common/temporary/HoiRobert', you cannot miss it ;)
The README.txt file illustrates contents of each file. The Polhemus recording doesn't have a hrd file, please let me know if you need the configuration file, I can fetch it from the lab PC tomorrow (for the analysis I didn't use it).

**Comment by robertoostenveld** [comment]
Thanks, found it! I have copied the data to `/home/common/matlab/fieldtrip/data/test/issue1746`. We can use that location in a test script that can be executed on the compute cluster.

**Comment by robertoostenveld** [comment]
Hi @ruiliu-psy couldd you try the code in https://github.com/fieldtrip/fieldtrip/blob/master/test/test_issue1746.m on your dataset and check whether it makes sense?

**Comment by ruiliu-psy** [comment]
Hi @robertoostenveld thanks for the quick action!
The headerformat ('*.csv') is not supported yet. Error occured in both ft_read_header and ft_read_data.

**Comment by robertoostenveld** [comment]
did you use the latest master version from github?

**Comment by ruiliu-psy** [comment]
yeah, the one your updated 17h ago. Here's the error report, but 'delimitedtext' seems correct to me.

```
Error using readtable (line 216)
The file type 'delimitedtext' is not recognized.

Error in liberty_csv (line 54)
  csv = readtable(fullname, 'FileType', 'delimitedtext', 'delimiter', ',', 'ReadVariableNames', true,
  'VariableNamingRule', 'preserve');

Error in ft_read_header (line 2758)
      hdr = feval(headerformat, filename);
```

**Comment by robertoostenveld** [comment]
ah, I see that is a MATLAB version issue. I wrote the code one 2020a, but see that some of the options are unsupported on 2018b. Can you try once more after changing that line to 

```
  csv = readtable(fullname, 'FileType', 'text', 'Delimiter', ',', 'ReadVariableNames', true);
```
