### ISSUE TITLE
Source analysis

### ISSUE THREAD

**Issue by venus1670** [fieldtrip/fieldtrip#1747]
**Remove the following lines in case they don't apply**

- Please ask the community on the [discussion list](http://www.fieldtriptoolbox.org/discussion_list/) for help on _using_ FieldTrip.
- Please see [here](http://www.fieldtriptoolbox.org/about/) if you want to contact the lead developpers privately. 
 

Hello dears
I have preprocessed meg data from decaf and I want to compute connectivity but I couldn't have deal with programming on field trip. Please someone help me what should I do? I have a power spectrum result and I don't know what are the steps to measure connectivity.

Best regards,

Zahra.saeedian.76@gmail.com
Whatsup:+989374941007

**Comment by schoffelen** [comment]
I don't understand the question. Also, please ask it on the discussion forum, as instructed
