### ISSUE TITLE
Incorrect array dimensions in ft_checkdata when called from ft_timelockanalysis after ft_redefinetrial

### ISSUE THREAD

**Issue by johalgermissen** [fieldtrip/fieldtrip#1750]
My goal is to average data of certain trials that are part of the same condition using ft_timelockanalysis.
Right before calling ft_timelockanalysis, I have called ft_redefinetrial.

The input cell array looks fine to me:
```
scd = 

  struct with fields:

         trial: {1×620 cell}
          time: {1×620 cell}
         label: {64×1 cell}
       fsample: 1.0000e+03
    sampleinfo: [620×2 double]
     trialinfo: [620×1 double]
           cfg: [1×1 struct]
```
All cells in scd.trial are of size {64×4500 double} and all cells in scd.time are of size {1×4500 double}.

I get the following error:

```
the input is raw data with 64 channels and 620 trials
the call to "ft_selectdata" took 0 seconds and required the additional allocation of an estimated 2 MB
Unable to perform assignment because the size of the left side is 1-by-64-by-4499 and the size of the right
side is 64-by-4500.

Error in ft_checkdata>raw2timelock (line 1519)
    tmptrial(i,:,begsmp(i):endsmp(i)) = data.trial{i};

Error in ft_checkdata (line 478)
      data = raw2timelock(data);

Error in ft_timelockanalysis (line 205)
data = ft_checkdata(data, 'datatype', {'timelock+comp' 'timelock'});

Error in EEGfMRIPav_CueLocked_8_time_create (line 262)
                           ERPdata{iSub,iCondi} = ft_timelockanalysis(cfg,scd);
 
1519     tmptrial(i,:,begsmp(i):endsmp(i)) = data.trial{i};
```

I saved the error and put it on the DCCN system under /home/common/temporary/FieldtripError_ft_checkdata/ft_timelockanalysis_20210503T122440.mat

 - Operating System: DCCN Linux Cluster
 - MATLAB version: 2018b
 - FieldTrip version: version on DCCN cluster on May 3, 2021

Thanks for any pointers!

**Comment by schoffelen** [comment]
This looks like a typical 'round off' error to me. It seems that you have adjusted the time axis of your individual trials (e.g. made them response locked), causing a shifted time axis in each of the trials. Given that the trial-specific shift has likely not been expressed in integer multiples of the sampling delta-t, unfortunate numeric round off issues might lead to occasional dropping of samples, as is the case here.

**Comment by schoffelen** [comment]
In the past, several attempts have been made to make this more robust, but occasionally it might still fail, particularly in situations in which a trial's sampled time-axis is about halfway in between the samples of the 'master' time-axis, against which all individual trials are to be referenced. 

I think that the solution here would be to slightly shift the individual time axes of the trials, such that the sampled time points are better aligned across trials. Since the time resolution is 1/fsample at best, this won't have a consuence for downstream interpretation:

for k = 1:numel(csd.time)
  % identify the sample in the time axis closest to time point 0, for this trial -> this only works if the time axis runs from negative time to positive time
  ix = nearest(csd.time{k},0);
  csd.time{k}=csd.time{k}-csd.time{k}(ix);
end

ft_timelockanalysis should now run without error

**Comment by schoffelen** [comment]
Note that this does not address the reported issue, where you observed the error while running in a for-loop only

**Comment by robertoostenveld** [comment]
just for reference: I copied the data to the test directory
```
cd /home/common/matlab/fieldtrip/data/test/
cp /home/common/temporary/FieldtripError_ft_checkdata/ft_timelockanalysis_20210503T122440.mat issue1750.mat
```

**Comment by schoffelen** [comment]
If we'd want to save on memory, we could consider pruning the number of trials down to 4 or so, provided the trials with the min across time and the max across time, as well as the 3d trial are in the dataset,  i think it can be reproduced

**Comment by robertoostenveld** [comment]
I did this

```
figure 
hold on

for i=1:length(data.time)
  x = data.time{i};
  y = i*ones(size(x));
  
  plot(x, y, '.');
end
```
which gave this
<img width="672" alt="Screenshot 2021-05-04 at 18 32 57" src="https://user-images.githubusercontent.com/899043/117037838-3cb80000-ad07-11eb-9054-175c08547508.png">

and after zooming in this

<img width="672" alt="Screenshot 2021-05-04 at 18 33 14" src="https://user-images.githubusercontent.com/899043/117037870-46d9fe80-ad07-11eb-8048-87f539a07da2.png">
 
I don't know what happened w.r.t. the alignment of the trials, but I would not know how to average those samples over trials...

**Comment by johalgermissen** [comment]
Thanks both!

Indeed---I checked my data and the EEG resolution is 1000 Hz, so `scd.time{1}(1:10)`_before_ calling ft_redefinetrial() is 
`-1.7000   -1.6990   -1.6980   -1.6970   -1.6960   -1.6950   -1.6940   -1.6930   -1.6920   -1.6910`

but the RT resolution of my data is 10,000 Hz for some reason, so `behav.RT(1:10)` gives
`0.5294    0.6963    0.6587    0.6502    0.9186    0.7103    0.9076    0.8774    0.8365    0.7538`

which I then multiply them with the sampling rate (1000) to obtain samples, which gives non-integer samples:
`529.4071  696.3265  658.7346  650.1986  918.5860  710.2864  907.6278  877.4113  836.4967  753.7739` 
so yeah such weird behavior might have been expectable...

Just rounding RTs to milliseconds already solves the problem (no error, but still warnings:
```
Warning: correcting numerical inaccuracy in the time axes 
Warning: correcting numerical inaccuracy in the time axes 
Warning: inconsistent sampleinfo 
```
With @schoffelen suggested for-loop, at least the last warning (about inconsistent sampleinfo) goes away.

I'd theoretically be happy with just round RTs to ms but I'm further looking into why I still get warnings...

**Comment by johalgermissen** [comment]
Maybe at least worth to check (within ft_checkdata or ft_timelockanalysis) whether samples are integers, and throw a warning or a more descriptive error message if that's not the case....?

**Comment by johalgermissen** [comment]
Okay I found another error (I did some RT interpolation at a later step and forgot to round that to ms too), now the warnings are gone.

Still I noticed that after rounding RTs to 1 ms, ft_redefinetrial() still behaves weirdly...
I do
`format long g`
and first 3 entries of scd.time{1}(1:4) are
`                      -1.7                    -1.699                    -1.698                    -1.697`
and around 0 it's data.time{1}(1699:1702)
`                    -0.002                    -0.001                         0                     0.001`

RT2useSamples is
`529   696   659   650`
and I do
```
cfg                 = [];
cfg.offset          = -RT2useSamples; % vector with begin samples relative to t=1
out                 = ft_redefinetrial(cfg,scd);
```
but now out.time{1}(1:4) gives me
`         -2.22899999999996         -2.22799999999996         -2.22699999999996         -2.22599999999996`
but that seems weird to me... is that again numerical imprecision?

@schoffelen's for-loop then fixes it back to 3 digits past the comma, so no downstream problem, was just wandering whether ft_redefinetrial my additionally introduce imprecision.

**Comment by johalgermissen** [comment]
@robertoostenveld and me now talked about it and decided to just round the offset (which is to be provided in data _samples_, not in seconds) should be rounded to integers.

If the difference between the offset and it's rounded version is above some threshold, one could throw a warning to the user.

See pull request Update ft_redefinetrial.m  #1754
