### ISSUE TITLE
Consider a cloud CI service

### ISSUE THREAD

**Issue by acampbel** [fieldtrip/fieldtrip#1758]
Given public open source projects have free support for cloud ci services, consider leveraging one of them here. 🎉

https://blogs.mathworks.com/developer/2020/12/15/cloud-ci-services/

**Comment by schoffelen** [comment]
Thanks for reaching out Andy, but what's the question exactly? Indeed, ideally we'd want to professionalise our code development, including unit tests etc, but at the moment we don't have any resources available to work on this. Thus, it doesn't have our priority

**Comment by acampbel** [comment]
no question, just a suggestion. I understand the resource limitation, just wanted to ensure you were aware of this CI infrastructure that is available for you if/when you would like to leverage it.

**Comment by acampbel** [comment]
oh I see, I think I accidentally added the question label. oops sorry

**Comment by robertoostenveld** [comment]
let's close this here and continue at https://github.com/fieldtrip/playground/issues/14
