### ISSUE TITLE
Regression broken?

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1760]
I am trying to do correction for multiple comparisons using regression analysis.
I followed the example on this page https://www.fieldtriptoolbox.org/tutorial/cluster_permutation_freq/

After running the example (up to "[stat] = ft_freqstatistics(cfg, freqFIC_planar_cmb, freqFC_planar_cmb);"), I try to calculate my own regression using the following code. I change the design to contain continuous values (in this case random) and change the stats to "ft_statfun_indepsamplesregrT".

```
freqFC_planar_cmb2.label     = freqFC_planar_cmb.label;
freqFC_planar_cmb2.dimord    = freqFC_planar_cmb.dimord;
freqFC_planar_cmb2.freq      = freqFC_planar_cmb.freq;
freqFC_planar_cmb2.time      = freqFC_planar_cmb.time;
freqFC_planar_cmb2.powspctrm = freqFC_planar_cmb.powspctrm;

freqFIC_planar_cmb2.label     = freqFIC_planar_cmb.label;
freqFIC_planar_cmb2.dimord    = freqFIC_planar_cmb.dimord;
freqFIC_planar_cmb2.freq      = freqFIC_planar_cmb.freq;
freqFIC_planar_cmb2.time      = freqFIC_planar_cmb.time;
freqFIC_planar_cmb2.powspctrm = freqFIC_planar_cmb.powspctrm;

cfg.design = rand(1,149);
cfg.statistic = 'ft_statfun_indepsamplesregrT';

[stat] = ft_freqstatistics(cfg, freqFIC_planar_cmb2, freqFC_planar_cmb2);
```

The code runs fine but "stat.stat" contains NaNs only. Does not seem right. I might not be using the function as it is intended to be used, but I should probably get an error indicating so. Also, what is the proper way to do regression if it is not the way it is done above.

**Comment by schoffelen** [comment]
I cannot reproduce this: when I run it, the results contain NaNs, where the input also contains NaNs, i.e. at the edges of the TFR. The rest looks fine to me.

**Comment by schoffelen** [comment]
@arnodelorme. Can this be closed?
