### ISSUE TITLE
ft_rejectvisual - Add doc for cfg.ylim

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1762]
**Is your feature request related to a problem? Please describe.**
The option cfg.alim was renamed to cfg.ylim, but the corresponding line in the help section was removed.

**Describe the solution you'd like**
Add following line to the help section:
```
cfg.ylim - Limits for the y axis. can be [] (default, limits set automatically), [min max], 'maxabs', 'zeromax' or 'minzero'.
```

These are the options I see implemented in the subfunctions. If you agree with the phrasing, I'll make a PR.

**Comment by robertoostenveld** [comment]
Using `git blame` I identified that this was introduced in ac8810f365. There is no reason for ylim not being documented, please go ahead and add it to the help with a PR.

**Comment by NirOfir** [comment]
Thanks for the tips! I didn't know any of that.
