### ISSUE TITLE
error in MATLAB2018b with isnan("something")

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1781]
**Describe the bug**
data2bids subfunction output_compatible chokes on string in input ("a", instead of 'a')

**To Reproduce**
I don't have an example handy, but @KrisijanArmeni stumbled upon this, trying to feed in events that have values as a string "...". The subfunction output_compatible chokes on the evaluation of isnan("somestring").

**Screenshots**

**Environment and versions (please complete the following information):**
 - Linux 
 - MATLAB 2018b
 - FieldTrip version quite outdated, but the local code in data2bids (i.e. the subfunction seems stable). 

**Additional context**
JM can confirm the error in MATLAB2018b with isnan("a")

**Comment by robertoostenveld** [comment]
besides @KristijanArmeni reporting this, what makes you think this is not a user error, i.e. trying to specify a sampling rate as "a" ;-)

I know that formatting and validating the tables to output in a TSV file is not trivial. One of the aspects is in a column containing only numbers (and the occasional nan or inf), versus the case of a column only containing strings (with the occasional "1" that is not to be interpreted as a number). Do you know which TSV it is, and possibly which column?

**Comment by schoffelen** [comment]
Well, the context is that we aim at decorating an existing tsv with individual word onset events. To this end, an (admittedly handcrafted) events struct array is passed to data2bids, where the events have values like "THE" "ADVENTURES" "OF" "SHERLOCK" "HOLMES", instead of 'THE' 'ADVENTURES' 'OF' 'SHERLOCK' 'HOLMES'. We could of course solve it on our end by converting the strings into chars, but I don't know whether our use case is exceptional in that regard.

**Comment by robertoostenveld** [comment]
Ok, so it is for something in an events TSV. 

I never really understood the MATLAB string objects and continue to always use char-arrays. Do you have a reason for using strings rather than char-arrays? In the TSV file they would appear in the same format anyway and upon reading the TSV back into MATLAB you would not be able to tell the difference.
