### ISSUE TITLE
document and test the interface between SPM and fieldtrip

### ISSUE THREAD

**Issue by malinINCF** [fieldtrip/fieldtrip#1803]

**Comment by robertoostenveld** [comment]
The current documentation is on https://www.fieldtriptoolbox.org/getting_started/spm/ but lacks any example code. 

There are two files https://github.com/fieldtrip/fieldtrip/blob/master/test/test_spm_ft_integration.m and  `test_spm_ft_integration.mat` that hopefully demonstrate how to get data from fieldtrip to spm and vice versa... looking at the code, I see that it is not really that useful. 

Perhaps @vlitvak can give us a typical spm12 MEEG data structure in a mat file to demonstrate how to go from spm to fieldtrip.

What would be needed to demonstrate data going from fieldtrip to spm?

**Comment by vlitvak** [comment]
[spm_fieldtrip_integration.zip](https://github.com/fieldtrip/fieldtrip/files/6725275/spm_fieldtrip_integration.zip)

[maeafdfMspmeeg_subject1.zip](https://github.com/fieldtrip/fieldtrip/files/6725284/maeafdfMspmeeg_subject1.zip)

Here is an example dataset and two code examples, that I also included now in SPM under man/example_scripts (one's been there for many years, the other is new).

**Comment by schoffelen** [comment]
Just for reference: I just had a meeting with Luca, where we discussed the PR about the 'getting started with SPM' documentation. I made some suggestions for improvement, and we hope to get the majority of the documentation part of the deliverable merged soon. So far most of the changes in the documentation focusses on streamlining the documentation and highlighting the interaction between FT and SPM functionality, and how the tolboxes depend on one another. An open issue is still the documentation and testing of the interface to SPM, which probably at minimum would mean a test function (which is then also put on the getting started page) that shows how to use spm2fieldtrip to import the example file sent by Vladimir.

**Comment by schoffelen** [comment]
I think a minimum test would be:

ft_hastoolbox('spm12',1);
D=spm_eeg_load(<fname>);
data=spm2fieldtrip(D);

I just tried this, and it didn't work, because external/spm12/ lacks the spm_eeg_load function.

if I do:
ft_hastoolbox('spm8',1);
D=spm_eeg_load(<fname>);
data=spm2fieldtrip(D);

it produces a data object that looks fine (at first sight) to me.

**Comment by robertoostenveld** [comment]
this has been done on the website repository with https://github.com/fieldtrip/website/pull/437
