### ISSUE TITLE
Missing sampleinfo warning for ft_timelockanalyis

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1813]
**Describe the bug**
Not a significant bug, but I think that ft_checkdata in line 98 of ft_timelockanalysis returns an unwanted warning:
```
Warning: the data does not contain sampleinfo 
Warning: reconstructing sampleinfo by assuming that the trials are consecutive segments of a
continuous recording 
```
I think that sampleinfo is removed when ft_componentanalysis is called (which I suppose is pretty common, since ICA is a standard step), so I'm not sure why this warning is returned, but I got lost trying to read through ft_checkdata.

**To Reproduce**
Since this is a pretty minor bug, I didn't create a simple test dataset but I can if needed.

**Expected behavior**
Should this warning be returned at all? Under what conditions would ft_timelockanalysis use the sampleinfo at all?

**Environment and versions (please complete the following information):**
 - Operating System: Centos 7
 - MATLAB version R2018b
 - FieldTrip version 20210623

**Comment by robertoostenveld** [comment]
this is indeed a warning that is shown too often, also in cases where the `sampleinfo` field is not needed at all.

**Comment by NirOfir** [comment]
Thanks! Sounds like a relatively minor issue that can only be fixed with a lot of work. I saw that even if I remove the check in line 98, it still pops up later, so I suppose it will require sifting through a lot of code and possible scenarios.

**Comment by robertoostenveld** [comment]
agreed, lots of work for a minor improvement. I will close this issue.
