### ISSUE TITLE
Unable to read nicoletfile .e extension

### ISSUE THREAD

**Issue by balandongiv** [fieldtrip/fieldtrip#1820]
**Describe the bug**
Read a `nicoletfile`  `.e` extension using `ft_read_data` return an error.

via the line

```
hdr = ft_read_header('C:\somefolder\a.e');
dat = ft_read_data(nicoletfile, 'header', hdr);
```

Produce the error: 

> Unrecognized function or variable 'nicoletfile'.
> 
> Error in untitled (line 2)
> dat = ft_read_data(nicoletfile, 'header', hdr);

**Environment and versions (please complete the following information):**
 - Operating System: [e.g. Windows 10]
 - MATLAB version [ R2020b, type `ver 64 bit`]
 - FieldTrip version ["most recent master branch from github", type `ft_version`]

**Additional context**
I only allowed share the `.e` upon request. Link can be shared privately,only for debugging purpose.

**Comment by schoffelen** [comment]
mI think that this is a user error. Tha matlab error states that the variable 'nicoletfile' does not exist. the first input to ft_read_data should be a string that defines the name of an existing file
