### ISSUE TITLE
partialization with PLV returns the wrong number of channels

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1828]
**Describe the bug**

`test_pull1304` started failing, due to the output number of channels being inconsistent:

```
Data_stat = 

  struct with fields:

        label: {3x1 cell}
       dimord: 'chan_chan_freq'
    plvspctrm: [2x2x102 double]
         freq: [1x102 double]
          dof: 32
          cfg: [1x1 struct]
```

**To Reproduce**

Execute `test_pull1304` 😁

**Additional context**

This is a consequence of #1824, which in turn relates to #1802. Although the computation now works, the representation of the partialized PLV estimate is still not consistent.

**Comment by schoffelen** [comment]
can I do git rm ft_connectivityanalysis?

**Comment by robertoostenveld** [comment]
it will remain forever connected to you in the git history.

**Comment by schoffelen** [comment]
but git history can be rewritten, can it not?

**Comment by robertoostenveld** [comment]
we might be able to erase your memory of it, but the 500 forks will always remember 😈

**Comment by schoffelen** [comment]
I forgot to add a few lines in the plv section of ft_connectivityanalysis. Shall I just push this hotfix directly into master?

**Comment by robertoostenveld** [comment]
sure

**Comment by schoffelen** [comment]
OK, hotfixed...
