### ISSUE TITLE
fieldtrip2eeglab - missing case for FieldTrip usual data structure 

### ISSUE THREAD

**Issue by LucaLaFisca** [fieldtrip/fieldtrip#1857]
This function should be able to deal with usual FieldTrip data structure.
e.g., eeglab_data = fieldtrip2eeglab(data); % where data is a FT raw structure
Right now, it requires header and data array to be passed as input, separately.

**Comment by robertoostenveld** [comment]
Both fieldtrip2eeglab  and eeglab2fieldtrip are in https://github.com/fieldtrip/fieldtrip/tree/master/external/eeglab, which means they are formally maintained outside of fieldtrip. However, I have to admit that the synchronization from the actual EEGLAB release to `external/eeglab` is not so consistently done. 

@arnodelorm, are you keeping these two functions up to date somewhere in https://github.com/sccn/eeglab/?

**Comment by arnodelorme** [comment]
Yes,

One is here https://github.com/sccn/dipfit/blob/master/eeglab2fieldtrip.m
And the other one there https://github.com/sccn/eeglab/blob/develop/functions/miscfunc/fieldtrip2eeglab.m

However the second one uses File-IO and the function pop_fileio
https://github.com/sccn/eeglab/blob/develop/functions/popfunc/pop_fileio.m
(The last function should not require any EEGLAB function when called from the command line but to double check)

Arno

**Comment by robertoostenveld** [comment]
I think it would be good if the 2nd one were updated so that it can be used either as 

    EEG = fieldtrip2eeglab(hdr, dat, evt) % from ft_read_xxx

or

    EEG = fieldtrip2eeglab(data) % from ft_preprocessing etc.

That will make the instructions for side-by-side use on https://www.fieldtriptoolbox.org/getting_started/eeglab/ simpler.

**Comment by arnodelorme** [comment]
Yes, that sounds like a good idea.

I have update the function fieldtrip2eeglab and pop_fileio. However, there is a problem with events. The function ft_preprocessing does not seem to handle events in continuous data.

Arno
