### ISSUE TITLE
cluster-based permutation of TFR-within subjects experiments-data preparation

### ISSUE THREAD

**Issue by kejinjing89** [fieldtrip/fieldtrip#1864]
I want to ask how to combine the time-frequecncy data obtained by ft_freqanalysis from each subject, within each condition, into one variable such as the GA_TFRFIC and GA_TFRFC dataset mentioned in the tutorial? And the  link cannot open:
  ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/tutorial/cluster_permutation_freq/GA_TFR_orig.mat

Many thanks.

- Please ask the community on the [discussion list](http://www.fieldtriptoolbox.org/discussion_list/) for help on _using_ FieldTrip.
- Please see [here](http://www.fieldtriptoolbox.org/about/) if you want to contact the lead developpers privately.

**Comment by robertoostenveld** [comment]
This is not the right place to ask support for _using_ FieldTrip. Please see https://www.fieldtriptoolbox.org/support/

Also see https://www.fieldtriptoolbox.org/faq/i_am_having_problems_downloading_from_the_ftp_server/ for the question about downloading the mat file.
