### ISSUE TITLE
topoplot_common() only applies the colormap to the 1st figure

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1865]
**Describe the bug**
Hi, when calling topoplot_common() with multiple datasets and setting cfg.colormap, the choice is only applied to the first figure. This is because cfg.colormap is handled before the loop over the datasets (lines 188-202) using ft_colormap(). This also means that the figure is created by ft_colormap() rather than open_figure(), though I can't think of an issue with that.
 
**To Reproduce**
I'm being lazy right now, but I can add a test code if you'd like me to.

**Expected behavior**
The same colormap should be applied to all figures.

**Suggested solution**
1. Have open_figure return a handle, and store the handles in a graphical objects array (lets call it h for now) inside the loop.
2. Move the colormap bit to after the loop over datasets.
3. Use set(h, 'Colormap', cfg.colormap) to apply the colormap to the entire graphical array. This can't be done inside ft_colormap() because it itself relies on colormap() which only takes scalar objects... Alternatively, we could call ft_colormap() in a loop, or change ft_colormap() to rely on set() too.

**Comment by schoffelen** [comment]
Thanks for reporting. I stumbled across this as well, and only then found your reported issue. I went for option 2, after discussing this with Robert

**Comment by NirOfir** [comment]
Thanks!
