### ISSUE TITLE
add citation information

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1889]
> `CITATION.cff` files are plain text files with human- and machine-readable citation information for software (and datasets). Code developers can include them in their repositories to let others know how to correctly cite their software.

We should add this https://citation-file-format.github.io to our main code repository.

**Comment by robertoostenveld** [comment]
We should also check which files get included in the automatic zip release on the ftp server, some `.github` specific files might have to be excluded.

**Comment by schoffelen** [comment]
As far as I can see, the citation file can contain a pointer to a version of the software, should this be dynamically updated for each of the releases? In addition, the citation file can contain a reference to the paper.
