### ISSUE TITLE
Reshape in ft_connectivity_wpli does not work if channel combinations are supplied

### ISSUE THREAD

**Issue by stefanches7** [fieldtrip/fieldtrip#1891]
Hello, I face a following bug: with the 2-dimensional input (Repetitions x Channelcombinations), that is declared possible in the function's comment, reshape in 
https://github.com/fieldtrip/fieldtrip/blob/7cfc41a851c643df8a29ca49afdee6e542d4847a/connectivity/ft_connectivity_wpli.m#L69

throws a "Size vector must have at least two elements" error.

**Comment by schoffelen** [comment]
From the bug report, it is not clear what the use case is that the associated PR tries to resolve. The test_bug1891 does not provide any insights either.

**Comment by stefanches7** [comment]
@schoffelen Right sorry, that would be the use case. I'm happy to include additional information wherever you see fit. I will comment the use case in the PR/test now

**Comment by schoffelen** [comment]
Gotcha, I was confused by the input of a real-valued square matrix in the test function... the meaning of the dimensions would be observation x channelcombinations in this case, where the squareness (implicitly) suggested chan x chan or so.

**Comment by stefanches7** [comment]
Yes it wasn't the luckiest choice :D now I've changed it to 200*400 and added a comment.

**Comment by schoffelen** [comment]
OK, thanks!
