### ISSUE TITLE
ft_rejectartifact fails with input data that consists of overlapping trials

### ISSUE THREAD

**Issue by johalgermissen** [fieldtrip/fieldtrip#1910]
Dear Fieldtrip developers,

I have an issue with ft_rejectartifact which I believe should not occur:

For plotting purposes, I load raw MEG data and epoch them into trials with ft_reprocessing.
These trials overlap (sometimes). I now want to reject certain segments from these trials using ft_rejectartifact.
This works fine with `​cfg.artfctdef.reject = 'nan'`, but crashes with `cfg.artfctdef.reject = 'complete'`.
I guess this is undesired behavior? 

With `​cfg.artfctdef.reject = 'nan'` it works fine:
```    
cfg = [];
cfg.artfctdef.visual.artifact = badSegments; % N x 2 vector with timings of bad segments to reject
cfg.artfctdef.reject = 'nan'; % nan complete
data2 = ft_rejectartifact(cfg, data1); % should be nTrial trials still, just with NaNs
```
gives
```
detected  22 visual artifacts
rejected   0 trials completely
rejected   0 trials partially
filled parts of  32 trials with NaNs
filled parts of   0 trials with zeros
filled parts of   0 trials with a specified value
resulting 200 trials
the call to "ft_rejectartifact" took 1 seconds and required the additional allocation of an estimated 0 MB
```

but with  `cfg.artfctdef.reject = 'complete'`:
```
cfg = [];
cfg.artfctdef.visual.artifact = badSegments; % N x 2 vector with timings of bad segments to reject
cfg.artfctdef.reject = 'complete'; % nan complete
data3 = ft_rejectartifact(cfg, data1);
```
I get the following error message:
```
detected  22 visual artifacts
rejected  32 trials completely
rejected   0 trials partially
filled parts of   0 trials with NaNs
filled parts of   0 trials with zeros
filled parts of   0 trials with a specified value
resulting 168 trials
the input is raw data with 267 channels and 200 trials
Error using ft_fetch_data (line 165)
some of the requested samples occur twice in the data and have conflicting values

Error in ft_redefinetrial (line 284)
    data.trial{iTrl} = ft_fetch_data(dataold, 'header', hdr, 'begsample', begsample(iTrl), 'endsample', endsample(iTrl), 'chanindx',
    1:hdr.nChans, 'skipcheckdata', 1);

Error in ft_rejectartifact (line 579)
    data        = ft_redefinetrial(tmpcfg, data);
```
This error disappears if epochs are shorter and do not overlap.

I am surprised that the function apparently correctly identifies the number of resulting trials (168), but crashes at a fairly late stage because some trials overlap/ "some samples occur twice in the data". I suppose this is due to a warning mechanism in ft_redefinetrial that wants to prevent samples from occurring twice in the data for a different purpose/ a different Fieldtrip function. But in this particular context, shouldn't it be possible to use ft_rejectartifact on overlapping trials?

I hope this is enough information (error occurred with different data sets, so should occur with any data set I presume).
I'm not sure what the best way forward is because I guess you put in this warning mechanism for a reason.
Would it be possible to switch it off for this particular purpose in ft_artifactreject?

Best regards,
Johannes
 
**Environment and versions (please complete the following information):**
 - Operating System: Donders Linux Cluster
 - MATLAB version: 2019b
 - FieldTrip version: /home/common/matlab/fieldtrip/

**Comment by johalgermissen** [comment]
Ah I didn't realize before that `ft_rejectartifact` also works on a `cfg` object...
I'll try that for now 👍

**Comment by schoffelen** [comment]
What's the status of this @johalgermissen, can it be closed?

**Comment by schoffelen** [comment]
Or does it still require action from you/some other people?

**Comment by johalgermissen** [comment]
Hi @schoffelen I think it can be closed, I found my work-around---only thing worth considering might be changing the error message (so it's clear to other users why it doesn't work?).
