### ISSUE TITLE
Bug in ft_trialfun_general with maximum possible trials

### ISSUE THREAD

**Issue by elsyLOL** [fieldtrip/fieldtrip#1912]
When setting cfg.trialdef.ntrials     = inf; defining a trial structure fails. 

**This is the code:**
cfg = [];
    cfg.dataset             = 'EEG\RAW\20211029_ELMERI_Sternberg3.vhdr';
    cfg.trialfun             = 'ft_trialfun_general';
    cfg.trialdef.length = 1;                      % duration in seconds
    cfg.trialdef.ntrials     = inf;                    % Bug in ft_trialfun_general, fixed it on line 114 however, may break other stuff
    cfg                      = ft_definetrial(cfg);
    
    % read the data from disk and segment it into 1-second pieces
    ICAdata           = ft_preprocessing(cfg);
    
**Here is the error that MATLAB outputs:**
evaluating trial function 'ft_trialfun_general'
reading the header from 'EEG\RAW\20211029_ELMERI_Sternberg3.vhdr'
reading the events from 'EEG\RAW\20211029_ELMERI_Sternberg3.vhdr'
Nonfinite endpoints or increment for colon operator in index.

Error in ft_trialfun_general (line 114)
    trl = alltrl(1:cfg.trialdef.ntrials,:);

Error in ft_definetrial (line 199)
    [trl, event] = feval(cfg.trialfun, cfg);

**This is a suggested fix that works, but may break other functionality:**
Edit line 113 to:
if isinteger(cfg.trialdef.ntrials)

**Environment and versions (please complete the following information):**
 - Operating System: [e.g. Windows 10]
 - MATLAB version R2021a
 - FieldTrip version 20211102, seems to affect all versions after the "improvements" of the function in September

/elmeri

**Comment by schoffelen** [comment]
I am confused. You mention that it 'seems to affect all versions after the improvements of the function in September'.
Does this mean that using inf as a value for the input argument used to work before?
If not, why do you think that this should work to begin with?

Currently the default is [], why don't you specify that in your cfg?

**Comment by elsyLOL** [comment]
Thank you for the reply. In previous versions, such as 20210507 that I used before upgrading to the November version setting ntrials as inf defined the maximum number of trials fitting the data. The documentation still refers to this setting (e.g., https://www.fieldtriptoolbox.org/reference/ft_definetrial/). 

Line 29 in ft_definetrial_general implicitly suggests the use as an empty value for this setting. Have no tested with cfg.traildef.ntrial = []; and confirmed that the functionality is now as expected.

May I suggest updating the documentation and maybe stating it more explicitly in the function header that the setting has changed from earlier versions of fieldtrip.

/elmeri

**Comment by schoffelen** [comment]
Well, if previous functionality was that inf was a supported value, then I suggest to change the code, and not the documentation. Please feel free to submit this is as a PR.

My suggestion is to change 

if ~isempty(cfg.trialdef.ntrial)

into 

if isempty(cfg.trialdef.ntrl) && isfinite(cfg.trialdef.ntrl)

**Comment by robertoostenveld** [comment]
It might that I am to blame here for breaking something that worked in the past and that should indeed work. That would have been related to the changes to https://github.com/fieldtrip/fieldtrip/commits/master/trialfun/ft_trialfun_general.m around September. I recall being a bit puzzled about the various combinations that need to be supported for `cfg.trialdef.ntrials` and `cfg.trialdef.length`. The example that @elsyLOL provided should be enough for me to reproduce it and I'll make sure it gets fixed.

**Comment by robertoostenveld** [comment]
I was able to reproduce it, added it to the test script, and fixed it. The fix is now on the master branch and will be included in the next release.

Thanks for reporting!
