### ISSUE TITLE
user defined (but preamble related) cfg options are not always correctly passed on

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1921]
**Describe the bug**
High-level ft functions that recurse into ft_selectdata (or other high level functions) don't take along some of the preamble generated cfg options, causing mayhem downstream

**To Reproduce**

data.trial{1} = nrand(2,4);
data.trial{1} = randn(2,4);
data.trial{2} = randn(2,4);
data.time{1} = 1:4;
data.time{2} = 1:4;
data.label={'a';'b'}

cfg=[];
cfg.trials=1;
cfg.trackmeminfo='no';
cfg.length = 2;
ft_redefinetrial(cfg, data);

**Expected behavior**
Expected behavior is no error

**Screenshots**
<img width="945" alt="Screenshot 2021-11-15 at 19 28 07" src="https://user-images.githubusercontent.com/1517611/141834992-c9f000a2-2467-45a2-af9d-a8c95c930705.png">

**Environment and versions (please complete the following information):**
 - Operating System: Mac and Linux
 - MATLAB version 2021a/2021b
 - FieldTrip version master branch

**Additional context**
I ran across this when profiling ft_qualitycheck, where a lot of time is lost in memtic/memtoc

**Comment by schoffelen** [comment]
I think a straightforward solution is to pass on trackmeminfo etc. as to be kept fields when a temporary cfg is created before calling ft_selectdata (or another high level ft-function).

**Comment by schoffelen** [comment]
Note that if I change the parameter in ft_default, it seems to work fine.

So this raises the questions: are the options trackmem/data/time/ to be configureable by the user on a function-by-function basis, or not?

**Comment by robertoostenveld** [comment]
I would indeed expect these to be configurable on a function-by-function basis. Should these not be treated just like `showcallinfo`? For example in ft_virtualchannel:

```
   tmpcfg   = keepfields(cfg, {'trials', 'tolerance', 'showcallinfo'});
```

**Comment by schoffelen** [comment]
Yes, I think that sweeping the code and adding 'trackmeminfo'/'tracktimeinfo'/'trackdatainfo', would go a long way into the right direction.

However - I tried this in a branch for ft_freqanalysis - and still got issues, possibly due to an extra level of recursion that I missed.

**Comment by robertoostenveld** [comment]
let me have a look at this.
