### ISSUE TITLE
ft_selectdata does not handle selections within cell arrays when cfg.select = 'union'

### ISSUE THREAD

**Issue by JonathanShor** [fieldtrip/fieldtrip#1926]
**Describe the bug**
ft_selectdata fails when `cfg.select = 'union'` and there are selections to be made from cell arrays:

> Check for incorrect argument data type or missing argument in call to function 'isnan'.
> 
> Error in ft_selectdata>makeselection (line 527)
>     if ~isempty(selindx) && all(isnan(selindx))
> 
> Error in ft_selectdata (line 309)
>     if fieldhastime,    varargin{i} = makeselection(varargin{i}, datfield{j}, dimtok, find(strcmp(dimtok,'time')),
>     seltime{i},    avgovertime,     cfg.select, average);  end

**To Reproduce**
1. Generate a ft_preprocessing output `preprocessed` with a cell array `.time` with entries that span [-1 4], with variable length, and several channels defined.
2. `cfg.latency = [-1 2]`
3. `cfg.channel = {some subset of channels}`
4. `cfg.select = 'union'`
5. `clipped = ft_selectdata(cfg, preprocessed)`

**Expected behavior**
I expect to receive all trials back for the channels indicated, with timepoints extending outside latency being excluded. A trial that did not reach either latency boundary would be unchanged. Contrast this with the current `cfg.select = 'intersection'` behavior in which all trials are trimmed to the shortest trial's duration.

**Environment and versions (please complete the following information):**
 - Operating System: Linux
 - MATLAB version R2021a
 - FieldTrip version This is FieldTrip, revision 20210912.

**Additional context**
The 'intersection' code explicitly handles the case that `selindx` is a cell array. I will try to produce a pull request to replicate how it is handled there.

**Comment by JonathanShor** [comment]
Unfortunately, I don't think I'll be able to produce a PR, or at least not now. I'm not familiar enough with the fieldtrip structures to feel confident I'll handle this correctly in all cases.

For example, can I just throw it to `cellmatselect`? I'd guess no, since that's how the 'intersect' case handles it. But I can't see where the actual intersection, i.e. excluding of non-universal data points is happening in that case.

Happy to provide more detail about reproducing this if needed.

**Comment by schoffelen** [comment]
Hi Jonathan, 
For me the following works:

% create some data
data.trial{1} = randn(2,10);
data.time{1}  = -5:4;
data.trial{2} = randn(2,10);
data.time{2}  = -3:6;
data.label    = {'chan01';'chan02'};

cfg = [];
cfg.latency = [-2 1];
cfg.intersect = 'union';
cfg.channel = data.label(1);
datasel = ft_selectdata(cfg, data);

I am using the master branch version of fieldtrip, where it seems that ft_selectdata has changed since the release version you refer to. However, I doubt whether those changes interfere with the functionality that you refer to.

Could you elaborate a bit more on what I need to do to reproduce?

**Comment by JonathanShor** [comment]
> 
> cfg.intersect = 'union';
> 

Is this the argument I should be using? Per the docs, I was using `cfg.select = 'union';`.

I just ran your example, which does indeed work fine. If I remove the intersect field of cfg, and replace it with select, it fails as I report above.

Perhaps I'm just using the wrong cfg field? Tho, https://www.fieldtriptoolbox.org/reference/ft_selectdata/ does not mention intersect as a field option.

**Comment by JonathanShor** [comment]
And just to aid your debugging, unless .select is deprecated, I think there must be a bug. There's a `switch` on line 501; in one case, it tests `selindx` for being a cell array (line 503) and then handles the `all(isnan` test appropriately. In the other case, the 'union' case, it does no such cell array test and immediately throws `selindx` entirely into `isnan` (line 527), as if you could not reach that case with `selindx` being a cell array.

**Comment by schoffelen** [comment]
My bad, Jonathan. Typo on my end. I can confirm your issue. We will work on it

**Comment by schoffelen** [comment]
OK, just as a side remark, the following works (albeit a bit convoluted):

tmp = ft_checkdata(preprocessed, 'datatype', 'timelock');
tmp = ft_selectdata(cfg, tmp);
clipped = ft_checkdata(tmp, 'datatype', 'raw');

Not sure why you'd need the 'unionized' data represented as a raw data structure in the first place.

Anyhow, for now I think you should be on your way, we'll investigate how to address the issue.
