### ISSUE TITLE
data2bids "copy" does not follow symbolic link

### ISSUE THREAD

**Issue by Remi-Gau** [fieldtrip/fieldtrip#1931]
**Describe the bug**

If the source data used as inputs for BIDS conversion is a symbolic link (which is almost always the case when working with datalad datasets) then data2bids copy option only copies the symbolic link and not the data that the link points to.

This ends up creating a BIDS dataset that cannot be dissociated from the source data

**To Reproduce**

Run the demo of data2Bids (https://www.fieldtriptoolbox.org/example/bids_eeg/) but put make sure the input is a datalad dataset.

The output looks something like this

```
├── code
│   └── convert_to_bids.m
├── dataset_description.json
├── participants.tsv
├── sourcedata                        <-- Source data is a datalad dataset
│   ├── .datalad
│   ├── Eeglab_data.set -> .git/annex/objects/MF/wK/MD5E-s3949288--6d5485dc3dde5ac3f7f0d22ae88fc348.set/MD5E-s3949288--6d5485dc3dde5ac3f7f0d22ae88fc348.set
│   ├── .git
│   └── .gitattributes
└── sub-01
    ├── eeg
    │   ├── sub-01_task-changedetection_channels.tsv
    │   ├── sub-01_task-changedetection_eeg.json
    │   ├── sub-01_task-changedetection_eeg.set -> .git/annex/objects/MF/wK/MD5E-s3949288--6d5485dc3dde5ac3f7f0d22ae88fc348.set/MD5E-s3949288--6d5485dc3dde5ac3f7f0d22ae88fc348.set      <-- the .set data points to the annexed data in the source data
    │   └── sub-01_task-changedetection_events.tsv
    └── sub-01_scans.tsv
```

**Expected behavior**

It would be expected that "copy" actually followed the symbolic link so that the raw dataset can live independently of the source data.

**Environment and versions (please complete the following information):**
 - Operating System: linux ubuntu 18.04
 - MATLAB version 2017a
 - FieldTrip version : shasum a8d8623a2

**Comment by robertoostenveld** [comment]
This happens from https://github.com/fieldtrip/fieldtrip/blob/4b50f71105f6bb250018b815bb628e6f3e9de2b6/data2bids.m#L1810 onward and is conditional on the file format (CTF, BrainVision, or otherwise). 

On https://nl.mathworks.com/help/matlab/ref/copyfile.html I read that 

> Starting in R2020a, copyfile('symlinkToMyFile','newFile') copies the target of the symlink (that is, myFile.m) to the destination. In previous releases, on Linux®, copyfile copies the symlink instead.

You mention that you are using 2017a. It should be solved in 2020a onwards.

**Comment by Remi-Gau** [comment]
> You mention that you are using 2017a. It should be solved in 2020a onwards.

good to know. thanks.

For the record in case someone explores the issues archives: another way to solve this for the datalad usecase is to unlock the files to copy with `datalad unlock`
