### ISSUE TITLE
data2bids "SEEGChannelCount" does not include "DBS" channels

### ISSUE THREAD

**Issue by richardkoehler** [fieldtrip/fieldtrip#1935]
**Describe the bug**

When writing BIDS sidecar files for iEEG data, data2bids only counts channels with the type "SEEG" for the field "SEEGChannelCount" in the *ieeg.json sidecar file. However, according to the BIDS specifications, the field "SEEGChannelCount" should include the 

> Number of iEEG depth channels included in the recording (for example, 8).

This includes DBS channels, as these are also depth channels (this is supported by the fact that there is no field "DBSChannelCount" in the BIDS specifications).

See: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#sidecar-json-_ieegjson

The relevant line of code in line 1180 in data2bids.m is:
`ieeg_json.SEEGChannelCount           = sum(strcmpi(hdr.chantype, 'seeg'));`

I replaced this with the following line, which seems to work. However, I am not very familiar with MatLab, so I am sure this is not the best way to code.
`ieeg_json.SEEGChannelCount           = sum(strcmpi(hdr.chantype, 'seeg')) + sum(strcmpi(hdr.chantype, 'dbs'));`

Any thoughts or suggestions on this matter? Thanks in advance!

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10
 - MATLAB version R2029b
 - FieldTrip version 4b50f7110 (should correspond to the "most recent master branch from github)

**Comment by robertoostenveld** [comment]
Thanks, you are correct. I have updated the code.

**Comment by richardkoehler** [comment]
Great, thanks so much!
