### ISSUE TITLE
IRASA and 'fourier' output

### ISSUE THREAD

**Issue by gdemarchi** [fieldtrip/fieldtrip#1937]
Dear all,
(dunno whether it is a bug, feature (request) or what :-) )
I wanted to use the 1/f-cleaned spectrum that comes out from IRASA for further analysis (e.g. beamforming and connectivity, where I would need the 'fourier' output), but I see from the code (l. 67) of  _ft_specest_irasa.m_  that:

`ft_error('The current version ft_specest_irasa outputs ''fractal'' or ''original'' power only. For more information about the update, see https://www.fieldtriptoolbox.org/example/irasa/');
`

Now, the question is whether this limitation has some theoretical reason, or is it just because of the current implementation. I'm tempted to comment out ll. 208 and 235 from _ft_specest_irasa.m_ and see how it runs ( :-) ), but before investing any energy and energy in coding and PR-ing, I wanted to check out with you, especially with @StolkArjen and @schoffelen that were involved in the original implementation, to see whether I'm going to commit a space/time/frequency crime or so ...
If not, I can imagine it would be relatively straightforward to have the options of 'fractal_fourier' and 'original_fourier' as possible outputs, without abs()-ing, that would eventually be used in some subsequent analysis ...

**Comment by schoffelen** [comment]
Hi GP! 
Don't shoot the messenger here, but I think that this limitation is indeed 'theoretically' allowed. I have just cleaned up a bit after @StolkArjen and @ruiliu-psy made the original implementation, so I might be wrong, but:

the irasa estimate is based on combining power estimates across abs(fft(timeseries-tapered-with-a-hanning-window)).^2 after stretching and compressing the sampling rate (i.e. pretending that the sampling was actually slower/faster than the real sampling rate). The idea is that this keeps the 1/f more or less where it is, and the bandlimited peaks start shifting around, and thus smooth out when taking a median across the stretched/compressed segments. I can imagine that this works for the power estimates, but I don't dare to start thinking about the effect of the compression/stretching on the phase estimate of the Fourier coefficients, but my intuition tells me that it is not correct to just pretend that it's allowed...

**Comment by schoffelen** [comment]
This question has been picked up in an off-list e-mail exchange between @gdemarchi e me. It is not really relevant to discuss further here, hence closing.
