### ISSUE TITLE
A parameter missing for bst fooof

### ISSUE THREAD

**Issue by vlitvak** [fieldtrip/fieldtrip#1939]
Running 

 cfg               = [];
cfg.foilim        = [1 45];
cfg.pad           = 4;
cfg.tapsmofrq     = 2;
cfg.method        = 'mtmfft';
cfg.output        = 'fooof_aperiodic';
fractal = ft_freqanalysis(cfg, data);

with the latest Brainstorm from GiHub I get

Unrecognized field name "border_threshold".

Error in process_fooof>FOOOF_matlab (line 257)
            opt.peak_width_limits/2, opt.proximity_threshold, opt.border_threshold, opt.peak_type, opt.guess_weight,hOT);

Error in process_fooof (line 30)
eval(macro_method);

Error in ft_freqanalysis (line 1033)
    [fs, fg] = process_fooof('FOOOF_matlab', TF, freq.freq, opt, hasOptimTools);

It seems 'border_threshold' is something new they added. When adding it around line 1015 in ft_freqanalysis with the default value of 1 (as in BST code) it seems to work.

**Comment by schoffelen** [comment]
Thanks for reporting Vladimir! I also came across something similar recently. I might have missed this particular option. I'll check.

BW, JM

**Comment by schoffelen** [comment]
Found it. It was solved here: 

https://github.com/fieldtrip/fieldtrip/commit/248a99ccdfd5d73162c7de4ed0e0ba5a791844d4#diff-0e05dbfae447c9cfe8d3baed2ffb6e2bfd06c73e4debcd34e32d526743fa43a3

I guess that if you upgrade to the latest Fieldtrip as well, it should work :)

**Comment by vlitvak** [comment]
I checked the code on GitHub by eye but might have missed it.
