### ISSUE TITLE
'original events' do not align with the time-shifted and appended data

### ISSUE THREAD

**Issue by YangCao-1** [fieldtrip/fieldtrip#1940]
Hi ,
**Describe the bug**
When I use ft_databrowser to show the data trial by trial from **ft_appenddata** and with **self-constructed .sampleinfo** (i.e. reconstruct the .sampleinfo by assuming that the trials are consecutive segments of a continuous recording ),
the original events do not align with the time-shifted and appended data. 

**To Reproduce**
Backgroud information:
Each participant has 3 blocks ( 120 trials for each block). Each block has a .eeg, a .vhdr, and a .vmrk file.
After ft_definetrial for each block, we got data1, data2, data3 for the three blocks respectively.
(The events are stored in the 1st column of .trialinfo)

**1. Append data**
I appended the 3 blocks together for each participant as one file:

`cfg=[];
alldata=ft_appenddata(cfg, data1, data2, data3)`

**2. Reconstruct the .sampleinfo**  
`alldata=removefields(alldata,{'sampleinfo'});
alldata.sampleinfo=nan(size(alldata.trialinfo,1),2);
sps = 1:length(alldata.trialinfo)* length(alldata.time{1});
duration = length(alldata.time{1});
first = 1;
for s = 1:length(alldata.trialinfo) 
alldata.sampleinfo(s,:) = [sps(first) sps(duration)];
first = duration + 1;
duration = duration+length(alldata.time{1});
end`

**3. browse data using ft_databrowser**
`cfg=[];
cfg.continuous='no';
cfg.preproc.demean        ='yes';
cfg.preproc.baselinewindow = [-0.4 0];
cfg=ft_databrowser(cfg,alldata);`

**4. See error**
The time location of the event ( i.e. the  'red line' , Stimulus=S244) is not at 0 s in the X-axis.
![image](https://user-images.githubusercontent.com/65195603/145853419-625501aa-3c77-4d90-9895-bf2f48dfcaac.png)

**Expected behavior**
The original events align with the time-shifted and appended data.

**Environment and versions (please complete the following information):**
DCCN cluster

**Comment by schoffelen** [comment]
1) you describe that you hand-crafted a sampleinfo, which probably does not coincide with how the original segments relate to the original recording. So there is no reason to expect that ft_databrowser is going to perform according to your expectations.
2) ft_databrowsers somehow extracts 'magically' the events from the data structure, and it's unclear where it's derived from, it is probably derived from one of the data1/2/3.cfg fields. The events are expressed in samples relative to the recording, and ft_databrowser assumes that the sampleinfo is consistent with that sampling. There is no guarantee that this is the case in your data.

**Comment by YangCao-1** [comment]
Dear Jan-Mathijs, I wanted to apologize that I may have not expressed it clearly. 
I copied Robert's message for this issue here to add more background. 

![image](https://user-images.githubusercontent.com/65195603/145987425-e103beb0-816e-4f87-b1f6-44514c6471b0.png)

For here, the link is
https://github.com/fieldtrip/fieldtrip/blob/4b50f71105f6bb250018b815bb628e6f3e9de2b6/ft_databrowser.m#L356

I was following Robert's suggestion, but please close this issue if it is irrelevant.

**Comment by robertoostenveld** [comment]
it would be good to improve the detection of data in ft_databrowser for which the `data.cfg.previous.previous...event` should not be used (as in this case).

**Comment by schoffelen** [comment]
what is the status of this @YangCao-1 ? Does it still require action, or can it be closed?

**Comment by YangCao-1** [comment]
closed, please.

Thank you!

Yang
________________________________
