### ISSUE TITLE
How can I use ft_prepare_mesh with tetrahedral element?

### ISSUE THREAD

**Issue by NasirehDayarian** [fieldtrip/fieldtrip#1943]
Hi 
I am trying to generate a tetrahedron mesh with ft_prepare_mesh.  I write this codes

cfg=[];
cfg.tissue={'brain','skull','scalp'};
cfg.method='tetrahedral';
cfg.numvertices = [300 200 100];
bnd=ft_prepare_mesh(cfg,segmentedmri);

but when run, the following error occurs:

Error using cgalv2m (line 87)
output file was not found, failure was encountered when running command:
\n"...\Software\FieldTrip\fieldtrip-master\external\iso2mesh\bin\cgalmesh.exe"
"C:\Users\...\AppData\Local\Temp\iso2mesh-...\pre_cgalmesh.inr" C:\Users\dayarian.n\AppData\Local\Temp\iso2mesh-...\post_cgalmesh.mesh" 
30.000000 1.000000 0.500000 3.000000 1.000000 1648335518

I cannot fix it.  I appriciate it if any one helps me.
Nasireh

**Comment by schoffelen** [comment]
Hi Nasireh, this is not the right location to ask this type of questions. It would be better to ask it on the fieldtrip discussion list. If you haven't subscribed yet, here's a link with more information: https://www.fieldtriptoolbox.org/discussion_list/

I am not a windows user myself, so I cannot comment on this problem, but there are many people subscribed to the discussion forum, and some of them might be able to provide some pointers.

Please also have a look at this page, in formulating your question in general: https://www.fieldtriptoolbox.org/faq/how_to_ask_good_questions_to_the_community/
