### ISSUE TITLE
Problem reading neuromag data - fixed by changing ft_read_event

### ISSUE THREAD

**Issue by SchollJ** [fieldtrip/fieldtrip#1948]
Dear Fieldtrip team,

Fieldtrip version: 20211203

I've collected data (just diode check for now) on a Neuromag scanner (OHBA, Oxford). I tried to read in the events with this code:
addpath('[MyPath]/MATLAB/fieldtrip-20211203')
cfg = [];
cfg.dataset ='/MYPATH/Pilot_diode/MEG/data_1.fif'; 
cfg.trialdef.eventtype = 'STI101'; % define channel for events
dummy                   = ft_definetrial(cfg); 

This gave me the error that no events were detected. I've followed through the scripts called by ft_definetrial and noticed that in ft_read_event, within
 case {'neuromag_fif','neuromag_mne',neuromag_mex'}
there was a problem detecting the triggers:
all of these were empty:
binaryindx = find(strcmp(ft_chantype(hdr), 'digital trigger'));
      otherindx  = find(strcmp(ft_chantype(hdr), 'other trigger'));
      analogindx = find(strcmp(ft_chantype(hdr), 'analog trigger'));

And as a result, binary indices that were not in my data got defined (see what I've commented out below). I've replaced this by telling the script to look for STI101 and this now works.
if isempty(binaryindx) && isempty(analogindx) && isempty(otherindx)
        % in case of problems with older systems and MNE reader we use a predefined set of channel names
        %binary     = {'STI 014', 'STI 015', 'STI 016'};
        %binaryindx = match_str(hdr.label, binary);
        otherindx=match_str(hdr.label,'STI101');
      end

Was there something else I somehow missed? As I realise making my own changes to the field trip toolbox is not good as it will be gone when I get the newer version at some point.

Best wishes
Jacquie

**Comment by matsvanes** [comment]
Hi Jacquie,

I tried to reproduce your error with data from OHBA and using the most recent FieldTrip version (eaaabf8ff), but I couldn't reproduce it. I believe at least `ft_read_event` is equivalent with your version of FT, but I could try the same with the exact version of fieldtrip that you're currently using in case there are other critical functions that are different. 
As Jan-Mathijs asked, have you tried this on different data? In any case, if you keep having this error, feel free to drop me a line and I can look into it more (i.e. with your version of FT and using your data).

**Comment by SchollJ** [comment]
Hi Mats,
thank you very much!! I'm going to get some actual MEG participant data,
rather than the diode check. I'm wondering whether anything might have been
weird about the diode check to cause it (maybe that there was no MEG data,
but only the diode data, plugged in as an EEG/eye movement sensor?). I'll
let you know what I find.
Best wishes
Jacquie

**Comment by schoffelen** [comment]
What is the status of this? @SchollJ I believe that this one can be closed. Please feel free to reopen if you think that the issue is due to something on our end, and if it has not yet been adequately resolved.
