### ISSUE TITLE
I have a problem for reading an EEG data by using FieldTrip Toolbox. Any suggestion?

### ISSUE THREAD

**Issue by elf-tly** [fieldtrip/fieldtrip#1951]
I try to read a segmented EEG data exported from Brainvision Analyzer program by using the last version of FieldTrip Toolbox. However something goes wrong and trials (except the last one) cannot be read, returns empty. It throws a warning message “Warning: endsample is before begsample, returning empty data” for the unread trials and then reads the last trial.

Actually, I did not have such a problem with the older version and I could read the data without any problem. I use Matlab R2018b which is suitable version for FiledTrip Toolbox.

Is there anyone who have the same problem or have any suggestion?

**Comment by schoffelen** [comment]
Hi elf-tly I think it would be best to ask your question on the discussion forum: https://www.fieldtriptoolbox.org/discussion_list/

The github issues are not read by many people. 

I am not a brainvision user myself so cannot comment at this point.

**Comment by elf-tly** [comment]
Hello Mr. Schoffelen,

Actually it is not a problem related with Brainvision, it is a tecnical problem with FieldTrip last version I guess, because I tried 2 versions one is the last and the other one is a bir older fieldtrip-20180306. With the older one, I can read whole the data without any problem however with the new one trials cannot be read and return null, it just read the las trial. I guest there is a loop problem. What do you think about it?

**Comment by schoffelen** [comment]
I think two things: please escalate this to the discussion list, and put a breakpoint in the code, so that you can investigate what is going on with this particular dataset. Also, I would recommend you to check other datasets, to investigate whether this is a code problem as such, or an interaction between code and a specific dataset.
