### ISSUE TITLE
MVPA-Light Toolbox Integration Is Not Working

### ISSUE THREAD

**Issue by batiyilmaz** [fieldtrip/fieldtrip#1953]
Dear FieldTrip developers,

I've been trying to install the MVPA-Light toolbox for days,  I'm trying to use the toolbox integrated with FieldTrip, however, although I've tried everything and followed each step in the instructions, I'm still getting these errors in MATLAB while trying to run this tutorial: https://www.fieldtriptoolbox.org/tutorial/mvpa_light/

When I call ft_statistics_mvpa I get this error:
"Error using ft_hastoolbox
the MVPA-LIGHT toolbox is not installed, see https://github.com/treder/MVPA-Light

Error in ft_statistics_mvpa (line 166)
ft_hastoolbox('mvpa-light', 1);"

I asked the developer of the toolbox Matthias Treder and he suspected that the error might be related to FieldTrip. Can you please help me with resolving this issue? I'm a Mac user and my MATLAB version is R2022a. My FieldTrip version says "This is FieldTrip, revision f7adf3ab0." when I type "ft_version"

Thank you for your time and help in advance.

**Comment by robertoostenveld** [comment]
Hi Bati, 

In [ft_hastoolbox](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_hastoolbox.m) on line 590 the toolbox is added using the startup script from mvpa-light. Apparently that does not result in the expected path settings. However, that section only runs in case the toolbox is not detected, which uses the dependencies listed on line 238 and the `is_present` function (which checks those two functions). So what might happen is that the `startup_MVPA_Light` is executed but subsequently the two dependencies are still not on the path.

In the MATLAB editor you can add a breakpoint for example on line 469 (where `status` will be false) and then you can step through the code, one line at a time. See https://nl.mathworks.com/help/matlab/matlab_prog/debugging-process-and-features.html#responsive_offcanvas for some background. If you step through the code, you can see precisely what happens and where it fails.

**Comment by batiyilmaz** [comment]
Hi Robert,

Thank you for your reply. As I'm not very experienced in MATLAB, can I ask whether this problem can be solvable by following the steps you described? Should I add some lines to my startup file to include those dependencies listed on line 238?

**Comment by schoffelen** [comment]
As dicussed extensively with Matthias, MVPA-light is not included as an external toolbox in fieldtrip. In addition MVPA-light has its own path management function. These two aspects make the automatic handling of paths as per ft_hastoolbox a bit shaky.

This should work: 
- get started with MVPA-light as per the instructions provided by Matthias, i.e. download it yourself, add it to your path and run the MVPA light startup script. 
- once the above is done correctly, fieldtrip should be able to detect the required functionality automatically. 

One note: Matthias has been reorganizing his toolbox recently, with some changes in function names etc. The old version of ft_hastoolbox depended on those old function names. I am pretty sure that I updated ft_hatoolbox recently to reflect the external changes of MVPA, but the off chance is that there might be a genuine interaction with FieldTrip

**Comment by batiyilmaz** [comment]
Hi all, I made sure that MVPA-Light is working as a stand-alone toolbox successfully and I managed to fully follow its classification tutorial on its own repository. However, whenever I try to integrate it with FieldTrip, it yields this same problem. Regarding the recent update to ft_hastoolbox, should I update my FieldTrip to the latest version? It's still not working. Thank you in advance.

**Comment by schoffelen** [comment]
Something went wrong with the synchronization of the code. ft_hastoolbox is still searching for a function mv_crossvalidate that does not exist anymore since @treder changed the toolbox on his end (without notifying me). These things happen, when there are dependencies like this. I will change it (once more) in the code base, but this will not be available to you right away (the code change will only become available in the release version of FieldTrip once a series of checks have been successfully performed). I suggest that you create an empty m-file in the MVPA-light toolbox, called mv_crossvalidate.m. Ft_hastoolbox checks for the existence of this file on your matlab path (not whether it's funtional), so it should work for you as a workaround for the time being (assuming that the other changes that Matthias made to the code did not break the interaction of the MVPA toolbox with Fieldtrip).

**Comment by batiyilmaz** [comment]
Hi @schoffelen,

Thank you for the update. Should I create a new file called "mv_crossvalidate.m" inside of the MVPA-Light toolbox folder to make the integration work for now?

**Comment by schoffelen** [comment]
Closing for now, feel free to re-open if needed

**Comment by treder** [comment]
Not I didn't change the interface. I removed `mv_crossvalidate` from `ft_statistics_mvpa` a year ago when we did the overhaul of the interface. I suspect at the time we didn't adapt `ft_hasttoolbox` accordingly. `mv_crossvalidate` has not been in use for over a year, I just recently removed the deprecated code.

**Comment by schoffelen** [comment]
All good Matthias @treder, all covered now.
BW, JM

**Comment by treder** [comment]
OK thanks @schoffelen .
