### ISSUE TITLE
Large logo printed in ft_defaults is not ideal for the embedded case (e.g. in  SPM)

### ISSUE THREAD

**Issue by vlitvak** [fieldtrip/fieldtrip#1954]
The FT logo printed in the command line every time ft_defaults is run (https://github.com/fieldtrip/fieldtrip/pull/1894) is not ideal for the embedded case (e.g. in SPM) as there are two logos in a raw with some messages in the middle which is not very aesthetic. We could either add an option to suppress it or print a shorter version.

**Comment by schoffelen** [comment]
Would it work if we just make the logo printing conditional on whether ft_defaults is called from a function, or not? In case it's called from a function (as I assume that this is the case for the large majority of under-the-hood calls from SPM), the logo will not be plotted.

**Comment by robertoostenveld** [comment]
Let me tag @schoffelen and @gllmflndn on this.

In principle open source (at least GPL) software does not require advertising its original source or license agreements. But giving (and receiving) credit for academic open source software is important, and for that the users have to be aware that they are using a significant piece of some software - even when that software is used "under the hood".  

FieldTrip never printed something explicitly, until [in November](https://github.com/fieldtrip/fieldtrip/pull/1918) we implemented the ascii art FieldTrip logo, inspired by SPM. Prior to that FieldTrip already included one-time printed licenses or acknowledgments for these: 

````
mac036> find /Users/roboos/matlab/fieldtrip/external -name \*license*.m 
./mne/mne_license.m
./artinis/artinis_license.m
./duneuro/duneuro_license.m
./openmeeg/openmeeg_license.m
````

These are handled in https://github.com/fieldtrip/fieldtrip/blob/f7adf3ab06bb0955656b6175cb849b8cf03b5c7b/utilities/ft_hastoolbox.m#L482

I think that some smart handling of the FieldTrip license or logo could be implemented as well. I would not mind if SPM remains quiet on FT, or if something small is printed, then we should also do that for SPM being used in FieldTrip.

**Comment by robertoostenveld** [comment]
@arnodelorme perhaps this is relevant for you and EEGLAB as well. Please see above and share your thoughts...

**Comment by arnodelorme** [comment]
Yes, I would tend to agree with Vlad. It can be distracting to have the logo show up every time and sometimes multiple times for a single command.

**Comment by gllmflndn** [comment]
Adding an option via the `ft_default` variable to disable the display of the new message would be great.

I also agree with you @robertoostenveld on the importance of giving credit where it's due. We should probably expand the section that mentions FieldTrip on the [SPM website](https://www.fil.ion.ucl.ac.uk/spm/software/spm12/#Collaborations). I'm open to any suggestion on how best to proceed.
