### ISSUE TITLE
data2bids scans.tsv unix support

### ISSUE THREAD

**Issue by richardkoehler** [fieldtrip/fieldtrip#1957]
**Describe the bug**
Using data2bids on a windows system writes out "filenames" in the scans.tsv files with a backslash, e.g.:
> filename
> ieeg\sub-001_ses-01_task-Rest_run-01_ieeg.vhdr

This can lead to path issues when sharing data and reading in scans.tsv in a unix system. To my knowledge, the forward slash "/" works on both windows and unix systems, so we could simply always write out filenames with a forward slash, e.g.:
> filename
> ieeg/sub-001_ses-01_task-Rest_run-01_ieeg.vhdr

I replaced the following statement in line 2034:
`  this.filename = {fullfile(datatype2dirname(cfg.datatype), [f x])};`

with:
`  path = fullfile(datatype2dirname(cfg.datatype), [f x]);
  path(strfind(path,'\')) = '/';
  this.filename = {path};`

I apologize in advance because I am everything but a matlab expert, but this solution seems to work for me.
Thanks in advance for your input!

**Environment and versions (please complete the following information):**
 - Operating System: Windows 11
 - MATLAB version R2020b
 - FieldTrip version  "most recent master branch from github"

**Comment by robertoostenveld** [comment]
Some background: the `fullfile` function appends the pieces that comprise the full path and filename and should - depending on the platform - insert the right slash in between (either `/' or '\'). There is also the `filesep` function that can be used in MATLAB. 

Your solution works, but I would rather get to the source of the problem and solve it there. Can you try to find specifically where the wrong slash comes from? Could it be that in `cfg.outputfile` you have specified the wrong slashes yourself?

**Comment by richardkoehler** [comment]
Thanks for the quick reply!

Maybe I wasn't precise enough about my issue. So the `data2bids` (and `fullfile`) function does exactly what is supposed to: I work on a windows computer, so it inserts a `\` into the `filename` of the `scans.tsv`.
However, if I now share the dataset with someone using a unix-based system, they might run into an error when reading the `scans.tsv`, as unix only supports `/` and not `\`.

I actually didn't use `cfg.outputfile`, I specified the directory in `cfg.bidsroot`. I tried switching it from 'C:\Users\..\BIDS_rawdata' to 'C:/Users/../BIDS_rawdata', but that didn't solve the problem. I assume `fullfile` automatically converts the `/` to `\`, since I am on windows. 
Is there anything else I could try?

**Comment by robertoostenveld** [comment]
ah, so we should look up the requirements on the direction of the slashes in the scans.tsv!

Have you searched the BIDS specification, neurostars, or elsewhere online for the requirements? If that requirement specifies that `scans.tsv` should only have forward slashes (which I suspect), then data2bids running in MATLAB on windows should replace the backslashes with forward slashes.

The consequence would also be that someone who reads the scans.tsv on windows is required to replace the `/` with a `\` to make valid filenames.

**Comment by richardkoehler** [comment]
> The consequence would also be that someone who reads the scans.tsv on windows is required to replace the / with a \ to make valid filenames.

I hope I am not wrong here, but I think this might actually not be the case. People seem to suggest that Windows can handle both / and \ operators for paths. I also tested it on my machine and both /, \ and a mix of them seem to work.

Yes, I have looked into the BIDS specification (this issue wasn't addressed before) and actually a PR for BIDS Version 1.7.0 has just been approved yesterday:
https://github.com/bids-standard/bids-specification/pull/867 
So likely, starting from BIDS Version 1.7.0, the BIDS specification will state the following:

> ## Specification of paths
> 
> Several metadata fields in BIDS require the specification of paths,
> that is, a string of characters used to uniquely identify a location in a directory structure.
> For example the `IntendedFor` or `AssociatedEmptyroom` metadata fields.
> 
> Throughout BIDS all such paths MUST be specified using the slash character (`/`),
> regardless of the operating system that a particular dataset is curated on or used on.
> 
> Paths SHOULD NOT be absolute local paths,
> because these might break when a dataset is used on a different machine.
> It is RECOMMENDED that all paths specified in a BIDS dataset are relative paths,
> as specified in the respective descriptions of metadata fields that require the use of paths.

As it seems this change will be made for the next BIDS Version, we could either wait until then, or prepare a PR now, whichever you think is more prudent.

**Comment by sappelhoff** [comment]
> Have you searched the BIDS specification, neurostars, or elsewhere online for the requirements? If that requirement specifies that scans.tsv should only have forward slashes (which I suspect), then data2bids running in MATLAB on windows should replace the backslashes with forward slashes.

In the BIDS spec, it was (until now) very implicitly and inconsistently documented to use forward slashes for paths, see for example:

- [IntendedFor for MRI](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#using-intendedfor-metadata)
- [AssociatedEmptyRoom for MEG](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#sidecar-json-_megjson)
- [IntendedFor for MEG](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson)

The PR https://github.com/bids-standard/bids-specification/pull/867 intends to make this explicit and clear (based on one of your comments some months ago actually @robertoostenveld :slightly_smiling_face:). I think forward slashes work everywhere for paths, so we should consistently use those (correct me if I am wrong, please).

**Comment by robertoostenveld** [comment]
I suggest to improve data2bids straight away and not make it conditional on BIDS versions, as data2bids has not yet been updated to handle PET (1.6.0) or microscopy (1.7.0) data anyway.

**Comment by richardkoehler** [comment]
Okay, well I am happy to work on a PR, but my matlab skills are close to zero. Would the code I posted above be the way to move forward or do you see a better approach?
```
path = fullfile(datatype2dirname(cfg.datatype), [f x]); 
path(strfind(path,'\')) = '/'; 
this.filename = {path};
```
I borrowed this solution from here: https://de.mathworks.com/matlabcentral/answers/117110-dealing-with-and-windows-vs-unix-for-path-definition#answer_418108
