### ISSUE TITLE
make a function that returns the affine coordinate transformations, like ras2als and ctf2acpc 

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#1976]
Is there a conceivable objection against adding a second optional output to ft_convert_coordsys, returning the (affine-) transformation (if method==0), so that it can be re-used outside de function?

Context: now that this function can be very easily applied to switch between generic coordinate systems (e.g. 'lip' 2 'ras' and vice versa), I would find it useful to lay my hands on the corresponding transformation matrices...

What do you think, @robertoostenveld ?

**Comment by schoffelen** [comment]
Note that there seems to be a inconsistency in the order of the inputs into transform_general (line 207 in ft_convert_coordsys). The sub-function behaves as it should, but the variable naming (+docu) suggests that the first/second input arguments are 'from' and 'to'. It seems to be the other way around

**Comment by robertoostenveld** [comment]
@schoffelen and I discussed this and came to the conclusion that moving line 124-362 from `ft_convert_coordsys` to a new function `utilities/ft_affinecoordinates` would be clean, resolve the specific use case, and would also align with the existing `utilities/ft_headcoordinates`. 

I will prepare a PR for this
