### ISSUE TITLE
accepting and returning filter states from ft_preproc_Xfilter

### ISSUE THREAD

**Issue by tierneytim** [fieldtrip/fieldtrip#1981]
Hi, 

We would like to speed up the [SPM filtering](https://github.com/spm/spm/blob/main/spm_eeg_filter.m)  (which relies on calling the fieldtrip filters) by filtering data in temporal chunks rather than channel by channel. This is to avoid accessing non-contiguous memory in the memory-mapped MEEG objects, which can come at a substantial performance burden. 

To achieve this we would need to return the internal filter [states](https://uk.mathworks.com/help/matlab/ref/filter.html#buag1h6-4)  from the filter.m function. 

Can the fieldtrip ft_preproc_Xfilter.m funnctions as well as [filter_with_correction.m](https://github.com/fieldtrip/fieldtrip/blob/master/preproc/private/filter_with_correction.m#L65) be adapted to return  and accept  filter states?

@vlitvak

**Comment by tierneytim** [comment]
Hi @schoffelen, @vlitvak 

Thank you for the thoughtful reply.  
In respsonse to your questions:

- _What should the filter state be if a causal filter is requested, or a 'onepass-reverse' filter?_

the first time the function is called the user would pass zeros and after that whatever matrix was returned by the previous function call. As such I don't think there is a difference between how forward and reverse filters are called, only in how the input data is handled. 

- _How does the code know about the direction of the filter for a given filter state?_
The code does not, that would be a user responsibility

- _But also, how does the code know that it is 'allowed' to apply a given state of the filter to a next chunk of data (see my first remark)?_
again it doesn't, it would be the user responsibility

- _And isn't there going to be an issue with the fact that the ft_preproc_filter functions demean the data prior to filtering, which means the introduction of a potential discontinuity at the edges, even if the data were temporally contiguous?_
I think this is a much bigger issue that I had not considered. the same dc correction would need to apply to every chunk to keep the states valid. 

All these things considered I am inclined to agree with you that 'this knowledge is beyond the philosophy of those functions.'.  We just were hoping we could keep calling the fieldtrip code within SPM and not start reinventing wheels. 
If no one else has any other insights or workarounds I would consider this issue closed.

**Comment by robertoostenveld** [comment]
> As such I don't think there is a difference between how forward and reverse filters are called

Well, if you call a reverse filter repeatedly on separate chunks you would have to go backwards in time, and the filter state represents the state just prior to the first sample, not the state after the last sample. I read JMs comment as "to interpret the filter state properly, you need to know a bit more than just the vector (or matrix) with numbers".

I don't think we should close the issue yet, it is interesting to consider code improvements and valuable to not reinvent wheels.

Have you already looked at [ft_preproc_online_filter_init.m](https://github.com/fieldtrip/fieldtrip/blob/master/preproc/ft_preproc_online_filter_init.m) and [ft_preproc_online_filter_apply.m](https://github.com/fieldtrip/fieldtrip/blob/master/preproc/ft_preproc_online_filter_apply.m)? Those were implemented for realtime applications where data arrives in chunks  and for example used [here](https://github.com/fieldtrip/fieldtrip/blob/master/realtime/example/ft_realtime_signalviewer.m).

**Comment by robertoostenveld** [comment]
if you apply a onepass-reverse filter, the data gets flipped, filtered, and flipped back. The first sample them becomes the last and vice versa. See https://github.com/fieldtrip/fieldtrip/blob/7cd6e1bf1069d46954a0bd4bafff98cf02b0feb0/preproc/private/filter_with_correction.m#L66

That also means that the filter state applies to just "after" the (flipped) first sample of the just-filtered chunk and should be applied to the "next" chunk which is the one _preceding_ (in chronological time) the one that was just filtered, not the one that follows. If you want to know more about the one and two-pass filters, see https://doi.org/10.1109/TASSP.1974.1162602. It is from 1974, I am not sure though whether that is the original paper. The `onepass-reverse` will in practice not be used  often, it is mainly to evaluate the potential effect of a filter. But the two-pass filter is very common (and default) to achieve a neutral phase response.  

In `filter_with_correction` you can see the same consideration applied to the temporary offset removal using the first sample for forward filters or the last sample for reverse filters. Oh... I now see that the `onepass-zerophase` and `onepass-reverse-zerophase` are not consistent. I'll note that down in a separate issue.

The online versions of the filtering are explicitly defined and implemented for one pass (i.e. causal filters) and should only be applied for continuous subsequent chunks. That is a much simpler case than the offline 
 
**important insight**: I now realize that for a two-pass filter I would have no idea to represent state. This might require two states: one for the data prior to, and one for the data following the chunk. Actually, I don't think it would be possible to implement a two-pass filter chunk-wise. That means that you are limited to one-pass forward (i.e. causal) filters as implemented in the online filter functions.

**Comment by tierneytim** [comment]
I have already written some test code that implements this, as you describe, on real data.  It filters the whole dataset forwards in chunks. Then states are set to zero and the filter is applied backward in chunks. This is feasible and it produces relative errors of 1e-8 when compared to the twophase filter working on the entire dataset.

**Comment by robertoostenveld** [comment]
so that means that you have to store the half-filtered chunks in between, right?

**Comment by tierneytim** [comment]
yes, they are saved back to the memory-mapped object. Even with this inefficiency, the performance gain is notable (on my pc) and allows for datasets too large for RAM to be processed easily.

**Comment by robertoostenveld** [comment]
I think the use-case is too narrow to make any changes to FieldTrip low-level functions. The code that you have can be adjusted to use `ft_preproc_online_filter_apply`, which is as close as we can keep our respective code-bases together. The looping over chunks with the reading/writing remains SPM specific. 

If you agree, I will close this issue.
