### ISSUE TITLE
the onepass-zerophase and onepass-reverse-zerophase filter are not consistent w.r.t. offset removal

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1985]
this was identified in #1981 

In https://github.com/fieldtrip/fieldtrip/blob/7cd6e1bf1069d46954a0bd4bafff98cf02b0feb0/preproc/private/filter_with_correction.m#L82
the offset is not removed, whereas in
https://github.com/fieldtrip/fieldtrip/blob/7cd6e1bf1069d46954a0bd4bafff98cf02b0feb0/preproc/private/filter_with_correction.m#L84
it is removed. To make it consistent I suggest to remove it for `onepass-reverse-zerophase`.

@Spaak I see you committed this originally in 2014. Do you agree?

**Comment by Spaak** [comment]
Yes, I agree. I think the original implementation was by Andreas Widmann, fwiw, I merely committed without any real authoring.
