### ISSUE TITLE
add support in ft_read_headshape for the .jmesh format

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1992]
See http://openjdata.org/ and #1991

As discussed with @fangq

**Comment by robertoostenveld** [comment]
this probably requires `fieldtrip/external/jsonlab` to be updated

**Comment by schoffelen** [comment]
Hi @fangq what is the status of this. Is anything needed on our end to push this forward?

**Comment by fangq** [comment]
@schoffelen and @robertoostenveld, please see my above PR. This lightweight patch allows fieldtrip to read and write basic JMesh files.

The JMesh spec supports various shape and mesh constructs, but I assume the mesh support in fieldtrip is largely focused on triangular surfaces. So, similarly to my JMesh patch for nibabel (nipy/nibabel#1114), I focused on extracting the below fields
* `MeshVertex3/MeshNode` -> `shape.pos`
* `MeshTri3/MeshSurf` -> `shape.tri`
* `MeshTet4/MeshElem` -> `shape.tet`

in addition, I created 4 JMesh specific fields - if there are more appropriate existing fields, I will be happy to rename
* `_DataInfo_` -> shape.info
* `shape.poslabel` to store nodal labels
* `shape.trilabel` to store triangle labels
* `shape.tetlabel` to store tet labels

a test unit was added and it runs fine on various MATLAB versions, with the exception of 2022b - you will need to update JSONLab to include this [JSONLab commit](https://github.com/fangq/jsonlab/commit/0448eb1ead7978cb90d2d251fd25f9f3652858b4) to avoid an error.

**Comment by schoffelen** [comment]
Thanks @fangq for you swift action! We'll look at it ASAP. Currently, there's another ft_read_headshape related PR on its way https://github.com/fieldtrip/fieldtrip/pull/2183 , and I am not keen on resolving the merge conflicts... I will check what the most painless order of merging is going to be. Conceptually, the other file format has a similar feature as the jmesh file format, in that gmsh meshes can also contain per-node data. It would be good to represent that additional information in a consistent way in the fieldtrip structure.

**Comment by fangq** [comment]
@schoffelen, with a quick look at #2183, I don't see any potential conflicts (they are under separate `case` and `elseif`), and git should merge smoothly.

from reading the code you are writing, I wonder how comprehensive you want to transencode mesh data to your shape struct? 

for example, JMesh mesh data element can have [various properties](https://github.com/NeuroJSON/jmesh/blob/master/JMesh_specification.md#common-geometry-properties), such as `Normal`, `Color`, `Tag`, `Value` etc. I see you are also trying to explicitly translate various `elementdata` from gmsh. do you want to do the same for JMesh?

if so, a pain-less way to losslessly carry all JMesh data (including non-transencoded fields) is to define `shape.raw` to carry a copy of the entire parsed struct by `loadjson` or `loadbj`, like I did in my [nibabel patch or reading](https://github.com/nipy/nibabel/pull/1114/files#diff-de0d4daf1502d7fb250c9cd41c326c18617a66bb92bc7eb3478301f39cadab80R122) and [writing](https://github.com/nipy/nibabel/pull/1114/files#diff-de0d4daf1502d7fb250c9cd41c326c18617a66bb92bc7eb3478301f39cadab80R206-R221). It should only take a few lines. Let me know if you want me to add that.

also, I am happy to translate more mesh data to shape struct, although I am not entirely sure about the subfield formats, for example, is `shape.hex` a 8-column integer array? if so, I can map [MeshHex8](https://github.com/NeuroJSON/jmesh/blob/master/JMesh_specification.md#meshhex8) to it if present. For `shape.pos`, is it required to be 3-column or can be different sizes?

**Comment by schoffelen** [comment]
hi @fangq thanks for checking! And don't worry about any potential merge conflicts, that will be on our desk. Right now, the main reason for supporting gmsh is to build in support for simnibs. I still need to think a bit about striking the right balance, but to some extent the low-level reading function read_gmsh_binary may be as generic as possible, and the intermediate fieldtrip readers ft_read_headhsape, possibly ft_read_headmodel only harvest the necessary information. I think that this is the analogy with the jmesh format, which apparently is already perfectly capable of extracting the rich data from the file (much more than what is needed for the applications of the mesh in FT). Fow now, I could only think of requiring at minimum the .pos (indeed always Mx3), the elements, can be tri (Nx3) /tet (Nx4)/hex (indeed Nx8) /(line (Nxwhatever)?) . Then, perhaps an added scalar value per element (or node) to indicate e.g. an anatomical region, segmentation tissue, surface object. Typically, this is coded as a pair of fields shape.tissue (Mx1) vector, and shape tissuelabel (Px1 cell-array). Alternatively, some (freesurfer derived) shapes also output a .curv .sulc etc field. 
I guess the long story short is that there is not a very strict and consistent way in which additional information is broadcasted to the command line. Perhaps it's indeed elegant to keep a version of all JMesh data in shape.orig (at least this is the name of the field that we also use to keep for instance a file's header information as parsed by the low-level reading functions).

**Comment by fangq** [comment]
@schoffelen, thanks for the detailed explanation.

I just pushed this commit to PR #2187, adding `shape.orig` and `shape.hex`

**Comment by robertoostenveld** [comment]
Thanks both for working on this, it is very useful to consider this in relation to the gmsh format to ensure consistency and completeness. As a reminder, a fundamental and generic design choice in FieldTrip is to make data structures as small as possible, but as complete as required. 

I think that labeled mesh data should be described as in https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_datatype_parcellation.m

Furthermore, here [on line 119 in ft_plot_mesh](https://github.com/fieldtrip/fieldtrip/blob/40bc1c7c8ec98226e2fc05007fc642954feed793/plotting/ft_plot_mesh.m#L119) you can see some of the fields that meshes can have. Indeed also geometry fields `line` (Nx2), but also `poly` (Nx?) and data fields such as `color`. In ft_read_headshape you can also see that `sulc`, `curv`,  `area`,  `thickness` and `atlasroi` are existing fields that can contain "data". Rather than making specific fields like `poslabel` etc., I think it is better to rely on `getdimord` just like we do for other fields in data structures. Just like `time` and/or `freq` define the dimensions along which the data field `powsptrm` is defined, `pos` and/or `hex` can describe dimensions along which the data fields `tissue`, or `curv` or `color` are defined.

**Comment by fangq** [comment]
@robertoostenveld, I mapped additional fields in [this commit](https://github.com/fieldtrip/fieldtrip/pull/2187/commits/95b1ad3b337d5fd18177e1d49d5248ac12cac4a1)
* `MeshEdge` -> `shape.line`
* `MeshPLC` -> `shape.poly`

for `color`, I wonder what format does FT expect? I can translate [`MeshVertex3.Properties.Color`](https://github.com/NeuroJSON/jmesh/blob/master/JMesh_specification.md#color) if a matching format presents.

I will probably let @schoffelen and you help with the proper naming of the label fields as you are more familiar with how `getdimord` works. From a quick read, it seems the function looks for `shape.type_label` subfield?
