### ISSUE TITLE
brickwall filter in ft_preproc_*<pass/stop>filter zeroes out too few frequencies

### ISSUE THREAD

**Issue by cjthomas-opensource** [fieldtrip/fieldtrip#1994]
Using ft_preproc_bandstopfilter.m (via ft_preprocessing) with the 'brickwall' filter type seems to produce incorrect results.

I'm using a brick wall filter to remove power-line noise (and additional narrow-band noise at 562 Hz) from a recording. Before finding FT's "brickwall" band-stop option, I implemented my own version, which worked acceptably. Switching to FT's implementation gave marginal attenuation and also boosted signal amplitude by about a factor of 10 for unknown reasons. Frequency spectrum plots are attached ("before" and "after" using each function).

I've included my function for producing the ft_preprocessing configuration structure used for calling FT's implementation, a screenshot of the relevant ft_preproc_bandstopfilter code from the present version of the GitHub repository, and my personal implementation (more verbose than it needs to be, but this is code I'll be sharing with students, so clarity took priority over terseness).

I'm not sure I understand what the ft_preproc_bandstopfilter implementation is doing. It _looks_ like it's only squashing one side of the spectrum and leaving components on the other side intact, which will give you complex-valued output. That doesn't explain where the amplitude boosting is coming from, so there's something I'm still missing about it.

I hereby grant you permission to use any of the code I've attached that you want under any license that you want. (LoopUtil and ExpUtils are under a CC license that _should_ be upgrade-compatible, but giving you blanket permission as the sole author skips any possible headaches in that regard.)

Matlab version reads as "9.8.0.1538580 (R2020a) Update 6" (via "version").

OS version reads as "Linux smolder 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux" (via "uname -a"). It's one of the versions of Mint 20.

Field Trip version reads as "This is FieldTrip, revision 20211118." (via "ft_version"), but per above I've inspected the most recent repository code version and suspect that it has problems with this specific filter case too.

(Matlab files are renamed as .txt files to facilitate attaching them.)

(LoopUtil filtering, before and after:)
![looputil-noise-narrow-stim-before](https://user-images.githubusercontent.com/71090515/156222272-51045d04-60e3-47f9-89d7-c307a054fd7c.png)
![looputil-noise-narrow-stim-after](https://user-images.githubusercontent.com/71090515/156222267-97416a3a-4d23-439e-ac02-505f65b74b5d.png)

(FT filtering, before and after:)
![ft-noise-narrow-stim-before](https://user-images.githubusercontent.com/71090515/156222136-f35ceb74-46d7-4975-8079-c21bd8bc0cbc.png)
![ft-noise-narrow-stim-after](https://user-images.githubusercontent.com/71090515/156222135-f2986521-a93a-42c9-a381-2a4ae978b038.png)

(Code to get a FT configuration structure for brick-wall band-stop filtering:)
[euFT_getFiltPowerBrick.m.txt](https://github.com/fieldtrip/fieldtrip/files/8163765/euFT_getFiltPowerBrick.m.txt)

(Code to do brick-wall band-stop filtering using LoopUtil:)
[nlProc_filterBrickBandStop.m.txt](https://github.com/fieldtrip/fieldtrip/files/8163766/nlProc_filterBrickBandStop.m.txt)

(FT's brick-wall band-stop filter code from the repository, as of 1 March 2022:)
![ft_preproc_bandstopfilter-brickwall](https://user-images.githubusercontent.com/71090515/156223718-a63dcf02-39ab-4496-a89e-f48a76253886.png)

**Comment by cjthomas-opensource** [comment]
I'm afraid that the earliest I'd be able to fix all "brickwall" instances myself would be around Christmas. Modifying the code won't take much time, but rigorously testing all of the filters with the new code to make sure they're producing correct output will. I'm presently over-committed at work and that situation is likely to continue for at least half a year and probably longer.

Per above, anyone who wants to fix the brick-wall filter before then (or to have a student do so) is free to copy the sample code I provided.

The amplitude issue still puzzles me; I'm not sure what's causing it (the contributions of the un-squashed frequency components to amplitude should have been negligible for my test case).

**Comment by StolkArjen** [comment]
Sorry, I don't recall the decisions that went into this implementation a decade ago. And I'm not sure I fully grasp the issue raised here either based on the above. Along the lines of JM's suggestion, a code suggestion (PR) accompanied with a direct pre/post comparison plot would certainly help.

**Comment by schoffelen** [comment]
Well, I for sure got a lot balder in the past decade. What about you, Arjen?

**Comment by StolkArjen** [comment]
Wish I could say the same ;)
