### ISSUE TITLE
ft_preproc_dftfilter out of memory

### ISSUE THREAD

**Issue by skoenig3** [fieldtrip/fieldtrip#1996]
**Describe the bug**
Error using  * ft_preproc_dftfilter (line 187)
Requested 9001x3686400 (494.4GB) array exceeds maximum array size preference (255.6GB). This might cause
MATLAB to become unresponsive.

**To Reproduce**
- Running fieldtrip preprocessing on 30 minutes of  54 channels iEEG data recorded at 2048 Hz. Running dtf filtering at 60, 120, 180, 240, and 300 Hz with 2 Hz neighbor width and a band width of 0.5 Hz.
- Ran into error with download of fieldtrip from 2/10/2022
- ft_preproc_dftfilter version is identical to what is currently on github
- No error when using in a previous fieldtrip version (fieldtrip-20200224) on this machine and another one.

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10 64 bit
 - MATLAB version: 2021a
 - FieldTrip version: ft_version did not work again whatever latest version on 2/10/2022 was

**Comment by schoffelen** [comment]
You have to buy a bigger computer, or otherwise loop across channels. The requested method requires an fft of the data, which in your case is just a beast in terms of memory consumption. I cannot make it any different. Given your recording, why don't you just use a bandstopfilter?
