### ISSUE TITLE
improve dccnpath and test data organization

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1998]
To facilitate external testing it would be good to reorganize the `dccnpath` function a little bit.

We now have three locations with test data 

1. /home/common/matlab/fieldtrip/data
2. /home/common/matlab/fieldtrip/data/ftp
3. /home/common/matlab/fieldtrip/data/test

but the 1st only contains some unzipped files from the 2nd. Better would be to simplify this to two locations: `ftp` (aka public) and `test` (aka private).

**Comment by robertoostenveld** [comment]
I also have part of the test data on a SSD drive that is attached to my laptop (at home or when traveling). That is `/Volumes/SamsungT7/data/test`, which is also reflected in the  `dccnpath` function. Better would be if the two 

- /home/common/matlab/fieldtrip/data/ftp
- /home/common/matlab/fieldtrip/data/test

would map exactly onto these two folders:

- /Volumes/SamsungT7/fieldtrip/data/ftp
- /Volumes/SamsungT7/fieldtrip/data/test

I will reorganize my local copy of the test data accordingly.

**Comment by robertoostenveld** [comment]
these improvements will help continued work on https://github.com/apjanke/fieldtrip-parallel-support/issues/1

**Comment by schoffelen** [comment]
For what it is worth: https://github.com/fieldtrip/fieldtrip/blob/master/test/test_issue1952.m contains some code that shows how to - from within matlab uninteractively - grab data from the ftp-server .

Could perhaps be useful.

In that context, I was wondering whether it would make sense to make a sibling function to dccnpath (e.g. dccnload or dccndata) that works as 'load' but does some voodoo under the hood

**Comment by robertoostenveld** [comment]
I have moved the unzipped `Subject01.ds` and similar datasets from `/home/common/matlab/fieldtrip/data` to `/home/common/matlab/fieldtrip/data/ftp/test/ctf` (which already contained a `edf` directory). These are all publicly shared datasets, but so far only as zip files in  `/home/common/matlab/fieldtrip/data/ftp/tutorial`.

**Comment by robertoostenveld** [comment]
I renamed a few other test .mat files to make them more consistent with the rest:

```
roboos@mentat002> mv test_bug161.mat bug161.mat
roboos@mentat002> mv test_bug2476.mat bug2476.mat
roboos@mentat002> mv test_bug2743.mat bug2743.mat
roboos@mentat002> mv test_issue1632.mat issue1632.mat
roboos@mentat002> mv test_issue922.mat issue922.mat 
roboos@mentat002> mv test_pull1456.mat pull1456.mat 
roboos@mentat002> mv test_pull574.mat pull574.mat 
```

**Comment by apjanke** [comment]
Excellent. I should be able to easily pull the whole `ftp` thing down into my homelab now.

**Comment by robertoostenveld** [comment]
well, "easily"? .... it still took me two days and I only live 2 km from the university. It would have been faster had I cycled over there with some portable medium  💾 🚴. But if you are patient, its is indeed not hard ;-)

**Comment by robertoostenveld** [comment]
I also updated the test scripts on the master branch, they should (just as before) read the data from the correct location. Feel free to add your local drive or mount point to the `dccnpath` function.

**Comment by apjanke** [comment]
"Easily" and "quickly" are two different things if you can just fire off the download and head out for your weekend. ;)

In addition to the various specific locations defined in `dccnpath`, I think we may need or want to add support for custom user-defined locations, specified via environment variables and/or Matlab appdata values, so that other FieldTrip users (like the VORtech folks' testing environment) can point them at their local paths which we can't know about in advance (and they may not want published in a public code library), without the need for any modifications to the FieldTrip source code. Basically, a way for `dccnpath` to pull "candidate" filesystem locations from the external environment in a way that can be hooked in to various users' environment definition mechanisms. What do you think?

**Comment by robertoostenveld** [comment]
> What do you think?

The most consistent would be to use the global `ft_default` variable (which is set by `ft_defaults.m` and used by all high-level FT functions), for example like this:

global ft_default
ft_default.dccnpath = '/your/local/path'; % this replaces /home/common/matlab/fieldtrip/data

I will implement it like this, you can give it a try

**Comment by robertoostenveld** [comment]
The test batch runs through on our compute cluster without further issues. I can now also run the test scripts on my macbook, where I have specified in my `startup.m`  that 

```
  global ft_default
  ft_default.dccnpath    = '/Volumes/SamsungT7/fieldtrip';
```

Hence I think this can be closed.
