### ISSUE TITLE
Add support for SPM in ft_read_json and elsewhere

### ISSUE THREAD

**Issue by vlitvak** [fieldtrip/fieldtrip#2003]
We are working on a BIDS dataset in SPM and there is an issue with reading JSON files as FT asks for a separate toolbox for that which is not included in SPM by default. We have a function in SPM12 for reading JSON so I would suggest adding support for it as an alternative. 

Also, it seems that event_tsv.m has a separate subfunction that duplicates the same functionality of ft_read_json.  There could also be instances of this elsewhere, I didn't look. See the proposed changes attached
[4Robert.zip](https://github.com/fieldtrip/fieldtrip/files/8305072/4Robert.zip)
.

**Comment by robertoostenveld** [comment]
Thanks for the suggestions. JSON reading and writing is regretfully still a bit messy, with there not being a single definite piece of code that does everything well.

The function `spm_jsonread.m` is not yet in `fieldtrip/external/spm12`, but I will add it as well (including mex files).

**Comment by robertoostenveld** [comment]
@vlitvak could you review how I have now implemented `ft_read_json`, conditional on the presence of the optional toolboxes?

**Comment by vlitvak** [comment]
Looks good, just the comments are the wrong way around.
