### ISSUE TITLE
avoid dependency issues between jnifty, jsonlab, and iso2mesh

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2005]
In https://github.com/robertoostenveld/fieldtrip/pull/11 @fangq identified potentially problematic code duplication

> jsonlab and jnifty have been developed as part of iso2mesh.
> 
> one choice you have is to remove external/jnifty and external/jsonlab and update external/iso2mesh to the git version. The pro side of this approach is that there is no duplication; the con-side is reduced modularity, and also the needs for testing if iso2mesh were to be updated (not sure how many functions have dependencies)
> 
> the second approach is to either ensure that addpath to external/jnifty and external/jsonlab happens after addpath to external/iso2mesh, or remove the duplicated functions in iso2mesh - the downside of doing this is that some iso2mesh functions that depends on these two sub-packages may not work (although I am not sure if it matters for fieldtrip).

We should discuss this dependency issue in more detail, if needed in a zoom call.

**Comment by fangq** [comment]
@robertoostenveld, given that fieldtrip uses direct copies of toolboxes in `external`, there should be quite a bit flexibility (as opposed to git submodule) in keeping/removing files relevant to fieldtrip.

The way I fixed this duplication when packaging iso2mesh for Debian (`octave-iso2mesh`) is to create separate packages for `octave-jnifti`/octave-jsonlab` and declare those as dependencies to `octave-iso2mesh`, then remove duplicated units from iso2mesh, see

https://salsa.debian.org/pkg-octave-team/octave-iso2mesh/-/blob/debian/latest/debian/control#L16
https://salsa.debian.org/pkg-octave-team/octave-iso2mesh/-/blob/debian/latest/debian/rules#L22-28

another solution is to create a sub-folder `external/iso2mesh/private` and move those units inside this folder. This will still ensure iso2mesh functions can run without asking users to explicitly install/enable jnifti/jsonlab.
