### ISSUE TITLE
Error in ft_virtualchannel when working with TFR data

### ISSUE THREAD

**Issue by rensch13** [fieldtrip/fieldtrip#2012]
An error occurred during the DCCN hackathon when projecting TFR data to virtual channels. Bug discovered during Thursday hackathon with @robertoostenveld. Seems like a loop over time dimension is missing

command:
virt_channels = ft_virtualchannel(cfg, TFData, source_av);

mat-file with cfg, TFData, source_av is too big to attach, saved it at 

temporary/4Robert

**Comment by schoffelen** [comment]
This sounds like an excellent opportunity for your first PR, no? :)

**Comment by robertoostenveld** [comment]
for reference, I copied the mat file with the data to reproduce the problem to `/home/common/matlab/fieldtrip/data/test/issue2012.mat`

**Comment by schoffelen** [comment]
I must say that I did not consider a use case with TF data in the input.

When I try it out, the code chokes on the svd step, where the input data is assumed a nchanxnchan covariance(-like) matrix. In other words, the freq dimension has been averaged out. I suggest that the time dim also should be averaged out if needed.

**Comment by schoffelen** [comment]
I addressed the issue, but now the code chokes on the testdata, because ft_apply_montage is confused to get the correct dimord, probably due to the fact that there are 21 time and 21 freqbins in the data.

**Comment by schoffelen** [comment]
If I try to subselect some data with ft_selectdata, the output is incorrect, so this requires a new issue (sth like ft_selectdata fails with fourier input TF-data if # of freq and time bins are the same)
