### ISSUE TITLE
printor function in ft_checkdata gives error (does not exits)  

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2021]
One of the toolkit participants got an error when reading in data in `.mat` file format with a variable "data" in it, but that nevertheless was _not_ a fieldtrip data structure. 

When reading a mat file (as if it were a raw data file), the code tries to interpret it as a file containing a raw data structure. This is then passed through `ft_checkdata`, where in this very specific case (the "data" variable was not a recognized structure) the `printor` function would be called to print an informative error message. However, the `printor` function does not exist in FT or in MATLAB 2021b.

**Comment by schoffelen** [comment]
huh, what about this one? https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/printor.m

**Comment by schoffelen** [comment]
This is totally weird. I can confirm the problem. Yet, printor exists in utitlities/private/

However, somehow (also with me on my mac and matlab2021a) if I do 'which ft_checkdata', matlab returns fieldtrip/fileio/private/ft_checkdata.m. I can imagine a reason why ft_checkdata is shadowed in fileio/private, but I don't understand why this takes precedence on the path...

**Comment by schoffelen** [comment]
Add to last comment: the fileio/private/ft_checkdata is returned when in the debugger. Perhaps it has to do with the handling of the mat-file.

**Comment by schoffelen** [comment]
Gotcha, the error stack mentions that ft_checkdata (the one that cannot find printor) is called from ft_fetch_header, the latter is in fileio/private
