### ISSUE TITLE
vmrk reader fails for segmented data

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#2026]
**Describe the bug**
this came up during the toolkit: when reading in a brainvision vmrk file, the returned events may be incorrect if the markers in the text file are formatted according to: a,,b,c,d,e -> i.e. if there are missing numbers between commas.
This can be related to a call to strsplit, which does not return an empty element for the missing numbers, altough the rest of the code expects this. 

**To Reproduce**
1. Do: strsplit('a,,b,c', ',');
2. if the output is {'a' 'b' 'c'} then the code will return wrong samples for the events
3. the old fashioned tokenize() or matlab built in split() seems to work fine

**Additional context**
could be a matlab version or character encoding issue, but not sure

**Comment by robertoostenveld** [comment]
I have copied one of the problematic datasets to `/home/common/matlab/fieldtrip/data/test/issue2026`
