### ISSUE TITLE
writecell is not supported for motion BIDS

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2039]
This follows up on PR #2034. 

With `test_example_bids_motion20220113` and MATLAB R2018b I detected a regression error

```
Undefined function or variable 'writecell'.

Error in data2bids (line 1839)
              writecell(hdr.label', cfg.outputfile,'FileType', 'text', 'Delimiter', '\t');

Error in test_example_bids_motion20220113 (line 62)
data2bids(cfg);
 
>> which writecell
'writecell' not found.
```

The [mathworks documentation](https://nl.mathworks.com/help/matlab/ref/writecell.html) specifies that it is introduced in R2019a. Hence its use violates our [backward compatibility policy](https://www.fieldtriptoolbox.org/development/guideline/code/#ensure-that-it-runs-on-older-matlab-versions).

**Comment by schoffelen** [comment]
good: note that the drop in replacement for writematrix has limited functionality w.r.t. the mathworks version. I only included the functionality that was needed for data2bids to work.

**Comment by robertoostenveld** [comment]
Yes, I saw. It now has slightly more functionality to match the code update in `data2bids`, it now can also append to an existing text file.
