### ISSUE TITLE
Making ft_read_event/ read_eyelink_asc on asc data from Eyelink1000 more robust at detecting rows with MSG

### ISSUE THREAD

**Issue by johalgermissen** [fieldtrip/fieldtrip#2041]
I recently tried to use Fieldtrip (/home/common/matlab/fieldtrip on the Donders HPC cluster) to read in & epoch some eye-tracking data saved in the .asc data file format coming from an Eyelink 1000 (originally .edf file convert to .asc).

The **file itself** looks fine, I can open it in any text editor and confirm that it looks as expected, containing messages that I sent as triggers to the file, e.g.

```
1010878	  944.3	  549.3	  978.0	...
1010878	  944.4	  545.2	  977.0	...
MSG	1010879 StartActionCue
1010879	  950.8	  544.2	  972.0	...
1010879	  957.3	  542.9	  972.0	...
```

**Reading** it in also works fine using `ft_read_data`/ `ft_preprocessing`.

Just **epoching is the problem**.
I tried `ft_read_event` to read out the messages and set up a `trl` matrix for epoching trials, like this:

```
iSub    = 2;
asctmp  = dir(fullfile(eyelinkDir, sprintf('s_%02d*.asc', iSub)));
ascFullFileName = fullfile(asctmp.folder, asctmp.name);
event   = ft_read_event(ascFullFileName);
event
```

However, it did not find any events:
```
  0×0 empty struct array with fields:

    type
    value
    sample
    offset
    duration
````

which is weird. I confirmed this problem for multiple data sets (some complete, some incomplete).
I put some example data sets on the Donders HPC cluster under `/home/common/temporary/4EyelinkASC/`

I figured out that [ft_read_event](https://github.com/fieldtrip/fieldtrip/blob/master/fileio/ft_read_event.m) calls [read_eyelink_asc](https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/read_eyelink_asc.m), which explicitly searches for the **string MSG**: 

```
  elseif regexp(tline, '^MSG')
    asc.msg = cat(1, asc.msg, {tline});
```

and all the messages I sent to the Eyelink start with the string "MSG" (I confirmed in my data, see above).

I'm not sure what the problem is with my data... but I'm willing to contribute to solve it & make read_eyelink_asc more robust...

I did come across this **email exchange** https://mailman.science.ru.nl/pipermail/fieldtrip/2019-November/039661.html from 3 years ago which reports a similar problem (searching for MESSAGE instead of MSG), and solved it eventually with a workaround using `ft_read_header`. I also got my personal work-around with `ft_read_header`, but I guess that ideally, `ft_read_event` should work too....

Any ideas where this problem might come from?
Can you reproduce it with the files I uploaded?
Alternatively, in line with the email exchange mentioned above, I'd be willing to contribute another function that explicitly searches for certain strings (e.g. using `ft_read_header`) if you agree that it would be useful to have such a function...

**Comment by robertoostenveld** [comment]
I won't work on it straight away, but I have just secured the files and copied them to the test directory

```
roboos@mentat002> mkdir /home/common/matlab/fieldtrip/data/test/issue2041
roboos@mentat002> cp *.asc /home/common/matlab/fieldtrip/data/test/issue2041
```

**Comment by robertoostenveld** [comment]
on `/home/common/matlab/fieldtrip/data/test/original/eyetracker/eyelink` are some more examples, one of these was probably used to make the original implementation.  

Looking at `ft_read_event`, I see that only the lines starting with `INPUT` are converted into events. All other lines, including `MSG` but also `SSACC` and `EBLINK` could also be converted into events. Please have a go at it.

**Comment by schoffelen** [comment]
Not much seem to have been happening here, the referenced PR now also returns the other events' (fix, sacc, blink) (onset and duration) information.

The reading of the asc is extremely slow, due to the for-loop across lines, and the multiple sscanf and cat operations. For now I decided to keep it like this, because it would require another overhaul of the low-level reading function, which may make it less robust.

**Comment by schoffelen** [comment]
OK, I tried to revamp the eyelink ascii reader. It's still slow for large data files, but I think it is already quite much faster. It now relies a bit more on the file format description and avoids the sscanf operation per line wherever it can be avoided. I suggest to merge the PR, and rely on the current test code in test_pull694.
@johalgermissen would you mind trying out a bit the new functionality soon?
