### ISSUE TITLE
ft_spike_maketrials() no longer works as expected

### ISSUE THREAD

**Issue by dustinf1989** [fieldtrip/fieldtrip#2054]
**Describe the bug**
The tutorial found at https://www.fieldtriptoolbox.org/tutorial/spike/ no longer works

**To Reproduce**
Enter the code until you reach the section 'Adding trigger event information to spike structure' (Reproduced below)

```
spike = ft_read_spike('p029_sort_final_01.nex');

cfg              = [];
cfg.spikechannel = {'sig002a_wf', 'sig003a_wf'}; % select only the two single units
spike = ft_spike_select(cfg, spike);

cfg          = [];
cfg.dataset  = 'p029_sort_final_01.nex';
cfg.trialfun = 'trialfun_stimon';
cfg = ft_definetrial(cfg);

cfg.timestampspersecond =  spike.hdr.FileHeader.Frequency; % 40000
spikeTrials = ft_spike_maketrials(cfg,spike);
```
This issues multiple warnings:

> Warning: your trials are overlapping, trials will not be statistically independent, some spikes will be
> duplicated 

The following warning is given twice, presumably once for each unit:

> Warning: could not determine dimord of "hdr" in:
> 
>                 cfg: [1×1 struct]
>                 hdr: [1×1 struct]
>               label: {'sig002a_wf'  'sig003a_wf'}
>           timestamp: {1×2 cell}
>     timestampdimord: '{chan}_spike'
>                unit: {1×2 cell}
>          unitdimord: '{chan}_spike'
>            waveform: {[1×32×164456 double]  [1×32×134803 double]}
>      waveformdimord: '{chan}_lead_time_spike'
> 
>  
> Warning: not making selection in hdr 

**Expected behavior**
Trials would be created as in the tutorial

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10
 - MATLAB version 2022a
 - FieldTrip version 20220531

**Comment by robertoostenveld** [comment]
what makes you think that the warnings (which are informative, but might be too detailed for you) cause the computations not to work any more?

**Comment by robertoostenveld** [comment]
I must say that the second warning is confusing and not needed, as the code should not try to determine the order of the dimensions in the `hdr` field. That is the header of the original data, it is not `channels x frequencies` (chan_freq) or so.

**Comment by dustinf1989** [comment]
Thank you very much for such a quick response, and sorry for not being completely clear.  After running the above code, we are told to run

```
spikeTrials.trialtime(1:5,:)
ans
   [ -2.750000000000000  3.353600000000000
     -2.750000000000000   2.318725000000000
     -2.750000000000000   4.755700000000000
     -2.750000000000000   1.051875000000000
     -2.750000000000000   2.853950000000000]
```
However, it produces
```
spikeTrials.trialtime(1:5,:)
ans =
   -2.7500    0.0250
   -2.7500    0.0250
   -2.7500    0.0250
   -2.7500    0.0250
   -2.7500    0.0250
```
So the trial structure created is no longer correct (assuming the numbers in the tutorial are correct).

**Comment by dustinf1989** [comment]
> I must say that the second warning is confusing and not needed, as the code should not try to determine the order of the dimensions in the `hdr` field. That is the header of the original data, it is not `channels x frequencies` (chan_freq) or so.

Thanks, so it seems line 183 should be changed to include `hdr `then.

`    fn = setdiff(fn, {'label', 'cfg', 'hdr', 'dimord', 'time', 'trial', 'trialtime'});`

**Comment by robertoostenveld** [comment]
I have confirmed the problem, and traced it to `trialfun_stimon` where the samples, values and timestamp vectors are created. The samples field is empty now and then, which causes the samples vector to be shorter than the other two. So they don't align.

I will update the  `trialfun_stimon` in the documentation and on the download server.

**Comment by robertoostenveld** [comment]
The problem might be due to previous (not recent) changes to `ft_read_event` or to the plexus reading code, that caused the missing values to be represented as `[]`, whereas previously it might have been `nan` (as I am using now).

**Comment by robertoostenveld** [comment]
The `hdr` warning is solved with commit https://github.com/fieldtrip/fieldtrip/commit/29e833ccdded7c90ee2860c9033711b2b244f7cd

thanks!
