### ISSUE TITLE
Plotting ISI histogram no longer works in Spike train analysis tutorial

### ISSUE THREAD

**Issue by dustinf1989** [fieldtrip/fieldtrip#2055]
**Describe the bug**
The tutorial to generate an ISI histogram from an example t file no longer works: https://www.fieldtriptoolbox.org/tutorial/spike/

**To Reproduce**
From tutorial: We also read in an additional dataset consisting of an M-clust .t file, that can be found [here](https://download.fieldtriptoolbox.org/tutorial/spike/tt6_7.t)

```
% read in the .t file
filename    = 'tt6_7.t'
cfg         = [];
cfg.dataset = filename;
spike2 = ft_read_spike(cfg.dataset)

% convert timestamps to seconds
cfg                     = [];
cfg.trl                 = [0 max(spike2.timestamp{1})+1 0];
cfg.timestampspersecond = 10^6;
spike2Trial = ft_spike_maketrials(cfg,spike2);

% run the isi histogram
cfg      = [];
cfg.bins = [0:0.001:0.2];
isih = ft_spike_isi(cfg,spike2Trial);

% plot the isi histogram with the Poincare return map
cfg             = [];
cfg.interpolate = 5;
cfg.window      = 'gausswin';
cfg.winlen      = 0.005;
cfg.scatter     = 'no';
cfg.colormap    = jet(300);
figure, ft_spike_plot_isireturn(cfg,isih)
```
The call `spike2Trial = ft_spike_maketrials(cfg,spike2);` Raises error:

> Index exceeds the number of array elements. Index must not exceed 0.
> 
> Error in ft_spike_maketrials (line 195)
>           spike.(fn{i}){iUnit} = spike.((fn{i})){iUnit}(:,:,sel);

**Environment and versions (please complete the following information):**
 - Operating System:Windows 10
 - MATLAB version R2022a
 - FieldTrip version fieldtrip-20220531

**Additional context**
I was able to generate the plot by commenting two lines in the `ft_read_spikes` function.

```
case 'mclust_t'
    fp = fopen(filename, 'rb', 'ieee-le');
    H = ReadHeader(fp);
    fclose(fp);
    % read only from one file
    S = read_mclust_t({filename});
    spike.hdr = H(:);
    [p, f, x] = fileparts(filename);
    spike.label     = {f};  % use the filename as label for the spike channel
    spike.timestamp = S;
%     spike.waveform  = {};   % this is unknown
%     spike.unit      = {};   % this is unknown
    spike.hdr       = H;
```

Why were these fields created if they don't exist in .t files and will it cause an issue to exclude them?

**Comment by robertoostenveld** [comment]
there is now a new test script based on the current tutorial. It runs through (i.e. gives no error), but note that it does not check whether the output values and figures make sense. 

@dustinf1989 thanks for reporting, please continue reporting if you encounter problems. For small issues that you can resolve yourself you might also want to send a pull request directly, see https://www.fieldtriptoolbox.org/development/git/
