### ISSUE TITLE
Joint PSTH figure tutorial output is incorrect

### ISSUE THREAD

**Issue by dustinf1989** [fieldtrip/fieldtrip#2056]
**Describe the bug**
At the end of the spike tutorial, joint PSTHs are created but the axes are wrong due to NaNs.

**To Reproduce**
Go to: https://www.fieldtriptoolbox.org/tutorial/spike/#the-joint-peri-stimulus-time-histogram

Produce figures using this code
```
% compute the spike densities
cfg         = [];
cfg.latency = [-1 3];
cfg.timwin  = [-0.025 0.025];
cfg.fsample = 200;
[sdf] = ft_spikedensity(cfg,spikeTrials);

% compute the joint psth
cfg               = [];
cfg.normalization = 'no';
cfg.channelcmb    = spikeTrials.label(3:4);
cfg.method        = 'jpsth';
jpsth = ft_spike_jpsth(cfg,sdf);

cfg.method = 'shiftpredictor';
jpsthShuff = ft_spike_jpsth(cfg,sdf);

% subtract the predictor
jpsthSubtr = jpsth;
jpsthSubtr.jpsth = jpsth.jpsth-jpsthShuff.shiftpredictor;

cfg        = [];
figure
ft_spike_plot_jpsth(cfg,jpsth)
figure, ft_spike_plot_jpsth(cfg,jpsthShuff)
figure, ft_spike_plot_jpsth(cfg,jpsthSubtr)
```

**Expected behavior**
The PSTHs should range from -1 to 3 seconds but they end up ranging from -1 to 1 so theta modulation isn't seen. `jpsth.psth ` contains NaNs for the data from 1 to 3 seconds.

**Screenshots**

![spike_tutorial_PSTH](https://user-images.githubusercontent.com/42267055/175034807-b64009cc-a950-49b9-aaaa-caa09392813e.png)

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10
 - MATLAB version: R2022a
 - FieldTrip version: fieldtrip-20220531

**Additional context**

**Comment by robertoostenveld** [comment]
could you give it a try in trying to figure out a solution?

**Comment by dustinf1989** [comment]
Yeah, I'm giving it a go but so far unsuccessful.

**Comment by schoffelen** [comment]
I think that this is now fixed with the latest version of the FieldTrip code.
