### ISSUE TITLE
Spike and LFP Tutorial no longer working properly

### ISSUE THREAD

**Issue by dustinf1989** [fieldtrip/fieldtrip#2057]
**Describe the bug**
The [Preprocessing and analysis of spike and local field potential data](https://www.fieldtriptoolbox.org/tutorial/spikefield/) tutorial doesn't work properly. I implemented a small fix based on the spike analysis tutorial, but some figures and outputs are different than the tutorial page.

**To Reproduce**
The function should be changed to this (maybe also more changes are required):

```
function trl = trialfun_stimon_samples(cfg)
hdr   = ft_read_header(cfg.dataset);
event = ft_read_event(cfg.dataset);
correctresponse  = 10041;
begintrial       = 10044;
endtrial         = 10045;
stimon           = 10030;
distractorChange = 12000;
targetChange     = 12001;
attCnds          = 20001:20004;       % att in/out by target change first/second
E          = struct2cell(event);

% replace empty cells with nan, otherwise the values are shifted
sel = cellfun(@isempty, E(:));
E(sel) = {nan};

samples    = cell2mat(E(1,:));        % now in vector form
value      = cell2mat(E(2,:));
timestamps = cell2mat(E(3,:));        % now in vector form
begmark    = find(value==begintrial); % loop through the trial beginnings
endmark    = find(value==endtrial);   % loop through the trial endings
trl = [];

for k=1:length(begmark)
    vals = value(begmark(k):endmark(k));
    if any(ismember(vals,attCnds)) && ~isempty(find(vals==correctresponse))
        % create the trl matrix in sample units
        samp = samples(begmark(k):endmark(k)); % in timestamp units
        beginSamp      = samp(find(vals==stimon));
        sampDistractor = samp(find(vals==distractorChange));
        sampTarget     = samp(find(vals==targetChange));
        endSamp        = min([sampTarget(:);sampDistractor(:)]); % limit until first change
        offset         = -round(hdr.Fs*2.75);
        trl            = [trl; [beginSamp+offset endSamp offset]];
    end
end
```

**First difference**
Under the heading "Computing the spike triggered average LFP," the first figure is reproduced accurately, but the code for the second figure generates a figure identical to the first one in this section. Setting `cfg.latency = [-2.75 0]` does not have the desired effect.

**Second difference**
The last segment of code generates two figures, both contain a higher resolution time axis `length(statSts.time) = 777` than in the tutorial where it is 155. This leads to quantitatively different figures, possibly due to changes in default parameters called by `ft_spiketriggeredspectrum_stat`.

![spike_LFP_tutorial1](https://user-images.githubusercontent.com/42267055/175064330-abb41c60-9367-4c6d-bf6c-78ac0b2e227e.png)

![spike_LFP_tutorial2](https://user-images.githubusercontent.com/42267055/175064354-3e3baf18-ab87-4c42-85aa-c9037a622f21.png)

**Expected behavior**
That the figures and variables would be the same as the tutorial page.

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10
 - MATLAB version: 2022a
 - FieldTrip version: fieldtrip-20220531

**Additional context**
The proposed change to the function was [discussed for the related spike analysis tutorial](https://github.com/fieldtrip/fieldtrip/issues/2054)

**Comment by robertoostenveld** [comment]
@dustinf1989 can you please revisit this and let us know whether all issues that you are aware of have been resolved? If so, please close this issue.

**Comment by schoffelen** [comment]
OK, this is apparently something tricky.
I have identified a few things that might already fix it into the right direction.

First of all, there's a critical issue in the trialfun_stimon_sample that causes a (possibly matlab version specific) mismatch between values and samples, causing the 'trl' to be off, and thus causing the data.trial{1}(:,4005:4006) to fail.

Next, no latency selection seems to be performed in the latest version of ft_spiketriggeredaverage, causing the pre/post sta's not to look according to the figures on the website. 

I have fixed both in my development version of the repo and will push soon. I don't know yet about the spectra.

**Comment by schoffelen** [comment]
The spiketriggered spectrum computation is a bit of a black box to me. I am not going to touch that, and to be honest I am surprised that it works at all. The functionality bypasses the ft_specest_mtmconvol module. It does not seem to allow for padding, so that the requested frequencies are a non-trivial function of the length of the first trial in the data, it seems (by reading the code). It could be that everything is mathematically correct, but at least in the displayed figure, the bands of the different frequencies are of different width, which suggests a rounding issue w.r.t. the requested frequency bins in relation to the frequency bins that were actually obtained.

**Comment by schoffelen** [comment]
I changed the winstepsize to 0.05 in the code on the website, which reduces the number of time bins.

**Comment by schoffelen** [comment]
I think that this one can be closed
