### ISSUE TITLE
'all' not default in ft_freqanalysis under mtmconvol

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#2061]
Hi,

Tiny issue: Although the help of ft_freqanalysis() says 'all' is the default for cfg.toi when cfg.method = 'mtmconvol', it is actually required by the code:
https://github.com/fieldtrip/fieldtrip/blob/8e4f5fe1b2786a9cd3d832e498fa30dc6bf188b4/ft_freqanalysis.m#L317

Should I submit a PR to fix the help section or the code to treat 'all' as the default?

Thanks!

**Comment by robertoostenveld** [comment]
Good catch. 

I am not sure what should be done by the code when the user (or the default) specifies `all`. The code could take the original time axis of the input data , but that would result in a time resolution that is very high (time steps of one sample, which often means 1 ms). I think that time steps of 50 ms or so are more realistic, and usually would result in a 50x smaller data representation than time steps of 1 ms.

Perhaps it is better not to have a "smart" default but rather force the decision on the user. @schoffelen what do you think?

**Comment by schoffelen** [comment]
I tend to agree with @robertoostenveld, i.e. let the user explicitly take a decision about the cfg.toi specification. I suggest therefore to amend the help section of the function, rather than removing 'toi' from ft_checkconfig.

**Comment by NirOfir** [comment]
Thanks, that makes a lot of sense. I made a PR for this issue: #2064.

One more question: Now that the Hilbert method is documented, should I remove the bit from the undocumented local options?
