### ISSUE TITLE
Do not use 'input' as a variable name

### ISSUE THREAD

**Issue by AljenU** [fieldtrip/fieldtrip#2062]
Matlab has a builtin function called input, to ask for user input. Variable names should not be the same as the name of a matlab (builtin) function. The variable will shadow the function, making it impossible to call the function. And, it can lead to confusion as to what the code is doing / makes it harder to interpret the code.

**Comment by robertoostenveld** [comment]
can you be more specific where `input` is used as input variable?

**Comment by robertoostenveld** [comment]
I do agree that it is better not to use `input` as variable name.

**Comment by schoffelen** [comment]
as long as the variable is only called 'input' in the scope of the function, why should this be a problem, as long as the matlab function is not called within the respective function?

**Comment by robertoostenveld** [comment]
while going over `besa2fieldtrip` I have also fixed some minor bugs and revived the `test_besa2fieldtrip` script
