### ISSUE TITLE
ft_selectdata() restricts latency based on trials excluded by cfg.trials

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#2072]
**Describe the bug**
Not sure if a bug or a feature :) When trying to select a certain time window only within certain trials, ft_selectdata() restricts the TOI based on all trials in the data set, including those that are irrelevant. This is because time selection (line 284) happens before rpt selection (line 296). And a small detail, ft_selectdata() misses the check for "trial" and "channels" in the cfg. 

**To Reproduce**
Run the following code:
```
% Simulate data
data = [];
data.fsample = 1000;
data.label   = {'1', '2', '3'};
for i = 1:3
    data.time{i}  = -0.5:1/data.fsample:i;
    data.trial{i} = randn(length(data.label), length(data.time{i}));
end

% This will cut the TOI to [-0.5, 1]
cfg = [];
cfg.trial   = 2;
cfg.latency = [-0.5, 1.5];
data_cut    = ft_selectdata(cfg, data);
[data_cut.time{1}(1), data_cut.time{1}(end)]

% This will give the correct TOI of [-0.5, 1.5]
cfg = [];
cfg.trials  = 2;
data_cut    = ft_selectdata(cfg, data);
cfg = [];
cfg.latency = [-0.5, 1.5];
data_cut    = ft_selectdata(cfg, data_cut);
[data_cut.time{1}(1), data_cut.time{1}(end)]`
```

**Expected behavior**
For me it makes sense to first choose trials and then the other dimensions, but I'm pretty sure I'm missing some reason it isn't so. The obvious solution now is to run ft_selectdata() twice, first selecting trials then moving on to TOI. However, I'm wondering if this issue justifies a code change?

**Environment and versions (please complete the following information):**
 - Operating System: CentOS 7
 - MATLAB version R2018b
 - FieldTrip version 2020628.

Thanks!

**Comment by schoffelen** [comment]
Hi @NirOfir sorry to be so slow on this. Indeed I agree with you on the expected outcome

If I change line 941 in ft_selectdata from:

if iscell(varargin{1}.time) && ischar(cfg.latency) && ~strcmp(cfg.latency, 'minperiod')

into 

if iscell(varargin{1}.time) && ~isequal(cfg.latency, 'minperiod')

it seems that the function works as expected for your case. I am not sure about the potential side effects of this change, though. Last time I made a small change in the code, it took me 5 days to get the batch of test functions in order again.

Can I suggest that you submit the above change (after verification that it works for you) as a PR? Then you do not only get the credits for the fix, but also the blame if something else breaks :).

**Comment by schoffelen** [comment]
Oh and @NirOfir please add a test function (according to the files in fieldtrip/test) that includes the above example code.
