### ISSUE TITLE
bug in subfunction sphsplint

### ISSUE THREAD

**Issue by howdobrain** [fieldtrip/fieldtrip#2076]
**Describe the bug**
There is a bug in recent versions of ft_scalpcurrentdensity. Specifically, the subfunction sphsplint results in the same data in every EEG channel.

**To Reproduce**
Run ft_scalpcurrentdensity with cfg.method = 'spline'.

**Expected behavior**
This function should apply a laplacian spatial filter to EEG channels. Instead, it outputs the same data to every channel.

**Environment and versions (please complete the following information):**
This is an issue with 2022 versions of fieldtrip, possibly 2021 too. It is not an issue with 2020 versions.

**Additional context**
This subfunction is also used in ft_channelrepair with cfg.method = 'spline'.

**Comment by schoffelen** [comment]
OK thanks!

**Comment by schoffelen** [comment]
can you please paste in here what your data object looks like? As far as I know, a spline interpolation requires the electrode positions in 3D (in something like data.elec.chanpos), a .lay template is a 2D projection for visualization and does not provide realistic information about the electrode geometry. I don't have a data structure handy, so I repeat my question to send us a small snippet of data (even with the time courses and time axes removed, e.g. by calling data = removefields(data,{'trial' 'time'}) to reduce its size. You can find information in this link on how to get data to us. https://www.fieldtriptoolbox.org/faq/how_should_i_send_example_data_to_the_developers/

**Comment by schoffelen** [comment]
Hi Elizabeth, what is the status with this? Is there anything that can be done on our end?

**Comment by howdobrain** [comment]
Hi Jan-Mathijs, we solved it on our end. Thanks and best -

--
Elizabeth L Johnson, PhD
Assistant Professor
Departments of Medical Social Sciences and Pediatrics
Northwestern University Feinberg School of Medicine
dynamic-brain.org<https://dynamic-brain.org>
________________________________

**Comment by schoffelen** [comment]
okido! Thanks for letting us know
