### ISSUE TITLE
Using ft_singleplotER with TRF data to average out the time dimension

### ISSUE THREAD

**Issue by ldbolanos** [fieldtrip/fieldtrip#2081]
Hi,

I am processing EMG data and have a spectrogram where time is between [-2, 2] seconds, and frequency is between [20, 200] Hz.

I would like to obtain a power spectral density plot (i.e., power vs. frequency) out of this spectrogram by averaging within each frequency bin the values between [0, 0.5] seconds (thus, effectively removing the time dimension).

Reading the documentation of `ft_singleplotER`, I found the ["Undocumented local options"](https://github.com/fieldtrip/fieldtrip/blob/c2177cd2619f72b5103b30c7139e0a6fe68b53e3/ft_singleplotER.m#L95-L97) stating:

```
cfg.zlim/xparam (set to a specific frequency range or time range [zmax zmin] for an average 
over the frequency/time bins for TFR data.  
Use in conjunction with e.g. xparam = 'time', and cfg.parameter = 'powspctrm').
```

I tried to use it as:

```
cfg             = [];
cfg.channel     = 'Biceps';
cfg.layout      = 'my_cap.mat';
cfg.parameter   = 'powspctrm';
cfg.xparam      = 'time';
cfg.zlim        = [0.0 0.5];

ft_singleplotER(cfg, tfr_data);
```

but I got a) a warning saying 
```
Warning: The option cfg.xparam is deprecated, support is no longer guaranteed
```
and b) a plot with the x axis ranging [-2, 2], which is my time dimension, instead of [20, 200], as I know those are my frequencies.

Therefore, I am assuming the warning is indeed true and the result is incorrect.

Is there some other way of accomplishing what I want? (Besides doing everything manually)

Thanks in advance!

**Comment by robertoostenveld** [comment]
Let me remove the "undocumented options" section in the code, as that is outdated. The option `cfg.xparam` is not used anywhere anymore, the parameter along the horizontal (x) axis is either time or frequency and is determined automatically by looking at the data.

**Comment by robertoostenveld** [comment]
to select and average data over a range you can use ft_selectdata. In your case I think that something like this should work

```
cfg = [];
cfg.parameter = 'powspctrm'
cfg.latency = [0 0.5]
cfg.avgovertime = 'yes'
cfg.keeptimedim = 'no'
frequencyspectrum = ft_selectdata(cfg, timefrequencyspectrum)
```

**Comment by robertoostenveld** [comment]
I have improved documentation, so that (hopefully) you don't have to rely on undocumented options. But reading the code to see what it does is always recommended.

**Comment by ldbolanos** [comment]
I think that is exactly what I was looking for! Thank you.
