### ISSUE TITLE
Errors in functions from external/freesurfer are not gracefully caught, and lead to uninformative matlab errors

### ISSUE THREAD

**Issue by michaelruvalcaba** [fieldtrip/fieldtrip#2086]
Hello everyone,

I am not that well verse in programming, but I am hoping someone can help me with this problem. I am trying to run recon-all on a specific subject and it runs without error. However, when I try loading the freesurfer pre-op MR I get the following error: 

```
/bin/bash: /scratch/tp8b1bdb8d_514a_4abc_9438_4b27f2cf52f1.load_mgh.m.mgh: Permission denied

ERROR: could not open /scratch/tp8b1bdb8d_514a_4abc_9438_4b27f2cf52f1.load_mgh.m.mgh for reading
Dot indexing is not supported for variables of this type. 

Error in ft_read_mri (line 401)
    ndims = numel(size(tmp.vol));

```

When looking at the line 401 in ft_read_mri this is what the code reads:

```
 ndims = numel(size(tmp.vol));
    if ndims==3
      img = permute(tmp.vol, [2 1 3]); %FIXME although this is probably correct
      %see the help of MRIread, anecdotally columns and rows seem to need a swap
      %in order to match the transform matrix (alternatively a row switch of the
      %latter can be done)
    elseif ndims==4
      img = permute(tmp.vol, [2 1 3 4]);
    end

```

I am running freesurfer_x86_64-5.3.0 and using MATLAB 2019b. 

Any help is greatly appreciated. Thank you!!

**Comment by vijayiyer05** [comment]
I suggest to [add a breakpoint](s.html) at the offending line. 
Once the breakpoint is hit, I would execute the command `class(tmp)` to see what type it is. 
Dot indexing is typically for structure variables. It seems like `tmp` is not ending up as a struct variable as expected by the code.

**Comment by schoffelen** [comment]
In addition to Vijay's suggestion it would be helpful if you provide us with the full error stack (i.e. all the red stuff that matlab prints), and some more information about the fieldtrip version you have been using. Line 401 in ft_read_mri in my FieldTrip does not relate to the code that you pasted. Therefore, it is difficult to judge. Also, are you running on windows? Also, what is the exact input into ft_read_mri ?

The nature of your error suggests that FT has a problem either uncompressing the file, or reading the uncompressed data.

Background: a Freesurfer generated *.mgz file is a zipped file which is to be uncompressed on-the-fly before it can be read. The uncompression step attempts to write some file into a temporary directory (in your case starting with /scratch/tp..../, but it is a bit unclear to me why the filename is something like blablab.load_mgh.m.mgh...

I would expect you to have done something like:

mri = ft_read_mri('<some-path>/mri/T1.mgz'); and not mri = ft_read_mri('load_mgh.m')

**Comment by michaelruvalcaba** [comment]
> I suggest to [add a breakpoint](s.html) at the offending line. Once the breakpoint is hit, I would execute the command `class(tmp)` to see what type it is. Dot indexing is typically for structure variables. It seems like `tmp` is not ending up as a struct variable as expected by the code.

Hi Vijay. Thank you for your suggestion. The offending line is line 401 correct (ndmis = numel)?

**Comment by michaelruvalcaba** [comment]
> In addition to Vijay's suggestion it would be helpful if you provide us with the full error stack (i.e. all the red stuff that matlab prints), and some more information about the fieldtrip version you have been using. Line 401 in ft_read_mri in my FieldTrip does not relate to the code that you pasted. Therefore, it is difficult to judge. Also, are you running on windows? Also, what is the exact input into ft_read_mri ?
> 
> The nature of your error suggests that FT has a problem either uncompressing the file, or reading the uncompressed data.
> 
> Background: a Freesurfer generated *.mgz file is a zipped file which is to be uncompressed on-the-fly before it can be read. The uncompression step attempts to write some file into a temporary directory (in your case starting with /scratch/tp..../, but it is a bit unclear to me why the filename is something like blablab.load_mgh.m.mgh...
> 
> I would expect you to have done something like:
> 
> mri = ft_read_mri('/mri/T1.mgz'); and not mri = ft_read_mri('load_mgh.m')

Hi Jan. 

The entire error is:
```
/bin/bash: /scratch/tp8b1bdb8d_514a_4abc_9438_4b27f2cf52f1.load_mgh.m.mgh: Permission denied

ERROR: could not open /scratch/tp8b1bdb8d_514a_4abc_9438_4b27f2cf52f1.load_mgh.m.mgh for reading
ERROR: loading /home/knight/ecog/DATA_FOLDER/Loma_Linda/LL10/3D_Images/freesurfer_pre-op/freesurfer/mri/T1.mgz as MGH
Dot indexing is not supported for variables of this type.

Error in ft_read_mri (line 401)
    ndims = numel(size(tmp.vol));

Error in LL10_Recon_Pipeline (line 196)
fsmri_pre_acpc = ft_read_mri([subdir '3D_Images/freesurfer_pre-op/freesurfer/mri/T1.mgz']);

```

The Freesurfer version I am using is 5.3.0-modified-perl

The specific command I am trying to run that is generating the error is:
```
fsmri_pre_acpc = ft_read_mri([subdir '3D_Images/freesurfer_pre-op/freesurfer/mri/T1.mgz']);
```

Also, when I tried navigating to the T1.mgz file to open it, it says "T1.mgz: Lzma library error: Corrupted input data"

I'm not sure what that means. Thank you!!

**Comment by michaelruvalcaba** [comment]
> In addition to Vijay's suggestion it would be helpful if you provide us with the full error stack (i.e. all the red stuff that matlab prints), and some more information about the fieldtrip version you have been using. Line 401 in ft_read_mri in my FieldTrip does not relate to the code that you pasted. Therefore, it is difficult to judge. Also, are you running on windows? Also, what is the exact input into ft_read_mri ?
> 
> The nature of your error suggests that FT has a problem either uncompressing the file, or reading the uncompressed data.
> 
> Background: a Freesurfer generated *.mgz file is a zipped file which is to be uncompressed on-the-fly before it can be read. The uncompression step attempts to write some file into a temporary directory (in your case starting with /scratch/tp..../, but it is a bit unclear to me why the filename is something like blablab.load_mgh.m.mgh...
> 
> I would expect you to have done something like:
> 
> mri = ft_read_mri('/mri/T1.mgz'); and not mri = ft_read_mri('load_mgh.m')

Also, the scratch file that it is mentioning doesn't even exist :(

**Comment by schoffelen** [comment]
The lines that start with ERROR: are generated by freesurfer's MRIread function. These should probably be addressed first, before we can be sure whether it is a problem with fieldtrip.

You have still not provided us with information about the operating system, nor about the fieldtrip version. To avoid the possibility that you are using a stale version of fieldtrip, could you please try whether your error reproduces with the latest fieldtrip version?

Also, could you also please report the output that matlab gives when you type the following on the command line:

which MRIread

**Comment by michaelruvalcaba** [comment]
> I suggest to [add a breakpoint](s.html) at the offending line. Once the breakpoint is hit, I would execute the command `class(tmp)` to see what type it is. Dot indexing is typically for structure variables. It seems like `tmp` is not ending up as a struct variable as expected by the code.

Hi Vjay,

I added the breakpoint and ran 'fsmri_pre_acpc = ft_read_mri([subdir '3D_Images/freesurfer_pre-op/freesurfer/mri/T1.mgz']);' and the output I get is:
```
/bin/bash: /scratch/tp669d11ac_84e2_4b12_b901_4b9ecfc417f1.load_mgh.m.mgh: Permission denied

ERROR: could not open /scratch/tp669d11ac_84e2_4b12_b901_4b9ecfc417f1.load_mgh.m.mgh for reading
ERROR: loading /home/knight/ecog/DATA_FOLDER/Loma_Linda/LL10/3D_Images/freesurfer_pre-op/freesurfer/mri/T1.mgz as MGH
K>> 
```
Then I typed class(tmp) in the command window and received 'double'

**Comment by schoffelen** [comment]
To reiterate: there is a problem with MRIread that does not manage to unzip the file on the fly. Again, my question is: what is the operating system you are working on? Also, if you open fieldtrip/external/freesurfer/load_mgh.m you will see that from line 55 onwards there is some code that attempts to unzip the *.mgz file, creating a temporary filename that includes the string load_mgh.m etc. This is where it goes wrong for you, because the computer you are working on apparently does not manage to create the unzipped file.

**Comment by michaelruvalcaba** [comment]
Hi Jan,

I am using an nxserver on my mac and do you know how I can check my
fieldtrip version? All I have is a folder called fieldtrip, but I am not
sure where to navigate to find the version.

When running which(MRIread) this is what I get:

>> which(MRIread)
mri = MRIread(fstring,headeronly,permuteflag)
Error using which
Must be a string scalar or character vector.


Best,
Michael Ruvalcaba
Knight Lab
Helen Wills Neuroscience Institute
University of California, Berkeley

**Comment by schoffelen** [comment]
I don't know what an 'nxserver' is. Also, you should type either which('MRIread') or which MRIread, not which(MRIread)

**Comment by michaelruvalcaba** [comment]
This is what I get:

```
>> which MRIread
/srv/local/freesurfer_x86_64-7.2.0/matlab/MRIread.m
```

Ah this may be the issue because I was running freesurfer 5.2.0 instead of
7.2.0?

Best,
Michael Ruvalcaba
Knight Lab
Helen Wills Neuroscience Institute
University of California, Berkeley

**Comment by schoffelen** [comment]
I don't think so. The matlab code that the freesurfer people have written, is very old, and hardly ever updated.

I think that you have a permission problem, and cannot write to the assumed temporary folder called /scratch/

the matlab code that is shipped with freesurfer uses the function fsgettmppath to determine where to write the temporary file. You may need to tweak this function in order to get it to work, or you may need to specify a dummy environmental variable, or overrule your system's default by specifying setenv('TMPDIR', '<name-of-a-directory-that-exists-and-that-you-have-write-and-read-access-to>')

**Comment by michaelruvalcaba** [comment]
The thing is I do have permission to that folder and the file does not even
exist. Hm.

Best,
Michael Ruvalcaba
Knight Lab
Helen Wills Neuroscience Institute
University of California, Berkeley

**Comment by michaelruvalcaba** [comment]
What's odd is that I have never had a problem with running recon-all on
past subjects but for some reason this is happening with this one.

Best,
Michael Ruvalcaba
Knight Lab
Helen Wills Neuroscience Institute
University of California, Berkeley

**Comment by schoffelen** [comment]
It's not a matter of 'not being able to run recon-all', it seems to be a file access problem on your compute system. Not a FieldTrip problem per se, and not something that I can solve for you. Please check in with your local system administrator, or with your peers to get it fixed for you.

**Comment by schoffelen** [comment]
Note to self: we may want to consider to improve the FT codebase, in that we build in a check whether the freesurfer contributed reading functions return an output as expected. Right now, those functions typically produce textual output without actually throwing an error, if things go wrong.

**Comment by schoffelen** [comment]
candidate functions to consider are:
ft_read_mri
ft_read_atlas
ft_read_headshape
