### ISSUE TITLE
BIDS with NaN samples

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2096]
This dataset fails to import

https://openneuro.org/datasets/ds002680/versions/1.2.0

Because there are NaNs in the sample column (onset column is OK). It does pass the validator.

https://openneuro.org/datasets/ds002680/versions/1.2.0/file-display/sub-002:ses-01:eeg:sub-002_ses-01_task-gonogo_run-1_events.tsv

**Comment by arnodelorme** [comment]
Aug 8th 2022 was my last pull

**Comment by schoffelen** [comment]
sorry @arnodelorme I was unclear. What snippet of code did you run, causing the 'failure to import' said data?

**Comment by arnodelorme** [comment]
You place the dataset above in 

```
cfg.dataset = xxxx
```

And then call any Fieldtrip function.

**Comment by schoffelen** [comment]
With the current version of the code and downloaded data (using run 1 for subject 2 as referred to above), I cannot reproduce the earlier error: 

>> filename=fullfile(pwd,'sub-002_ses-01_task-gonogo_run-01_eeg.set');
>> event=ft_read_event(filename);
found matching BIDS sidecar '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_events.tsv'
reading header information from '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_eeg.json'
reading '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_eeg.json'
>> cfg.dataset = filename;
>> cfg.trl = [1 1000 0];
>> data=ft_preprocessing(cfg);
found matching BIDS sidecar '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_eeg.json'
reading '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_eeg.json'
found matching BIDS sidecar '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_channels.tsv'
reading '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_channels.tsv'
found matching BIDS sidecar '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_electrodes.tsv'
reading '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_electrodes.tsv'
found matching BIDS sidecar '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_coordsystem.json'
reading '/home/dyncon/jansch/Downloads/ds002680/sub-002/ses-01/eeg/sub-002_ses-01_task-gonogo_run-01_coordsystem.json'
Warning: First argument must be text. 
processing channel { 'FP1' 'FP2' 'F3' 'F4' 'C3' 'C4' 'P3' 'P4' 'O1' 'O2' 'F7' 'F8' 'T3' 'T4' 'T5' 'T6' 'FZ' 'PZ' 'T5'' 'T6'' 'O1'' 'O2'' 'P3"' 'P4"' 'PZ"' 'OZ' 'I' 'CB1"' 'CB2"' 'CB1' 'CB2' }
reading and preprocessing
reading and preprocessing trial 1 from 1

the call to "ft_preprocessing" took 6 seconds and required the additional allocation of an estimated 5 MB
>>
