### ISSUE TITLE
Issue with loading raw data from Neuralynx

### ISSUE THREAD

**Issue by georgiosspyropoulos** [fieldtrip/fieldtrip#2100]
Hello,

I am having issues with extracting individual channels (32 channels of voltage recordings and eyedata in the .bin format) from a raw Neuralynx datafile (.nrd). This issue is present for some sessions, which are interspersed by sessions that are loaded without trouble. 
Specifically, I am getting the following error when using ft_spikesplitting:

**Error using read_neuralynx_dma (line 240)
problem with STX at the end of the file
Error in ft_read_header (line 1757)
    hdr = read_neuralynx_dma(filename);
Error in ft_spikesplitting (line 80)
hdr = ft_read_header(cfg.dataset, 'headerformat', cfg.headerformat);**

I am using the latest version of fieldtrip in Matlab 2020b, which is ran in Red Hat Enterprise Linux 8.2 (Ootpa).

An example raw data file/session can be found at:

https://www.dropbox.com/sh/tsdlvpd71tft2u6/AABJCzWcZoutDSpUVFzseuRra?dl=0

Please let me know if you need an invitation to the dropbox folder.

The code I am using for the extraction is a version of the following:

**root = folder 

filename = fullfile(root, 'DigitalLynxRawDataFile.nrd');

% Add path of fieldtrip e.g. addpath('/mnt/hpc/opt/fieldtrip_esi/private/')

cd('/mnt/hpc/opt/fieldtrip_esi/private/')

% extract bin files for each channel

cfg = [];
cfg.dataset = filename;
cfg.output  = fullfile(root, 'recording.smda'); % output directory
cfg.latency = [0 inf];          % define the segment of the original data to split
cfg.format  = 'int32';
cfg.channel = 'all';
cfg         = ft_spikesplitting(cfg);**

I suspect that the files that are giving me trouble were corrupted during transfer, but is there a way to restore them, even partially?

I would appreciate any and all help...

-Giorgos

**Comment by schoffelen** [comment]
Too bad about the files being (likely) corrupted. I am not sure how we could be of help at this point? I would start with using the debugger and inspect the matlab workspace just before the error is thrown. Also, I would look up the technical document that describes the file format in detail, in order to understand why the particular error that you report is thrown to begin with. The error is thrown because a number - expected to be 2048 - turns out to be different. I don't know what that would mean in practice, and also I don't know whether that means that the data that is still 'in the file' is to be trusted at all.

**Comment by robertoostenveld** [comment]
This `nrd` corruption is something I have encountered in the past with our own data as well, and I suspect that we might have some code that (as an example or faq on the website or so) can help with this. Similar as https://www.fieldtriptoolbox.org/faq/discontinuous_neuralynx/

I can take this onto me.

**Comment by robertoostenveld** [comment]
@georgiosspyropoulos can you try the code below? It will copy the file into multiple chunks, one for each correct piece. 

```
function fix_neuralynx_nrd(infile, outfile)

% FIX_NEURALYNX_NRD reads a raw data file sample-by-sample, checks the STX
% and CRX and (when correct) writes it to a new file. If an error is
% detected, it starts a new file and continueswith the remaing correct
% samples.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% The data is simply a stream of constant size records,  the size of the
% record is dependent on the number of Input Boards in the system.  8 in your
% case, there are 32 - 32 bit integers from each Input Board.
%
% // Digital Lynx Packets look like this for a 1 board system:
% // stx (or SOP)    0x00000800
% // Packet ID       0x00000001
% // siz             0x0000002A   (# A/D data ints + #extra wds = 32+10)
% // TimeStamp Hi    1 32 bit word
% // TimeStamp Low   1 32 bit word
% // cpu             1 32 bit word
% // ttl             1 32 bit word
% // 10 extras      10 32 bit words
% // A/D data       32 32 bit words per board
% // CRC             1 32 bit XOR of the entire packet including stx
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% since Cheetah 4.80 the DMS log files have a 16384 byte header
% determine whether that is the case in this file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fid = fopen(infile, 'rb', 'ieee-le');
buf = fread(fid, 10, 'uchar=>uchar');
if all(buf(1:4)==35)
  % the file starts with "####"
  hdroffset = 16384;
elseif all(buf>31 & buf<127)
  % the file does not start with "####" but the header seems to be ascii anyway
  hdroffset = 16384;
else
  hdroffset = 0;
end

if hdroffset
  fseek(fid, 0, 'bof');
  orig = fread(fid, [1 hdroffset], 'uint8=>char');
else
  orig = [];
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% since Cheetah 5.0 the DMA log file does not always start with a complete
% packet but can start with an incomplete "junk" packet after the header.
% The junk due to that incomplete packet should then also be skipped.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if hdroffset
  % skip the standard ascii header
  fseek(fid, hdroffset, 'bof');
  % read a single block
  buf = fread(fid, 274, 'uint32=>uint32');
  % search for the first known values of a proper packet
  junk = find((buf(1:(end-1))==2048) & (buf(2:(end-0))==1), 1) - 1;
  if ~isempty(junk)
    % add the additional junk samples to the header offset
    hdroffset  = hdroffset + junk*4;
  end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% since modifying our hardware from 256 to 32 channel (19 March 2007), the
% number of channels in a DMA log file can vary. Start with the assumption
% that the file is from the 256 channel system with 8 boards that we have
% in Nijmegen and verify the CRC
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nboards    = 8;
nchanboard = 32;
blocksize  = nboards*nchanboard+18; % in 4 byte words
fseek(fid, hdroffset, 'bof');
% read a single block
buf = fread(fid, blocksize, 'uint32=>uint32');
% determine the number of boards by systematically checking the CRC value
while (nboards>0)
  if neuralynx_crc(buf(1:blocksize-1))==buf(blocksize)
    % the CRC is correct for this number of boards
    break
  else
    nboards    = nboards - 1;           % decrease by one
    blocksize  = nboards*nchanboard+18; % in 4 byte words
  end
end

if ~nboards
  error('could not determine the number of boards and channels');
end

sample = 1;
fseek(fid, hdroffset, 'bof');

part = 1;
fprintf('starting new file\n');
[p, f, x] = fileparts(outfile);
outfid = fopen(fullfile(p, [sprintf('%s-%03d', f, part) x]), 'w');
fwrite(outfid, orig);

while ~feof(fid)
  buf = fread(fid, blocksize, 'uint32=>uint32');
  check_stx = buf(1)==2048;
  check_crc = buf(end)==neuralynx_crc(buf(1:blocksize-1));
  if ~check_stx || ~check_crc
    fprintf('error at sample %d\n', sample);
    fclose(outfid);

    % search for the first known values of a proper packet
    junk = find((buf(1:(end-1))==2048) & (buf(2:(end-0))==1), 1) - 1;
    fseek(fid, 'cof', -blocksize+junk*4);

    part = part + 1;
    fprintf('starting new file\n');
    outfid = fopen(fullfile(p, sprintf('%s-$03d', f, part), x), 'w');
    frwite(outfid, orig);

  else
    fwrite(outfid, buf);
    sample = sample + 1;
  end
end
fclose(outfid);
fclose(fid);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SUBFUNCTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function crc = neuralynx_crc(dat)
crc = zeros(1,1,class(dat));
for i=1:length(dat)
  crc = bitxor(crc, dat(i,:));
end

```

**Comment by georgiosspyropoulos** [comment]
Dear Robert,

First of all, I greatly appreciate your help. 

I ran the code you shared with me on the example session I provided via dropbox and got the following error:

**error at sample 25579161
Error using fseek
Offset must be a double.
Error in fix_neuralynx_nrd (line 113)
    fseek(fid, 'cof', -blocksize+junk*4);** 

Does this make any sense to you?

All the best,

Giorgos

**Comment by robertoostenveld** [comment]
No it does not. Please use `dbstop if error` to see what is going on by stopping in the MATLAB debugger at the line that causes your problem.

**Comment by schoffelen** [comment]
@georgiosspyropoulos what is the status of this? Does it need input from our end to get this resolved? If not, I suggest to close the issue.

**Comment by georgiosspyropoulos** [comment]
Dear Jan-Mathijs,

The issue hasn't been resolved from the fieldtrip side. However, I was
informed that there is available software from NeuraLynx that I used to
successfully extract the channels from the raw data file: This means that
the raw data file was not corrupt after all. The software can be looked
into and potentially be integrated into fieldtrip by anyone with the
technical know-how/time, and can be found here:
https://neuralynx.com/software/category/matlab-netcom-utilities

All the best,

Giorgos
