### ISSUE TITLE
Fix units when reading NeuroOmega files

### ISSUE THREAD

**Issue by richardkoehler** [fieldtrip/fieldtrip#2110]
**Description**
When reading in MatLab files from NeuroOmega amplifiers using for example:
`ft_read_data(file, 'header', hdr, 'dataformat', 'neuroomega_mat', 'headerformat', 'neuroomega_mat')`,
the data in units of `µV` is currently calculated by dividing the array of values of each channel, which are an array of integers:

![grafik](https://user-images.githubusercontent.com/70506259/191917151-7c54429f-11eb-4b20-ba56-dd1d6b2ab656.png)

by the `BitResolution` of each channel, which is a `double`:

![grafik](https://user-images.githubusercontent.com/70506259/191917343-956514d5-8c49-492b-92a0-5a65d8d95118.png)

---

**However**, according to communication with the manufacturer, the file also contains  the `Gain` for each channel:

![grafik](https://user-images.githubusercontent.com/70506259/191923334-9ff74ca3-f327-49e2-9bd0-dab9fa59c92c.png)

... which we must also divide by to acquire the actual value in `µV`, like: `data[µV] = rawdata[int] * BitResolution / Gain`.

---

**Two checks** additionally convinced me that this must be true:
1. In my case for an ECoG recording: `BitResolution / Gain => 38.147 / 55 ~ 0.7`, which is the ` Input Bit Resolution` specified in the user manual (see last row):
![grafik](https://user-images.githubusercontent.com/70506259/191924277-52265c04-ef0f-45cf-bf2e-02b4b387614b.png)

2. We performed a recording with a NeuroOmega amplifier and a 2nd amplifier (TMSi Saga) in the same session, and only if we divide by the gain (55), do the power spectra line up:
![grafik](https://user-images.githubusercontent.com/70506259/191927406-600bd46b-019c-401b-88d0-bd8a8cd9ecb9.png)
If we do not divide by the gain the power spectra do not match:
![grafik](https://user-images.githubusercontent.com/70506259/191927337-6ca9d084-2ef7-4357-ba17-ad8506b85ed3.png)

---

Of course, I am open for discussion and I want to stress that I am neither a computer nor data scientist so I might be missing some background information.
I will create a draft pull request though, as a suggestion to fix this issue.

---

**Environment and versions:**
 - Operating System: Windows 11
 - MATLAB version: R2021b
 - FieldTrip version: most recent master branch from github

**Comment by schoffelen** [comment]
Hi @richardkoehler, thanks for reporting this, and suggesting this improvement. I don't know whether there are many people who use this particular data format in combination with FieldTrip, so I am not sure who could chime in here. We (i.e. the people at Donders) don't work with this particular data format, and we don't have any test data on the shelf to confirm/disconfirm your diagnosis. To take this forward, I would suggest to make this PR a genuine PR by asking you to make the suggested code changes, and ideally also send us a small snippet of test data + accompanying code that can be used for verification. Does that sound like a plan?
