### ISSUE TITLE
ft_trialfun_general cannot recognise trialvalues with "0"

### ISSUE THREAD

**Issue by tiborauer** [fieldtrip/fieldtrip#2117]
A recent commit has updated how ft_trialfun_general recognises character trailvalues, and it excludes "0" from valid characters:
https://github.com/fieldtrip/fieldtrip/blob/616a14c5a516967f208f3ad18118e642393c4e79/trialfun/ft_trialfun_general.m#L195
I wonder whether the exclusion of "0" is intentional or the code should be like this:
```matlab
elseif ischar(event(i).value) && ~isempty(regexp(event(i).value, '^[SR]+[\s]*+[0-9]{1,3}$')) 
```

**Comment by schoffelen** [comment]
My bad @tiborauer, feel free to submit a PR
