### ISSUE TITLE
include sessions.tsv for data2bids

### ISSUE THREAD

**Issue by JonathanVHoecke** [fieldtrip/fieldtrip#2120]
For the data2bids functions,
there is currently no automatic sessions.tsv file created.

This modality agnostic file is optional, but a key component when having multiple sessions for a subject.
My suggestion would be to include it very similar as the scans.tsv, but it is one level up (listing the sessions, instead of the scans) as soon as there are multiple sessions.

https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#sessions-file

Thank you very much for your help
Jonathan Vanhoecke,
ICN Lab - Charité Berlin

**Comment by robertoostenveld** [comment]
That is a good idea. For the optional `scans.tsv` it is clear what it can contain (a list of runs, i.e. recordings. I just added it to the data2bids code and used the following to test it:

```
cfg = [];
data = ft_timelocksimulation(cfg);

cfg = [];
cfg.datatype = 'eeg';
cfg.bidsroot = 'bids';
cfg.sub = '01';

cfg.ses = '01';
cfg.sessions.acq_time = datetime(now, 'ConvertFrom','datenum');
cfg.sessions.pathology = 'healthy';
data2bids(cfg, data);

cfg.ses = '02';
cfg.sessions.acq_time = datetime(now + datenum(days(7)), 'ConvertFrom','datenum');
cfg.sessions.pathology = 'sick';
data2bids(cfg, data);

cfg.ses = '03';
cfg.sessions.acq_time = datetime(now + datenum(days(14)), 'ConvertFrom','datenum');
cfg.sessions.pathology = 'healthy';
cfg.run = 1;
data2bids(cfg, data);

cfg.run = 2;
data2bids(cfg, data);
```

could you give it a try and check that it works as expected?

**Comment by robertoostenveld** [comment]
... and if not, please reopen this issue.

**Comment by JonathanVHoecke** [comment]
Thanks, Robert, for your quick reply! I am going to a conference now, I'll test it end of this week 👍

**Comment by JonathanVHoecke** [comment]
@robertoostenveld 
Dear Robert, I can confirm that your adaptations worked in adding separate fields (custom columns) to the sessions.tsv.
I need to test to combine different sessions across multiple subjects, but I would get back to you if it does not work out.
(I expect behavior to be analogue to the scans.tsv)

![image](https://user-images.githubusercontent.com/72917013/197416973-73491bef-7cdf-4864-9b4c-cdd8a2512fe4.png)


Thanks again for your addition

**Comment by JonathanVHoecke** [comment]
@robertoostenveld
Dear Robert. I can confirm it works for multiple subjects with multiple sessions. Thanks again for your help!
![image](https://user-images.githubusercontent.com/72917013/197631371-9d958e3d-8737-4b2a-bb2d-09af8397382a.png)
