### ISSUE TITLE
ft_freqanalysis

### ISSUE THREAD

**Issue by SepidehKhoneiveh** [fieldtrip/fieldtrip#2121]
Hi 
I am new in fieldtrip and I have some problems in running my scripts. 
I want to calculate coherence in my eeg data. using this steps : http://old.fieldtriptoolbox.org/tutorial/coherence?s[]=ft&s[]=freqanalysis
the problem is that I am having problem in calculating frequency domain. I am using the following code:
the problem is that I am getting this error: 
Error using nearest
the value 2053.6 should be within the range of the array from 1 to 50 with a tolerance of 0.25 and 0.25 on both sides

Error in dpss (line 16)
i = nearest(s, time_halfbandwidth, true, true);

Error in ft_specest_mtmfft>double_dpss (line 362)
tap = dpss(double(a), double(b), varargin{:});

Error in ft_specest_mtmfft (line 151)
        tap = double_dpss(ndatsample,ndatsample*(tapsmofrq./fsample))';

Error in ft_freqanalysis (line 627)
      [spectrum,ntaper,foi] = ft_specest_mtmfft(dat, time, 'taper', cfg.taper, options{:}, 'feedback', fbopt)

clc
close all
clearvars
%%
cfg.dataset='data_filt_0.5_30.set';
cfg.hdr=ft_read_header(cfg.dataset);
cfg.data=ft_read_data(cfg.dataset,'header',cfg.hdr);
Data=ft_preprocessing(cfg);
%% laplacian
cfg=[];
cfg.method='spline';
cfg.elec=Data.elec;
data_L=ft_scalpcurrentdensity(cfg, Data);
%%
cfg            = [];
cfg.output     = 'fourier';
cfg.method     = 'mtmfft';
cfg.foilim     = [4 8];
cfg.tapsmofrq  = 5;
cfg.keeptrials = 'yes';
freqfourier    = ft_freqanalysis(cfg, data_L);
 
It means alot if anyone can help me with this problem. 
bests

**Comment by schoffelen** [comment]
Hi Sepideh, could you please ask your question in the appropriate channel, i.e. the online fieldtrip discussion list?
The github issue tracker is not meant for this type of questions.

Best,
Jan-Mathijs

**Comment by schoffelen** [comment]
Hi @SepidehKhoneiveh do you need help in following this up on the discussion list? I was on the look out for your question to appear there, but so far I haven't seen it.
