### ISSUE TITLE
ft_rejectartifact does not allow overlaps

### ISSUE THREAD

**Issue by xiaochenzheng** [fieldtrip/fieldtrip#2124]
**Describe the bug**
I have EEG segments which have overlapped samples. It used to work with an old fieldtrip version but not anymore (see error message attached. 
For ft_databrowser i can add cfg.allowoverlap = 'yes', but this does not seem to work for ft_rejectartifact.

**Screenshots**
![image](https://user-images.githubusercontent.com/22767241/198258114-7671fd70-e937-4563-9bc0-9588a2dee0a1.png)

**Additional context**
The issue has been discussed on DCCN mattermost.

**Comment by schoffelen** [comment]
issue can be confirmed with the below code

function test_issue2124

% MEM 2gb
% WALLTIME 00:10:00
% DEPENDENCY ft_rejectartifact

% reported issue is that ft_rejectartifact (with data in the input) fails
% on overlapping data segments, which used to work in the past

% create a minimal data example
data = [];
data.trial{1} = randn(1,100);
data.trial{2} = randn(1,100);
data.time{1}  = (0:99)./100;
data.time{2}  = (0:99)./100;
data.label    = {'label'};
data.sampleinfo = [1 100;51 150];

cfg = [];
cfg.artfctdef.reject   = 'complete';
cfg.artfctdef.zvalue.artifact = [11 20];
dataout = ft_rejectartifact(cfg, data);
