### ISSUE TITLE
ft_preproc_derivative does not take the length of the time step into account

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#2129]
**Describe the bug**
Currently ft_preproc_derivative does not 'correct' for the length of the time step. This leads to the computed gradient being sampling frequency dependent.

**To Reproduce**
   x = sin((0:999).*2.*pi); dx = gradient(x); dx2 = gradient(x(1:2:end)): % gradient is used in ft_preproc_derivative
   figure;plot(dx);hold on;plot(dx2); 
   figure;plot(0:999, dx); hold on;plot(0:2:999, dx2);
   figure;plot(0:999, dx); hold on;plot(0:2:999, dx2./2);

**Expected behavior**
One could argue that the computed gradient should be independent of the 'deltaT'. This can be achieved by including information about fsample in ft_preproc_derivative

**Additional context**
I came across this by working on an example to detect saccades from eyetracker data, where the algorithm used by eyelink is based on a plain velocity (and accelaration) based thresholding, where the threshold - understandably - is expressed in degree/s (or degree/s^2), i.e. independent of the sampling rate of the signal.

@robertoostenveld I would be in favor of changing the default behavior of ft_preproc_derivative (and in the upstream code). How should we go about this change in behavior, and breach of backward compatibility?)

**Comment by robertoostenveld** [comment]
hmm, good point. Besides using the `gradient` function, we also use `diff` somewhere in preprocessing, right? 

I don't have a solution yet, but thinking this a bit further: should it not also affect the chanunit field, which for MEG would become `T/s` or `T/sample`?

**Comment by schoffelen** [comment]
I did a quick check on diff earlier, but could not locate it right away. It could be that at some point the occurrence of diff was replaced by a call to gradient

**Comment by robertoostenveld** [comment]
there is `cfg.absdiff` for jump detection.

**Comment by schoffelen** [comment]
the absdiff option in preproc does a plain abs(diff(dat, 1, 2));
