### ISSUE TITLE
ft_electroderealign project not projecting

### ISSUE THREAD

**Issue by franquia** [fieldtrip/fieldtrip#2136]
**Describe the bug**
While adapting an electrode array to a headmodel provided in https://www.fieldtriptoolbox.org/workshop/oslo2019/forward_modeling/ (headmodel_dipoli) the tool does not project the electrodes onto the headshape mesh. Instead they get projected onto a plane. 

**To Reproduce**
Following the instrucions from the aforementioned forward modeling tutorial and after importing attached files:

if strcmp(headmodel_dipoli.type, 'bemcp')
scalp_index = 3;
elseif strcmp(headmodel_dipoli.type, 'dipoli')
scalp_index = 1;
end
cfg = [];
cfg.method = 'project'; % onto scalp surface
cfg.headshape = headmodel_dipoli.bnd(scalp_index); % scalp surface
elec_realigned = ft_electroderealign(cfg, elec);

figure
hold on
ft_plot_sens(elec_realigned, 'elecsize', 40);
ft_plot_headmodel(headmodel_dipoli, 'facealpha', 0.5);
view(90, 0)

Units of both electrodes and headmodel in mm. Tried also to convert both to m with 'ft_convert_units()' without any change. 

**Expected behavior**
Projection of the electrodes on to the head surface mesh. 

**Screenshots**
Initial situation:
![imagen](https://user-images.githubusercontent.com/118190595/201680558-0c75c2d9-a994-478c-a2a5-07a4426e379f.png)

After executing projection:
![imagen](https://user-images.githubusercontent.com/118190595/201680446-abc822b9-6202-42a4-8a93-429c812b1a6a.png)
![imagen](https://user-images.githubusercontent.com/118190595/201680765-c9a56ce7-7e83-4dfd-82d4-afd8e96fa40f.png)

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10
 - MATLAB version R2021a
 - FieldTrip version : ft_version returns unknown, i downloaded it from github on 30/10/2022

**Additional context**
Could not add headmodel_dipoli to the zip because of the size of the file. However it was the file downloaded straight from your page.

[Simulations.zip](https://github.com/fieldtrip/fieldtrip/files/10003760/Simulations.zip)

**Comment by robertoostenveld** [comment]
I can confirm a weird projection with the `headmodel_dipoli.mat` from https://download.fieldtriptoolbox.org/workshop/oslo2019/forward_modeling/ and your `elec_manual.mat` file.

However, you write that both are in mm, which seems incorrect. The head model is in meter, and has numbers like this

````
>> cfg.headshape.pos(1:10,:)
ans =
    0.0025    0.0035    0.1135
    0.0015    0.0105    0.1125
   -0.0065    0.0045    0.1125
   -0.0035   -0.0055    0.1145
    0.0065   -0.0095    0.1155
    0.0165   -0.0025    0.1135
    0.0185    0.0085    0.1115
    0.0125    0.0185    0.1105
    0.0025    0.0225    0.1115
   -0.0085    0.0205    0.1105
````

 whereas your elec structure is specified to be in `mm`, but the numbers are like this 

````
>> elec.elecpos(1:10,:)
ans =
   -0.0243    0.1015    0.0272
    0.0247    0.1016    0.0272
   -0.0414    0.0684    0.0677
    0.0424    0.0693    0.0687
   -0.0574    0.0106    0.0797
    0.0585    0.0106    0.0800
   -0.0568   -0.0562    0.0601
    0.0569   -0.0588    0.0604
   -0.0366   -0.0888    0.0026
    0.0356   -0.0900    0.0015
````

which looks more like they are expressed in m than mm. 


If you plot both of them with their respective individual units, 

````
figure
hold on
ft_plot_sens(elec, 'elecsize', 40, 'unit', 'mm');
ft_plot_headmodel(headmodel_dipoli, 'facealpha', 0.5, 'unit', 'm');
view(90, 0)
`````

it looks fine (this is actually what you are doing if you don't specify the `unit` option) , but if you plot them with the **same** units

````
figure
hold on
ft_plot_sens(elec, 'elecsize', 40, 'unit', 'mm');
ft_plot_headmodel(headmodel_dipoli, 'facealpha', 0.5, 'unit', 'mm');
view(90, 0)
````

you'll see that they don't match.

When I convert the units of your elec structure in meter, then it works fine

````
cfg = [];
cfg.method = 'project'; % onto scalp surface
cfg.headshape = headmodel_dipoli.bnd(scalp_index); % scalp surface
elec_realigned = ft_electroderealign(cfg, elec);

figure
hold on
ft_plot_sens(elec, 'elecsize', 10);
ft_plot_sens(elec_realigned, 'elecsize', 10);
````

And I see a small shift in the electrodes: 

<img width="672" alt="Screenshot 2022-11-14 at 16 22 29" src="https://user-images.githubusercontent.com/899043/201697992-3be9e9d7-4a88-4cd9-9784-1fcb9f38aee4.png">

**Comment by robertoostenveld** [comment]
So in short: you assigned the wrong units to your elec structure. The numbers are consistent with the units being in meter, but you specified mm. The headmodel is actually in meter. When you plot them together - ignoring the units - it looks fine. But ft_electroderealign does not ignore the units and projects all electrodes (which are in the middle of the head) on a triangle that is probably somewhere at the neck.
