### ISSUE TITLE
improve support for HED tags when defining and selecting trials/epochs

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2138]
**Is your feature request related to a problem? Please describe.**

HED is one of the standards incorporated in BIDS. It allows the specification of evens with tags that convey much more information than trigger codes. When analyzing a BIDS-formatted dataset with HED tags, I would like house those tags in definetrial, preprocessing, and trial-selection in subsequent analysis steps. 

**Describe the solution you'd like**

Ideally `ft_definetrial` with all defaults would recognize the HED tags; this would require updates to `ft_trialfun_general`.Alternatively, we write a `ft_trialfun_hed` and put that in https://github.com/fieldtrip/fieldtrip/tree/master/trialfun

Furthermore, documentation on the website should make this visible.

**Describe alternatives you've considered**

The user writes their own trialfun.

**Additional context**

This is something that I discussed with the HED development team during their progress meeting.

... tagging @VisLab, @dungscout96, @arnodelorme; please tag others that should be in the loop.

**Comment by robertoostenveld** [comment]
Regarding documentation, https://www.fieldtriptoolbox.org/example/getting_started_with_reading_raw_eeg_or_meg_data/ is a very general "getting started" page

The page https://www.fieldtriptoolbox.org/example/making_your_own_trialfun_for_conditional_trial_definition/ explains so-called `trialfuns`, i.e. custom functions for a more fancy translation of events or triggers into a specification of trials/epochs.

The page https://www.fieldtriptoolbox.org/faq/what_is_the_relation_between_events_such_as_triggers_and_trials/ documents `events` as they are used in FieldTrip. 

The page https://www.fieldtriptoolbox.org/example/bids/ gives an intro on BIDS and pointers to concrete examples to use [data2bids](https://www.fieldtriptoolbox.org/reference/data2bids) for dataset conversion/curation.

**Comment by robertoostenveld** [comment]
Using the example dataset, I have made some changes to the fieldtrip code in #2139. The important one is that [fileio/private/events_tsv.m](https://github.com/fieldtrip/fieldtrip/pull/2139/files#diff-d51e6fe2374b2b703896ef01607f40a80d80aff097747f175920058e77c8b7cd) now explicitly deals with the HED column. There were no changes needed in the higher-level code of `ft_read_event`, `ft_trialfun_general` or `ft_definetrial`.

**Comment by robertoostenveld** [comment]
the following script now works, where the last section is using the HED tags

```
%%

bidsroot = dccnpath('/home/common/matlab/fieldtrip/data/test/issue2138');

% this is the original
filename1 = fullfile(bidsroot, 'sub-001/ses-01/eeg/sub-001_ses-01_task-WorkingMemory_run-1_eeg.set');

% this is the one with enriched HED tags
filename2 = fullfile(bidsroot, 'sub-002/ses-01/eeg/sub-002_ses-01_task-WorkingMemory_run-1_eeg.set');

%%
% just to check that this works

hdr1 = ft_read_header(filename1, 'readbids', false);
event1 = ft_read_event(filename1, 'readbids', false);

hdr2 = ft_read_header(filename2, 'readbids', false);
event2 = ft_read_event(filename2, 'readbids', false);

%%
% default is readbids=true, which causes the sidecars to be read

hdr1 = ft_read_header(filename1);
event1 = ft_read_event(filename1);

hdr2 = ft_read_header(filename2);
event2 = ft_read_event(filename2);

%%
% show the events

cfg = [];
cfg.dataset = filename1;
cfg.trialdef.eventtype = '?';
ft_definetrial(cfg);

cfg = [];
cfg.dataset = filename2;
cfg.trialdef.eventtype = '?';
ft_definetrial(cfg);

%%
% this is some random ERP analysis using "normal" events

cfg = [];
cfg.dataset = filename1;
cfg.trialdef.eventtype = 'show_letter';
cfg.trialdef.eventvalue = {'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z'};
cfg.trialdef.prestim = 0.3;
cfg.trialdef.poststim = 0.7;
cfg = ft_definetrial(cfg);

cfg.baselinewindow = [-inf 0];
cfg.demean = 'yes';
rawdata = ft_preprocessing(cfg);

% make a selective average
cfg = [];
cfg.trials = ismember(rawdata.trialinfo.eventvalue, {'A' 'B' 'C'});
erp = ft_timelockanalysis(cfg, rawdata);

assert(sum(erp.cfg.trials)==9);

%%
% this is the same analysis for a dataset that also contains HED tags

cfg = [];
cfg.dataset = filename2;
cfg.trialdef.eventtype = 'show_letter';
cfg.trialdef.eventvalue = {'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z'};
cfg.trialdef.prestim = 0.3;
cfg.trialdef.poststim = 0.7;
cfg = ft_definetrial(cfg);

cfg.baselinewindow = [-inf 0];
cfg.demean = 'yes';
rawdata = ft_preprocessing(cfg);

% make a selective average
cfg = [];
cfg.trials = ismember(rawdata.trialinfo.eventvalue, {'A' 'B' 'C'});
erp = ft_timelockanalysis(cfg, rawdata);

assert(sum(erp.cfg.trials)==9);

%%
% this is a similar analysis, but now using HED tags

cfg = [];
cfg.dataset = filename2;
cfg.trialdef.eventtype = 'HED';
cfg.trialdef.eventvalue = 'Sensory-event,Visual-presentation,(Character,(Center-of,Computer-screen)),Target,*';
cfg.trialdef.prestim = 0.3;
cfg.trialdef.poststim = 0.7;
cfg = ft_definetrial(cfg);

cfg.baselinewindow = [-inf 0];
cfg.demean = 'yes';
rawdata = ft_preprocessing(cfg);

% make selective averages
cfg = [];
cfg.trials = contains(table2cell(rawdata.trialinfo), 'Items-to-memorize,Item-count,Target,Label/3');
erp_load3 = ft_timelockanalysis(cfg, rawdata);

cfg.trials = contains(table2cell(rawdata.trialinfo), 'Items-to-memorize,Item-count,Target,Label/5');
erp_load5 = ft_timelockanalysis(cfg, rawdata);

cfg.trials = contains(table2cell(rawdata.trialinfo), 'Items-to-memorize,Item-count,Target,Label/7');
erp_load7 = ft_timelockanalysis(cfg, rawdata);
```

how does this look to you @VisLab, @dungscout96, @arnodelorme ?

**Comment by robertoostenveld** [comment]
if these code changes address phase 1 of the desired improvements, we should think about where to document this so that people also start using this. Should we make a HED section under https://www.fieldtriptoolbox.org/getting_started/#getting-started-with-data-from-other-software ? 

Thinking further ahead, we could make further improvements in the automatic expansion of the `events.tsv` with the code book in the `events.json`. That could be HED specific using the restful API to the Python implementation, but it could also be more generic. However, I feel that that falls outside the scope of this issue.

**Comment by robertoostenveld** [comment]
Could someone tag Denise, Deepa and Scott on this? I could not find their github handles.

**Comment by arnodelorme** [comment]
Here is one run from one subject along with the HED dictionary file

https://drive.google.com/drive/folders/16kqXIgs2HMVWCu-dIhe2Cb1T8YeBZ_Bn?usp=share_link

- Dung will take the event file and dictionary and return and updated event file or table with HED columns
- Robert can look into ft_definetrial (or maybe ft_read_event since this might be this function that reads the sidecar file - Robert would know better)
- Arno can work on the ft_trialfun_hed program
- Robert and Arno can work on a draft documentation page

Dung: I created a function to do the assembling in MATLAB. It takes the events.tsv file and the events.json file and calls the web service to do the assembling. Right now the code to communicate with the web service is quite low-level. As most HED tools are being written in Python and made available via REST API, I will probably write more abstract classes to handle the requests/response in the future. (see attached zip file)

[hed_assemble.m.zip](https://github.com/fieldtrip/fieldtrip/files/10043592/hed_assemble.m.zip)

**Comment by dungscout96** [comment]
Tagging @smakeig, @monique2208, @deepagupta

This is a great start! Thanks @robertoostenveld .

Couple questions:
1. The HED annotations do contain which letter was presented, e.g. "(Character,Label/D)" or "(Character,Label/+)". Can you check again in your file?
2. It seems that the `ft_read_header` function searchs for the json sidecar using BIDS inheritance principle. Here the sidecar is at the top-level of the dataset. Is this true?
3. It's not clear to me from the documentation and the examples above how `cfg.trialdef.eventtype` and `cfg.trialdef.eventvalue` works. 

Here's an excerpt of the first two rows of the event table
| onset       | duration | sample | event_type  | task_role | letter | trial | memory_cond | value | HED                                                                                                                                                                                  |
|-------------|----------|--------|-------------|-----------|--------|-------|-------------|-------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 5.716       | 1257.05  | 1430   | show_cross  | fixate    | +      | 1     | 3           | nonWM | Sensory-event,Visual-presentation,(Cross,(Center-of,Computer-screen)),(Task,Fixate),(Character,Label/+),Experimental-trial/1,(Condition-variable/Items-to-memorize,Item-count,Target,Label/3)  |
| 10.96222101 | 305.95   | 2742   | show_letter | to_ignore | D      | 1     | 3           | gD    | Sensory-event,Visual-presentation,(Character,(Center-of,Computer-screen)),Non-target,(Character,Label/D),Experimental-trial/1,(Condition-variable/Items-to-memorize,Item-count,Target,Label/3) |

In the "normal events" example
```
cfg.trialdef.eventtype = 'show_letter';
cfg.trialdef.eventvalue = {'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z'};
```
"show_letter" is a value in the "event_type" column and the letters are values of the "letter" column. It seems that `.eventtype` access the "event_type" column directly. Is this a convention in Fieldtrip? By similar logic, `.eventvalue` seems to index the "letter" column by default, which seems unlikely.

In the example using HED tags
```
cfg.trialdef.eventtype = 'HED';
cfg.trialdef.eventvalue = 'Sensory-event,Visual-presentation,(Character,(Center-of,Computer-screen)),Target,*';
```
`.eventtype` seems to indicate the column and `.eventvalue` specifies the column value.

-----------

This implementation assumes that the HED annotation has already been assembled and put into events.tsv file. This is currently not how we distribute HED for events annotation in BIDS. Here's a draft of a function that takes the events.tsv and events.json files and do the assembling by calling the web service.
[hed_assemble.m.zip](https://github.com/fieldtrip/fieldtrip/files/10043785/hed_assemble.m.zip)
We can integrate this as a routine when dealing with BIDS-HED dataset. @VisLab please feel free to review this function.

**Comment by VisLab** [comment]
Yes, this is indeed a good start! 

There are some details that we need to think about and I'll need to look at the documentation for Fieldtrip to make sure that I understand.

One of the issues is the location of the events. A simple search such as: 
 ```code
contains(table2cell(rawdata.trialinfo), 'Items-to-memorize,Item-count,Target,Label/3');
```

won't work in general because HED tags can appear in any order. Searching probably requires parsing and creating a set or
searching for the tags one at a time. There is some core MATLAB code in the `pop_hedepoch` that does this, but I think it needs updating.

On the documentation, I would be happy to work on.

**Comment by VisLab** [comment]
@dungscout96: I read over the source code for `hed_assemble` and it seems okay.  This function we should probably implement directly at some point in MATLAB.  We're going to have to decide which things to do as web services and which to do directly.

**Comment by robertoostenveld** [comment]
The HED tags do indeed contain letter information, I overlooked that. I have now updated the example/test script so that all three analyses give the same result (the average of A, B, and C trials). See [test_issue2138.m](https://github.com/fieldtrip/fieldtrip/blob/7ab4b04d637ebbe389376a4b82b0e272782c2b50/test/test_issue2138.m).

Rather than using `contains`, the test script now also demonstrates how to use a regular expression to find matching tags. Note however that this part of the logic is in the MATLAB script of the user and not under fieldtrip control. FieldTrip only expects a boolean (or indexed) list in `cfg.trials`, how that list is generated is up to the user.

**Comment by robertoostenveld** [comment]
I have now also added a [ft_trialfun_hed](https://github.com/fieldtrip/fieldtrip/blob/7c85f9b2c237a93aadd5231df9c5f97e0a872b28/trialfun/ft_trialfun_hed.m) that does not use the event structure as returned by `ft_read_event`, but that reads the table and - when needed - assembles the HED tags on the fly. 

@dungscout96 your `hed_assemble`  did not work for me due to `Undefined function 'getSessionInfo'`

**Comment by robertoostenveld** [comment]
What I believe remains to be done is to write some documentation. I suggest that goes under "Getting started with HED", and that would be pull request against https://github.com/fieldtrip/website. Don't worry about formatting of the markdown for the website, I can fix that later.

**Comment by VisLab** [comment]
> 
> @dungscout96 your `hed_assemble` did not work for me due to `Undefined function 'getSessionInfo'`

The `getSessionInfo` is part of a support library for HED web services for MATLAB:
     [https://github.com/VisLab/hed-examples/tree/main/hedcode/matlab_scripts/web_services](https://github.com/VisLab/hed-examples/tree/main/hedcode/matlab_scripts/web_services)

The tutorial [HED services in MATLAB](https://hed-examples.readthedocs.io/en/latest/HedMatlabTools.html) explains the usage with examples.

**Comment by robertoostenveld** [comment]
@dungscout96 thanks, it now works. I have added the `hed_assemble` and dependencies as `fieldtrip/external/hedtools`. I have also added the case where the HED tags are assembled on the fly to the example/test scripts.

**Comment by VisLab** [comment]
**Note the corrected link above for the matlab tools**.  I accidentally put a link to my forked repository not the actual official one. @robertoostenveld.  It is corrected above.
