### ISSUE TITLE
openmeeg after segmentation with ft 

### ISSUE THREAD

**Issue by khoubeib94** [fieldtrip/fieldtrip#2146]
**Describe the bug**
cannot run openmeeg after ft_segmentation because of meshes intersection
i ve tried on plenty of mri 

**Expected behavior**
2 meshes are intersecting !

**Screenshots**
![image](https://user-images.githubusercontent.com/107060619/205080521-c5968015-6abb-4df8-b280-3657c604c964.png)
![image](https://user-images.githubusercontent.com/107060619/205080713-f9cd189f-8839-4008-bfc0-f3e3032d998d.png)

**Environment and versions (please complete the following information):**
 - Operating System: [Windows 10]
 - MATLAB version [ R2021b]
 - FieldTrip version [revision 20210616]

**Comment by schoffelen** [comment]
This is not a bug in the code. It's a bug in your data. You need to check the quality of the segmentation.

**Comment by robertoostenveld** [comment]
you may want to look here https://www.fieldtriptoolbox.org/workshop/natmeg/dipolefitting/#construct-the-eeg-volume-conduction-model where a similar problem is discussed.
