### ISSUE TITLE
Mutual information connectivity analysis changed behaviour

### ISSUE THREAD

**Issue by xvrijdag** [fieldtrip/fieldtrip#2149]
The mutual information connectivity analysis using the IBTB toolbox was working fine in the 2020 version. Recently, I upgraded to the latest 2022 version. The same analysis was no longer providing the same results. The analysis results were now containing complex numbers. 

The following code was used:
            cfg           = [];
            cfg.method    = 'mi';
            cfg.mi.numbin = 20;
            cfg.mi.lags   = 0;
            MI_ibtb{k,expoI}= ft_connectivityanalysis(cfg, data);

By investigating the code changes in this period I noticed that a new method (gcmi) has been added to ft_connectivity_mutualinformation, however the IBTB toolbox methods are still intact. To maintain backwards compatibility the method is set to ibtb if not defined.

By investigating the changes in ft_connectivityanalysis I found that the cfg.mi.methods is set to gcmi in line 379. This makes the code not backward compatible. I would suggest to change this to ibtb.

I confirmed this to be the issue by adding cfg.mi.method = 'ibtb'; to the code above.

**Comment by schoffelen** [comment]
Hi Xavier,

In ft_connectivityanalysis, 'mi' is an undocumented method. However, if the user defines 'mi' as method, in line 379 the (sub)method is defined by default to be 'gcmi'. The reason for this, is that the 'ibtb' is not activelly supported anymore, and the 'gcmi' method is superior to the binned method as implemented in the ibtb-toolbox. The lower level ft_connectivity_mutualinformation function still has 'ibtb' as the old default, but this indeed is overwritten by 'gcmi' if the user calls the function (as desired) from ft_connectivityanalysis. I agree that this is confusing. 

I suggest to change the default in ft_connectivity_mutualinformation to 'gcmi'. 

You can then still use 'ibtb' (for as long as it works) by explicitly specifying it in the cfg for ft_connectivityanalysis.

Will you make the change and submit as a PR?

PS: this still does not explain the complex values you get, but that's I think something different.

**Comment by schoffelen** [comment]
Hi Xavier,

What is the difference between a documented and undocumented method?
Would have probably been nice with the introduction of GCMI to make a note in the ft_connectivity_mutualinformation file to document this suggested change of methodology.

That would have been nice indeed. That’s why I always nudge people to add suggestions for changes to documentation and code.

Best wishes,

Jan-Mathijs


Any idea where I need to start looking to understand why I get complex results from GCMI?

Switch on the debugger and start going through the code line-by-line.

Best wishes,
Jan-Mathijs
