### ISSUE TITLE
Increasing uniformity with DIPFIT/EEGLAB

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2158]
@robertoostenveld. Instead of using the file in DIPFIT

```
dipfit/standard_BEM/standard_vol.mat
```

is it possible to use

```
template = ft_read_headmodel('standard_bem.mat');
```

The two files look to have the same coordinate system, same surfaces, etc... They are slightly different but look like different versions of the same model. Thanks.

**Comment by arnodelorme** [comment]
In fact, we could remove the files in [DIPFIT](https://github.com/sccn/dipfit). However, the Fieldtrip version does not have the elec subfolder and the [electrodes](https://github.com/sccn/dipfit/blob/master/standard_BEM/elec/standard_1005.elc) aligned with the model. Could they be added to Fieldtrip?

**Comment by robertoostenveld** [comment]
I indeed believe then to be the same, or at least to come from the same source. It is the BEM model that I made for this simulation study <https://doi.org/10.1016/s1388-2457(01)00460-6>.

FieldTrip also includes the corresponding electrodes, those are in the `fieldtrip/template/electrode` directory. The ones that start with "standard_" are the ones that fit on the head. And the MRI is included in `fieldtrip/template/anatomy` as `single_subj_T1.nii` (at 2 mm) and `single_subj_T1_1mm.nii`

Let me do a detailled comparison on the head models...

**Comment by robertoostenveld** [comment]
except for some trivial updates to the fields (pnt->pos, added unit=mm) the structures are identical:

```
vol_eeglab = 
  struct with fields:

     bnd: [1×3 struct]
    cond: [0.3300 0.0041 0.3300]
     mat: [3000×3000 double]
    type: 'dipoli'
>> vol_ft
vol_ft = 
  struct with fields:

     bnd: [1×3 struct]
    cond: [0.3300 0.0041 0.3300]
     mat: [3000×3000 double]
    type: 'dipoli'
    unit: 'mm'
>> isequal(vol_eeglab.bnd(1).pnt, vol_ft.bnd(1).pos)
ans =
  logical
   1
>> isequal(vol_eeglab.bnd(2).pnt, vol_ft.bnd(2).pos)
ans =
  logical
   1
>> isequal(vol_eeglab.bnd(3).pnt, vol_ft.bnd(3).pos)
ans =
  logical
   1
>> isequal(vol_eeglab.mat, vol_ft.mat)
ans =
  logical
   1
```

They will hence give exactly the same forward solutions.

**Comment by arnodelorme** [comment]
OK, I will make the necessary adjustments. Thanks Robert
