### ISSUE TITLE
3D scan of electrode positions - problem with specifying anatomical landmarks

### ISSUE THREAD

**Issue by akadamczyk** [fieldtrip/fieldtrip#2164]
Hello, 

**Describe the bug**
my problem concerns:
1. the selection of anatomical landmarks (fiducials: Nas, LPA, RPA) using ft_electrodeplacement in the 3D electrode scan (tutorial file, 3D electrode scan acquired with the structure sensor by Occipital). Trying to select and save the fiducial gives the following error:
![image](https://user-images.githubusercontent.com/122791086/212669804-8f2037d5-24a2-4d32-a8bc-1d20960e15d8.png)
2. the number of vertices that are loaded (different values from those provided in the tutorial: https://www.fieldtriptoolbox.org/tutorial/electrode/)

**To Reproduce**
% load 3-D electrode scan
head_surface = ft_read_headshape('Model.obj');
disp(head_surface)
![image](https://user-images.githubusercontent.com/122791086/212672387-36029e0c-801b-4133-9c5a-1f8050310fdf.png)
% convert to 'mm':
head_surface = ft_convert_units(head_surface, 'mm');
% specify anatomical landmarks (nasion, right/left preauricular) in accordance to the instruction provided here: https://www.fieldtriptoolbox.org/tutorial/electrode/  "first select the anatomical landmark, then select the electrode label ('1' for the first fiducial), then enable rotate, then rotate the head, then disable rotate, and repeat."
figure;
cfg = [];
cfg.method = 'headshape';
fiducials = ft_electrodeplacement(cfg, head_surface);

**Additional context**
Matlab: 2021a, FieldTrip: 20220426, macOS Ventura: 13.0.1 (22A400) 

I am attachning 'raw file' downloaded from the FieldTrip tutorial website (Model.obj), and 'preprocessed' file after loading it into Matlab on my machine (head_surface.mat). 

I would be super grateful for your help .

All the best, 
Agnieszka 
[files.zip](https://github.com/fieldtrip/fieldtrip/files/10425549/files.zip)

**Comment by robertoostenveld** [comment]
Hi Agnieszka 

thanks for sharing in the MEG meeting this morning and reporting it here.

I can identify some issues: 
- the "v" keyboard press to update the light does not work
- linking electrodes to labels (by clicking in the table and clicking in the figure) is very confusing to me

I have not yet been able to reproduce your subplot error, but will continue trying around

**Comment by robertoostenveld** [comment]
ah, got it:

```
Error using subplot
Requires valid axes handle for input.
Error in ft_electrodeplacement>cb_keyboard (line 1183)
    subplot(opt.axes(1)); 
Error while evaluating Figure WindowKeyPressFcn.
```

I got this error when pressing the button "1" which I noticed in the `cb_keyboard` function. The code mentions `% the following code is largely shared by FT_SOURCEPLOT, FT_VOLUMEREALIGN, FT_INTERACTIVEREALIGN, FT_MESHREALIGN, FT_ELECTRODEPLACEMENT`. 

Looking at the code, I see that these options are there to support the workflow used in https://www.fieldtriptoolbox.org/tutorial/human_ecog/#electrode-placement for clicking on SEEG electrodes in a CT scan.

**Comment by akadamczyk** [comment]
Thank you for taking a look right away, I really appreciate this. This function is also supposed to work for 3d electrode positions mentioned in this tutorial: https://www.fieldtriptoolbox.org/tutorial/electrode/#recording-data . Is there another way to read in this type of data?

**Comment by robertoostenveld** [comment]
I used the following code for testing

```
load head_surface.mat
head_surface.coordsys = 'unknown'

cfg = [];
cfg.method = 'interactive';
head_surface1 = ft_meshrealign(cfg, head_surface)

% alpha 1.0
% rotate x -90, apply
% rotate z 55, apply
% quit

head_surface1.coordsys = 'ctf' % approximately

%%

cfg = [];
cfg.channel = {'lpa', 'nas', 'rpa'};
cfg.method = 'headshape';
fiducials1 = ft_electrodeplacement(cfg, head_surface1)

%%

cfg = [];
cfg = [];
cfg.method        = 'fiducial';
cfg.coordsys      = 'ctf';
cfg.fiducial.lpa  = fiducials1.elecpos(1,:); %position of LPA
cfg.fiducial.nas  = fiducials1.elecpos(2,:); %position of NAS
cfg.fiducial.rpa  = fiducials1.elecpos(3,:); %position of RPA
head_surface2 = ft_meshrealign(cfg, head_surface1);

%%

ft_determine_coordsys(head_surface2)
```

this adds an initial interactive realignment to put the head more-or-less upright with the vertex to z and the nose to x. That makes it easier to rotate during the clicking of the fiducials (step 2). The 3rd step is to use the fiducials and ft_determine_coordsys at the end checks that the axes go through the fiducials.

@akadamczyk  can you give it a try with the latest master version from fieldtrip? You can download that here as master.zip, or use a git/github client.

**Comment by robertoostenveld** [comment]
> This function is also supposed to work for 3d electrode positions mentioned in this tutorial: https://www.fieldtriptoolbox.org/tutorial/electrode/#recording-data . Is there another way to read in this type of data?

Yes, it should work both for surface/headshape data and ct/volume data. That is why it got confused with the buttons. 

There is no other way of reading the data, so the mismatch between the number of triangles remains to be solved. However, I don't have the full model. Can you also send me the `Model.mtl` and the `Model.jpg` files? ... oh no, I can download them myself from the tutorial paper. Nevermind...

I'll keep this issue open fore now to follow on on the reading, and on the documentation/tutorial update.

**Comment by akadamczyk** [comment]
Hi @robertoostenveld, 
I coregistered individual electrode positions to individual MRI scan (without moving electrodes inward as suggested here: https://www.fieldtriptoolbox.org/tutorial/electrode/#summary-and-further-reading), but after plotting electrodes on top of the head (skin) surface:

`figure;`
`ft_plot_sens(elec_aligned);`
`hold on;`
`ft_plot_mesh(headmodel.bnd(3),'facealpha', 0.85, 'edgecolor', 'none', 'facecolor', [0.65 0.65 0.65]); %scalp`

frontal electrodes seem to be too close to (submerged in) the head (skin)... should I be worried about this?
<img width="284" alt="image" src="https://user-images.githubusercontent.com/122791086/212904235-5d7c341e-b4cd-443d-ad15-568b5ddaf7e9.png">

I am attaching a matlab figure. I would appreciate your opinion.

Best, 
Agnieszka
electrodes_on_headskin.fig.zip

**Comment by robertoostenveld** [comment]
Please check the updated tutorial at https://www.fieldtriptoolbox.org/tutorial/electrode/. Note that it will take about 5 minutes to refresh on the server.

**Comment by schoffelen** [comment]
@akadamczyk can this issue be closed? If so, please feel free to do so.
