### ISSUE TITLE
improve diagnostics for meshes that are the input for EEG BEM 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2168]
it can happen that meshes that are the input for `ft_prepare_headmodel` are not correct. A common error is that there are "holes" in the segmentation, which causes (with the default meshing algorithm) spikes to appear. 

The BEM methods underneath `ft_prepare_headmodel` should have better checks for correct surfaces, with the appropriate nesting and no intersections.

(as discussed with @canoni and @mcpiastra)

**Comment by robertoostenveld** [comment]
see also https://mailman.science.ru.nl/pipermail/fieldtrip/2020-December/040547.html
and https://www.fieldtriptoolbox.org/faq/why_does_my_eegheadmodel_look_funny/

**Comment by canoni** [comment]
Another way to deal with the “holes” in the scalp segmentation might be to improve the skull segmentation (sorry if this is already discussed somewhere online and I did not find it). This might be added to the FAQ, linked above, if approved by Fieldtrip experts. If the skull segmentation is too thick, it seems that this can impact the scalp segmentation: If the skullmask extends the scalpmask at certain points, this line in ft_volumesegment (version 20221126) removes part of the scalpmask (producing holes): 

“line 741   scalpmask(skullmask>0)=0;”.

It is especially relevant if one runs ft_volumesegment with default options (cfg.spmversion = 'spm12' and cfg.spmmethod = 'old'). In this case, a grey matter, white matter and csf segmentation is done using SPM. Skull segmentation is, in this case, based on the brain segmentation: The volume segmented as brain is dilated, cp. line 702 and 703 in ft_volumesegment (version 20221126):

line 702  braindil  = imdilate(brainmask>0, strel_bol(6));
line 703  skullmask = braindil & ~brainmask;

Reducing the radius in line 702 resulted in thinner skullmasks and made the holes in the scalp segmentation disappear in my data. I.e., I changed line 702 in my local ft_volumesegemnt code from “ imdilate(brainmask>0, strel_bol(6));” to “ imdilate(brainmask>0, strel_bol(4));” It seems that the number 6 is anyway pretty random and therefore can be changed?

If the skull segmentation is bad and this produces the holes in the scalp, the much better option probably is, to improve the skull segmentation by changing cfg.spmmethod = 'old' to cfg.spmmethod = 'new' when running ft_volumesegment. Maybe this is also something that could be mentioned in the FAQ linked above.

**Comment by canoni** [comment]
This might also be added to the FAQ from above, as a way to manually improve segmentations:
https://www.fieldtriptoolbox.org/getting_started/seg3d/

**Comment by canoni** [comment]
and here another link to the FAQ, as a way to plot segmentation and mesh results? https://www.fieldtriptoolbox.org/example/coregistration_quality_control/

**Comment by robertoostenveld** [comment]
@canoni wrote in this [comment](https://github.com/fieldtrip/fieldtrip/issues/2168#issuecomment-1406811641) 

> Another way to deal with the “holes” in the scalp segmentation might be to improve the skull segmentation ...

I agree that the segmentation has room for improvements. However, this specific issue serves to improve the diagnostics on meshes, not on the segmentation. Please make a separate issue to propose changes ft_volumesegment.

**Comment by robertoostenveld** [comment]
The `ft_headmodel_dipoli`, `ft_headmodel_openmeeg` and `ft_headmodel_bemcp` functions now do some internal checks on the meshes being correct. Note that not all possible flaws will be detected, but hopefully this makes the code already more robust.
