### ISSUE TITLE
3D scan electrode positions - ft_electrodeplacement error using fieldtrip-20230128

### ISSUE THREAD

**Issue by Irina-Ch** [fieldtrip/fieldtrip#2186]
**Describe the bug**
This might be the follow up of the issue #2164.

Following the tutorial: https://www.fieldtriptoolbox.org/tutorial/electrode/, I got an error with ft_electrodeplacement (including on the data that I marked successfully previously). When I rolled back from fieldtrip-20230128 to fieldtrip-20220707, the script would run properly again.

**To Reproduce**
Exactly following the tutorial:  https://www.fieldtriptoolbox.org/tutorial/electrode/
1. After loading the 3D model in and going through the first steps:
head_surface = ft_read_headshape(model);
disp(head_surface)
head_surface = ft_convert_units(head_surface, 'mm'); 
ft_plot_mesh(head_surface); 

2. Error occurs with ft_electrodeplacement: 
cfg = [];
cfg.method = 'headshape';
cfg.channel = {'nas', 'lpa', 'rpa'}; 
fiducials = ft_electrodeplacement(cfg, head_surface); 

**Error**
After clicking on the 3D scan to mark the position and then on the label in the little window on the right (see the printscreen below), the position is not marked and instead the following output is given:

Error using lower
Cell elements must be character arrays.

Error in ft_chantype (line 686)
    chantype(intersect(strmatch(label2type{i}{j}, lower(label)), find(strcmp(chantype, 'unknown')))) = label2type{i}(1);

Error in ft_datatype_sens (line 254)
      sens.chantype = ft_chantype(sens);

Error in ft_datatype_sens (line 210)
    sens      = ft_datatype_sens(sens, new_argin{:});

Error in ft_datatype_sens (line 180)
    sens      = ft_datatype_sens(sens, new_argin{:});

Error in ft_plot_sens (line 77)
sens = ft_datatype_sens(sens);

Error in ft_electrodeplacement>cb_headshaperedraw (line 1227)
      ft_plot_sens(elec, 'elecshape', 'sphere', 'label', 'off');

Error in ft_electrodeplacement>cb_eleclistbox (line 1686)
    cb_headshaperedraw(h);
 
Error while evaluating UIControl Callback.

**Expected behavior**
Assignining markers to the fiducials+nasion.

**Screenshots**
![image](https://user-images.githubusercontent.com/72854213/217586607-ab3f7fe6-0426-4fb0-a54a-340f67f0a4f7.png)

**Environment and versions (please complete the following information):**
 - Operating System:  Windows 10, Linux
 - MATLAB version R2022a
 - FieldTrip version 20230128 (bug), 20220707 (works fine!)

**Comment by schoffelen** [comment]
Hi Irina,

could it be related to this PR? https://github.com/fieldtrip/fieldtrip/pull/2184 
Rather than going back in terms of FT version, could you try the latest one from the repo and check whether your issue persists?

**Comment by schoffelen** [comment]
so that means picking version 20230206 or so

**Comment by schoffelen** [comment]
Or perhaps your current error is due to something that is fixed with this PR: https://github.com/fieldtrip/fieldtrip/pull/2185. If that's the case, upgrading to a later version is not going to work, because the PR still needs to be merged.

**Comment by robertoostenveld** [comment]
Hi Irina, I was able to confirm your bug. Following the merge of #2185 (just an hour ago), and pulling the latest master version, the error has disappeared. So it should now be solved.

thanks for reporting!
