### ISSUE TITLE
ROI_MNI_V4 Original Region descriptions of 9170 ROIs

### ISSUE THREAD

**Issue by Kalana304** [fieldtrip/fieldtrip#2189]
Hi, I am trying to use the ROI_MNI_V4.nii provided to create a more finer scale connectome. Do you have the descriptions of all the 9170 regions it contains than the anatomical regions defined based on coarser AAL atlas?

**Comment by schoffelen** [comment]
Hi @Kalana304 I don't have a clue what you ask about. In general, also, this is not the location to ask this type of questions, as you have seen in the accompanying text that shows up when you try to open an issue. If you require input from the community, I suggest that you sign up for the fieldtrip discussion list, and ask your question there. Not sure whether your particular question is specific for the fieldtrip audience, so I don'
t know whether the community can help you along.
