### ISSUE TITLE
a way to fix this problem 'not all input channels of the montage are unique'

### ISSUE THREAD

**Issue by SymmetricMatrix** [fieldtrip/fieldtrip#2193]
**Describe the bug**
```
Error using ft_apply_montage (line 313)
not all input channels of the montage are unique

Error in ft_prepare_montage (line 185)
        montage2 = ft_apply_montage(montage2, groupmontage{g}, 'keepunused', true);

Error in preproc (line 331)
      montage = ft_prepare_montage(tmpcfg);

Error in ft_preprocessing (line 361)
    [dataout.trial{i}, dataout.label, dataout.time{i}, cfg] = preproc(data.trial{i}, data.label,  data.time{i}, cfg, begpadding, endpadding);
```
**To Reproduce**
```
cfg = [];
cfg.channel = channel_pre;
cfg.reref = 'yes';
cfg.refmethod = 'bipolar';
cfg.refchannel = 'all';
cfg.groupchans = 'yes';
cfg.bpfilter       = 'yes';
cfg.bpfreq         = range;
cfg.bsfilter       = 'yes';
cfg.bsfiltord      = 3;
cfg.bsfreq         = [49 51; 99 101; 149 151];

data_pre = ft_preprocessing(cfg,edf_data);
```
**Expected behavior**
[![pSj5JH0.png](https://s1.ax1x.com/2023/02/22/pSj5JH0.png)](https://imgse.com/i/pSj5JH0)
channel_pre is raw edf label
bbb is montage.labelnew
ccc is what we want
obviously, bbb is 2 more than ccc, due to 'LL7-LL8' and 'LL8-LL9' repeated twice.
[![pSjo3T0.png](https://s1.ax1x.com/2023/02/22/pSjo3T0.png)](https://imgse.com/i/pSjo3T0)

**a way to fix this problem**
```
#  in ft_prepare_montage.m
# 161 add
group_all = group;
# 171 change to
# tmpcfg.channel = label(startsWith(label, group{g}));
tmpcfg.channel = label(strcmp(group_all,group{g}));
```

**Environment and versions (please complete the following information):**
 - Operating System:  Windows 10
 - MATLAB version  R2021b
 - FieldTrip version  2020312

**Comment by schoffelen** [comment]
Rather than fixing it right away, we need to understand why you get the error to begin with. Why are there duplicated channels in your input montage?

The error is self explanatory, there are duplicate channels, and this is not allowed.

**Comment by SymmetricMatrix** [comment]
> channel_pre is raw edf label
I'm sorry I didn't clarify my question. The variable channel_pre in pic1 is raw edf label (input) and it is unique. And I have several sets of labels, like 'L1' ,'L2', 'L3' , 'LL1' ,'LL2', 'LL3' , 'LS1' ,'LS2', 'LS3' . I think function startsWith in line 171 may cause some incorrect combination. Obviously, the software has some optimization for this situation, but it still produces the error at the beginning of this issue.

**Comment by schoffelen** [comment]
can you please send us some data so that we can reproduce your issue? You can check the fieldtrip website fieldtriptoolbox.org for how to send us (small) datafiles. Hence, a edf_data object (with as few time samples as possible, to keep it small), as well as what you call channel_pre in the pasted code snippet, would be needed

**Comment by SymmetricMatrix** [comment]
> can you please send us some data so that we can reproduce your issue? You can check the fieldtrip website fieldtriptoolbox.org for how to send us (small) datafiles. Hence, a edf_data object (with as few time samples as possible, to keep it small), as well as what you call channel_pre in the pasted code snippet, would be needed

![test.zip](https://github.com/fieldtrip/fieldtrip/files/10805573/test.zip)


this is zip file contains data(test.mat) and cfg (cfg.mat), after load these two files then run the follow code, you can reproduce error
```
data_pre = ft_preprocessing(cfg,data_segmented);
```
