### ISSUE TITLE
load_nifti fails with spaces in the path name

### ISSUE THREAD

**Issue by crisluengo** [fieldtrip/fieldtrip#2196]
**Describe the bug**
`load_nifti` fails if there are spaces in the path name. See here: https://stackoverflow.com/q/75533345/7328782

**To Reproduce**
See the linked SO post.

**Environment and versions (please complete the following information):**
Probably all of them.

**Additional context**
You can fix this by adding quotes around the file name in the shell command to run `gzip`. In [this spot](https://github.com/fieldtrip/fieldtrip/blob/205c3af9697b4a6f905ec4cced35a5a1a8ee1623/external/freesurfer/load_nifti.m#L66), change
```matlab
  if(strcmp(computer,'MAC') || strcmp(computer,'MACI') || ismac)
    cmd = sprintf('gunzip -c %s > %s', niftifile, new_niftifile);
  else
    cmd = sprintf('zcat %s > %s', niftifile, new_niftifile);
  end
```
into
```matlab
  if(strcmp(computer,'MAC') || strcmp(computer,'MACI') || ismac)
    cmd = sprintf('gunzip -c "%s" > "%s"', niftifile, new_niftifile);
  else
    cmd = sprintf('zcat "%s" > "%s"', niftifile, new_niftifile);
  end
```
(not tested, but it should do the trick).

[By the way, the `if` line can be simplified to `if ismac`, there is no point in also checking the value of `computer`.]

**Comment by schoffelen** [comment]
why do people have spaces in their path to begin with?

is the suggested change backward compatible to older matlab versions? is it a matlab version problem to begin with, it sounds rather generic to me?

load_nifti is not under the fieldtrip team's control, but shared with the toolbox as a courtesy to the user. The issue would best be handled with the freesurfer folks.

for now, I can offer to consider merging your suggested change, if:
1) it will be tested on older matlab versions, too
2) the PR will consist of some test code and data that allows us to test it on our end

I recommend to also take this up with the freesurfer folks.

**Comment by schoffelen** [comment]
forget my question about the backward compatibility, the added quotes are of course part of the system call, no matlab version specificity

**Comment by crisluengo** [comment]
I submitted [the same report to the freesufer repo](https://github.com/freesurfer/freesurfer/issues/1075) when I noticed it wasn't your code. Still, since you have a copy, you should fix your copy too.

This issue is unrelated to the MATLAB version, it is related to the shell command created. The error is produced by the shell command, not MATLAB. Currently you create `zcat file name > other name`, when you want to create `zcat "file name" > "other name"`.

I did not make a PR because I don't use this toolbox, I have no data to test with, and I hardly ever use MATLAB any more. I just wanted to let you guys now about this issue.

**Comment by schoffelen** [comment]
Thanks for the feedback, we'll look into it.

**Comment by schoffelen** [comment]
Thanks again for reporting. I can confirm the issue, when I call load_nifti directly to load in a zipped file

However, in fieldtrip, decompression of zipped nifti files already takes place at a higher level: it bypasses the system call in load_nifti, and decompresses the file in a scratch-dir in order to keep the path clean.

For now, I lean towards keeping things as is, and I will keep an eye on the freesurfer folks taking action.
