### ISSUE TITLE
ft_redefinetrial to allow for nan removal

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#2202]
the use case would be a pipeline with ft_rejectartifact with nan replacement.
for a subsequent TFR one might consider to remove the nans (and change the data representation as if artifacts have been partially rejected). This avoids the whole trial's TFR to be NaN'ned. Does this sound like a sufficiently generic functional enhancement @robertoostenveld ?

**Comment by robertoostenveld** [comment]
I think this is already possible with ft_artifact_nan combined with ft_redefinetrial

**Comment by schoffelen** [comment]
Nice, you're right! Didn't know this. Note: ft_artifact_nan could use boolvec2artifact, right now it does the boolvec 2 artifact conversion with its own code.
