### ISSUE TITLE
Functionality to plot contour lines around specified area on a sourceplot

### ISSUE THREAD

**Issue by JoannaZioga** [fieldtrip/fieldtrip#2210]
Reach 'contour' functionality of ft_plot_mesh directly from ft_sourceplot

**Comment by schoffelen** [comment]
Who is going to work on this?

**Comment by robertoostenveld** [comment]
@JoannaZioga you could get started by writing a script similar to the test scripts that you can find in the https://github.com/fieldtrip/fieldtrip/tree/master/test directory , and mainly like the inspect_xxx scripts. The script should come with some data, include all the function calls, and demonstrate how the ft_sourceplot should be called to get what you want. At this moment the script should fail (i.e. the plot would not show , when we make improvements it should pass.

**Comment by schoffelen** [comment]
@JoannaZioga how are we going to move this forward? Do you have a script that illustrates your intended use case?

**Comment by JoannaZioga** [comment]
@schoffelen sorry I got distracted and missed this, as I didn't need to use this functionality eventually! I'm afraid I don't have anything apart from a conceptual description of what's needed to be done. I should be able to draft something (based on Robert's instructions above) if still needed when my workload allows.. Might need some time to get my head around this :)

**Comment by schoffelen** [comment]
@JoannaZioga do you still want to move this forward?

**Comment by JoannaZioga** [comment]
Hi Jan Mathijs, I'm afraid I cannot move this forward, as I haven't managed to make any progress on it back then and my work is now focused somewhere else.
