### ISSUE TITLE
Unable to import ds002885

### ISSUE THREAD

**Issue by dungscout96** [fieldtrip/fieldtrip#2214]
**Describe the bug**
When we tried to import a fif file from ds002885, downloaded from NEMAR.org, we received the error: "Dot indexing is not supported for variable of this type" for fiff_make_dir_tree at line 55.

**To Reproduce**
1. Download the dataset from NEMAR/Openneuro
2. Import using Fieldtrip
3. Observe crash

**Expected behavior**
Data successfully loaded

**Comment by schoffelen** [comment]
First few thoughts:
- I don't have an account on Nemar
- Have you tried reading another dataset, to check whether it's code or data
- the function that throws the error is in fieldtrip/external, so not maintained by the fieldtrip core developers
- the reported error stack is quite meagre, so unclear to see what's going on
- have you checked with the debugger what's going on?
- we don't see information about the version of the code that you used, nor on matlab version, operating system etc.

**Comment by schoffelen** [comment]
I downloaded sub-01 through datalad

I tried:

ft_read_header('sub-01_task-DSMW_meg.fif');

this reproduces the error you report

I tried:

ft_read_header('sub-01_task-EmptyRoom_meg.fif');
and
ft_read_header('sub-01_task-Reference_meg.fif');

this works fine.

So there is no principled problem with the code, which - to reiterate - is not maintained by the FieldTrip team.
