### ISSUE TITLE
BDF file reading error

### ISSUE THREAD

**Issue by vlitvak** [fieldtrip/fieldtrip#2221]
We have some BDF files that give an error with fileio but convert OK in EEGLAB with biosig. The error is below and this is an example:

https://liveuclac-my.sharepoint.com/:u:/g/personal/skaalit_ucl_ac_uk/EVqtJeGWdYRNhB4rFGWLOuUBj1dxafnd-wyQu0e5-9lV6A?e=dffq6S

Vladimir

error reading from Test32Data24Con_10032023.bdf
One or more output arguments not assigned during call to "read_24bit".

Error in read_biosemi_bdf>readLowLevel (line 283)
  buf = read_24bit(filename, offset, numwords);

Error in read_biosemi_bdf (line 258)
      buf = readLowLevel(filename, offset, epochlength*nchans); % see below in subfunction

Error in ft_read_data (line 430)
    dat = read_biosemi_bdf(filename, hdr, begsample, endsample, chanindx);

**Comment by robertoostenveld** [comment]
Do you know the source of these files, i.e., are they written by Biosemi software?

**Comment by robertoostenveld** [comment]
when I do `dbstop if error`, I end up with the error in epoch/block 67.

When I look at the file size with

```
>> ft_read_header('issue2221.bdf')
ans = 
  struct with fields:

             Fs: 4096
         nChans: 48
          label: {48×1 cell}
        nTrials: 1
       nSamples: 405504
    nSamplesPre: 0
           orig: [1×1 struct]
       chantype: {48×1 cell}
       chanunit: {48×1 cell}

>> 405504*3*48
ans =
    58392576

>> ls -al issue2221.bdf
-rw-r--r--@ 1 roboos  staff  38940928 Mar 24 19:59 issue2221.bdf
```

I would say that the file is too short. I would expect (besides the header) 58392576 bytes, and it only has 38940928.

Could it be that it was truncated during file transfer?

**Comment by vlitvak** [comment]
We are doing a phantom study and these files come from there. The software is the original one as far as I understand. I think the student converts them on the same PC where they are recorded and it’s more then one file. When we started it worked fine and then this problem appeared and I think every file is faulty now.
