### ISSUE TITLE
[ENH] enable fooof fitting parameters and output the original power spectrum

### ISSUE THREAD

**Issue by ruiliu-psy** [fieldtrip/fieldtrip#2222]
1) I would like to do fit nonlinear 1/f background with FOOOF to analyze my data. Currently, ft_freqanalysis() only grabs the default opt from brainstorm. It would be more flexible to allow users to specify the fitting parameters in the cfg structure in fieldtrip.

2) It would be more efficient if ft_freqanalysis returns the original power spectrum from the fooof output (currently stored in the structure fooofparams.power_spectrum, which needs to be unlogged), it wouldn't be necessary to compute the original spectrum again as illustrated in the [example](https://www.fieldtriptoolbox.org/example/fooof/).

**Comment by schoffelen** [comment]
I don't understand:

1. in cfg.fooof.<option> you can specify (and overrule) the brainstorm defaults
2. cfg.output gives the possibility for 'fooof_aperiodic' / 'fooof_peaks' or just 'fooof' 

So it is unclear what needs to be done in addition to address the things you mention @ruiliu-psy , but I may miss the point

**Comment by ruiliu-psy** [comment]
Re 1. ah, yes, you are right. I got an error only when specifying the parameter min_peak_height = Inf.

Re 2. I was thinking return the original, periodic and aperiodic spectra at once, but it's not necessary, I can also call the function multiple times. Regarding the example webpage, it compute the periodic spectrum = original - aperiodic, which is different from the 'fooof_peaks'. I'm not sure if this is intended/recommended. (I can help with changing the ft website page, if you want.)

**Comment by schoffelen** [comment]
could you please be a bit more specific, and ideally suggest a solution? I don't know about the scale of the peaks, so perhaps a little bit more information is welcome

**Comment by ruiliu-psy** [comment]
Re1. sorry I meant the error occurred when I set cfg.fooof.max_peaks = Inf (allowing fooof to fit infinite number of peaks). This option is legitimate in the python version.
Re2. as for the scale of fooof_peaks, following this [example](https://www.fieldtriptoolbox.org/example/fooof/), I just simply plotted the (original-aperiodic) and fooof_peaks, they are on a very different scale.
`% compute the fractal and original spectra
cfg               = [];
cfg.foilim        = [1 200];
cfg.pad           = 4;
cfg.tapsmofrq     = 2;
cfg.method        = 'mtmfft';
cfg.output        = 'fooof_aperiodic';
fractal = ft_freqanalysis(cfg, data);
cfg.output        = 'pow';
original = ft_freqanalysis(cfg, data);
**cfg.output        = 'fooof_peaks';
peaks = ft_freqanalysis(cfg, data);**

% subtract the fractal component from the power spectrum
cfg               = [];
cfg.parameter     = 'powspctrm';
cfg.operation     = 'x2-x1';
oscillatory = ft_math(cfg, fractal, original);

% display the spectra on a log-log scale
figure();
hold on;
plot(log(original.freq), log(original.powspctrm),'k');
plot(log(fractal.freq), log(fractal.powspctrm));
plot(log(fractal.freq), log(oscillatory.powspctrm));
plot(log(fractal.freq), log(peaks.powspctrm));
xlabel('log-freq'); ylabel('log-power');
legend({'original','fractal','oscillatory','peaks'},'location','southwest');`

<img width="490" alt="Screenshot 2023-03-28 at 09 34 58" src="https://user-images.githubusercontent.com/71086397/228163271-3a5eed7f-92fb-40c4-b7ab-1c7e4f80f4f2.png">

I don't have straightforward answers so far, will have to compare the brainstorm and the python versions.

**Comment by schoffelen** [comment]
why do you think that they are in a different scale? the peaks are about 3 orders of magnitude above the 'background', which is exactly what is shown in the purple line. I think I miss the point (again).

Could you either please paste the error you get, or investigate it a bit more with the debugger and write down here what is going wrong in the code according to you?

**Comment by ruiliu-psy** [comment]
I might misinterpreted what the 'fooof_peaks' suppose to be. Shouldn't it match the yellow line? Why "the peaks are about 3 orders of magnitude above the 'background'"? what are the 'fooof_peaks'?

yes, I'll look into the error regarding max_peaks later today.

**Comment by schoffelen** [comment]
the purple line are the fooof peaks. I would assume that this is created from the modelled parameters, i.e. peak location/width/height/and whatever else fooof is estimating

**Comment by ruiliu-psy** [comment]
> why on earth would you want to fit an infinite number of peaks?
coz i'm not sure how many peaks are there. the learning rule became stoping when it peak height < cfg.fooof.min_peak_height

**Comment by ruiliu-psy** [comment]
> the purple line are the fooof peaks. I would assume that this is created from the modelled parameters, i.e. peak location/width/height/and whatever else fooof is estimating

shouldn't it more or less aligned with the yellow line? that's my confusion.

**Comment by ruiliu-psy** [comment]
okay, I still don't quite understand what is in the fooof_peaks. I thought by the following help comment meant fooof_peaks = the periodic spectrum (so should align wit the yellow line). That was my misunderstanding then. Thanks for the elaboration, you can close the issue. To ensure the same performance as setting max_peaks = Inf as in the python version, I just give it a very large number, so that the fitting stops with cfg.fooof.min_peak_height.

`%                     'fooof_peaks' returns a power-spectrum with the fooof
%                       based estimate of the aperiodic signal removed,
%                       it's expressed as
%                       10^(log10(fooof)-log10(fooof_aperiodic))`

**Comment by robertoostenveld** [comment]
Dear both, the github issues are to discuss issues and potential improvements to the FieldTrip code and/or documentation. This specific issue seems to move towards a more general support question on "what is FOOOF and how should I use it?", which is not appropriate here. I suggest that @ruiliu-psy reaches out to the FOOOF developers and/or support platform (if such a thing exists), or that you take it offline elsewhere.
