### ISSUE TITLE
Eyetracking import: accountability for MSG 9999

### ISSUE THREAD

**Issue by deepagupta** [fieldtrip/fieldtrip#2223]
**Bug description**
When reading the eye tracking file, read_smi_txt.m is not accounting for the new trial message: MSG 1 # Message: 9999

**To Reproduce**
Run ft_read_header>read_smi_txt.m to read the eyetracking IDF file 
[NDARAA075AMK_Video1_Events.txt](https://github.com/fieldtrip/fieldtrip/files/11141891/NDARAA075AMK_Video1_Events.txt)

**Expected behavior**
The eyetracking file read may not succeed

**Environment and versions (please complete the following information):**
 - Operating System: Mac OS X
 - MATLAB version: 2023a
 - FieldTrip version: "most recent master branch from github"
 - Eyetracking file to be read version: IDF Converter 3.0.20 (sample attached)

**Suggestion**
line#45 in ft_read_header>read_smi_txt.m  could be changed from:
if numel(tline) && any(tline(1)=='0':'9')
to:
if numel(tline) && any(tline(1)=='0':'9') && ~contains(tline,'Message')

**Comment by robertoostenveld** [comment]
Hi Deepa

When I tried reading the txt file you shared, I see that it fails on other aspects as well.

```
>> ft_read_header('NDARAA075AMK_Video1_Events.txt', 'headerformat', 'smi_txt')
Unrecognized field name "Fs".
Error in ft_read_header (line 2610)
    hdr.Fs                  = smi.Fs; 
```

That is because certain fields in the header are formatted differently. As more changes are needed, can you please make the required changes to the `read_smi_txt` file and send them as a pull request? 

best regards,
Robert

**Comment by deepagupta** [comment]
Hi Robert,

Regarding if other events are a possibility: So far we didn't see any other events than this Message. However, I can report it as and when I see it. 

Regarding your latter comment: Surely, I can send a pull request. I am working on it as I complete the checks. Btw, may I please know which version of fieldtrip you are using? - Just curious as I am not getting that error right now. 

Kind thanks,
Deepa

**Comment by robertoostenveld** [comment]
I am using (more or less) the latest master version. 

The file that you shared has header lines without the `##  ` at the start, which is what https://github.com/fieldtrip/fieldtrip/blob/0beabe62dd34bc64d3ccbdb0ebbb0d86d2ed7aff/fileio/private/read_smi_txt.m#L70 searches for. The error that I showed above is from ft_read_header, not from read_smi_txt itself.

**Comment by deepagupta** [comment]
Thank you Robert for kindly sharing that. I fixed that sampling rate error that you mentioned but after that I saw that there was also the timestamp error occurring along with empty 'smi.dat' and empty 'smi.header' struct field issues. I have fixed all of this and tried to push the two relevant files. But of course, I'll get the fatal permission error. So, I am attaching the file code here. I hope this helps. Please let me know if I can assist any further as this could be further improved also (right now this accounts for Saccades but could also account for the Fixations, Blinks and more in the future).

```
function smi = read_smi_txt(filename)

% READ_SMI_TXT reads the header information, input triggers, messages
% and all data points from an SensoMotoric Instruments (SMI) *.txt file
%
% Use as
%   smi = read_smi_txt(filename)

% Copyright (C) 2016, Diego Lozano-Soldevilla (CerCo)
%
% This file is part of FieldTrip, see https://urldefense.com/v3/__http://www.fieldtriptoolbox.org/__;!!Mih3wA!HujJdJ3W8MF5OVd1guCbgLjX-d5Z5FEuuEu-Btd8cx7S-ur0iIUP4fWES6-BWIPf6dbLFYyWxOGKW1AS3iQ$ 
% for the documentation and details.
%
%    FieldTrip is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    FieldTrip is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with FieldTrip. If not, see <https://urldefense.com/v3/__http://www.gnu.org/licenses/__;!!Mih3wA!HujJdJ3W8MF5OVd1guCbgLjX-d5Z5FEuuEu-Btd8cx7S-ur0iIUP4fWES6-BWIPf6dbLFYyWxOGKpdA6xis$ >.
%
% $Id$

smi.header  = {};
smi.label   = {};
smi.dat     = [];
current     = 0;

%file type is upgraded version
flag_file_type_CM = 0;

% read the whole file at once
fid = fopen_or_error(filename, 'rt');
aline = fread(fid, inf, 'char=>char');          % returns a single long string
fclose(fid);

aline(aline==uint8(sprintf('\r'))) = [];        % remove cariage return
aline = tokenize(aline, uint8(sprintf('\n')));  % split on newline

for i=1:numel(aline)
  tline = aline{i};
  
  if numel(tline) && (any(tline(1)=='0':'9') || flag_file_type_CM)
    
      tmp = {};
   if flag_file_type_CM && numel(regexp(tline, 'Table Header for Saccades:'))
       smi.header = cat(1, smi.header, {tline});
          i = i+1;
          tline = aline{i};
          smi.header = cat(1, smi.header, {tline});
          temp = split(tline,'  ');
          emptyCells = cellfun(@isempty,temp);
          temp(emptyCells) = [];  
          smi.label = temp;
          clear temp
          clear emptyCells
   elseif numel(regexp(tline,'Saccade','match')) 
      tmp    = split(tline,'  ');
      emptyCells = cellfun(@isempty,tmp);
      tmp(emptyCells) = [];
      current = current + 1;
      clear emptyCells
   elseif ~flag_file_type_CM
      % if regexp(tline, '^[0-9]')
      tmp = regexp(tline,'[^\t\r\n\f\v]*','match')';
      % exclude SMP sting
      smp = regexp(tmp','SMP');
      smpidx = find(cellfun(@numel,smp)==1);
    
      current = current + 1;
      smi.type{1,current} =  sscanf(tmp{smpidx}, '%s');
      tmp(smpidx,:) = [];
    end
    
    for j=1:size(tmp,1)
      val = sscanf(tmp{j,1}, '%f');
      if isempty(val)
        smi.dat(j,current) =  NaN;
      else
        smi.dat(j,current) =  val;
      end
    end
    
  elseif regexp(tline, '##')
    smi.header = cat(1, smi.header, {tline});
    
    template ='## Sample Rate:';
    if strncmp(tline,template,length(template))
      smi.Fs = cellfun(@str2num,regexp(tline,'[\d]+','match'));
    end
    
    template = '## Number of Samples:';
    if strncmp(tline,template,length(template))
      smi.nsmp = cellfun(@str2num,regexp(tline,'[\d]+','match'));
    end
    
    template = '## Head Distance [mm]:';
    if strncmp(tline,template,length(template))
      smi.headdist = cellfun(@str2num,regexp(tline,'[\d]+','match'));
    end
    	    
  elseif numel(regexp(tline, 'Time*'))
      
        smi.label = cat(1, smi.label, {tline});
        smi.label = regexp(smi.label{:},'[^\t\r\n\f\v]*','match')';
        typeln = regexp(smi.label','Type');
        typeidx = find(cellfun(@numel,typeln)==1);

        % delete Type column because only contains strings
        smi.label(typeidx,:) = [];
        % preamble data matrix
        smi.dat = zeros(size(smi.label,1),smi.nsmp); 
      
  else
    % all other lines are not parsed
    
     template ='Sample Rate:';
     if contains(tline,template)
       smi.Fs = cellfun(@str2num,regexp(tline,'[\d]+','match'));
       flag_file_type_CM = 1;
     end
    
  end
  
end

% remove the samples that were not filled with real data
% smi.dat = smi.dat(:,1:current);

% place the timestamp channel outside of the data
if flag_file_type_CM
    term = 'Start';
else 
    term = 'Time';
end

c = find(strcmp(smi.label, term)); 
  smi.timestamp = smi.dat(c,:);
  smi.dat(c,:) = [];
  smi.label(c) = [];
end

```

**Comment by arnodelorme** [comment]
Hi Robert, maybe there was some confusion here. Let's discuss tomorrow.

**Comment by deepagupta** [comment]
Thank you Arnaud.

**Comment by deepagupta** [comment]
Thank you Arnaud and Robert for giving me the opportunity to contribute. 
[Note: I have given my code pop_eyetracking.m (reads events not samples) separately to Arnaud for the plugin.]

**Comment by schoffelen** [comment]
Can this be closed? I was not part of the discussion before, and I don't know the eventual outcome, but I see elsewhere on github some code that has branched off off read_smi_txt, and another file that reads in event information (probably along the formatting of the file that was shared in this issue). 

As far as I understand what has been going on, is that eyetracking events can be exported to a text file (from the original idf file), which yields a type of file that contains rich information about onsets of saccades etc. I think that the fieldtrip codebase would be improved if such functionality were also implemented here. The best place to deal with such functionality would be in ft_read_event, and perhaps have a dedicated file that reads such event files (which apparently are different files than the files that contain the eyetrackers' time series (for which the original read_smi_txt.m was written).

Perhaps it would be good to consider to merge the branched off code back into fieldtrip

**Comment by deepagupta** [comment]
I think this can be closed now because after discussing with me, Arnaud had kindly decided to take this with Robert by himself. Thank you.

**Comment by schoffelen** [comment]
There is no documented trace of Arno discussing this with Robert, but I am fine to close for now. (although I think it is still unresolved from the point of view of FieldTrip)

**Comment by deepagupta** [comment]
@arnodelorme , kindly advise if this needs to be reopened. Just to refresh, I was asked to create this report by you following which we had added the code to handle this - managing MSG 1 # Message: 9999 token for eyetracking- and you had mentioned to me that you'd directly take the rest of the discussion to Robert over a meeting with him which was to happen thereafter.  Regarding @schoffelen 's comment about resolving for Fieldtrip, I don't know the latest status. You may please let us know. Hope this is somewhat helpful for the decision otherwise this is closed. Thanks and regards, Deepa :)
