### ISSUE TITLE
Help: Wrong magnetic field result for current dipole in spherical conductor

### ISSUE THREAD

**Issue by youyouhdhd** [fieldtrip/fieldtrip#2224]
Hello everyone
I am a beginner in fieldtrip, my name is wanghd, from China, and I am using fieldtrip to do research on mcg issues. First of all, I would like to thank the developer for providing such a handy toolbox, my problem with fieldtrip is as follows:
When I used the "openmeeg" method to calculate the meg-positive problem, I found some anomalies in the results, and the referenced fieldtrip link is as follows
https://www.fieldtriptoolbox.org/workshop/oslo2019/forward_modeling/
I refer to the above tutorial to solve the magnetic field generated by the current dipole in the outer plane of a spherical conductor, which is located at the center of the sphere, and verify the calculated leadfield, the results are shown in the figure below:
![Snipaste_2023-04-15_17-48-29](https://user-images.githubusercontent.com/54936458/232226435-146deb4b-9b53-4496-8baa-d5ec9a8cce98.jpg)

As you can see, the results are very unconventional, and I have used other calculation libraries (including the University of Helsinki's boundary element calculation library, singleshell and singlesphere methods) to get different results for the magnetic field, so I don't know where the error occurred, and I hope that anyone can help me.
![Snipaste_2023-04-15_18-14-21](https://user-images.githubusercontent.com/54936458/232226457-e2a4bda1-ed6d-4113-b803-aad765300d0f.jpg)
![Snipaste_2023-04-15_17-50-17](https://user-images.githubusercontent.com/54936458/232226461-eaf474b4-2814-4e43-a6fb-26211a298373.jpg)
![Snipaste_2023-04-15_18-14-03](https://user-images.githubusercontent.com/54936458/232226464-ecfcb65d-daba-4009-9b32-e435ca2f6592.jpg)

PS: I calculated the EEG problem in the example using the "openmeeg" method, and the results are roughly similar to the correct results in the example in terms of the shape of the leadfield, but there are only differences of order of magnitude.
The data I used will be uploaded to google drive, thanks again!
https://drive.google.com/drive/folders/1RIuPS5kOC2OVcijLZ9j8BD0I3hcz4bix?usp=share_link

**Comment by robertoostenveld** [comment]
It is unclear what you are trying to achieve, as you are switching between EEG and MEG, but then also mention MCG. Furthermore, why are you using a spherical model for MCG? A sphere approximates the head, but is a poor approximation of the torso.
 
What is it that you expect to get as result?

**Comment by youyouhdhd** [comment]
> 

Thanks for your reply, I want to apply fieldtrip with openmeeg to mcg field, but I found the result is rather weird when I calculate the forward problem, different from the dipole magnetic field result mentioned in the paper, so I use the single-layer sphere model to do the verification of my calculation process. Only this example is more detailed in the fieldtrip tutorial, although it is about eeg. So you understand why I have such strange questions.
In fact, I was simply verifying that I was using openmeeg the right way, and unfortunately, I got three different results using three methods, so that I don't even know which one is correct.😢

**Comment by robertoostenveld** [comment]
At this moment there is no reason for me to assume that there is anything wrong with the code, hence I will close this issue. Please ask questions about the use of FT on the mailing list, see https://www.fieldtriptoolbox.org/support/

You may want to check https://www.fieldtriptoolbox.org/tag/headmodel/, also in the https://github.com/fieldtrip/fieldtrip/tree/master/test directory you can find example scripts that compute forward solutions with different methods and that compare them, for example in https://github.com/fieldtrip/fieldtrip/blob/master/test/test_bug1042.m
