### ISSUE TITLE
ft_freqanalysis superlets fails with cfg.foilim

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#2232]
**Describe the bug**
ft_freqanalysis looks for cfg.foi to determine the required number of cfg.order elements (one per frequency) in: https://github.com/fieldtrip/fieldtrip/blob/02cf9660c01f545f84cfa1c2f2bf75e57c022547/ft_freqanalysis.m#L358
Since foilim is only expanded to foi later:
https://github.com/fieldtrip/fieldtrip/blob/02cf9660c01f545f84cfa1c2f2bf75e57c022547/ft_freqanalysis.m#L532-L537
This returns an error for a missing field in the cfg.
I think an unexpected side-effect of this is that the bit that was supposed to expand the order to the correct size multiplies it by the number of frequencies instead:
https://github.com/fieldtrip/fieldtrip/blob/02cf9660c01f545f84cfa1c2f2bf75e57c022547/ft_freqanalysis.m#L359-L360

**To Reproduce**
Run the following code:
```
data = [];
data.trial   = {randn(3, 1001)};
data.time    = {linspace(0, 1, 1001)};
data.label   = {'A', 'B', 'C'};

cfg             = [];
cfg.feedback    = 'no';
cfg.method      = 'superlet';
cfg.output      = 'pow';
cfg.pad_type    = 'zero';
cfg.polyremoval = -1;
cfg.pad         = 'nextpow2';
cfg.toi         = 'all';
cfg.foilim      = [3, 50];
cfg.width       = 3;
cfg.gwidth      = 3;
cfg.combine     = 'additive';
cfg.order       = 5;
freq = ft_freqanalysis(cfg, data);
```

**Possible solution**
Either foilim needs to be expanded into foi earlier (but I guess pulling this bit of code up will require moving other things as well), or the part about order will have to be moved down to a later part of the code?

**Comment by NirOfir** [comment]
I'll add a couple of things I noticed later:

1. The name cfg.combine is a bit confusing, because it controls how the sequence of wavelets is created and not how they are combined (which is always by the geometric mean). I suggest renaming it to sequence/increment/step
2. The default of cfg.combine in the paper is multiplicative, so I think we should make that the default in FT too.
3. The default order is 1, which I don't think makes a lot of sense, because that just computes a wavelet transform. Since I don't know of a reasonable default, I would suggest leaving it without a default. My preference would be to add an error if a user sets the order to 1 for all frequencies (which might be too strict compared to the rest of the toolbox, so returning a warning is another option, although these are often turned off), but I'm happy to hear other opinions.
4. One unrelated tiny issue is that the requested FOI is compared against Nyquist 3 times (for different methods). I think this can be done once after FOI is defined.

**Comment by schoffelen** [comment]
@DanBenHa what's your take on all this, since you are one of the main stakeholders of this code. If there's no interest to push this further, I will briefly have a look at the issue that inspired this issue, perhaps solve it, but otherwise keeps the detailed points raised by @NirOfir untouched

**Comment by DanBenHa** [comment]
Without having looked at it in detail, @NirOfir points seem reasonable.

It's been years since I last used fieldtrip, or MATLAB for that matter, so I'm fine if anyone wants to take this over.

**Comment by schoffelen** [comment]
@NirOfir can you pull the suggested changes in the associate PR and check whether it now works for you?

**Comment by NirOfir** [comment]
Thanks! Works perfectly.
