### ISSUE TITLE
ft_sourceproj issue

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2274]
The code below is from a tutorial I worked on with Robert and available on this page 

https://eeglab.org/tutorials/09_source/EEG_sources.html#performing-source-reconstruction-in-a-volume

To reproduce the bug

```
load('-mat', 'bug.mat');
figure; ft_sourceplot(cfg, sourceProj);
```

The error is 

```
Warning: functional data is complex, taking absolute value 
 In ft_sourceplot at line 454

Incorrect number or types of inputs or outputs for function 'abs'.

Error in ft_sourceplot (line 455)
    fun = abs(fun);
 ```

The issue is that fun is a cell array. 
![Screen Shot 2023-07-10 at 9 24 44 AM](https://github.com/fieldtrip/fieldtrip/assets/1872705/ab07f90f-19a8-4fd0-9f99-52b6caa98c20)
[bug.mat.zip](https://github.com/fieldtrip/fieldtrip/files/12005929/bug.mat.zip)

Fieldtrip version used is "This is FieldTrip, revision 7a9b314c3." (a few weeks old?)

**Comment by robertoostenveld** [comment]
I was able to reproduce and have fixed it.
