### ISSUE TITLE
Improve code testing that contributors can do on their local computer

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2279]
*Description:* The suggestion is to add two new functions inside the fieldtrip/test repository:

1. ft_checklocaldata: checks if the public data are already downloaded on the local computer and suggests to the contributor to download the public data that are missing. Also, it can suggest to the contributor which test scripts can run based on the available local computer memory.

2. ft_inventorise_test: will select certain test scripts to run based on the pre-selected dependencies given by the contributor. Then it will run these test scripts, and it will print a list of the test that failed and need to be manually inspected.

**Comment by robertoostenveld** [comment]
I am not sure whether we need new functions, or whether we should revamp/repurpose the existing [ft_test](https://github.com/fieldtrip/fieldtrip/blob/6dde47e406941cb6bb405dd9e66c25712aeafd97/utilities/ft_test.m) function. For a start, you could move it over from `fieldtrip/utilities` to the `fieldtrip/test` directory. 

I suggest that you first write a design document that would also serve as or contribute to online documentation on the website. If I were a naive user, I would expect guidance related to testing on https://www.fieldtriptoolbox.org/development/testing/, so what would you write on that page? I think that page needs some redesign anyway, for example: "why test?", "how to test yourself?", "how does the automatic testing work?" and "how to add new tests?"

**Comment by contsili** [comment]
This issue is related to #2294.
