### ISSUE TITLE
fieldtrip seems to be conflicted with TCP/IP communication

### ISSUE THREAD

**Issue by Y2KdeLaplace** [fieldtrip/fieldtrip#2284]
**Describe the bug**
`trig = tcpclient('192.168.3.24',3200,'Timeout',0.001); % simulate receiving triggers
 write(trig,1,'double')
addpath('D:\#work\Toolboxes\fieldtrip')
 ft_defaults
 hdr = ft_read_header('D:\debug\rawdata\002_xxx_1.vhdr');
datals = ft_read_data('D:\debug\rawdata\002_xxx_1.eeg','header',hdr);
write(trig,1,'double')
**Warning: DRAIN timed-out while waiting for data to be sent. All remaining data will be flushed. **
write(trig,1,'double')
Warning: DRAIN timed-out while waiting for data to be sent. All remaining data will be flushed. `
Before I added fieldtrip path, i could normally use `write` function in `tcpclient` to send number to anouther MATLAB instance.  
After I added pathn and initialized fieldtrip, using `write` function would receive a warning massage. And the received TCP/IP in anothor MATLAB wouldn't received any massage.

**To Reproduce**
1. turn on two MATLAB instance
2. use `tcpserver` and `tcpclient` to establish TCP communication
3. send massage from client MATLAB
4. addpath filedtrip and command ft_default
5. read any eeg data or header
6.  send massage from client MATLAB again
7. server MATLAB will not receive massage

**Expected behavior**
fieldtrip should not influence TCP/IP communication in MATLAB

**Environment and versions (please complete the following information):**
 - Operating System: Windows 11
 - MATLAB version R2021a
 - FieldTrip version: unknown from ft_version

**Additional context**
I want to know the reason why i cann;t receive massage.

**Comment by robertoostenveld** [comment]
I failed replicating the problem. On a remote linux computer I did the following

```
restoredefaultpath
clear all

server = tcpserver(3200)

while true
  try
    str = read(server, 1, "char");
    fprintf(str);
  catch
    disp('restarting');
  end
end
```

and on my macbook I did the following

```
restoredefaultpath
clear all

client = tcpclient('dccn-c031.dccn.nl', 3201);

write(client, 'hello world', 'char');

addpath ~/matlab/fieldtrip/
ft_defaults

write(client, 'hello again', 'char');
```

and the server nicely prints `hello world` and `hello again`.

It might be something that is windows specific, although I cannot come up with anything. 

Does it specifically happen if you run `ft_defaults`? That function does not clear any variables, but does make a network connection by default. Perhaps windows can only keep a single TCP connection open, which causes your original one to be closed ... (just speculating).

Could you try it with 

```
addpath somewhere/fieldtrip
global ft_default
ft_default.trackusage = false
ft_defaults
```

to prevent the network tracking ping to be sent?

**Comment by Y2KdeLaplace** [comment]
Now I think it may be the problem of TCP setting. I set the 'Timeout' parameter 0.001, which was too small. Sorry for bothering you.
