### ISSUE TITLE
Passing the checkmaxfilter option better arround

### ISSUE THREAD

**Issue by paschels** [fieldtrip/fieldtrip#2297]
When using raw data (before Maxfilter correction), one has to bypass the `Maxshield data should be corrected using Maxfilter prior to importing in FieldTrip.` error. To do so, for "reading" functions like `ft_read_header` and `ft_read_event`, setting the option `checkmaxfilter` to `false` works fine. However, that is not the case for all function with `cfg` as argument for which the way to go is by assigning `cfg.checkmaxfilter = false;`. Until now I only had problem with `ft_definetrial` and the error was coming from `ft_trialfun_general` function with the following error:
`Error using ft_read_header (line 1973)
Maxshield data should be corrected using Maxfilter prior to importing in FieldTrip.
Error in ft_read_event (line 1632)
      hdr = ft_read_header(filename, 'headerformat', headerformat, 'checkmaxfilter', checkmaxfilter, 'readbids', readbids, 'password', password);
Error in ft_trialfun_general (line 117)
  event = ft_read_event(cfg.headerfile, eventopt{:});Error in ft_definetrial (line 198)
    [trl, event] = feval(cfg.trialfun, cfg);`

The simplest way I have found to correct this is to add this line
`eventopt = ft_setopt(eventopt, 'checkmaxfilter', ft_getopt(cfg, 'checkmaxfilter'));`
in the `ft_trialfun_general` [here](https://github.com/fieldtrip/fieldtrip/blob/1a41b3a87dac8769d50b52012ca5b43eb8176171/trialfun/ft_trialfun_general.m#L93). So basically, when using such data, one should ensure that the `checkmaxfilter` variable is set to `false` everywhere where it is used by a "reading" function.  I will expand upon this issue later if I run into any more problems concerning the study of data with no Maxfilter correction.

**Comment by robertoostenveld** [comment]
I confirmed and fixed this with https://github.com/fieldtrip/fieldtrip/commit/1af47b1d211a513a575afb8bd7a69d97d3414c92.
