### ISSUE TITLE
fieldtrip2fiff result cannot be read for Subject01.ds   

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2309]
**Describe the bug**

Upon converting Subject01.ds with `fieldtrip2fiff` I get this error when I try to read the resulting fif file. 

```
Index in position 2 exceeds array bounds. Index must not exceed 1.
Error in ft_read_event (line 1746)
        events_code = str2num(char(events_id(:, 2))); 
```

I cannot tell whether the error is in the writing, or in the reading.

**To Reproduce**

```
cfg = [];
cfg.dataset = 'Subject01.ds';
data = ft_preprocessing(cfg);

event = ft_read_event(cfg.dataset);

fieldtrip2fiff('Subject01.fif', data, 'event', event)

%%

fif_hdr = ft_read_header('Subject01.fif') % this works
fif_event = ft_read_event('Subject01.fif') % this fails
```

**Expected behavior**

I expect the fif data to be identical to the CTF data , and the header and events to be sufficiently similar so that I can run the same preprocessing and averaging pipeline. 

**Environment and versions (please complete the following information):**
 - macOS 13.4.1 on Intel
 - MATLAB Version: 9.12.0.1956245 (R2022a) Update 2
 - FieldTrip latest version, including commit 930362ef335522015f463f5eb04185ea4df80de2

**Comment by schoffelen** [comment]
it's not even unconfirmed anymore...
