### ISSUE TITLE
ft_freqstatistics not working with "analytic" method

### ISSUE THREAD

**Issue by emmaducos** [fieldtrip/fieldtrip#2324]
**Describe the bug**
While doing the tutorial on stats over time-frequency M/EEG data that I found here : https://www.fieldtriptoolbox.org/workshop/natmeg2014/statistics/
in the "compute statistics" paragraph, the function ft_freqstatistics is used with the configuration method "analytic".
I copy pasted the code in my Matlab window, and I got the following error: 

> Execution of script ft_statistics_analytic as a function is not supported:
> C:\Users\xxx\Documents\project\rxpgen\03_rxpgen_analysis\rxpgen_toolbox\fieldtrip-20230913\ft_statistics_analytic.m
> 
> Error in [ft_freqstatistics](matlab:matlab.internal.language.introspective.errorDocCallback('ft_freqstatistics', 'C:\Users\xxx\Documents\project\rxpgen\03_rxpgen_analysis\rxpgen_toolbox\fieldtrip-20230913\ft_freqstatistics.m', 197)) ([line 197](matlab: opentoline('C:\Users\xxx\Documents\project\rxpgen\03_rxpgen_analysis\rxpgen_toolbox\fieldtrip-20230913\ft_freqstatistics.m',197,0)))
>   [stat] = statmethod(cfg, dat, design);

**To Reproduce**
1. Go to 'https://www.fieldtriptoolbox.org/workshop/natmeg2014/statistics/'
2. copy paste code until section "compute statistics"
3. run & see error

**Expected behavior**
No bug, statistics computed as shown in the tutorial. 

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10 
 - MATLAB version R2023b (in an interactive cell format .mlx)
 - FieldTrip version 20230913

**Additional context**
I am using the interactive cell format .mlx of matlab for my scripts, which is similar to jupyter in python. Up so far, I did not have issues with this version over .m scripts. 
I run it again with the cfg.debug option, and got the following data:

> the call to "ft_selectdata" took 0 seconds
> using "ft_statistics_analytic" for the statistical testing
> -----------------------------------------------------------------------
> An error was detected while executing ft_freqstatistics with
> 
> Ce9dei2ZOo_ds =
> Ce9dei2ZOo_is =
> Ce9dei2ZOo_ns =
> Ce9dei2ZOo_ws =
> FjmoT6aA_current_ft_toplevel =
>    1
> 
> FjmoT6aA_ft_path =
> C:\Users\xxx\Documents\project\rxpgen\03_rxpgen_analysis\rxpgen_toolbox\fieldtrip-20230913
> 
> FjmoT6aA_ft_ver =
> 20230913
> 
> FjmoT6aA_highest_ft =
> ft_freqstatistics
> 
> FjmoT6aA_k =
>      4
> 
> FjmoT6aA_lowest_ft =
> ft_freqstatistics
> 
> FjmoT6aA_stack =
>   4×1 [struct](matlab:helpPopup struct) array with fields:
> 
>     file
>     name
>     line
> 
> cfg =
>               channel: 'MEG*1'
>             statistic: 'indepsamplesT'
>                  ivar: 1
>                design: [2 1 1 1 1 1 1 2 2 1 2 1 1 1 2 2 2 2 1 1 1 2 1 2 1 2 2 1 2 1 2 1 1 2 1 2 2 2 1 1 1 2 1 2 2 2 1 2 1 1 1 2 2 1 1 2 2 2 2 2 2 2 1 2 1 1 2 2 1 1 1 2 1 2 2 1 1 2 2 2 1 2 1 1 1 2 1 1 1 2 1 2 2 1 2 1 2 1 2 2]
>                method: 'analytic'
>              correctm: 'no'
>                 debug: 'displayonerror'
>            trackusage: 'no'
>           checkconfig: 'loose'
>             checkpath: 'pedantic'
>             checksize: 100000
>              showlogo: 'yes'
>          showcallinfo: 'yes'
>     outputfilepresent: 'overwrite'
>         trackcallinfo: 'yes'
>         trackdatainfo: 'no'
>         tracktimeinfo: 'yes'
>          trackmeminfo: 'no'
>               toolbox: [1×1 struct]
>          notification: [1×1 struct]
> 
> checkdatafields =
>    0   0   0   0   0   0
> 
> ft_nargout =
>      1
> 
> varargin =
>     {1×1 struct}
> 
> -----------------------------------------------------------------------

**Comment by schoffelen** [comment]
The error suggests that there is something wrong with the local copy of ft_statistics_analytic.

C:\Users\educos\OneDrive - Institut Pasteur Paris\Documents\project\rxpgen\03_rxpgen_analysis\rxpgen_toolbox\fieldtrip-20230913\ft_statistics_analytic.m

You might want to check whether the first line of the referenced function starts with the word 'function', more specifically it should read: function [stat, cfg] = ft_statistics_analytic(cfg, dat, design)

If that is not the case, something went wrong on your end.

**Comment by emmaducos** [comment]
Dear Schoffelen, 

I just checked my version of ft_statistics_analytic.m currently on my machine and this is the first line: 

function [stat, cfg] = ft_statistics_analytic(cfg, dat, design)

the word function is present, and should enable the use of this script as a function. But I still have the error. 

ps: I forgot to take out my name & institute name out of the paths, could you blank it out in your message, thx !

**Comment by emmaducos** [comment]
I have

**Comment by robertoostenveld** [comment]
I am not sure whether you meant to close the issue, or whether you clicked the close button upon editing out your name and email.

Could you execute the following in your MATLAB command window?

```
cfg = [];
cfg.statistic = 'ft_statfun_mean';
cfg.ivar = 1;
stat = ft_statistics_analytic(cfg, 1, 1)
```

This is most minimal computation that I can come up with, and it should return something a very simple structure.

**Comment by schoffelen** [comment]
I think this was indeed closed intentionally, as far as I can see, because a re-download of FT solved the issue.

**Comment by robertoostenveld** [comment]
ah thanks, I missed that. Good to read.

**Comment by emmaducos** [comment]
Thank you Robert and Schoffelen for your quick help !
