### ISSUE TITLE
 Time label mismatch in 'ft_multiplotER' and 'ft_topoplotER' integration

### ISSUE THREAD

**Issue by RaoXie** [fieldtrip/fieldtrip#2326]
**Describe the bug**
When using the 'ft_multiplotER' function to plot MEG time courses and then attempting to generate a topology plot for a specific time window, there is an issue where the time label displayed on the topoplot does not correspond correctly to the manually selected time range.

**To Reproduce**
1. call 'ft_timelockanalysis' to calculate timelocked average ERF
2. call 'ft_multiplotER' to create an interactive figure for event-related fields versus time
3. manually select a specific time window within the interactive plot 
4. click to call 'ft_topoplotER' and generate topology plot by averaging ERF across specified time window

`
%% time lock analysis
cfg=[];
tlc=ft_timelockanalysis(cfg,data);

%% interactive topology plot
figure;
cfg = [];
cfg.layout = 'CTF275_helmet.mat';
cfg.viewmode = 'butterfly';
% cfg.colorgroups = 'sequential';
ft_multiplotER(cfg, tlc);
`

**Expected behavior**
the time label on the left bottom on topoplot should correspond to the time range specified earlier in the interactive plot

**Screenshots**
![image](https://github.com/fieldtrip/fieldtrip/assets/93839122/02026b45-739c-4d46-8ac4-908bdc33bdc0)

**Environment and versions (please complete the following information):**
 - Operating System: centos
 - MATLAB version R2021b

**Comment by robertoostenveld** [comment]
I can confirm the problem. It is specific to viewmode=butterfly, and caused by the select_topoplotER subfunction ignoring that the x-axis of the figure is not what it seems due to it being plotted with ft_plot_vector.
