### ISSUE TITLE
ft_volumerealign fails on realigned.fid.pos

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2328]
@NataschaRoos reported that she has a problem with ft_volumerealign

<img width="608" alt="Screenshot 2023-10-06 at 12 35 27" src="https://github.com/fieldtrip/fieldtrip/assets/899043/56ef2a9c-a446-4b95-bf63-d2a3db833dcf">

The problem is due to realigned.fid being empty, which it inherits from the input mri.

The call to ft_volumerealign was immediately after reading the MRI from a nii file with ft_read_mri. Apparently ft_read_mri adds an empty fid field.

**Environment and versions (please complete the following information):**
 - Operating System: linux
 - MATLAB version: 2021a
 - FieldTrip version: 20230317

**Comment by schoffelen** [comment]
the reported line number in the error does not coincide with the equivalent line number of the version of ft_volumerealign on /home/common (or the master version). If I look in said version there's a check already for the presence of a fid field, so this issue seems to be old news.

if isfield(realign, 'fid')
    % also apply the transformation on the fiducials
    realign.fid.pos = ft_warp_apply(transform, realign.fid.pos);
  end

**Comment by schoffelen** [comment]
https://github.com/fieldtrip/fieldtrip/commit/7105fafffaaf1bb1eaa379612d42b9cf8fdab816

**Comment by schoffelen** [comment]
but perhaps the if statement needs to be expanded with || isempty(realign.fid)

**Comment by schoffelen** [comment]
ft_read_mri adding an empty fid is something I have never experienced myself. I suspect that @NataschaRoos uses a BIDS formatted anatomical, which causes the creation of a (possibly empty) fid structure in the lines beyond 865 of ft_read_mri, which is later added to the output mri structure.

**Comment by schoffelen** [comment]
so then the above suggested extra conditional statement should be added to ft_read_mri.

**Comment by robertoostenveld** [comment]
> ...uses a BIDS formatted anatomical ....

Ah, that explains it! She is using a frozen (and slightly older) version of FieldTrip, so the error popping up now and not in the past when she ran the same analysis already puzzled me. But she has indeed been bidsifying the MRI first, and now working on bidsifying the EEG. That explains the error becoming visible.

I will add a check like `isempty(realign.fid)`. I will also look at ft_read_mri, because I think that an empty `mri.fid` field is not desirable in general.

**Comment by robertoostenveld** [comment]
With the older frozen version of FieldTrip that @NataschaRoos uses, the solution for now is to remove the empty `mri.fid` field immediately following ft_read_mri.
