### ISSUE TITLE
Layouts Request (R-Nets & DCC Customized 64ch)

### ISSUE THREAD

**Issue by JessRamosS** [fieldtrip/fieldtrip#2330]
Request for adding/creating a layout file template for the BrainProduct R-Nets for Infant 64ch with 10-10 system (https://www.brainproducts.com/solutions/r-net/) and Standard DCC-customized 64ch layout for BrainProducts ActiCap [As discussed with @robertoostenveld and @marlenemeyer]

**Comment by robertoostenveld** [comment]
Hi Jessica, could you add the reference images of the R-Net and the DCC-customized electrode layouts here? Preferably as a PDF or high-quality bitmap. 

We don't have to follow the procedure here https://www.fieldtriptoolbox.org/tutorial/layout/#creating-a-layout-from-an-image as we don't have to start from scratch but can take the 5% layout from https://www.fieldtriptoolbox.org/template/layout/#standard-10-xx-cap as a starting point, but we still would need to know which electrodes to keep and which to remove.

**Comment by JessRamosS** [comment]
Hi Robert,
I have attached a pdf with the reference image for the R-Net and the DCC-customized electrode layouts. 

[RNetsP-BA-64.pdf](https://github.com/fieldtrip/fieldtrip/files/12859134/RNetsP-BA-64.pdf)
[actiCap_64Ch_DCC_customized.pdf](https://github.com/fieldtrip/fieldtrip/files/12859135/actiCap_64Ch_DCC_customized.pdf)

**Comment by robertoostenveld** [comment]
I used the 10-10 layout as the starting point with the following code

```
cfg = [];
cfg.layout = 'EEG1010.lay';
cfg.channel = {
  'Fp1'
  'Fp2'
  'AF7'
  'AF3'
  'AFz'
  'AF4'
  'AF8'
  'F7'
  'F5'
  'F3'
  'F1'
  'Fz'
  'F2'
  'F4'
  'F6'
  'F8'
  'FT9'
  'FT7'
  'FC5'
  'FC3'
  'FC1'
  'FCz'
  'FC2'
  'FC4'
  'FC6'
  'FT8'
  'FT10'
  'T7'
  'C5'
  'C3'
  'C1'
  'Cz'
  'C2'
  'C4'
  'C6'
  'T8'
  'TP9'
  'TP7'
  'CP5'
  'CP3'
  'CP1'
  'CPz'
  'CP2'
  'CP4'
  'CP6'
  'TP8'
  'TP10'
  'P7'
  'P5'
  'P3'
  'P1'
  'Pz'
  'P2'
  'P4'
  'P6'
  'P8'
  'PO9'
  'PO7'
  'PO3'
  'POz'
  'PO4'
  'PO8'
  'PO10'
  'O1'
  'Oz'
  'O2'
  };
cfg.skipcomnt = 'yes';
cfg.skipscale = 'yes';

layout = ft_prepare_layout(cfg);

save dcc_customized_acticap64.mat layout

%%

% read from disk and check

cfg = [];
cfg.layout = 'dcc_customized_acticap64.mat';
layout = ft_prepare_layout(cfg);
close all
ft_plot_layout(layout);

%%

cfg = [];
cfg.layout = 'EEG1010.lay';
cfg.channel = {
  'Fp1'
  'Fpz'
  'Fp2'
  'AF7'
  'AF3'
  'AFz'
  'AF4'
  'AF8'
  'F9'
  'F7'
  'F5'
  'F3'
  'F1'
  'Fz'
  'F2'
  'F4'
  'F6'
  'F8'
  'F10'
  'FT7'
  'FC5'
  'FC3'
  'FC1'
  'FCz'
  'FC2'
  'FC4'
  'FC6'
  'FT8'
  'T7'
  'C5'
  'C3'
  'C1'
  'Cz'
  'C2'
  'C4'
  'C6'
  'T8'
  'TP7'
  'CP5'
  'CP3'
  'CP1'
  'CPz'
  'CP2'
  'CP4'
  'CP6'
  'TP8'
  'P9'
  'P7'
  'P5'
  'P3'
  'P1'
  'Pz'
  'P2'
  'P4'
  'P6'
  'P8'
  'P10'
  'PO7'
  'PO3'
  'POz'
  'PO4'
  'PO8'
  'O1'
  'Oz'
  'O2'
  'Iz'
  };
cfg.skipcomnt = 'yes';
cfg.skipscale = 'yes';

layout = ft_prepare_layout(cfg);
layout.pos(:,1) = layout.pos(:,1)*0.9;
layout.pos(:,2) = layout.pos(:,2)*1.1 - 0.04;

save rnet64.mat layout

%%

% read from disk and check

cfg = [];
cfg.layout = 'rnet64.mat';
layout = ft_prepare_layout(cfg);

close all
ft_plot_layout(layout);
```

**Comment by robertoostenveld** [comment]
I have also added the two new layouts to the website, they should appear on https://www.fieldtriptoolbox.org/template/layout/ in about 5 minutes. @JessRamosS can you please check carefully that they are correct (and that you like them)?

**Comment by robertoostenveld** [comment]
The change to the website refreshing has to do with stricter RU-wide security measures. For now there is a work-around and the online documentation has been refreshed with the two new layouts. Please check.

**Comment by schoffelen** [comment]
I believe that this can be closed
