### ISSUE TITLE
issue for read Nicolet .e file 

### ISSUE THREAD

**Issue by tcs211** [fieldtrip/fieldtrip#2352]
**Describe the bug**
When reading my Nicolet .e file, in the script: read_nervus_header.m and the section of function channelInfo = read_nervus_header_ChannelInfo(h, StaticPackets, Index, ITEMNAMESIZE, LABELSIZE)

The nrIdx always very large and cause the loop to run even position already out of the actual file size, and it would take 3-5 minutes to read the file. 
for example: the log channel info nrIdx:  [2293760 4587520]
so i add bewlow code to stop the loop when it read exceed the file size, and it resolved the issue. Reading file could be complete in seconds.
>  if (ftell(h) >= filesize)
>     break;
>   end
full loop is below: 
for i = 1: nrIdx(2) 
  channelInfo(i).sensor = deblank(cast(fread(h, LABELSIZE, 'uint16'),'char')');
  channelInfo(i).samplingRate = fread(h,1,'double');
  channelInfo(i).bOn = logical(fread(h, 1 ,'uint32'));
  channelInfo(i).lInputID = fread(h, 1 ,'uint32');
  channelInfo(i).lInputSettingID = fread(h,1,'uint32');
  channelInfo(i).reserved = fread(h,4,'char');
  fseek(h, 128, 'cof');
  if (ftell(h) >= filesize)
    break;
  end
end

**Comment by tcs211** [comment]
> so if I understand it correctly, the snippet
> would have to be inserted around here?
>https://github.com/fieldtrip/fieldtrip/blob/52826a83851fdf3976a7ce201f2a59da08c8792f/fileio/private/read_nervus_header.m#L594C24-L594C24

Yes.
Besides, I add the code to get filesize in the begin of the function: read_nervus_header_ChannelInfo
```
fseek(h, 0, 'eof');
filesize = ftell(h);
```

I will give you the test file link by Email.
Thanks!

**Comment by tcs211** [comment]
here is the test EEG file link
https://drive.google.com/drive/folders/1dX3lwnOAknUV4kePm-NBa8v5V_3acfo-?usp=sharing
 
 
>>>>> Original Message <<<<<
From: fieldtrip/fieldtrip
To: fieldtrip/fieldtrip
Cc: Chin Sung Tung;Author
Sent Date: Mon,04 Dec 2023 18:23:23 Asia/Taipei
Subject: Re: [fieldtrip/fieldtrip] issue for read Nicolet .e file (Issue #2352)
 


so if I understand it correctly, the snippet
if (ftell(h) >= filesize)break;end
would have to be inserted around here?
https://github.com/fieldtrip/fieldtrip/blob/52826a83851fdf3976a7ce201f2a59da08c8792f/fileio/private/read_nervus_header.m#L594C24-L594C24
We do not have a Nicolet system ourselves. Would you be able to share a test file so that we can confirm the problem and that the solution works?
&mdash;

**Comment by tcs211** [comment]
My record of running ft_databrowser(cfg),  at the final: the call to "ft_databrowser" took 570 seconds
Matlab version R2023b
>> ft_databrowser(cfg)
Warning: Some channels ignored due to different sampling rates: Rate, IBI, Bursts, Suppr 
> In ft_read_data (line 1088)
In ft_databrowser (line 475) 
detected   0 visual artifacts
the different artifact types correspond to the following colors:
  visual = pink
the different event types correspond to the following colors:
  Hyperventilation     = black
  Impedance            = red
  Photic               = blue
  Posthyperventilation = lime
  UNKNOWN              = fuchsia
Warning: adding D:\fieldtrip\external\brewermap toolbox to your MATLAB path 
Warning: adding D:\fieldtrip\external\matplotlib toolbox to your MATLAB path 
Warning: adding D:\fieldtrip\external\cmocean toolbox to your MATLAB path 
Warning: adding D:\fieldtrip\external\colorcet toolbox to your MATLAB path 
Warning: Some channels ignored due to different sampling rates: Rate, IBI, Bursts, Suppr 
------------------------------------------------------------------------------------
You can use the following keyboard buttons in the databrowser
1-9                : select artifact type 1-9
shift 1-9          : select previous artifact of type 1-9 (does not work with numpad)
alt 1-9            : select next artifact of type 1-9
arrow-left         : previous trial
arrow-right        : next trial
shift arrow-up     : increase vertical scaling
shift arrow-down   : decrease vertical scaling
shift arrow-left   : increase horizontal scaling
shift arrow-down   : decrease horizontal scaling
t                  : open trial or segment selection dialog
c                  : open channel selection dialog
h                  : open horizontal scaling dialog
v                  : open vertical scaling dialog
p                  : open preproc editor
i                  : identify a specific channel
m                  : toggles between cfg.viewmode options
s                  : toggles between cfg.selectmode options
q                  : quit
------------------------------------------------------------------------------------

the call to "ft_databrowser" took 570 seconds

**Comment by tcs211** [comment]
I also test read_nervus_header, no error was recorded

```
>> cd D:\fieldtrip\fileio\private
>> header=read_nervus_header( 'D:\eeg_dataset\raw\20231124103712_100770.e')
```
This took 2 minutes to get the header object
With the break code, this would be done in 1 seconds

**Comment by robertoostenveld** [comment]
On my computer, without the break or any other change to the code, I get 

```
tic; header = ft_read_header( '20231124103712_100770.e'); toc
Elapsed time is 0.475157 seconds.
```

If I do include the break and put a breakpoint on that line, it does not get executed. 

The `read_nervus_header` function trying to read channel information past the end of the file (which is what your "fix" prevents) suggests that there is another problem at the root of this.

A hypothesis based on past experience on Windows computers and on your name is that you might be using different language settings in your operating system than I am using. Consequently it may be that reading a `char` from the file does not correspond to reading an 8-bit ASCII value. See also the section on ENCODING in https://nl.mathworks.com/help/matlab/ref/fopen.html. 

Could you try on line 37 whether specifying `'US-ASCII'` makes a difference?

```
h = fopen_or_error(filename,'rb','ieee-le','US-ASCII');
```

**Comment by tcs211** [comment]
Yes, it works by adding 'US-ASCII'. My Windows is Traditional Chinese version.
`h = fopen_or_error(filename,'rb','ieee-le','US-ASCII');`
Thanks for solving this problem!
