### ISSUE TITLE
function ft_singleplotTFR output

### ISSUE THREAD

**Issue by Fusenheizi** [fieldtrip/fieldtrip#2363]
When using ft_singleplotTFR and specifying a baseline and baselinetype, the program recalculates the powspectrm for visualization purposes. However, it seems that this operation is only used for visualization. Are there any corresponding computation outputs?

**Comment by schoffelen** [comment]
Hi @Fusenheizi this is not the place to ask questions. Please follow the directions on the FieldTrip website and ask your question on the discussion list.
