### ISSUE TITLE
Document and implement OPM coregistration on basis of only Polhemus 3D tracker.

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2365]

**Comment by robertoostenveld** [comment]
mentioning @contsili 

This requires that the sensor positions PLUS the fiducial/marker positions are known. The markers are clicked and expressed in polhemus coordinates (relative to the head), which  allows the sensor positions to be computed relative to the head.

This requires a template sensor array, which we already have in fieldtrip/template/gradiometer. 

I suggest that we add fiducial locations to the applicable gradiometer templates, just as we have it for `elec` structures. I believe that ft_transform_geometry will automatically work on those fiducial positions, just as on coilpos, coilori, and chanpos. 

We do have a template for fieldlinealpha1, but don't have a shared template for fieldlinebeta2 (we do have it, but it is not in FieldTrip yet).

**Comment by robertoostenveld** [comment]
Hi @tc-fieldline, 

I presume that there are markers on the alpha1 helmet similar as on the beta2 helmet. Can you give me their coordinates? I will then add them to the `template/gradiometer/fieldlinealpha1.mat` structure for consistency. copy them here, or send me an email with an excel file or so. 

thanks, Robert

**Comment by contsili** [comment]
I also have written code for the co-registration of the helmet with head points using the polhemus and the co-registration using the 3 HPI coils for a 32-sensor recording and a full 144-sensor recording. In both cases, a magnetic phantom was used.

**Comment by robertoostenveld** [comment]
This had been done by now, it is one of the methods described in https://www.fieldtriptoolbox.org/tutorial/coregistration_opm/
