### ISSUE TITLE
Problem with importing MEG datasets ds003352 & ds003922 with File-IO

### ISSUE THREAD

**Issue by asalazar4** [fieldtrip/fieldtrip#2372]
The NEMAR team is experiencing the following error when importing two MEG datasets (https://nemar.org/dataexplorer/detail?dataset_id=ds003352 , https://nemar.org/dataexplorer/detail?dataset_id=ds003922). Could we please have help resolving this?

```
Warning: assuming that the default scaling should be amplitude/distance rather than amplitude 

Reading data ...
FIF file detected, check if channel locations are rotated properly in the channel editor
Reading 30000 ... 130999  =     30.000 ...   130.999 secs...Error using reshape
Number of elements must not change. Use [] as one of the size inputs to automatically calculate the appropriate size for that dimension.

Error in fiff_read_raw_segment (line 160)
                    one = double(reshape(tag.data,nchan,this.nsamp));

Error in ft_read_data (line 1250)
      dat = fiff_read_raw_segment(hdr.orig.raw,begsample+hdr.orig.raw.first_samp-1,endsample+hdr.orig.raw.first_samp-1,chanindx);

Error in pop_fileio (line 197)
        alldata = ft_read_data(filename, 'header', dat, dataopts{:});

Error in pop_importbids (line 515)
                            EEG = pop_fileio(eegFileRaw); % fif folder

Error in load_dataset (line 21)
        [STUDY, ALLEEG] = pop_importbids(filepath, 'bidsevent','on','bidschanloc', bidsChan,'studyName',dsname,'outputdir', outputDir, 'subjects', subjects, 'ctffunc', ctffunc);

Error in run_pipeline (line 101)
[STUDY, ALLEEG, dsname] = load_dataset(opt.bidspath, opt.outputdir, opt.modeval, opt.subjects, opt.ctffunc);

Error in pop_run_pipeline (line 82)
	eval(command)
 
Error while evaluating Menu Callback.
```

**Comment by schoffelen** [comment]
Sure, no problem! Could you kindly point me to a single dataset in more detail so that I can do a selective download, and check out what might be going on. I suspect some recent changes to the low-level reading code. Could you confirm that you are using a very recent version of Fieldtrip, and perhaps that if you downgrade to a version from prior to november 2023 the reading works?

**Comment by asalazar4** [comment]
Thank you so much! We experienced the issue using v20230613 and v20240111 on ds003352 found here: https://nemar.org/dataexplorer/detail?dataset_id=ds003352

Please let me know if any additional details are need.

**Comment by schoffelen** [comment]
yes, I would like to know whether this occurs for a particular subject from that dataset. I'd rather not download 200 GB of data...

**Comment by asalazar4** [comment]
This error is given when importing Subject 1, Session 1, Task Color Spiraks, Run 00

```
Opening raw data file /expanse/projects/nemar/openneuro/ds003352/sub-1/ses-01/meg/sub-1_ses-01_task-ColorSpirals_run-00_meg.fif...
```

**Comment by schoffelen** [comment]
hi @asalazar4, I downloaded the referenced data file. To me it looks as if the datafile is corrupt. Specifically, when the low level function throws this error: 

Error in fiff_read_raw_segment (line 160)
                    one = double(reshape(tag.data,nchan,this.nsamp));

the number of elements in the tag.data field do not contain the expected number of data points to be the product of nchan*this.nsamp.

**Comment by schoffelen** [comment]
Hi @asalazar4 as per my previous comment, it could be that some of the data uploaded into the nemar repository are corrupted. We could consider building in some extra checks in the code for this, but that would require a bit of overhead in the lower level reading functions, and it would require work. Do you think such checks are necessary, and if so, who is going to implement this? @robertoostenveld what do you think?

**Comment by arnodelorme** [comment]
Note that all the files seem to be there. Also, you need not download the entire archive. You can download this file only. Based on the message, it could be that the data is truncated. We will add a comment to that dataset. Anyway, thank you for your answer.

**Comment by schoffelen** [comment]
Yes, indeed as I said the file is corrupted. The low-level reading function has read fewer bytes than the number of bytes suggested by the corresponding tag. In other words, there were fewer bytes available than numbers-of-channels times number-of-samples. My suggestion was related to the fact that we can build in a quick check (with additional overhead) that can throw a more informative error message than just a reshape error
