### ISSUE TITLE
Maxfilter issue when importing MEG datasets ds004276 & ds004483 with File-IO

### ISSUE THREAD

**Issue by asalazar4** [fieldtrip/fieldtrip#2373]
The NEMAR team is experiencing the following error when importing two MEG datasets (https://nemar.org/dataexplorer/detail?dataset_id=ds004276 , https://nemar.org/dataexplorer/detail?dataset_id=ds004483). Could we please have help resolving this?

```
--------
WARNING: This file contains raw Internal Active Shielding data. It may be distorted.
Elekta recommends it be run through MaxFilter to produce reliable results.
Consider closing the file and running MaxFilter on the data.
--------

	Range : 26000 ... 339999  =     26.000 ...   339.999 secs
Ready.
Error using ft_notification
Maxshield data should be corrected using Maxfilter prior to importing in FieldTrip.

Error in ft_error (line 39)
  ft_notification(varargin{:});

Error in ft_read_header (line 1973)
          ft_error('Maxshield data should be corrected using Maxfilter prior to importing in FieldTrip.');

Error in pop_fileio (line 146)
        dat = ft_read_header(filename);

Error in pop_importbids (line 515)
                            EEG = pop_fileio(eegFileRaw); % fif folder

Error in load_dataset (line 21)
        [STUDY, ALLEEG] = pop_importbids(filepath, 'bidsevent','on','bidschanloc', bidsChan,'studyName',dsname,'outputdir', outputDir, 'subjects', subjects, 'ctffunc', ctffunc);

Error in run_pipeline (line 101)
[STUDY, ALLEEG, dsname] = load_dataset(opt.bidspath, opt.outputdir, opt.modeval, opt.subjects, opt.ctffunc);

Error in pop_run_pipeline (line 82)
	eval(command)
 
Error while evaluating Menu Callback.

```

**Comment by schoffelen** [comment]
Also here, could you provide some more information with respect to the fieldtrip version you are using? We have been making some changes (intended improvements) to the fif-readers recently, and it might clash with the data you currently try to process (which means that we would need to further improve those improvements...

**Comment by robertoostenveld** [comment]
@schoffelen should we perhaps add an explicit "please look at the help of this function" or a "please use the checkmaxfilter option" to this line? https://github.com/fieldtrip/fieldtrip/blob/76830e3a00f5324e1cf5535b57c8c152c1e84905/fileio/ft_read_header.m#L2015

**Comment by schoffelen** [comment]
Yes, agreed, but I also want to look into this in  a bit more detail. I rewrote the logic about the check for internal shielding in the higher level code a bit (in the hope to make it more generic, rather than relying on the interpretation of a silent error of the lower-level code), so want to be sure that I did not introduce anything untowards.

**Comment by schoffelen** [comment]
OK, I checked and can confirm that the error is thrown as intended. I.e. the dataset has been obtained with active shielding switched on, which means that the error is genuine. This can be bypassed with the argument 'checkmaxfilter', to be set to 'yes'/true etc.. The only thing we can offer from the FieldTrip point of view, is indeed add a little bit of information to the error message, as per Robert's suggestion.

**Comment by arnodelorme** [comment]
OK, thanks guys for looking into that.
