### ISSUE TITLE
Fieldtrip-SimBio pipeline on macOS with Apple silicon - calc_stiff_matrix_val.mexmaca64 is missing

### ISSUE THREAD

**Issue by anikokusztor** [fieldtrip/fieldtrip#2378]
Hi, 

I have been testing the Fieldtrip-SimBio pipeline. At the ft_prepare_headmodel step, I have encountered the following error:

```
vol = ft_prepare_headmodel(cfg, mesh);
Error using calc_stiff_matrix_val
The mex file calc_stiff_matrix_val.mexmaca64 is missing

Error in sb_calc_stiff (line 84)
  [diinsy,cols,sysmat] = calc_stiff_matrix_val(node,elem,cond,mele);
```

Indeed there is no .mexmaca64 version for any of the mex files, only .mexmaci64 (for intel platforms).

**Environment and versions :**
Version: MATLAB '23.2.0.2485118 (R2023b) Update 6'
Operating System: macOS with Apple silicon Version: 14.2.1 Build: 23C71 
Java Version: Java 1.8.0_402-b08 with Amazon.com Inc. OpenJDK 64-Bit Server VM mixed mode
FieldTrip version is: 20240110
Compiler: MEX configured to use 'NAG Fortran' for FORTRAN language compilation.

I have tried to use previous Matlab versions but I have been running into issue in setting up mex compiler. Is there any chance for an Apple silicon compatible update in the near future? 

Thank you for your help in advance!
Aniko

**Comment by robertoostenveld** [comment]
Yes, there is such a chance, but it depends on people like you to compile the mex file for Apple Silicon and to contribute them back to the fieldtrip repository. We do not have arbitrary hardware ourselves and I cannot go out and buy a new macbook just to compile mex files (well... in theory I could, but the university is not going to reimburse it).

As long as there are no mexmaca64 mex files, a work-around might be to use the intel mex files with Rosetta. Again, since I don't have an M1/M2/M3 MacBook, I cannot try this out myself.

**Comment by anikokusztor** [comment]
I see. Although it was a long shot to me but I did give compiling simbio on my mac a go. I downloaded simbio from sourceforge (following [this](https://www.mrt.uni-jena.de/simbio/index.php?title=How_to) ) and followed the compilation steps [here](https://www.mrt.uni-jena.de/simbio/index.php?title=Compiling_SimBio) for macOS but i have run into several errors, a few of them I could resolve but now I'm facing a bigger issue: the makefiles set the fortran compiler to be g77 but that is not available on M1 and when I change it to gfortran, I get a bunch of errors in the fortran files... 

I don't think I have the required skills to resolve these unfortunately.

About the potential workaround: Mathworks page says the following: "MEX files built on macOS with Intel are not supported on the Apple silicon platform using Rosetta 2." I assume this means that I cannot use the intel mex files.

**Comment by robertoostenveld** [comment]
I think you should address the compilation challenges to the SIMBIO team, hope that the HomeBrew team can make a release of the g77 compiler, and that flang in https://llvm.org (which I understand to be behind all of this) will be ported to apple silicon.

I suspect that the Mathworks page you refer to is about the ARM version of MATLAB. The workaround with Rosetta would involve installing the Intel version of MATLAB and using that with the Intel mex files.

**Comment by anikokusztor** [comment]
I have tried three different MATLAB intel versions (2021b, 2022a, 2023a) and none of them works. I think the issue is that on the current macOS I cant setup the Fortran compiler on any of these matlab versions:
```
mex -setup -v FORTRAN
Verbose mode is on.
... Looking for compiler 'Intel oneAPI for Fortran' ...
... Looking for environment variable 'IFORT_COMPILER23' ...No.
... Looking for environment variable 'IFORT_COMPILER22' ...No.
... Looking for environment variable 'IFORT_COMPILER21' ...No.
... Looking for environment variable 'IFORT_COMPILER20' ...No.
... Executing command 'which ifort' ...No.
Did not find installed compiler 'Intel oneAPI for Fortran'.
Error using mex
Supported compiler not detected. For options, visit
https://www.mathworks.com/support/compilers.
```
Also i have found this [Deprecation notice](https://community.intel.com/t5/Blogs/Tech-Innovation/Tools/Deprecation-of-Intel-Fortran-Compiler-Classic-for-macOS/post/1472697) for ifort. So I can't find a solution on apple silicon at this point but I just want to leave this here in case other people run into the same issue.

**Comment by robertoostenveld** [comment]
thanks for reporting this back. I am sure that in the future we ourselves and others will again run into this, and hope that by that time we will be able to find a solution.

I propose to close this issue for now, ok?
