### ISSUE TITLE
FIF import issue

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2389]
This is using ds002885 https://nemar.org/dataexplorer/detail?dataset_id=ds002885

![Screenshot 2024-02-08 at 1 31 15 PM](https://github.com/fieldtrip/fieldtrip/assets/1872705/e83b96f3-5561-4f38-842f-6e0d9ccadb08)

**Comment by robertoostenveld** [comment]
Hi Arno,

What makes you think that this is an error in the code? Can you try reading in the file with mne-python to confirm that the file is correct or corrupt?

best
Robert

**Comment by schoffelen** [comment]
<img width="1030" alt="Screenshot 2024-02-12 at 10 59 24" src="https://github.com/fieldtrip/fieldtrip/assets/1517611/9632d7a0-625e-40b7-bc6b-6d25a9a6b574">
MNE-python also chokes on this file, I am afraid it's corrupted
