### ISSUE TITLE
Consider reducing the .git history size by removing large binary blobs

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#2396]
Currently a clone of the repo is getting quite sizeable (~1.8GB) where a lot of stuff is (of course) contained in the history in the .git folder. In the context of another repo I have found a way to remove large binary blobs from the git history. Is this something we could consider here as well? The attached 

[inspect_blobs.txt](https://github.com/fieldtrip/fieldtrip/files/14571377/inspect_blobs.txt)

lists the blobs, sorted on size. I used a recipe that is documented here: https://medium.com/@prankulgarg/want-to-remove-large-files-blobs-from-git-history-permanently-4723e72a84e1

**Comment by robertoostenveld** [comment]
I believe it is better to make a shallow clone of a repository, in which not all historical commits (and blobs) are not be present by default. See https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones

To me that seems like a better solution, as it does not require rewriting of history and would not break the forks that other people have of the repository (as the history of those would still be the original). 

Could you try this out?
