### ISSUE TITLE
The `ft_read_event` function doesn't work for '.nirs' files due to a repeat key-value pair in function code.

### ISSUE THREAD

**Issue by BAK262** [fieldtrip/fieldtrip#2398]
The `ft_read_event` function doesn't work for '.nirs' files due to an error in lines 1389 and 1394:
the key-value pair `'denoise', denoise` appears twice.

found in release version: fieldtrip-20240110

**Comment by robertoostenveld** [comment]
thanks for reporting, should be fixed now.
