### ISSUE TITLE
Source localization now require optimization toolbox

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2404]
The source localization code use to work even without the optimization toolbox. Now it generates an error if the toolbox is not present.

```matlab
load('-mat', 'tmp.mat');
ft_inverse_dipolefit(sourcemodel, sens, headmodel, dat, varargin{:})
```

![Screenshot 2024-04-08 at 3 20 02 PM](https://github.com/fieldtrip/fieldtrip/assets/1872705/0ae3ee9b-1f59-4647-a629-e234d458f733)
[tmp.mat.zip](https://github.com/fieldtrip/fieldtrip/files/14911399/tmp.mat.zip)

**Comment by arnodelorme** [comment]
Yes, I removed the optimization toolbox path

```
rmpath('/Applications/MATLAB_R2024a.app/toolbox/matlab/optimfun/');
```

Note that this was reported by a user to me that did not have the optimization toolbox and I tried to reproduce it on my machine. The code line 167 to 183 seems to require the optimset function that is only in the optimization toolbox.

**Comment by robertoostenveld** [comment]
`optimset` is not only in the optimization toolbox, it is also used for the `fminsearch` function that is part of the matlab (standard) toolbox

**Comment by robertoostenveld** [comment]
I believe that the optimization toolbox lives in `/Applications/MATLAB_R2023b.app/toolbox/optim`. But the organization of the directories is less clear than it was in the past.

**Comment by schoffelen** [comment]
there does not seem to be much progress here, closing for now
