### ISSUE TITLE
Beamforming oscillatory responses in combined MEG/EEG data

### ISSUE THREAD

**Issue by sinamakhdoomi** [fieldtrip/fieldtrip#2408]
cfg.location = [-19.5 -18.5 70.5];
ft_sourceplot(cfg, source_diff_int);

Running this code needs a big memory to process and at the end it could not plot completely a plot for me in MATLAB 2024. On the other hand, I would like to work on a project related to the source localization of our EEG dataset, while I find different method for MEG dataset. Based on the codes, the head model is changed for EEG dataset ,but which methods perform much more reliable and robust for EEG dataset of hand movement.

**Comment by schoffelen** [comment]
please ask your question on the fieldtrip discussion list.

I sent you the link to a page earlier, which explains step by step how to do this, and also provides useful information about how to interact with an online community

**Comment by schoffelen** [comment]
for reference: here's the e-mail conversation: 

On 17 Apr 2024, at 16:11, Schoffelen, J.M. (Jan Mathijs) <janmathijs.schoffelen@donders.ru.nl> wrote:

Hi Sina,

I did not ask you to use ‘a’ discussion list, but to ’the’ discussion list, i.e. https://www.fieldtriptoolbox.org/discussion_list/. I don’t have any incentive to do private tutoring. You need to ask your local supervisor and or research community for help. If that proves insufficient you can ask your question on the fieldtrip discussion list.

Good luck with your research,

Jan-Mathijs Schoffelen


On 17 Apr 2024, at 15:57, Sina Makhdoomi Kaviri <[sinam1@umbc.edu](mailto:sinam1@umbc.edu)> wrote:
Hi,

THanks for your reply. I tried a discussion list but all of the time it was really hard to understand and confused. I would like to work on a project related to localizing sources from the EEG dataset that we have. In this regard, I use beamforming, but I am confused about which of the code in source reconstruction is related to my work, please help me if it is possible.

Best regards,
Sina

On Tue, Apr 16, 2024 at 3:15 AM Schoffelen, J.M. (Jan Mathijs) <[janmathijs.schoffelen@donders.ru.nl](mailto:janmathijs.schoffelen@donders.ru.nl)> wrote:
Could you please ask this type of questions on the Fieldtrip discussion list. Although it sometimes feels different, I am not a personal helpdesk, and I don’t want to reply to questions on a one-to-one basis.

If you decide to do so, please give a little bit more context in asking the question. Writing ‘default variables’ and then providing some numbers is not really informative (in its context I would be able to make an educated guess, but the rest of the readership won’t be able to).

Good luck, 
Jan-Mathijs

**Comment by sinamakhdoomi** [comment]
Hi,

I am not sure where and how I can ask my questions and concerns. It is
really confusing me, and I am not sure what should I do for this process.

Best regards,
sina
