### ISSUE TITLE
EEG inverse mode;

### ISSUE THREAD

**Issue by sinamakhdoomi** [fieldtrip/fieldtrip#2410]
%% Minimum norm estimate

cfg                     = [];
cfg.method              = 'mne';                    % specify minimum norm estimate as method
cfg.latency             = [0.024 0.026];            % latency of interest
cfg.grid                = leadfield;            % the precomputed leadfield
cfg.headmodel           = headmodel;            % the head model
cfg.mne.prewhiten       = 'yes';                    % prewhiten data
cfg.mne.lambda          = 3;                        % regularisation parameter
cfg.mne.scalesourcecov  = 'yes';                    % scaling the source covariance matrix
minimum_norm_bem        = ft_sourceanalysis(cfg, EEG_avg);

Error using ft_checkdata (line 540)
This function requires 'comp', 'timelock' or 'freq' data as input, see ft_datatype_comp, ft_datatype_timelock or ft_datatype_freq.

Error in ft_sourceanalysis (line 175)
data = ft_checkdata(data, 'datatype', {'comp', 'timelock', 'freq'}, 'feedback', 'yes');

**Comment by robertoostenveld** [comment]
Dear @sinamakhdoomi,

Questions should go to the email discussion list. If that does not give you the answer that you want, that is too bad for you and I am sorry, but please don't try again elsewhere! 

FieldTrip is shared and maintained by volunteers, not _as_ their job, but _next to_ their job. The people at the Donders in Nijmegen (where the core team is working) cannot provide support on all questions. We share for free what we can (in the code, on the website, on the mailing list), but that might not be enough for everyone that is interested. If you need more support, you may want to look into BESA or BrainVision Analyzer, which are paid softwares that _do_ offer professional support.

You may also want to look in your local institutional environment for other people that you can team up with, from whom you can learn, and with whom you can collaborate directly.

best regards,
Robert

**Comment by sinamakhdoomi** [comment]
Hi professor Oostenveld,

Thanks for your reply and consideration. I apologize if I made a mistake
and ask questions through GitHub, while I could not find any exact
discussion mail directory to ask my questions. I want to use fieldtrip for
our lab and I will debug and modify the code individually. Thanks for your
help, I wish the best for your team.

Best regards,
Sina

**Comment by sinamakhdoomi** [comment]
Dear professor Oostenveld,

Thanks for your reply and consideration. I apologize if I made a mistake
and ask questions through GitHub, while I could not find any exact
discussion mail directory to ask my questions. I want to use fieldtrip for
our lab and I will debug and modify the code individually. Thanks for your
help, I wish the best for your team.

I appreciate your kind response and sorry again for my misunderstanding. I
have some problems with specific dataset, I asked again a question in
GitHub about the problem, but I think it is better to resolve it
individually regarding your busy schedule. Thanks again for your time.

Best regards,
Sina
