### ISSUE TITLE
 ft_rejectvisual failure

### ISSUE THREAD

**Issue by sinamakhdoomi** [fieldtrip/fieldtrip#2411]
**Describe the bug**
 ft_rejectvisual fails on remove channels.

**To Reproduce**
dataset = './dataset/S01_ME/motorexecution_subject1_run1.gdf';

%% preprocessing
cfg = [];
cfg.dataset              = dataset;
cfg.trialfun             = 'ft_trialfun_general';
cfg.trialdef.triallength = 1;                      % duration in seconds
cfg.trialdef.ntrials     = inf;                    % number of trials, inf results in as many as possible
cfg                      = ft_definetrial(cfg);

% read the data from disk and segment it into 1-second pieces
data_segmented           = ft_preprocessing(cfg);

cfg = [];
cfg.method = 'summary';
cfg.keepchannel = 'no';
cfg.preproc.reref = 'yes';
cfg.preproc.refchannel = 'eeg';
data_eeg_clean = ft_rejectvisual(cfg, data_segmented);

**Expected behavior**
No crash

Environment and versions:

 - MATLAB version 2024a

Additional context: 
I want to work with this dataset, which has NaN and different channels, but how can I do this by  ft_rejectvisual .

**Comment by schoffelen** [comment]
Can you please go to the following URL: https://mailman.science.ru.nl/mailman/listinfo/fieldtrip

Then, subscribe to the list, by following the instructions that are there

Then, send you e-mail with questions to fieldtrip@science.ru.nl

In asking your question, you should first carefullyl study this website, and the links therein: https://www.fieldtriptoolbox.org/faq/how_to_ask_good_questions_to_the_community/
