### ISSUE TITLE
error running ft_volumesegment on Mac M2

### ISSUE THREAD

**Issue by osamaNYUAD** [fieldtrip/fieldtrip#2417]
**Describe the bug**
mat2file.c not compiled - see Makefile

**To Reproduce**
https://www.fieldtriptoolbox.org/tutorial/beamformer/
follow tutorial and you will get an error 
cfg = [];
cfg.write      = 'no';
[segmentedmri] = ft_volumesegment(cfg, mri);

**Comment by schoffelen** [comment]
Some of this might already be fixed by upgrading the relevant code in external/spm12. The dev version on Github seems to support the apple silicon processors more gracefully

**Comment by osamaNYUAD** [comment]
Can you point me to the Dev location I should use to download the updated
function?

*Osama Abdullah, PhD*
MRI Physicist II
Core Technology Platforms
NYU Abu Dhabi
UAE O: +971 2 628-4990
UAE C: +971 56 6793378

NYU Abu Dhabi, Saadiyat Campus
Computational Research Building (A2), 015
P.O. Box 129188
Abu Dhabi, United Arab Emirates (GST Time Zone)

**Comment by schoffelen** [comment]
https://github.com/spm/spm 

I am not sure what is exactly needed, but if you clone the repo, and then ensure that this folder (+relevant subfolders) is on your path (rather than fieldtrip/external/spm12) then you might pull it off.

**Comment by robertoostenveld** [comment]
The https://github.com/spm/spm/tree/main/%40file_array/private folder does contain the mex files that we identified to be missing today. We should add them to the fieldtrip repository and release.

**Comment by robertoostenveld** [comment]
The should be 20 mex files for each platform, but for Apple M1/M2/M3 we only have 16. 

```
mac036-lan> find . -name \*.mexa64 | wc -l
      20
mac036-lan> find . -name \*.mexmaci64 | wc -l
      20
mac036-lan> find . -name \*.mexmaca64 | wc -l
      16
```
