### ISSUE TITLE
error while doing  ft_freqanalysis

### ISSUE THREAD

**Issue by mfibmm** [fieldtrip/fieldtrip#2429]
**Describe the bug**

i got this error

Index in position 2 is invalid. Array indices must be positive integers or logical values.

Error in ft_specest_hilbert (line 214)
    spectrum(:,ifreqoi,:) = dum(:,timeboi+prepad);

Error in ft_freqanalysis (line 697)
      [spectrum,foi,toi] = ft_specest_hilbert(dat, time, 'timeoi', cfg.toi, 'width', cfg.width, bpfiltoptions{:}, options{:}, 'feedback', fbopt, 'edgeartnan', cfg.edgeartnan);
 

while trying to process the folowing code 

 cfg = [];
cfg.method = 'hilbert';
cfg.output = 'fourier';
cfg.foi = 1:0.5:15;
cfg.channel = 'all';
cfg.bpfilttype = 'firws'; % Default filter type
cfg.bpfiltord = 4;        % Filter order, can be adjusted as needed
cfg.pad = 'nextpow2';     % Padding option to improve FFT efficiency
cfg.toi        = data_epoched.time{1};
% Perform frequency analysis with FieldTrip
freq = ft_freqanalysis(cfg, data_epoched);

 - Operating System: [Windows 11
 - MATLAB version R2023a
 - FieldTrip version [e.g., 20240504

**Comment by schoffelen** [comment]
please ask this type of questions on the fieldtrip discussion list, the github issue tracker is not meant for 'support' (and neither is the discussion list, but you may get lucky if you ask your question to the point, and show what you have already done to investigate the cause of the error). Please use the matlab debugger and inspect a bit more before re-posting your question on said discussion list.

**Comment by mfibmm** [comment]
Okay, could , please send me the fieldtrip discussion link ?
you just closed the case so no way to solve it

**Comment by mfibmm** [comment]
Your job is to solve the bugs in FileTrip, as far as i know, not assign me to somewhere else.
you should be more professional

**Comment by schoffelen** [comment]
https://letmegooglethat.com/?q=fieldtrip+e-mail+discussion+list
