### ISSUE TITLE
MEG channel names in FIF file not associated with channel locations

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2436]
This is related to bug https://github.com/fieldtrip/fieldtrip/issues/2395

However, this time, they are FIF data files instead of CFT.

Channel names are as follow and have no location associated with them

![Screenshot 2024-08-20 at 09 20 08](https://github.com/user-attachments/assets/d3bb1138-84ee-4cad-ab96-a28d5fb67c34)

This is the dataset https://nemar.org/dataexplorer/detail?dataset_id=ds003682

Let us know @robertoostenveld if anything can be done for this dataset. If not, we will make a note.

**Comment by schoffelen** [comment]
Hi @arnodelorme I think that it is pretty straightforward to also add the fix that @robertoostenveld implemented for the CTF data, at least I got this impression by checking the changes in the code associated with #2400 . Feel free to add the relevant lines of code also for the neuromag fif files as a PR.

**Comment by arnodelorme** [comment]
Thanks. I could find the change in https://github.com/fieldtrip/fieldtrip/commit/e6a0dcf668230dac651fe7c37e9e703e9ed21c34#diff-d7ce4476a33ff66e4a4583dfe7ca9956ab740809ff4b20035b7a9f79071fa9f7

However, the code is involved. It seems that he fieldline_v3 is first tested and splitlabel is processed in some other section. Ideally, the same code would be reused in ft_readheader for both CTF and FIF file. I would likely break something and implement an non optimal solution.

**Comment by robertoostenveld** [comment]
the splitting of labels on the '-' is done here https://github.com/fieldtrip/fieldtrip/blob/dff3747d267d3117f9c0ca7fee23eb367beb5a7a/fileio/ft_read_header.m#L2955

The default for the spltlabel option is set to `true` for CTF and FieldLine, but not for general fif files. 

Can you set the splitline option to true to try and try again?

**Comment by robertoostenveld** [comment]
Note that right now `ft_preprocessing` does not yet support setting the spltlabel option (and passing it down to `ft_read_header`), but that can be added.

**Comment by arnodelorme** [comment]
spltlabel is set by default for CTF data I think. Can the same be done for FIF data?

**Comment by arnodelorme** [comment]
I have added the following lines (see screen capture). It did not help. Could it be that FIF MEG channel location are not looked up based on channel labels?

![Screenshot 2024-08-27 at 18 26 04](https://github.com/user-attachments/assets/81f97300-ffdd-4fee-8c91-f3e657de7457)

**Comment by robertoostenveld** [comment]
There is no need to change the code:  the `splitlabel` option can be passed as key-value pair to the ft_read_header call. 

I now realize that your question has two aspects: one is about the labels, the other is about the positions. Can you first confirm that `ft_read_header(... 'splitlabel', true)` addresses the channel name question?

The `splitlabel` option (or the presence of the dash in the labels) has no interaction whatsoever with channel positions, that appears to be a different issue that you are encountering. Does the fif file contain sensor positions? You should follow the `mne2grad` function call at line 1351 in the code.

**Comment by arnodelorme** [comment]
It does not look like positions are loaded
It is the first file of subject 1 for https://nemar.org/dataexplorer/detail?dataset_id=ds003682

![Screenshot 2024-08-27 at 20 58 11](https://github.com/user-attachments/assets/c45cee9c-eaae-44ae-be78-e6546fb9f291)

**Comment by robertoostenveld** [comment]
From the [BIDS specification for raw MEG](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/magnetoencephalography.html): "Unprocessed MEG data MUST be stored in the native file format of the MEG instrument with which the data was collected". That does not apply here, so it is not a legal BIDS raw dataset.

In the `dataset_description.json` file I furthermore see "DatasetType": "derivative", so the dataset also does not claim to be raw, but it is derived/processed using custom Python scripts. I don't know what those scripts did, but apparently the derivative data is something for which FiieldTrip cannot determine the gradiometer positions without looking in the fif file and code in detail.

I would therefore consider the data to be limited readable in FieldTrip and don't see the need to spend further time on this.
