### ISSUE TITLE
CURRY File Format Reader doesn't work in all cases

### ISSUE THREAD

**Issue by CurryKaiser** [fieldtrip/fieldtrip#2446]
Dear FieldTrip Team,

it was nice talking to you at BIOMAG Sydney, Robert!

As promised I would provide what I can to improve the reader.

Attached you will find a .m file (hiding as a .txt) of our MATLAB reader. It is up to date and should cover all bases.
From there it shouldn't be to difficult to figure out where FieldTip's Curry reader diverges or transform the "curryStruct" according to FieldTrip conventions.

Best Regards,
Fabian Kaiser
Compumedics - Curry Dev Team

[LoadCurryDataFile.txt](https://github.com/user-attachments/files/17015953/LoadCurryDataFile.txt)

**Comment by CurryKaiser** [comment]
Additionally, I can supply some almost empty sample data:
[SampleFiles.zip](https://github.com/user-attachments/files/17116012/SampleFiles.zip)

**Comment by robertoostenveld** [comment]
Hi Fabian, thanks for following up. 

I investigated and checked the code, let me give a summary here

FieldTrip already has filetype detection in https://github.com/fieldtrip/fieldtrip/blob/4ba8f7d08f3436d71b3ffc6339ef325f08325b5f/fileio/ft_filetype.m#L968 

The ft_read_header, ft_read_data, ft_read_event and ft_read_sens functions all do "something" with Curry files that  is based on https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/load_curry_data_file.m. This is something that @vlitvak contributed some 6 years ago. 

Furthermore, we have https://github.com/fieldtrip/fieldtrip/blob/master/test/test_curry.m which is based on some test data that we have. The test script is executed every night and apparently runs through. 

I will try something similar to the exist tests on the new files.

**Comment by robertoostenveld** [comment]
it failed because the parameter and label file had the `.dpo` extension for one, instead of `.dpa`. I have added that to the existing code, and now it runs through. 

The code that you sent appears to be a cleaned up version of the code that is now included in FieldTrip. However, it is not drop-in compatible, hence I hesitate to start changing FieldTrip code to upgrade or "fix" something for which I don't have an indication that it is broken. 

Do you see reasons for replacing the existing `load_curry_data_file.m` with `LoadCurryDataFile.m`? 

Do you know if the problem that I now resolved also solves it for your Compumedics customers? I don't have their contact details (although I did take a photo of their BIOMAG badge, so could try to look them up), but probably you know who they are and you can follow up with them.

Please advise,
Robert

**Comment by CurryKaiser** [comment]
Hi Robert,
Thanks for all the hard work!
That might actually do the trick! Our expert for the MATLAB reader (Fernando) is currently out, and I don’t know the history of issues. But considering that one customer talked about not being able to load MEG, which I assume they acquired with Curry (and thus creating a parameter file during acquisition -  a .dpo file), and that all the sample data was loaded successfully on your end, it really sounds like it might just be that issue. If it is that, then I am sorry that I didn’t pick up on that earlier (I am still a bit green). So please hold out on investing any more time into this for the time being, I am gonna get in touch with Fernando (back in two weeks) and the customer.

Best,
Fabian

**Comment by CurryKaiser** [comment]
Hi Robert,

our expert is back and I also just noticed that your reader just seems to be an older version of our Matlab Reader with then at the end some code to fill the FieldTrip structure:
![image](https://github.com/user-attachments/assets/371fd4bf-054e-4e06-89ce-cae59ae57e7f)
(left yours, right ours)

I think its probably pretty easy to take that added code and put it in a wrapper, that way any time anyone complains, you can just replace your reader with our newest reader and the wrapper will convert the output structure.

Best,
Fabian

**Comment by schoffelen** [comment]
hi @CurryKaiser Fabian, I am joining the party a bit late, and have some difficulties in distilling whether something is now still needed from our end, or whether this issue can be considered sufficiently 'solved', and can be closed. If that's the case, please feel free to do so. If not, please give us some directions to what is still needed.

**Comment by CurryKaiser** [comment]
Yup, think its good for now, thank you all so much for your time! The last message was more for your information, if difficulties come up again, you can think about that proposal.
Until next time ;)
