### ISSUE TITLE
Write a custom skewness function

### ISSUE THREAD

**Issue by contsili** [fieldtrip/fieldtrip#2457]
**Is your feature request related to a problem? Please describe.**
A use during the workshop had a trial version MATLAB which does not include the toolbox with 'skewness' function

**Describe the solution you'd like**
Write a custom skewness function in the 'compat' folder

**Additional context**
'skewness' is used by ft_read_data

**Comment by schoffelen** [comment]
grepping the codebase for skewness seems to lead to at least 2 hits:

fileio/private/read_trigger.m
ft_heartrate.m

Initially, I thought to solve it in-place, but perhaps it's safer to overload

**Comment by robertoostenveld** [comment]
perhaps there is something from octave that we can borrow.

**Comment by schoffelen** [comment]
Leider nicht.
