### ISSUE TITLE
ft_badsegement does not use preproc correctly

### ISSUE THREAD

**Issue by chrisNatMEG** [fieldtrip/fieldtrip#2460]
**Describe the bug**
ft_badsegment applies preproc options when calculating std and mean for zvalue parameters but not when actually calculating the level (line 171). The level calculation uses the unprocessed data.

Issue can be fixed by replacing line 171 with:
dat = preproc(data.trial{trl}, data.label, data.time{trl}, cfg.preproc);
level = artifact_level(dat, cfg.metric, mval, sd, connectivity);

**Comment by schoffelen** [comment]
Hi Christoph @chrisNatMEG , thanks for catching this. It indeed does not seem to make sense NOT to apply the same preprocessing options at the (approximate) location that you mention. BTW, in the master branch of FT the call to ```artifact_level``` takes place in line 176 so it seems that you use a slightly outdated version of the code. Would you be fine with making a PR for this? this will give you the full digital credits in the git-history of the file

**Comment by robertoostenveld** [comment]
I just looked at this with Christoph, it also affects ft_badchannel and ft_baddata. The rejectvisual_summary function also does the z-scoring, but that is fine. @chrisNatMEG will make a PR.

**Comment by robertoostenveld** [comment]
FYI I shared the [git and GitHub tutorial slides](https://docs.google.com/presentation/d/1xaJdMa--5sovtNZI_BunG1ZbSM8qOwFJCExh8OK7mg0/edit?usp=sharing) from last week with Christoph, and also pointed him to the tutorial at https://www.fieldtriptoolbox.org/development/git/

**Comment by schoffelen** [comment]
https://xkcd.com/1597/
