### ISSUE TITLE
supportted MEG file format

### ISSUE THREAD

**Issue by SueJaH** [fieldtrip/fieldtrip#2469]
Hope you doing well! 

I have some confusions with the file format of MEG. I was wondering whether Fieldtrip support the curry float format (.cdt/ .dat) data collected by Neuroscan system. 

If not, is there any code can convert our data format (Figure 1) so that it can be read by Fieldtrip?
<img width="271" alt="figure 1" src="https://github.com/user-attachments/assets/c5c9f180-e45c-4224-951b-a8d740bfa2ce">

**Comment by schoffelen** [comment]
Please ask your questions on our fieldtrip discussion list. https://www.fieldtriptoolbox.org/discussion_list/
