### ISSUE TITLE
Implement SSVEP tutorial and simulation function

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#509]
As discussed with Stefan and Malina, we should extend and upgrade the seven example to a tutorial. As part of that, we should implement an ft_steadystatesimulation function.

**Comment by robertoostenveld** [comment]
how about this as a function interface for the end-user to simulate data?

```
% Use as
%   data = ft_steadystatesimulation(cfg)
% where cfg is a configuration structure that should contain
%   cfg.fsample   = scalar, sampling frequency in Hz (default = 512)
%   cfg.duration  = scalar, trial length in seconds (default = 4.56)
%   cfg.baseline  = scalar, baseline length in seconds (default = 0)
%   cfg.ntrials   = integer N, number of trials (default = 320)
%
% Furthermore, the behaviour of the stimuli  is specified with
%   cfg.stimulus1.mode = 'periodic' or 'transient' (default = 'periodic')
%   cfg.stimulus2.mode = 'periodic' or 'transient' (default = 'transient')
% 
% If the stimulus is periodic, the following options apply
%   cfg.stimulus1.onset       = in seconds, first stimulus relative to the start of the trial (default = 0)
%   cfg.stimulus1.onsetjitter = in seconds, max jitter relative to the start of the trial (default = 0)
%   cfg.stimulus1.isi         = in seconds i.e. for 10Hz you would specify 0.1 seconds (default = 0.1176)
%   cfg.stimulus1.isijitter   = in seconds, max jitter relative to the previous stimulus (default = 0)
%   cfg.condition             = 1*Ntrial vector with stimulus codes for each trial  (default = repmat([1 2 3 4], 1, 80))
%   cfg.gain                  = 1*Ntrial vector with gain for each for each trial (default = repmat([1 2 3 4], 1, 80))
%
% If the stimulus is transient, the following options apply
%    cfg.stimulus2.number      = scalar M, how many stimili are to be presented per trial
%    cfg.stimulus2.onset       = in seconds, first stimulus relative to the start of the trial (default = 1.0)
%    cfg.stimulus2.onsetjitter = in seconds, max jitter relative to the start of the trial (default = 0.2)
%    cfg.stimulus1.isi         = in seconds (default = 0.9)
%    cfg.stimulus2.isijitter   = in seconds, max jitter relative to the previous stimulus ((default = 0.2)
%    cfg.condition             = 1xM vector with stimulus codes (default = [1 1 2 2])
%    cfg.gain                  = 1xM vector with gain for each condition  (default = [1 1 1 1])
%
% Note that the onsetjitter is randomized between 0 and the value given, and is
% always added to the onset. The this also applies to the isijitter and the isi.
%
% Using the default settings, we model a peripherally presented flickering stimulus
% (which appears at different excentricities) together with a centrally presented
% transient stimulus (which appears 4x per trial).
```

This also allows to stimulate two simultaneous steady state stimuli.

**Comment by robertoostenveld** [comment]
note that I have avoided to configure the blocks. I hope that it is possible to configure it in a full event related design (subject instructions and responses per block are not relevant anyway). If blocks are needed, I would rather do 4x ft_steadystatesimulation followed by ft_appenddata.

**Comment by StefanWiens** [comment]
Looking nice, but I have some comments.
a) I thought the purpose of having blocks in the config is to get the relevant info for the trialinfo. How would you resolve this in the ft_appenddata?
b) Great idea to have two stimuli that can be defined independently as periodic or transient. Do I understand correctly that the cfg.stimulus1.mode determines periodic or transient?
c) If b) is correct, then I wonder why you need to have the separate options because they are almost identical except for .number. However, I wonder if this is necessary because it may be that somebody enters settings that cannot be resolved (eg 4 sec trial length with 8 stimuli and 1 sec isi). Wouldn't it be simpler to have the same options for all stimuli and then give an example on how to set it up to to simulate data for the tutorial?
d) " cfg.stimulus1.onsetjitter = in seconds, max jitter relative to the start of the trial (default = 0)" I think it is clearer to refer to start of the onset. They are numerically identical, but personally, it makes more sense because you talk first about .onset and then you state if you want it jittered. With this, the note at the end seems unnecessary (which has some typos).

**Comment by robertoostenveld** [comment]
Note that there were some small typo's in my example

a) the block condition is not used… oh, I realize it is. It corresponds to the mental load.

So there are three gain levels:
- One overall gain that is constant over many trials
- One gain for the flicker that varies per trial
- One gain per transient stimulus.

How about
```
%  cfg.condition           = scalar, applies to all trials
%  cfg.gain                = scalar, applies to all trials
%  cfg.stimulus1.condition = 1*Ntrial vector with stimulus codes for each trial
%  cfg.stimulus1.gain      = 1*Ntrial vector with gain for each for each trial
%  cfg.stimulus2.condition = 1xM vector with stimulus codes (default = [1 1 2 2])
%  cfg.stimulus2.gain      = 1xM vector with gain for each condition  (default = [1 1 1 1])
```

and add cfg.condition to a trialinfo column, and still use ft_appenddata (which will also append the trialinfo).

b) yes. The concept can be extended to stimulus3, stimulus4, etc. Each of them is periodic/transient/off. 

c) It is for scalability. Imagine a SSAEP experiment with two different modulation frequencies for each ear. Or imagine presenting 4 flickering visual stimuli at the same time. 

If people enter settings that don't fit, the code should error.

d) you are right. I only added the baseline as an afterthought and did not reconsider the existing options.

**Comment by StefanWiens** [comment]
I think I get this except for c)
What I meant was to list the options only once instead of listing the same options twice, first for periodic and then transient. It may also be easier to get that this pattern can be extended to many stimuli. (The number option may be nice because it forces the user to think this through.)

%    cfg.stimulus1.number      = scalar M, how many stimuli are to be presented per trial
%    cfg.stimulus1.onset       = in seconds, first stimulus relative to the start of the first stimulus (default = 1.0)
%    cfg.stimulus1.onsetjitter = in seconds, max jitter relative to the start of the trial (default = 0.2)
%    cfg.stimulus1.isi         = in seconds (default = 0.9)
%    cfg.stimulus1.isijitter   = in seconds, max jitter relative to the previous stimulus ((default = 0.2)
%    cfg.condition             = 1xM vector with stimulus codes (default = [1 1 2 2])
%    cfg.gain                  = 1xM vector with gain for each condition  (default = [1 1 1 1])

**Comment by StefanWiens** [comment]
Regarding your suggestion (below), I am confused about how gains vary--over trials or within trials? For example, stimulus2 below changes within trials whereas stimulus1 changes between trials? 


Suggestion: If you have gains for only within trials, then the info that is identical for many trials can be included in cfg.condition and cfg.gain (and fed to trialinfo).

%  cfg.stimulus1.condition = 1*Ntrial vector with stimulus codes for each trial
%  cfg.stimulus1.gain      = 1*Ntrial vector with gain for each for each trial
%  cfg.stimulus2.condition = 1xM vector with stimulus codes (default = [1 1 2 2])
%  cfg.stimulus2.gain      = 1xM vector with gain for each condition  (default = [1 1 1 1])

**Comment by robertoostenveld** [comment]
Re "What I meant was to list the options only once instead of listing the same options twice, first for periodic and then transient..."

The options are present for each stimulus. The stimulus is either transient or periodic. For transient some options apply, for periodic (partially) other options apply. Perhaps more clearly like this

```
cfg.stimulusK is a sub-structure for each simultaneously presented stimulus stream, where K=1, 2, etc
cfg.stimulusK.mode = transient or periodic
if the mode is transient, the following options apply
cfg.stimulusK.option = value
...
if the mode is periodic, the following options apply
cfg.stimulusK.anotheroption = value
...
```

Re "For example, stimulus2 below changes within trials whereas stimulus1 changes between trials?"

stimulus 1 in in the example is the flickering ring. It has a different eccentricity on each trial, but remains stationary within a trial.  

stimulus 2 in in the example is the bar.  It has a different orientation (or target/non-target value) on each presentation within the trial

**Comment by StefanWiens** [comment]
Re: Options
Indeed, it seems clearer to use the same options (if they apply to both types of stimuli) and then have specific options that apply only to transient or periodic.
------------------------------------------------------

Re "For example, stimulus2 ..."
My difficulty is that it is confusing to know when the condition applies to between trials and when it applies to within trials.

**Comment by robertoostenveld** [comment]
There are multiple factors (i.e. conditions). One at the block level, one at the trial level, and one at the transient-stimulus level. Each can have multiple levels (values for the gain).

**Comment by StefanWiens** [comment]
That sounds nice. Can you list the revised version?

**Comment by robertoostenveld** [comment]
```
% FT_STEADYSTATESIMULATION creates a simulated EEG dataset for a single subject. This
% function allows to simulate the effect of two simultaneously presented stimuli.
% Both can be presented as a periodic sequence, or as a single (or few) transient
% stimuli. This function creates a single block of data. You can call it repeatedly
% and use FT_APPENDDATA to combine the blocks.
%
% Use as
%   data = ft_steadystatesimulation(cfg)
% where cfg is a configuration structure that should contain
%   cfg.fsample   = scalar, sampling frequency in Hz (default = 512)
%   cfg.duration  = scalar, trial length in seconds (default = 4.56)
%   cfg.baseline  = scalar, baseline length in seconds (default = 0)
%   cfg.ntrials   = integer N, number of trials (default = 320)
%   cfg.condition = scalar, applies to all trials in this block (default = 1)
%   cfg.gain      = scalar, applies to all trials in this block (default = 1)
%
% There can be one or multiple stimuli. The behaviour of each stimuli is specified with
%   cfg.stimulus1.mode = 'periodic', 'transient' or 'off' (default = 'periodic')
%   cfg.stimulus2.mode = 'periodic', 'transient' or 'off' (default = 'transient')
%   cfg.stimulus3.mode = 'periodic', 'transient' or 'off' (default = 'off')
%   cfg.stimulus4.mode = 'periodic', 'transient' or 'off' (default = 'off')
%
% If the stimulus is periodic (below for example for stimulus1), the following options apply
%   cfg.stimulus1.onset          = in seconds, first stimulus relative to the start of the trial (default = 0)
%   cfg.stimulus1.onsetjitter    = in seconds, max jitter relative to the start of the trial (default = 0)
%   cfg.stimulus1.isi            = in seconds i.e. for 10Hz you would specify 0.1 seconds (default = 0.1176)
%   cfg.stimulus1.isijitter      = in seconds, max jitter relative to the previous stimulus (default = 0)
%   cfg.stimulus1.condition      = 1*Ntrial vector with condition codes for each trial (default = repmat([1 2 3 4], 1, 20))
%   cfg.stimulus1.gain           = 1*Ntrial vector with gain for each for each trial (default = repmat([1 2 3 4], 1, 20))
%   cfg.stimulus1.kernelshape    = 'sine'    
%   cfg.stimulus1.kernelduration = in seconds (default = isi)
%
% If the stimulus is transient (below for example for stimulus2), the following options apply
%   cfg.stimulus2.number         = scalar M, how many stimili are to be presented per trial (default = 4)
%   cfg.stimulus2.onset          = in seconds, first stimulus relative to the start of the trial (default = 1.0)
%   cfg.stimulus2.onsetjitter    = in seconds, max jitter relative to the start of the trial (default = 0.2)
%   cfg.stimulus1.isi            = in seconds (default = 0.9)
%   cfg.stimulus2.isijitter      = in seconds, max jitter relative to the previous stimulus ((default = 0.2)
%   cfg.stimulus2.condition      = 1xM vector with condition codes for each transient (default = [1 1 2 2])
%   cfg.stimulus2.gain           = 1xM vector with gain for each condition for each transient (default = [1 1 1 1])
%   cfg.stimulus2.kernelshape    = 'hanning'    
%   cfg.stimulus2.kernelduration = in seconds (default = 0.75*isi)
%
% RANDOMIZATIONS: 
%  - The onsetjitter is randomized between 0 and the value given, and is always added to the onset. 
%  - The isijitter is randomized between 0 and the value given, and is always added to the isi. 
%  - For periodic stimuli, which are constant within a trial, the condition code and gain are shuffled over all trials.
%  - For transient stimuli, the condition code and gain are shuffled within each trial.
%
% Using the default settings, we model a peripherally presented flickering stimulus
% that appears at different excentricities together with a centrally presented
% transient stimulus that appears 4x per trial. To simulate the experiment described
% at <website>, you have to call this 4 times with a different cfg.configuration and
% cfg.gain to model the task load and use FT_APPENDDATA to concatenate the trials. In
% this case cfg.condition models the factor "task load" (2 levels, low and high),
% cfg.stimulus1.condition models the factor "excentricity" (4 levels), and
% cfg.stimulation2.condition models the factor "stimulus type" (2 levels, non-target
% or target).
%
% See also FT_DIPOLESIMULATION, FT_TIMELOCKSIMULATION, T_FREQSIMULATION,
% FT_CONNECTIVITYSIMULATION, FT_APPENDDATA
```

**Comment by StefanWiens** [comment]
Very nice!  A few humble edits below... in bold

% FT_STEADYSTATESIMULATION creates a simulated EEG dataset for a single subject. This
% function allows to simulate the effect of **several independent stimulus trains**.
% These can be presented as a periodic sequence, or as single (or few) transient
% stimuli. This function creates a single block of data. You can call it repeatedly
% and use FT_APPENDDATA to combine **different** blocks.
%
% Use as
%   data = ft_steadystatesimulation(cfg)
% where cfg is a configuration structure that should contain
%   cfg.fsample   = scalar, sampling frequency in Hz (default = 512)
%   cfg.duration  = scalar, trial length in seconds (default = 4.56)
%   cfg.baseline  = scalar, baseline length in seconds (default = 0)
%   cfg.ntrials   = integer N, number of trials (default = 320)
%   cfg.condition = scalar, applies to all trials in this block (default = 1)
%   cfg.gain      = scalar, applies to all trials in this block (default = 1)
%
% There can be one or multiple stimuli. The behaviour of each stimuli is specified with
%   cfg.stimulus1.mode = 'periodic', 'transient' or 'off' (default = 'periodic')
%   cfg.stimulus2.mode = 'periodic', 'transient' or 'off' (default = 'transient')
%   cfg.stimulus3.mode = 'periodic', 'transient' or 'off' (default = 'off')
%   cfg.stimulus4.mode = 'periodic', 'transient' or 'off' (default = 'off')
%
% If the stimulus is periodic (below for example for stimulus1), the following options apply
%   cfg.stimulus1.onset          = in seconds, first stimulus relative to the start of the trial (default = 0)
%   cfg.stimulus1.onsetjitter    = in seconds, max jitter **that is added to the onset** (default = 0)
%   cfg.stimulus1.isi            = in seconds, i.e. for 10Hz you would specify 0.1 seconds **as the interstimulus interval** (default = 0.1176)
%   cfg.stimulus1.isijitter      = in seconds, max jitter relative to the previous stimulus (default = 0)
%   cfg.stimulus1.condition      = 1*Ntrial vector **with one condition code for each of the n trials** (default = repmat([1 2 3 4], 1, 20); **this gives one condition code that is used for each of 80 trials**)
**Robert: If there are 320 trials in ntrial, shouldn't the default capture this?**
%   cfg.stimulus1.gain           = 1*Ntrial vector **with one gain for each of the n trials** (default = repmat([1 2 3 4], 1, 20))
**Robert: If there are 320 trials in ntrial, shouldn't the default capture this?**
%   cfg.stimulus1.kernelshape    = 'sine'    
%   cfg.stimulus1.kernelduration = in seconds (default = isi)
%
% If the stimulus is transient (below for example for stimulus2), the following options apply
%   cfg.stimulus2.number         = scalar M, how many stimili are to be presented per trial (default = 4)
%   cfg.stimulus2.onset          = in seconds, first stimulus relative to the start of the trial (default = 1.0)
%   cfg.stimulus2.onsetjitter    = in seconds, max jitter **that is added to the onset** (default = 0.2)
%   cfg.stimulus1.isi            = in seconds **as the interstimulus interval** (default = 0.9)
%   cfg.stimulus2.isijitter      = in seconds, max jitter relative to the previous stimulus ((default = 0.2)
%   cfg.stimulus2.condition      = 1xM vector with condition codes for each transient **within a trial** (default = [1 1 2 2])
%   cfg.stimulus2.gain           = 1xM vector with gain for each condition for each transient **within a trial**(default = [1 1 1 1])
%   cfg.stimulus2.kernelshape    = 'hanning'    
%   cfg.stimulus2.kernelduration = in seconds (default = 0.75*isi)
%
% RANDOMIZATIONS: 
%  - The onsetjitter is randomized between 0 and the value given, and is always added to the onset. 
%  - The isijitter is randomized between 0 and the value given, and is always added to the **interstimulus interval** (isi). 
%  - For periodic stimuli, which are constant within a trial, the condition code and gain are shuffled over all trials.
%  - For transient stimuli, the condition code and gain are shuffled within each trial.
%
% Using the default settings, we model a peripherally presented flickering stimulus
% that appears at different excentricities together with a centrally presented
% transient stimulus that appears 4x per trial. To simulate the experiment described
% at <website>, you have to call this 4 times with a different cfg.configuration and
% cfg.gain to model the task load and use FT_APPENDDATA to concatenate the trials. In
% this case cfg.condition models the factor "task load" (2 levels, low and high),
% cfg.stimulus1.condition models the factor "excentricity" (4 levels), and
% cfg.stimulation2.condition models the factor "stimulus type" (2 levels, non-target
% or target).
%
% See also FT_DIPOLESIMULATION, FT_TIMELOCKSIMULATION, T_FREQSIMULATION,
% FT_CONNECTIVITYSIMULATION, FT_APPENDDATA

**Comment by StefanWiens** [comment]
Hi Robert!

Malina and I have finished a first draft of the tutorial_ssvep. You can find it in Dx.

Have a good weekend!
Stefan

**Comment by robertoostenveld** [comment]
I made the simulation function as discussed. I added another layer on top of it: it allows for three levels of conditions. This can be used e.g. to model task requirements or so.

The gains etc need to be further tested. Also the compatibility of the MATLAB table with other FT functions (esp ft_redefinetrial) needs testing.

I will make a test script on basis of the tutorial script. It should work both for real data, old simulated and newly simulated data.

**Comment by StefanWiens** [comment]
Nice! Do you want us to check them? I cannot find the script in Dx.

**Comment by robertoostenveld** [comment]
the new function is still in a branch of the repository (see further up, there is a link to a "commit"). I will add it to the release after some more testing. Right now I am in Stockholm, tomorrow meeting with colleagues who do SSAEPs to discuss it. This evening I will review the tutorial in the Dropbox and see whether the new function works there. If it does, I will also upload the new tutorial to the wiki.

**Comment by robertoostenveld** [comment]
here is the link to the commit https://github.com/robertoostenveld/fieldtrip/commit/888bca0e12ae600210c7719be4ddface0d4dd82f

**Comment by robertoostenveld** [comment]
this is part of the release already for some time, so this issue can be close
