### ISSUE TITLE
ft_trackusage.m bug in -nojvm mode

### ISSUE THREAD

**Issue by nbara** [fieldtrip/fieldtrip#539]
Hi Robert,

I get an error running Fieldtrip code when in `matlab -nojvm` mode. The same code worked well with previous fieldtrip versions.

```console
  File /Users/nicolas/Toolboxes/fieldtrip/utilities/ft_trackusage.m, line 142, in ft_trackusage
  File /Users/nicolas/Toolboxes/fieldtrip/ft_defaults.m, line 279, in ft_defaults
Undefined variable "java" or class "java.net.InetAddress.getLocalHost".
```

Disabling tracking with `ft_default.trackusage = 'no'` solves the issue, but I guess this is something that could be done automatically.

EDIT: actually `ft_default.trackusage = 'no'` doesn't solve the issue, but commenting out `ft_trackusage('startup');` in ft_defaults.m does.

**Comment by robertoostenveld** [comment]
Hmm, I have been making changes to this recently. Thanks for reporting. I can reproduce the problem:

```
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:
MATLAB:undefinedVarOrClass
Undefined variable "java" or class "java.net.InetAddress.getLocalHost". 
```

In implementing this, I did not consider nojvm. I will fix it asap.

**Comment by robertoostenveld** [comment]
this should fix it for now. The consequence is that in case of nojvm the tracker fails silently. 

I wonder how you got past the section 
```
  %% only enable the tracking for people at the DCCN
  knownuser = false;
  knownuser = knownuser || ~isempty(isempty(regexp(lower(gethostname), '^mac011', 'once')));
  knownuser = knownuser || ~isempty(isempty(regexp(lower(gethostname), '^mbp', 'once')));
  knownuser = knownuser || ~isempty(isempty(regexp(lower(gethostname), '^dccn', 'once')));
  knownuser = knownuser || ~isempty(isempty(regexp(lower(gethostname), '^fcdc', 'once')));
```

**Comment by robertoostenveld** [comment]
hmm, I see that you are not the only one that got past the section on "knownuser".

ah, the  ~isempty(isempty(..)) does not make sense. It should be like this
```
knownuser = knownuser ||  ~isempty(regexp(lower(gethostname), '^mac011', 'once'));
```
