### ISSUE TITLE
ft_version fails and goes into infinite loop

### ISSUE THREAD

**Issue by rdgao** [fieldtrip/fieldtrip#545]
this is a pretty specific problem but figured it might be helpful to share:

I clone FT from github some time ago, and I recently updated osx and it somehow erased command line tools, including git. As such, when ft_defaults is executed, ft_version is called, which triggers a warning at line 105 here (in ft_version):

![image](https://user-images.githubusercontent.com/7810219/31312345-575b395a-ab75-11e7-9f68-177e23fc19a8.png)

ft_warning, in turn, triggers the start of another loop which calls ft_version, and so on and so forth, creating an infinite loop with no user feedback. 

This is a rare and specific edge case where git should be there but is not, and is easy to fix as the user (once the problem is tracked down). But perhaps ft_warning should not be able to trigger an infinite loop?

**Comment by StolkArjen** [comment]
Hi Richard,

This may be due git's dependency on xcode on mac, see http://tips.tutorialhorizon.com/2015/10/01/xcrun-error-invalid-active-developer-path-library-developer-commandline-tools-missing-xcrun/

As a result, this query (in matlab) should produce an error
system(sprintf('git --version'))

What worked for me, is to execute the following in the terminal
xcode-select --install

Which should then produce something like this in matlab
system(sprintf('git --version'))
git version 2.8.4 (Apple Git-73)
ans =
     0

Hope this solves it for you

**Comment by rdgao** [comment]
Thanks for the reply, Arjen!

I was indeed able to solve the problem simply by reinstalling xcode, which produced the correct output as you suggested. I raised the issue, though, because I thought ft_warning and/or ft_defaults was doing something unexpected, as it fails silently and goes into an infinite loop. 

I don't know if it's worth the trouble to fix this problem that will probably occur very rarely - just wanted to bring it to your attention!

**Comment by robertoostenveld** [comment]
I have fixed it
