### ISSUE TITLE
ft_read_cifti fails in MATLAB R2017b & R2015b

### ISSUE THREAD

**Issue by ht93** [fieldtrip/fieldtrip#552]
Hi,

I found the `ft_read_cifti ` would fail in both matlab R2017b and R2015b. 
I have tried your newest release (by copy the newest `ft_read_cifti ` and all its dependency to my project folder), it also has the same problem.
Here is the error message:
```matlab
Cell contents indices must be greater than 0

Error in xml_parser>tag_element (line 227)
       xtree{Xparse_count} = element;

Error in xml_parser>compile (line 199)
                           frag = tag_element(frag);

Error in xml_parser (line 134)
tree = compile(tree);

Error in xmltree (line 41)
               tree.tree = xml_parser(varargin{1});

Error in ft_read_cifti (line 149)
tree = xmltree(xmldata);

Error in extract_signal (line 26)
x = ft_read_cifti('example.dlabel.nii', 'mapname', 'array');
``` 
Can anyone help?
Thank you very much!

**Comment by ht93** [comment]
I found why it happens...
Thanks.

**Comment by robertoostenveld** [comment]
it would be nice if you could describe here the reason for it failing and (presumably) your solution, as other people might come across the same issue and find this page.

**Comment by ht93** [comment]
@robertoostenveld 
The reason is the version of the xmltree is version 1.3.
It because we also use an old version of spm12 at the same time, spm12 overwrites the path of xmltree in MATLAB.
To avoid this you can either update spm12 to newer version or make sure your path of xmltree is linked to the one in fieldtrip.
