### ISSUE TITLE
Function call chokes if cfg.tpm is given as cell array of strings

### ISSUE THREAD

**Issue by jens-k** [fieldtrip/fieldtrip#599]
https://github.com/fieldtrip/fieldtrip/blob/22faafc5ac01225e62eb5b1bc6f4f8df9052aaac/ft_volumesegment.m#L437

This line expects a tpm structure in cfg.tpm and can't handle a cell array of strings. Therefore, one can only provide 4D NiFTIs and not single tpms. The latter results in:

```
Struct contents reference from a non-struct array object.

Error in spm_check_orientations (line 24)
dims = cat(1,V.dim);

Error in spm_load_priors8 (line 22)
spm_check_orientations(V);

Error in ft_volumesegment (line 437)
        opts.tpm      = ft_getopt(opts, 'tpm', spm_load_priors8(cfg.tpm));
```

...when calling it with cfg.spmversion = 'spm12'; cfg.spmmethod = 'new'. For the old segmentation it's done in line 389: cfg.tpm = ft_getopt(cfg, 'tpm'), without a call to spm_load_priors8, so there it works.

**Comment by schoffelen** [comment]
Hmm, probably I didn't consider the possibility to give in more than a single tpm.

Just for my information: a single string (as filename should work, true?). I believe that this was the intended behavrior. It would make sense to make this more robust, e.g. by either allowing your use (provided that the 'new' spm12 methods knows how to handle this, or does it explicitly require a 6-tissue tpm?), or by throwing an informative error.

**Comment by jens-k** [comment]
Yes, handing over one single tpm as filename works.

I guess so at least, because those particular tpms (macaque brain) produce an error later on (although they work with the old segmentation). 

```
Warning: Matrix is singular, close to singular or badly scaled. Results may be inaccurate. RCOND = NaN. 

Error using sqrtm (line 35)
Expected input to be finite.

Error in spm_maff8>M2P (line 293)
V  = sqrtm(J*J');

Error in spm_maff8>affreg (line 120)
    sol  = M2P(M);

Error in spm_maff8 (line 26)
[M,ll,h]      = affreg(buf, MG, x, ff, varargin{4:end});

Error in ft_volumesegment (line 446)
        Affine = spm_maff8(opts.image(1),3, 1,opts.tpm,Affine,'mni');
```

For the original problem, if this functionality is per se not supported, one could just tell people to stack their tpms in SPM (Util -> 3D to 4D file conversion).

**Comment by schoffelen** [comment]
Well, I haven't considered the possibility that people could use the function also for non-humans.
I can imagine that for macaques, mni is not really defined, is it?

But I guess that this relates to another issue than the one originally raised.

**Comment by jens-k** [comment]
Yes sorry, it's a bit off-topic, just thought it's an interesting hiccup and presents another difference when using old vs. new segmentation.

Concerning the original problem, as I said I don't think it's a deal breaker. I could add a comment on it in the documentary?

**Comment by schoffelen** [comment]
Hi Jens, I have updated my copy of ft_volumesegment, which I think is robust for a cell-array of strings for cfg.tpm. Would you be able to test it? Do you have a forked fieldtrip repo to which I can issue a PR? Or should I just merge it into Fieldtrip main, and hope that all is well?

**Comment by schoffelen** [comment]
Otherwise, the branch is on schoffelen/fieldtrip.git/ and is called tpmstuff

**Comment by jens-k** [comment]
Your version seems to work for me! 

(at least up to the point where the new segmentation crashes also with a 4D tpm).

**Comment by schoffelen** [comment]
But the later crash has to do with the macaque brain, true?

**Comment by jens-k** [comment]
Yes, seems to work. I tried it with the single tissue tpms from spm (grey, white, csf in /toolbox/OldSeg).

By the way, the problem is not the macaque brain but the macaque tpm. But I'm working on it.

**Comment by robertoostenveld** [comment]
is there already a resolution for this issue?

**Comment by schoffelen** [comment]
I believe that the original issue has been resolved
