### ISSUE TITLE
Field .sample is represented in seconds

### ISSUE THREAD

**Issue by jens-k** [fieldtrip/fieldtrip#607]
This concerns Blackrock data.

https://github.com/fieldtrip/fieldtrip/blob/4fbb2b6813690f82c603b8e1b86d63af81ddfc41/fileio/ft_read_event.m#L2088

Not sure if this is intended behavior. This way event.sample is given in seconds:
https://github.com/fieldtrip/fieldtrip/blob/4fbb2b6813690f82c603b8e1b86d63af81ddfc41/fileio/ft_read_event.m#L2098

**Comment by jens-k** [comment]
Mmh, the problem is that the data in the corresponding .ns* file can be sampled at different frequencies, e.g. when concurrently collecting lfp and spike data. The triggers in the .nev file, however, seem to be sampled at 30k. But I'm recording with 'Trellis Neuro' and this might differ between programs or settings?

Maybe the field shouldn't be called .sample then?

**Comment by schoffelen** [comment]
Hi Jens,
There's a 'blackrock' bug in bugzilla, which already identified the different sampling rates. I have CC'ed you to it. Currently, activity on that thread is pretty low indeed, but if we gain sufficient critical mass it may move forward again.

**Comment by jens-k** [comment]
Oh, sorry, I should have checked. I'll try to get my hands on some blackrock hardware soon and will try to work on it then.
