### ISSUE TITLE
Use of isfolder before /compat/R2017b is added to path

### ISSUE THREAD

**Issue by jens-k** [fieldtrip/fieldtrip#621]
https://github.com/fieldtrip/fieldtrip/blob/b34ba569068f1275e649391b6773f8cfedb7cbc3/utilities/ft_hastoolbox.m#L445

At the time when the /compat/* folders are added in ft_default lines 179-207, ft_hastoolbox may be called before /compat/R2017b/ had a chance to be added, such that isfolder is not yet known.

This happens for 2015b on Windows in ft_defaults line 196.
This happens for 2016b on Linux in ft_defaults line 198.

This leads to a silent error in ft_defaults (because it occurs in a try block) and isfolder remains unknown (leading to an error e.g. if you use ft_read_header).

**Comment by schoffelen** [comment]
Hehehe, and even it seems that if isfolder were on the path, it wouldn't work (since the input variable name on the first line is different from the variable name used in the function).

**Comment by robertoostenveld** [comment]
I have fixed this a few days ago: ft_defaults is now using isdir again and not isfolder.
