### ISSUE TITLE
implement low-level functions for connectivity

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#640]
following discussion with @schoffelen, I propose that we improve the code for some methods which are currently not easily available. 

MIM is available in [megconnectome](https://github.com/Washington-University/megconnectome/blob/master/analysis_functions/hcp_connectivity_mim.m) but not in FT. The style of the function is already very similar to ft_connectivity_xxx functions

PCC (partial and/or canonical correlation/coherence) is available in ft_sourcedescriptives for source level CSDs, but not for channels.

**Comment by robertoostenveld** [comment]
going over all functions in fieldtrip/connectivity, I realize that they are not so clean and consistent in their interface (some take a freq structure, some a CSD matrix). For now I think it has already improved a bit, so I'll close the issue.

**Comment by schoffelen** [comment]
indeed, I guess the odd one out is ft_connectivity_csd2transfer

ft_connectivity_laggedcoherence has never been really developed into a working version, and is not called from anywhere as far as I know
