### ISSUE TITLE
Wrong leadfields with OpenMEEG 2.4 

### ISSUE THREAD

**Issue by DanielMiklody** [fieldtrip/fieldtrip#674]
I ran into an issue recently when I set up a new computer to enlarge my database:
The EEG-leadfields fieldtrip produces with OpenMEEG 2.4 are different and wrong. I exchanged the binaries on 2 laptops to invesitagte this and found out, that 2.2. and 2.1 produce matching leadfields on both, but not with 2.4. Together with Maureen Clerc from OpenMEEG we found out that the sensor interpolations within `forward/ft_prepare_vol_sens.m` are the problem: [https://github.com/openmeeg/openmeeg/issues/264](https://github.com/openmeeg/openmeeg/issues/264).
I also added a pull request (Adopt to OpenMEEG 2.4 #673) that solved this issue for me.

**Comment by agramfort** [comment]
@DanielMiklody we'll still on the process of release 2.4 (we have indeed speed issues we're looking into). thanks for the PR #673 I will comment there.
