### ISSUE TITLE
mistake in ft_crossfrequencyanalysis.m ?

### ISSUE THREAD

**Issue by danidan12** [fieldtrip/fieldtrip#686]
On lines 238 and 260 of ft_crossfrequencyanalysis.m - the computation section of the modulation index - the lines read:
mi(i,j) = nansum(P.* (log(P)-log2(Q)))/log(nbin);

Apologies if I'm missing something, but don't the log terms all need to be in the same base?  A recent version of fieldtrip has them all as log2.

**Comment by robertoostenveld** [comment]
indeed unusual. https://en.wikipedia.org/wiki/Kullback–Leibler_divergence mentions that log2 is used when in bits.  @dieloz, do you perhaps know where this comes from?

**Comment by dieloz** [comment]
Sorry! I just realized about this thread... Indeed that's weird. I don't know who wrote this but it's surprising that the original paper didn't use log2 for a mutual information measure (see page 3 https://www.physiology.org/doi/pdf/10.1152/jn.00106.2010). I think it should go like this:

mi(i,j) = nansum(P.* (log2(P)-log2(Q)))/log2(nbin);
or shorter
mi(i,j) = nansum(P.* log2(P./Q))./log2(nbin)

**Comment by robertoostenveld** [comment]
would you care to propose a fix in the form of a pull-request?

**Comment by dieloz** [comment]
sure!
https://github.com/fieldtrip/fieldtrip/pull/720

**Comment by dieloz** [comment]
Sorry again for the uge delay: I'll try to stay closer to the github notifications :)
