### ISSUE TITLE
eyelink import with '.' values

### ISSUE THREAD

**Issue by tmosr** [fieldtrip/fieldtrip#694]
Hi

i looked at your code for the eyelink import to improve my own eyelink function. I think I may have found a bug. 

If a data line in the .asc file looks like this: 

``
4491234    .     .      0.0   736.0   482.0  5990.0 32768.0 .C...    
``

sscanf will produce a vector like this: 

``
[4491234]
``

Therefore i suggest to replace the line from https://github.com/fieldtrip/fieldtrip/blob/82c4b32a34aa4382d1ed62f5bdc2f7e5e66616db/fileio/private/read_eyelink_asc.m#L52 with something like this:

``
tmp = sscanf(strrep(tline, ' . ', ' NaN '), '%f');
``

This would then produce a vector like this:

``
[4491234 NaN NaN 0 736 482 5990 32768]
``

(haven't tested it)

best
Tobias

**Comment by robertoostenveld** [comment]
I made a test script like this
```
filename = {
  'BP2D1_2.asc'
  'ashcal.asc'
  'sub-v31_acq-l2_task-hyperlink_eyetrack.asc'
  };

% the hard-coded numbers below related to the size of the data were determined prior to the suggested change, it still works after the change

%%
i = 1;
hdr = ft_read_header(filename{i});
dat = ft_read_data(filename{i});
evt = ft_read_event(filename{i});
assert(isequal(size(dat), [4 782756]));
assert(numel(evt)==11);

%%
i = 2;
hdr = ft_read_header(filename{i});
dat = ft_read_data(filename{i});
evt = ft_read_event(filename{i});
assert(isequal(size(dat), [7 104517]));
assert(numel(evt)==210);

%%
i = 3;
hdr = ft_read_header(filename{i});
dat = ft_read_data(filename{i});
evt = ft_read_event(filename{i});
assert(isequal(size(dat), [4 1534424]));
assert(numel(evt)==1975);
```
with some files that I happen to have from different origins. There are no negative side effects on these files. 

Could you send me a file that has the " . " missing values so that I can include it in the test?

See http://www.fieldtriptoolbox.org/faq/how_should_i_send_example_data_to_the_developers

**Comment by tmosr** [comment]
Sure, this is a shortened version of the file I have: 

[the example file](https://www.sendspace.com/file/na8xtg)

**Comment by robertoostenveld** [comment]
thanks, I merged it in the master/release branch
