### ISSUE TITLE
qsubfeval uses a strange default matlab executable on DCCN cluster

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/fieldtrip#709]
In [qsubfeval at line 193](https://github.com/fieldtrip/fieldtrip/blob/af6871348043f8c912b0c9c24552f9bb8db4b412/qsub/qsubfeval.m#L193) `getenv('MATLAB_BIN')` is used. On the DCCN cluster this returns `/opt/matlab/R2012b/bin/matlab`, even when the Matlab version in which I'm running `qsubfeval` is R2017b. I realize that this is a DCCN-specific issue, but am wondering if we could not be doing something smarter to determine the appropriate Matlab version to run. (E.g. detect whether we are at the DCCN, then get current Matlab version, and construct `/opt/matlab/RXXXXz/bin/matlab` from that.)

**Comment by robertoostenveld** [comment]
I have this on the linux command line without starting MATLAB

roboos@mentat002> echo $MATLAB_BIN
/opt/matlab/R2017b/bin/matlab

and this from within MATLAB2017a

>> getenv('MATLAB_BIN')
ans =
    '/opt/matlab/R2017a/bin/matlab'


and this from within MATLAB2014a

>> getenv('MATLAB_BIN')
ans =
/opt/matlab/R2014a/bin/matlab

SO I cannot reproduce your issue. I suggest that you contact the TG at the DCCN to figure out why MATLAB_BIN is set incorrectly for you.

**Comment by robertoostenveld** [comment]
it might be interesting to consider https://se.mathworks.com/help/matlab/ref/matlabroot.html

**Comment by robertoostenveld** [comment]
is there still something to be done here? If not, I will close this issue.

**Comment by Spaak** [comment]
Ah sorry, I thought this was already closed. It is indeed too much of a DCCN-specific issue, I think. Am closing now.
