### ISSUE TITLE
Using ft_read_mri to read .mnc (minc) files requires SPM2 or SPM5 toolbox

### ISSUE THREAD

**Issue by anupdas777** [fieldtrip/fieldtrip#710]
When using ft_read_mri to read .mnc (minc) files, error in MATLAB pops up saying that it requires SPM2 or SPM5 toolbox. But, in the latest fieldtrip toolbox, only SPM8 and SPM12 toolboxes are installed. Could you please fix this bug and let me know at a1das@stanford.edu?

Thanks.

Anup

**Comment by robertoostenveld** [comment]
as far as I can tell, https://github.com/fieldtrip/fieldtrip/tree/master/external/spm2 contains SPM2. If you cannot find it on your computer, you can download SPM2 from http://www.fil.ion.ucl.ac.uk/spm/software/spm2.

**Comment by anupdas777** [comment]
Installing SPM2 does not solve the problem since one program is compatible for SPM2 and another is compatible for SPM12. SO it just gives errors even after downloading SPM2.

**Comment by robertoostenveld** [comment]
that seems a problem in SPM2 for which you should contact the SPM developers. As work-around you might be able to use another tool to convert the mnc file to a supported format. 

Perhaps you can implement a new reading function for mnc files that works with more recent MATLAB versions, for example based on https://se.mathworks.com/matlabcentral/fileexchange/32644-loadminc?focused=5198037&tab=function

**Comment by anupdas777** [comment]
loadminc function also gives error, does not work.
