### ISSUE TITLE
Computing 1020 electrode positions on unit sphere.

### ISSUE THREAD

**Issue by sappelhoff** [fieldtrip/fieldtrip#713]
Since reading @robertoostenveld's [article](http://robertoostenveld.nl/electrode/) on the 5% system for electrode positioning in EEG, I was a bit curious how the [xyz coordinates](http://robertoostenveld.nl/electrodes/plotting_1005.txt) on the unit sphere (for plotting) supplied with the blog post were actually computed. I have found the code here and the main functions seem to be (*please correct me if I am wrong*):

- [`elec1020_locate`](https://github.com/fieldtrip/fieldtrip/blob/0baf9e7b892a6c4cb5423641f33dbf8c18d8e389/private/elec1020_locate.m), which locates the positions of electrodes on contours (arcs drawn across the surface of a unit sphere) ... crucially, `elec_1020` calls the following two functions:
- [`elec1020_follow`](https://github.com/fieldtrip/fieldtrip/blob/d11daed366a426184c46bfb024a2cea7e04b1e19/private/elec1020_follow.m), which draws the contour between two points
- [`elec1020_fraction`](https://github.com/fieldtrip/fieldtrip/blob/9685fe18cf47e5a81caf9c23243394858fc7bf7a/private/elec1020_fraction.m), which finds a point on the countour at a fraction of the complete distance of the contour/arc

The code is a bit hard for me to understand and I would be very glad to receive a pointer to literature about the method/procedure to find these contours and compute positions along fractions of the contour.

What I have found so far are the ["Great Circle Distance"](https://en.wikipedia.org/wiki/Great-circle_distance) and a brief reference to a method, to compute [points at fractions](http://fraserchapman.blogspot.se/2008/09/intermediate-points-on-great-circle.html) of the Great Circle Distance. However my initial attempts at this were not fruitful, and the methods are often rather working with latitude and longitude (and geolocation) ... so I hope to receive some further hints here.

Thanks!

**Comment by robertoostenveld** [comment]
My 2001 code predates FieldTrip, but has recently been included into ft_electrodeplacement as method='1020'.

The implementation is not for a geometrical sphere, but for a triangulated mesh. You can of course use a triangulated sphere.

Starting from NAS, INI, LPA, RPA, it determines an approximate vertex, constructs sagittal and coronal contours through the vertex and then refines the vertex position. Then it starts contouring again and starts splitting the contours in 5, 10 and 20%  distances (i.e. the sum of all short line segments that comprise the contour is computed and divided into fractions). Those positions are used to make transversal contours on the left and right, which form the basis for the whole sequence of coronal contours.

Try this 
```
cd ~/matlab/fieldtrip/template/headmodel/skin/
headshape = ft_read_headshape('standard_skin_14038.vol')
headshape.coordsys = 'mni';

%%

cfg = [];
cfg.fiducial.nas =  [   3.0003   84.0000  -43.0000]
cfg.fiducial.ini =  [  12.9996 -116.0001  -53.0000]
cfg.fiducial.lpa =  [ -84.0001  -16.9997  -39.0000]
cfg.fiducial.rpa =  [  84.9999  -13.0003  -44.0000]
cfg.method = '1020';
elec = ft_electrodeplacement(cfg, headshape);

```
Please note that the anatomical landmarks are rough and not very accurate, I quickly made an estimate for them using ft_select_point3d(headshape, 'multiple', true), you could also use the MATLAB Data Cursor for that.

This will give a figure that (with the default feedback option) will be updated while the algorithm is going through its steps. You can see all the contours being constructed one by one (depending on how fast/slow your computer is).

![screen shot 2018-05-28 at 11 46 57](https://user-images.githubusercontent.com/899043/40608753-d7db8784-626c-11e8-993b-1d6b4be0afa1.png)
 
 The implementation of the algorithm is not 100% robust. It expects the anatomical landmarks to fall on a triangle, not precisely on a vertex or edge. You can find some lines in the code that try to deal with this.

**Comment by robertoostenveld** [comment]
PS please next time use the http://fieldtriptoolbox.org/discussion_list, where other people reading along might also learn from answers. Github issues is for code, not fur support.
