### ISSUE TITLE
Allow plotting of multiple channels using ft_singleplotER

### ISSUE THREAD

**Issue by Horschig** [fieldtrip/fieldtrip#714]
As it came up in the NIRS hackathon, hereby a request to have the channel averaging in ft_singleplotER optional, i.e. as a cfg-field (could e.g. be done analogue to ft_databrowser with cfg.viewmode = 'butterfly' or 'average' or 'vertical', where 'average' is the default). I see several ways this could be implemented, but all of them require a substantial amount of work (given the small added feature), and would therefore categorize this as a 'mid effort, low priority' (for NIRS users it is probably high priority). Note that someone of us here might pick this up in future if not being worked on from your side (over the next 2 years I have to say).

**Comment by robertoostenveld** [comment]
How do you propose to implement this? How would it look like from the user point of view? An option like

```
cfg.channel = {'C3',  'C4'}
cfg.combine = 'mean'
```
which would compute the mean, versus
```
cfg.channel = {'C3',  'C4'}
cfg.combine = 'no'
```
which would not combine?

It would be confounded with the existing option to plot multiple conditions. I would actually now use something like

```
cfg.channel = 'C3'
C3 = ft_selectdata(cfg, data)
C3.label = 'channel';

cfg.channel = 'C3'
C4 = ft_selectdata(cfg, data)
C4.label = 'channel';

cfg = [];
ft_singeplotER(cfg, C3, C4)
```

**Comment by KristijanArmeni** [comment]
I recently came to think that FT currently does not provide a high-level option to plot uncertainty estimates (say confidence intervals) to go with the ERP average curve (as in fig 2 here: https://doi.org/10.1111/ejn.13400). Would the feature requested in this issue (optional averaging) also be an opportunity to implement this functionality? I think this would be quite a significant data visualisation improvement. Perhaps on the user end as:

```cfg.combine = "meansd";```
or
```cfg.combine = "meanCI"```

Initially, my suspect for implementing would be Section 4 in ft_singleplotER:
```
%% Section 4: do the actual plotting

cla
hold on

yval = mean(datamatrix, 2); % over channels
yval = reshape(yval, size(yval,1), size(yval,3));
mask = squeeze(mean(maskmatrix, 1)); % over channels

ft_plot_vector(xval, yval, 'style', cfg.linestyle{i}, 'color', graphcolor, ...
  'highlight', mask, 'highlightstyle', cfg.maskstyle, 'linewidth', cfg.linewidth, ...
'hlim', [xmin xmax], 'vlim', [ymin ymax]);
```

If this would be desirable, I'd be willing to spend time on this if some initial guidance (and patience) is provided on how/where to best implement it.

**Comment by Horschig** [comment]
> I would actually now use something like
> 
> ```
> cfg.channel = 'C3'
> C3 = ft_selectdata(cfg, data)
> C3.label = 'channel';
> 
> cfg.channel = 'C3'
> C4 = ft_selectdata(cfg, data)
> C4.label = 'channel';
> 
> cfg = [];
> ft_singeplotER(cfg, C3, C4)
> ```

I tried the above, and it indeed works. However, it is more of a hack, because I have to set the label to something common. When not doing this, I get a very unspecific error:

```
>>  cfg = [];
>>  cfg.channel = '*O2Hb]';
>>  O2data = ft_selectdata(cfg, ftdata);
the call to "ft_selectdata" took 4 seconds

>> cfg.channel = '*HHb]';
>>  Hdata = ft_selectdata(cfg, ftdata);
the call to "ft_selectdata" took 0 seconds

>> cfg = [];
>> ft_singleplotER(cfg, O2data, Hdata)
Warning: the data does not contain a trial definition 
 In fixsampleinfo at line 80
 In ft_datatype_raw at line 147
 In ft_checkdata at line 268
 In ft_checkdata>raw2timelock at line 1497
 In ft_checkdata at line 469
 In ft_singleplotER at line 134

Warning: reconstructing sampleinfo by assuming that the trials are consecutive segments of a continuous recording 
 In fixsampleinfo at line 93
 In ft_datatype_raw at line 147
 In ft_checkdata at line 268
 In ft_checkdata>raw2timelock at line 1497
 In ft_checkdata at line 469
 In ft_singleplotER at line 134

> In fixsampleinfo (line 94)
  In ft_datatype_raw (line 147)
  In ft_checkdata (line 268)
  In ft_checkdata>raw2timelock (line 1497)
  In ft_checkdata (line 469)
  In ft_singleplotER (line 134)
Warning: the data does not contain a trial definition 
 In fixsampleinfo at line 80
 In ft_datatype_raw at line 147
 In ft_checkdata at line 268
 In ft_checkdata>raw2timelock at line 1497
 In ft_checkdata at line 469
 In ft_singleplotER at line 134

Warning: reconstructing sampleinfo by assuming that the trials are consecutive segments of a continuous recording 
 In fixsampleinfo at line 93
 In ft_datatype_raw at line 147
 In ft_checkdata at line 268
 In ft_checkdata>raw2timelock at line 1497
 In ft_checkdata at line 469
 In ft_singleplotER at line 134

> In fixsampleinfo (line 94)
  In ft_datatype_raw (line 147)
  In ft_checkdata (line 268)
  In ft_checkdata>raw2timelock (line 1497)
  In ft_checkdata (line 469)
  In ft_singleplotER (line 134)
the call to "ft_selectdata" took 0 seconds
Warning: could not determine dimord of "avg" in:

      time: [0x21191 double]
       avg: [0x21191 double]
     label: {}
       cfg: [1x1 struct]
      opto: []
    dimord: 'chan_time'

 
 In getdimord>warning_dimord_could_not_be_determined at line 670
 In getdimord at line 619
 In ft_singleplotER at line 344

Warning: could not determine dimord of "avg" in:

      time: [0x21191 double]
       avg: [0x21191 double]
     label: {}
       cfg: [1x1 struct]
      opto: []
    dimord: 'chan_time'

 
 In getdimord>warning_dimord_could_not_be_determined at line 670
 In getdimord at line 619
 In chanscale_common at line 61
 In ft_singleplotER at line 356

Warning: could not determine dimord of "avg" in:

      time: [0x21191 double]
       avg: [0x21191 double]
     label: {}
       cfg: [1x1 struct]
      opto: []
    dimord: 'chan_time'

 
 In getdimord>warning_dimord_could_not_be_determined at line 670
 In getdimord at line 619
 In chanscale_common at line 61
 In ft_singleplotER at line 356

Error using assert
The condition input argument must be a scalar logical.

Error in nearest (line 52)
assert(all(~isnan(val)), 'incorrect value (NaN)');

Error in ft_singleplotER (line 380)
xminindx = nearest(varargin{1}.(xparam), xmin);
```

I don't get the dimord warnings when setting *data.label to something common.

**Comment by robertoostenveld** [comment]
the dimord warning is because the data has zero channels, and the size of avg and time are [0x21191]. That makes it impossible to make the time selection, where the "assert" error pops up.

**Comment by robertoostenveld** [comment]
I think that this issue needs to be made [SMART](https://en.wikipedia.org/wiki/SMART_criteria) to allow us to resolve it.

**Comment by robertoostenveld** [comment]
I think that the [initial request](https://github.com/fieldtrip/fieldtrip/issues/714#issue-327219701) can be phrased as

* I want to plot multiple channels on top of each other (separately) using ft_singleplotER. Agreed @Horschig 

The [second request](https://github.com/fieldtrip/fieldtrip/issues/714#issuecomment-422042614) might be translated as

* I want to plot confidence intervals around a channel. Agreed @KristijanArmeni 

The two could in principle be combined, but don't have to.

**Comment by Horschig** [comment]
> 
> 
> the dimord warning is because the data has zero channels, and the size of avg and time are [0x21191]. That makes it impossible to make the time selection, where the "assert" error pops up.

Sure. but the error is not very informative for the average user. Better would be to check on a high-level for missing consistency between the inputted data. But that is a different issue. 
 
> 
> I think that the [initial request](https://github.com/fieldtrip/fieldtrip/issues/714#issue-327219701) can be phrased as
> 
>     * I want to plot multiple channels on top of each other (separately) using ft_singleplotER. Agreed @Horschig ?

Correct

> 
> 
> The [second request](https://github.com/fieldtrip/fieldtrip/issues/714#issuecomment-422042614) might be translated as
> 
>     * I want to plot confidence intervals around a channel. Agreed @KristijanArmeni ?
> 
> 
> The two could in principle be combined, but don't have to.

I agree

**Comment by robertoostenveld** [comment]
The proposal of @helenacockx (for multiple, but I think it might also apply to single plot) is to plot oxi and deoxi channels of a NIRS dataset like this:

```
cfg = [];
cfg.linecolor = 'rbrbrbrbrbrbrbrbrbrbrb';
ft_mutiplotER(cfg, nirsdata);
````

where `linecolor` must have the length of the number of channels,  whereas if multiple conditions are given as input

```
cfg = [];
cfg.linecolor = 'rgb';
ft_mutiplotER(cfg, cond1, cond2, cond3);
````

the `linecolor` must have the length of the number of conditions (=input datasets).

**Comment by robertoostenveld** [comment]
@helenacockx, can you send me a simple test dataset?

**Comment by robertoostenveld** [comment]
However, we should also look into making it consistent with `ft_databrowser`, which has already these

```
%   cfg.colorgroups             = 'sequential' 'allblack' 'labelcharx' (x = xth character in label), 'chantype' or vector with length(data/hdr.label) defining groups (default = 'sequential')
%   cfg.channelcolormap         = COLORMAP (default = customized lines map with 15 colors)
```

**Comment by robertoostenveld** [comment]
I think it would be better not to start with a real dataset, but generate a very simple synthetic one. That should then be plotted consistently in databrowser, multi- and in singleplotER.
