### ISSUE TITLE
incorrect link in warning message

### ISSUE THREAD

**Issue by nolasama** [fieldtrip/fieldtrip#715]
using ft_readheader on neuralynx data I got the warning:
Warning: the NEURALYNX_V3 toolbox is not installed, see
http://neuralynx.com/research_software/file_converters_and_utilities/ and take the version from
Ueli Rutishauser 

The provided address did not work, the software is now found at:
https://neuralynx.com/software/nlx-to-matlab-import-export-mex-files-for-linux-and-mac-os-x

Downloading this and adding a path the the precompiled resolved the warning. I didn't need to compile my own running matlab R2018a on red hat.

**Comment by schoffelen** [comment]
Thanks for the notification. Please feel free to update the warning message at the respective location in the code and send in a pull request, so that we can accommodate it in the release version.
