### ISSUE TITLE
qsubfeval extremely slow

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/fieldtrip#722]
I have tracked down an issue with qsubfeval I have been experiencing on our torque cluster for a while now. The 'problem' is, that if I call qsubfeval in a for-loop, each of the iterations sometimes takes about 5 seconds to run, making this a very impractical strategy to deploy many jobs from within an interactive matlab session.

I found out that virtually all time is spent in MATLAB's built-in system() function, while all that this intends to do is to echo a long string to the command line.

I found an overloaded version of system(), called jsystem on github. This function is released under the MIT license. 

https://github.com/avivrosenberg/matlab-jsystem/

Would it be an idea to replace the system()-calls with this >10 fold faster version (at least this was the speed up that I got in my interactive matlab session on c012)

**Comment by robertoostenveld** [comment]
why is the system call taking so long? This was not a problem before, so it might be because something changed on the cluster. Does it happen for all matlab versions? Can someone else reproduce?

**Comment by robertoostenveld** [comment]
I would rather not make qsub dependent on an external function/toolbox.

**Comment by robertoostenveld** [comment]
the proposed solution would also not work if java is not available, e.g. with -nojvm.

**Comment by schoffelen** [comment]
I have asked around, but in my group nobody is experiencing any problems it seems. Probably node-specific.

**Comment by schoffelen** [comment]
I haven't tried other matlab versions

**Comment by schoffelen** [comment]
than 2016b

**Comment by robertoostenveld** [comment]
can we close this issue?

**Comment by schoffelen** [comment]
Sure.
