### ISSUE TITLE
topoplot_common.m line 582 should be comment = cfg.comment?

### ISSUE THREAD

**Issue by hauselin** [fieldtrip/fieldtrip#751]
Hi, should line 582 in `topoplot_common` be `comment = cfg.comment;` rather than `comment = '';`? Currently it's `comment = '';`, which means we can't specify custom plot titles (and can't replicate the figures in the [tutorials (see figure 1)](http://www.fieldtriptoolbox.org/tutorial/cluster_permutation_freq). When I change it to that line to `comment = cfg.comment;` instead, I can then replicate the figures in the tutorial.

**Comment by schoffelen** [comment]
I think that '' is intended. cfg.comment is not intended for 'custom' titles, but will be either the combination xlim/ylim/parameter cfg.comment = 'auto', or a user specified selection cfg.comment='xlim' etc.

**Comment by hauselin** [comment]
Thanks! Though it seems that fieldtrip functions that call `topoplot_common` are specifying custom titles. For example, see `ft_clusterplot.m` lines 408, 410, 424 etc. (e.g., `cfgtopo.comment = strcat('time: ',num2str(time(ind_timewin_min+PlN-1)), ' s')`) and the actual plotting on line 432 `ft_topoplotTFR(cfgtopo, stat);`, and `ft_topoplotTFR` calls `topoplot_common`). But it seems that because of `cfg.comment = ''` in `topoplot_common`, `ft_clusterplot` never shows any plot titles, making the figures produced by `ft_clusterplot` a bit uninformative...

**Comment by schoffelen** [comment]
Ah, I see. Well I guess that ft_clusterplot is the only case where this behavior was expected to be supported. Somehow in the process of re-vamping the code this was lost.

**Comment by schoffelen** [comment]
Can you fix this in your local copy and make a pull request?

**Comment by robertoostenveld** [comment]
it seems that this was resolved, right? If not, please reopen the issue.
