### ISSUE TITLE
issue in multi-channel NIRS data tutorial 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#761]
FieldTrip user "Sunny" reported this email: 

Thanks a lot for providing us with fieldtrip which is really useful to analyze fNIRS data. I have an issue in the "Preprocessing and averaging of multi-channel NIRS data" tutorial. As I am unable to send my question in the email list, can you please help me with this issue?

Issue: In the  "Preprocessing and averaging of multi-channel NIRS data tutorial " http://www.fieldtriptoolbox.org/tutorial/nirs_multichannel

The "Epoch" section consists of a variable "data_flt" which is not defined. Can you please inform what is this variable related to? as this is needed to complete my analysis.

**Comment by robertoostenveld** [comment]
I think that data_flt should be replaced by data_down. Could someone check?

**Comment by schoffelen** [comment]
Sophie has already addressed Sunny's question on the discussion list, and Jorn also knows about it.

**Comment by robertoostenveld** [comment]
See also https://mailman.science.ru.nl/pipermail/fieldtrip/2018-July/012238.html, where the issue was discussed and a solution proposed.

**Comment by Horschig** [comment]
I resolved this a while ago

**Comment by Horschig** [comment]
@robertoostenveld this issue can be closed
