### ISSUE TITLE
[minor bug] private/rollback_provenance.m

### ISSUE THREAD

**Issue by xpekfdls** [fieldtrip/fieldtrip#778]
Hello, I'm one of the fiedtrip user.

First, I would like to thank you for developing this open source. 

I think it's a bug while using open source and I report it here.

When using the **ft_prepare_mesh function with the downsample option,** the function did not work. 
I traced the reason and confirmed that smooth option is not rolled back properly after downsampling the data(In rollback_provenance.m at line 82).
In ft_prepare_mesh function, it is judged whether the smooth option is empty or not. In the rollback_provenance function, the smooth option is recorded as 'yes' or 'no'. This causes an error.

Thanks

**Comment by robertoostenveld** [comment]
I just looked into your reported issue. The cfg.smooth option is used both for ft_volumedownsample and in ft_prepare_mesh, but in different ways (one is for the volume, the other for the mesh). I will submit a fix.
