### ISSUE TITLE
Why does ft_read_sens('xxx.ds') by default return the electrode definition and not the gradiometers?

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/fieldtrip#781]
I am certain that it used to be the other way around; the default was to return the gradiometers. I've now twice enountered people who were expecting to get a gradiometer definition but instead got the electrodes out, and were confused about how their superimposed sourcemodel/volume conductor/sensor array plots looked.

Should we change the default back to returning the gradiometers?

See:

https://github.com/fieldtrip/fieldtrip/blob/751d0e059157326f535c05ac1241c20c2bcfb3c6/fileio/ft_read_sens.m#L184-L185

**Comment by robertoostenveld** [comment]
The default was eeg (when present) for Neuromag. Furthermore, originally we simply ignored the electrode information in the res4 header for CTF. At a certain moment we improved the parsing of the res4 CTF header, causing the behaviour that you see.

**Comment by schoffelen** [comment]
Hi @spaak and @robertoostenveld, how shall we resolve this? Does it need to be?
if anything, I could imagine indeed that a user's expectation is to let the grad prevail in case of MEG. Yet the doumentation in the function is clear, where it states that 'eeg' is the default senstype

**Comment by Spaak** [comment]
My position is unchanged: default should be grad for CTF (as it used to be in the past).

**Comment by schoffelen** [comment]
Given Eelke's original report, where it seems that the reported confusion people had resulted from their use of the function at the level of the command line, and the fact that the documentation in the code is consistent, and the absence of any evidence that there might be a fieldtripcode internal issue that leads to problems w.r.t. forward computations or so, I suggest to close this.

**Comment by Spaak** [comment]
Are there any downsides to changing the default (back!) to 'meg'?

**Comment by robertoostenveld** [comment]
yes, the expectation and current scripts of Elekta users (more clinical sites, and MEG and EEG are more often combined) would be broken. If we were to break anything, it should be clear from the error message from FT code and should not lead to unclear errors further in the analysis pipeline. So if the file contains both EEG and MEG, and senstype is not specified, ft_read_sens could give an error. 

I propose that we review the documentation on the website and ensure that senstype=eeg/meg is always specified whenever ft_read_sens is called directly.

**Comment by robertoostenveld** [comment]
is the thumbs-up for the documentation (which I just did) or the error when both MEG and EEG are present?

**Comment by Spaak** [comment]
> is the thumbs-up for the documentation (which I just did) or the error when both MEG and EEG are present?

For explaining why there are downsides to changing the default back to MEG. This was unclear to me before (so I was still in favour of changing it back), but now I understand why we keep the changed default.
