### ISSUE TITLE
ft_prepare_headmodel missing symbol

### ISSUE THREAD

**Issue by neurohazardous** [fieldtrip/fieldtrip#813]
Hello all! I am running fieldtrip on a MacBook Pro Retina (2015) with El Capitan on Matlab R2017a. I installed Fieldtrip today (20/Sept/2018) and was going through the Beamformer tutorial (http://www.fieldtriptoolbox.org/tutorial/beamformer). When running ft_prepare_headmodel, I first got an error telling me to specify a tissue type. I did so by adding cfg.tissue = {'gray', 'white', 'csf'}; to my code. Then it ran for a bit before crashing with a message down the lines of... "Missing symbol '__Block_copy' required by" followed by lines and lines and lines of red MATLAB code that are similar to this:

 '/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices->/System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC->/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata->/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices->/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation->/Applications/MATLAB_R2017a.app/bin/maci64/libmwnativestrings.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwsettingscore.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwservices.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmex.dylib->/Users/hectorOrozco/Documents/MATLAB/fieldtrip-20180919/external/spm8/spm_bwlabel.mexmaci64'
Missing symbol '__Unwind_Resume' required by

After this, the error output was: Error in volumethreshold (line 34)
[cluster, n] = spm_bwlabel(output, 6);

Error in prepare_mesh_segmentation (line 143)
  seg = volumethreshold(seg, 0.5, tissue);

Error in ft_prepare_mesh (line 149)
    bnd = prepare_mesh_segmentation(cfg, mri);

Error in ft_prepare_headmodel (line 341)
        geometry = ft_prepare_mesh(tmpcfg, data);

Is there anything I can do about this? Did I miss any step on the tutorial? Let me know!

**Comment by robertoostenveld** [comment]
Hi,

There are two separate problems. The first (for which you have a work-around) is the missing "cfg.tissue", which should probably be fixed in the tutorial. I'll look into it.

The second is that your SPM mex files are not compatible with your version of MATLAB. That is not something we can fix. See http://www.fieldtriptoolbox.org/faq/matlab_complains_about_a_missing_or_invalid_mex_file_what_should_i_do?s[]=spm&s[]=mex#known_issues_with_spm_mex_files_and_workarounds and 
http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3365 for more background.

**Comment by robertoostenveld** [comment]
Regarding the first issue with the tutorial: although adding cfg.tissue = {'gray', 'white', 'csf'} makes the code run through, it is not correct for the singleshell method, which requires a single surface (not three). I added a check to make the code more strict. 

The correct operation is to take csf+grey+white together to construct the brain compartment in the segmentation (the outer surface of that is used for the singleshell method), and that is where (again) an SPM8 mex file fails. There is a try-catch in the code that causes that to remain invisible, but see ft_prepare_headmodel line 348. 

The correct solution is to specify cfg.tissue = {'brain'}, which happens to be the default. This results in SPM being used to merge csf+gray+white into a brain segmentation, after which the triangulated mesh is constructed. 

So please use the correct SPM version. You can do that e.g. with cfg.spmversion='spm12', or by adding that to the global ft_default variable (in that case all FT functions will use spm12).

**Comment by robertoostenveld** [comment]
If you take the latest FT version, you should get more meaningful feedback on the issue you ran into.

**Comment by neurohazardous** [comment]
Done; thank you very much for the prompt response!
