### ISSUE TITLE
Use of nargoutchk 

### ISSUE THREAD

**Issue by gllmflndn** [fieldtrip/fieldtrip#827]
`nargoutchk()` is used with two input arguments in some parts of the code, e.g.:
https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/ft_determine_units.m#L43
This syntax was introduced in `R2011b`. Would it be possible to add a replacement in `compat` or (preferably) remove their call entirely? A search revealed I had already come across this last year, see this bug report on Bugzilla:
http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3352
Thanks!

**Comment by schoffelen** [comment]
sorry for not following up. I'll check this asap

**Comment by schoffelen** [comment]
I think that it's a bit of an overkill to make the drop in replacement in compat. I checked and agree that it won't hurt to remove the call to nargoutchk altogether.

**Comment by schoffelen** [comment]
I have just pushed the changes to the main repo. It'll take some time before it's synced to the different copies of ft_determine/ft_convert

**Comment by gllmflndn** [comment]
Great! Thanks @schoffelen
