### ISSUE TITLE
FieldTrip code returning NaNs in powspctrm/crsspctrm matrix (EEG Analysis)

### ISSUE THREAD

**Issue by Lansze** [fieldtrip/fieldtrip#829]
Hi all,

I'm doing connectivity analysis on EEG signals, and my power analysis code is returning matrices that are partially filled with NaNs. There's also a singleton dimension that shouldn't exist (we expect a 3d matrix but get a 4D one).

Here's my code: https://pastebin.com/capjKex2

My error documentation is below:
This error was brought to my attention upon receiving the following error when trying to plot power correlations:

	Index in position 1 exceeds array bounds 
	(must not exceed 1).

	Error in ft_connectivityplot (line 287)
        tmp = reshape(dat(m,k,:,:), [nfreq ntime]);

FieldTrip code problem:
PowCorr and subsequent functions return structure fields that contain a singleton dimension which generates NaN for all indices

Current hypothesis: Fieldtrip is treating time-segmented data as a continuous line.

When I load in data and then index ALLEEG or EEG, I see:

         	times: [1×900060 double]
                data: [71×900060 single]

So I don't think the .set is missing time data, since this would show 1 time point per data point for all 71 channels. 

After conversion via eeglab2fieldtrip, the new structure E2F returns:

	      trial: {[71×900060 single]}
       	      time: {[1×900060 double]}
So it doesn't really seem like anything is going wrong here.

When running ft_freqanalysis, I get 4 warnings:
1) Warning: assuming that the units are "m" 	
2) Warning: the data does not contain a trial definition 
3) Warning: reconstructing sampleinfo by assuming that the trials are consecutive segments of a continuous
recording 
4) Warning: output time-bins are different from input time-bins 

I see 2 and 4 in a lot of sample code so I'm assuming these are benign. I have no idea what the first means(what is m? meters?). 3 is the one I'm interested in. Reconstructing sampleinfo is normally benign(see here https://mailman.science.ru.nl/pipermail/fieldtrip/2012-March/004962.html), but does the assumption mean all channels are being merged into 1 mega-channel?

After running ft_freqanalysis, I begin to see the problems. Indexing the output structure Freq returns:

Freq = 

  struct with fields:

        label: {1×71 cell}
       dimord: 'rpt_chan_freq_time'
         freq: [4 4.5000 5 5.5000 6 6.5000 7 7.5000 8]
         time: [1×301 double]
    powspctrm: [1×71×9×301 double]
     labelcmb: {2485×2 cell}
    crsspctrm: [1×2485×9×301 double]
    cumtapcnt: [1 1 1 1 1 1 1 1 1]
         elec: [1×1 struct]
          cfg: [1×1 struct]

The problem here is those singleton dimensions in Freq.powspctrm and Freq.crsspctrm--In either matrix, any 4th dimension less than 59 returns NaN. 

Then, I think the problem is clearly in (or begins in) this particular function. What's going wrong?

Things I've tried:

1) Squeezing out singleton dimension did not remove NaNs and just gave a different error

2) Updating cfg structures didn't change anything

2.5) Changing ft_freqanalysis padding didn’t do anything

3) Checking the data in EEGLab showed a really weird channel scroll

4) ICA did not remove the error

5) Try a new dataset (using cognit data). Same problem.

Next steps:
1) Debug ft_freqanalysis

Any help is greatly appreciated!

Best,
Alex

**Comment by Spaak** [comment]
> There's also a singleton dimension that shouldn't exist (we expect a 3d matrix but get a 4D one).
You are getting a singleton 'rpt' (= trial) dimension because you're specifying `cfg.keeptrials = 'yes'` in the call to `ft_freqanalysis`.

> In either matrix, any 4th dimension less than 59 returns NaN.
Have you had a look at this: http://www.fieldtriptoolbox.org/faq/why_does_my_tfr_contain_nans ?

**Comment by schoffelen** [comment]
https://mailman.science.ru.nl/pipermail/fieldtrip/2012-November/005918.html
