### ISSUE TITLE
 tal2mni.m outputs odd MNI coordinates

### ISSUE THREAD

**Issue by dlevitas** [fieldtrip/fieldtrip#830]
Hello,

I tried running tal2mni on a single set of Talairach coordinates, using the following command:
`tal2mni([-1 -32 58])` and got the following output:
`-1.0101  -35.9369   61.2263`, which seem like improper MNI coordinates (in the sense that I was expecting integers rather than decimals). Is there something wrong in how I'm passing the Talairach coordinates into the function?

If it's the case that this is correct (i.e. the best approximation) would it make sense to round these numbers (i.e. -1 -36 61)?

Thank you.

Dan

**Comment by schoffelen** [comment]
Why did you expect integer numbers?

**Comment by dlevitas** [comment]
That was my bad. Given the transform being used, I should've expected decimals rather than integers. I can just round them when reporting the coordinates in MNI. 

Thanks.
