### ISSUE TITLE
Use of tilde to ignore outputs

### ISSUE THREAD

**Issue by gllmflndn** [fieldtrip/fieldtrip#831]
Tilde is used in a few places in `ft_read_header.m` to ignore function outputs:
  https://github.com/fieldtrip/fieldtrip/blob/master/fileio/ft_read_header.m#L444-L475
Would it be possible not to use them for backward compatibility? They are anyway of no use in this context (last outputs of `fileparts`).

**Comment by robertoostenveld** [comment]
On http://www.fieldtriptoolbox.org/development/guidelines/code we state "the ~ output argument is not supported in MATLAB versions < 2009b and should be avoided"

But we also state elsewhere that version up to 5y old are to be supported, and 2009b is now 9 years old. I suspect that causes the tilde to creep into the code by now.

I am fine with trying to keep the tilde out of existing code. I recommend using the variable "dum" instead, as I know that is used elsewhere.

Could you do a PR?

**Comment by gllmflndn** [comment]
I came across an issue with `ft_hastoolbox` and old MATLAB versions that was due to the use of `~`. Looking at the current code, it seems that its use is widespread in the code:

```
data2bids.m:        [~, f, ~] = fileparts(cfg.dataset);
data2bids.m:  [p, f, ~] = fileparts(cfg.outputfile);
data2bids.m:  [p, f, ~] = fileparts(cfg.outputfile);
data2bids.m:  [p, f, ~] = fileparts(cfg.outputfile);
data2bids.m:  [p, f, ~] = fileparts(cfg.outputfile);
data2bids.m:[~, f, ~] = fileparts(f);
ft_prepare_layout.m:      [p, f, ~] = fileparts(cfg.layout);
fileio/ft_read_event.m:    [p, ~, ~] = fileparts(filename);
private/copy_brainvision_files.m:[~, f, ~] = fileparts(newheaderfile);
private/copy_brainvision_files.m:  [~, ff, ~] = fileparts(oldheaderfile); % re-reading as sometimes weird names comes up
private/copy_brainvision_files.m:  [~, ff, ~] = fileparts(oldheaderfile); % re-reading as sometimes weird names comes up
private/copy_ctf_files.m:[~, fo, ~] = fileparts(oldname);
private/copy_ctf_files.m:[~, fn, ~] = fileparts(newname);
private/estimate_fwhm2.m:%   [s,~] = gaussfit3D(dpos(sel,:), Cmat(sel,k));
private/ft_inv.m:    [kappa,~] = ginput(1);
private/prepare_mesh_fittemplate.m:[transform,~] = cpd_register(headshape,template, opt);
private/savevar.m:  [~,fileonly,~] = fileparts(filename);
utilities/ft_hastoolbox.m:  [p, f, ~] = fileparts(toolbox);
utilities/markdown2matlab.m:  elseif match(line, '{%[ -~]*%}')
utilities/markdown2matlab.m:  elseif match(line, '!\[[ -~]*\]([ -~]*)')
utilities/matlab2markdown.m:    [startIndex,endIndex] = regexp(line, '[!-~]*.png$');
external/bct/align_matrices.m:%       [v,~] = eig(M1); v1 = abs(v(:,end)); [a1,b1] = sort(v1);
external/bct/align_matrices.m:%       [v,~] = eig(M2); v2 = abs(v(:,end)); [a2,b2] = sort(v2);
fileio/private/ft_hastoolbox.m:  [p, f, ~] = fileparts(toolbox);
forward/private/ft_hastoolbox.m:  [p, f, ~] = fileparts(toolbox);
inverse/private/ft_hastoolbox.m:  [p, f, ~] = fileparts(toolbox);
inverse/private/ft_inv.m:    [kappa,~] = ginput(1);
plotting/private/extract_contour.m:    [row,~]  = find(tri == (indx(i))); %find neighbours
plotting/private/ft_hastoolbox.m:  [p, f, ~] = fileparts(toolbox);
utilities/private/savevar.m:  [~,fileonly,~] = fileparts(filename);
```

Has there been a change in the rule whether to use it or not? It is not required in most of the instances listed above.

**Comment by robertoostenveld** [comment]
no, just sloppy programming and not following the rules. 

Feel free to make the required changes and send a PR. 

But more importantly: to prevent this from happening again, could you try to catch it in the `test_checkcode.m` script? That would ensure that code with a `~` would not get released any more and that @schoffelen and I are automatically notified. See http://www.fieldtriptoolbox.org/development/dashboard/   and https://github.com/fieldtrip/fieldtrip/issues/1026#issuecomment-501635222

**Comment by robertoostenveld** [comment]
there are still a few occurrences. I'll leave them in for now, since the (to-be) updated `test_checkcode.m` should find them and raise an error.

**Comment by schoffelen** [comment]
I think that this issue can be closed no? @robertoostenveld

**Comment by robertoostenveld** [comment]
no, since there are still some occurrences, e.g. 

```
mac036-lan> grep '\[~' *.m
data2bids.m:      [~, ~, x] = fileparts(cfg.dataset);
data2bids.m:    [~, ~, xin] = fileparts(cfg.dataset);
data2bids.m:  [~, f, x] = fileparts(cfg.outputfile);
data2bids.m:      [~, optoidx, wavelengthidx]=find(hdr.opto.tra(labelidx,:));
ft_eventtiminganalysis.m:      [~,order_inv] = sort(order);
ft_prepare_layout.m:    [~, ~, e] = fileparts(cfg.image);
ft_prepare_neighbours.m:    [~, sensidx] = match_str(data.label, label);
ft_timelockanalysis.m:  [~, datacov] = rollback_provenance(cfg, datacov); % not sure what to do here
xdf2fieldtrip.m:[~, indx] = max(srate);
```

the regression function https://github.com/fieldtrip/fieldtrip/blob/master/test/test_checkcode.m still needs to be updated.

**Comment by schoffelen** [comment]
good to go now! Thanks to @robertoostenveld for the principled solution :)
