### ISSUE TITLE
nanmin and nanmax are missing 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#844]
Till reported by email that, when the stats toolbox is not available, he gets this error

```Undefined function 'nanmin' for input arguments of type 'double'. 

Error in ft_multiplotER (line 404) 
    xmin = nanmin([xmin varargin{i}.(xparam)]); 

Error in abr_example_preproc (line 100) 
    ft_multiplotER(cfg_mp,avgdata); 
```

**Comment by schoffelen** [comment]
what's the error?

**Comment by robertoostenveld** [comment]
sorry, missed that from the email:

```
Undefined function 'nanmin' for input arguments of type 'double'. 
```

**Comment by robertoostenveld** [comment]
there is actually not a very good reason to call nanmin, since min ignores nans in the same way.

**Comment by robertoostenveld** [comment]
... but it is used quite a bit. I think it helps in the code to make clear that a vector/matrix might contain nans, so I won't change it in the main FT code.
