### ISSUE TITLE
conflicts in SPM versions

### ISSUE THREAD

**Issue by TomRhysMarshall** [fieldtrip/fieldtrip#859]
I left a comment on the mailing list previously (https://mailman.science.ru.nl/pipermail/fieldtrip/2018-January/011981.html) about fieldtrip on mac with matlab2018 getting mixed up with versions of SPM8. This issue seems to persist.

E.g., when I now call

cfg             = [];
cfg.method      = 'singleshell';
cfg.spmversion  = 'spm12';
headmodel = ft_prepare_headmodel(cfg, seg);

(so 'spm12' is specifically asked for)
I get the error msg:
Invalid MEX-file '/Users/marshall/Documents/MATLAB/fieldtrip/external/spm8/spm_bwlabel.mexmaci64': dlopen(/Users/marshall/Documents/MATLAB/fieldtrip/external/spm8/spm_bwlabel.mexmaci64, 6): Library not loaded: @loader_path/libmex.dylib
  Referenced from: /Users/marshall/Documents/MATLAB/fieldtrip/external/spm8/spm_bwlabel.mexmaci64
  Reason: image not found.

...which seems to refer to spm8 mex files. So apparently, somewhere down inside the code my request to use SPM12 is not being propagated.

An example is in ft_prepare_headmodel. On line 336 a 'tmpcfg' is created, which is then used to call ft_prepare_mesh. However, tmpcfg doesn't inherit the .spmversion field from cfg.

If I add the line to ft_prepare_headmodel

tmpcfg.spmversion  = cfg.spmversion

Then this works. However I think this needs to happen a few other places too.

**Comment by schoffelen** [comment]
Thanks for notifying, and providing a solution. I'll check out the other functions and will fix.

**Comment by schoffelen** [comment]
Interestingly, for your specific case, spmversion is not an option for ft_prepare_headmodel.

**Comment by schoffelen** [comment]
This being said, and since you found your way to github, why don't you fix yourself :), and PR?

**Comment by schoffelen** [comment]
this relates to PR #861. To keep everything in a single location, I will close this and suggest to move the discussion to the PR
