### ISSUE TITLE
Add OpenEphys data support

### ISSUE THREAD

**Issue by reinderdorman** [fieldtrip/fieldtrip#860]
OpenEphys is an open access neurophysiological recording system/community (of which I have the feeling I keep hearing more and more about). Adding support for this is likely only appending for the format in read_header, read_data and read_events.

**Comment by robertoostenveld** [comment]
if you call the function read_openephys, put in in fileio/private and add the detection of the file format to ft_filetype, then you can use the example code at https://gist.github.com/robertoostenveld/bf05b9ba0f7e33f14df9f6ae753de66c and the format does not even have to explicitly coded into the reading functions.

See also https://gist.github.com/robertoostenveld/dca2e176daebf5bda02bba14b01ffe78 and the actual code toward the end of ft_read_header, data and event.

I believe it to be used by fileio/private/read_video.m and read_besa_besa.m

**Comment by robertoostenveld** [comment]
It probably should also be added to ft_read_spike. For that we don't have the plug-in approach.

**Comment by robertoostenveld** [comment]
I look forward to receiving a pull request that contributes this.

**Comment by robertoostenveld** [comment]
This issue has been open for some time. Since the original requester is not contributing to an implementation, and the Nijmegen team is too busy and does not need it, let's close it. Feel free to reopen if you want to contribute.
