### ISSUE TITLE
[minor bug] ft_icabrowser bug when displaying timecourse of components

### ISSUE THREAD

**Issue by gcosta18** [fieldtrip/fieldtrip#874]
On the function fieldtrip/contrib/misc/ft_icabrowser.m, when clicking on the "Timecourse" box for a particular component a wrong component is always shown.
This error is due to a + sign that should be a - one, on line 285

282 -        cfgtc = [];
283 -        cfgtc.layout = lay;
284 -        cfgtc.viewmode = 'butterfly';
285 -        cfgtc.channel = [i+(4-whichcomp)];
286 -        % cfgtc.ylim = [-5e-13 5e-13];
287 -         ft_databrowser(cfgtc, comp);

To get the correct channel it should be:

285 -        cfgtc.channel = [i-(4-whichcomp)];

**Comment by schoffelen** [comment]
Please feel free to submit this as a pull request (PR).

**Comment by schoffelen** [comment]
When will we get the PR? I suspect not anytime soon, therefore closing. Please feel free to reopen if a fix will be suggested soon.

**Comment by robertoostenveld** [comment]
@gcosta18 I propose you use ft_databrowser with viewmode=component.
