### ISSUE TITLE
ft_sourceanalysis issue 

### ISSUE THREAD

**Issue by junseokakim** [fieldtrip/fieldtrip#883]
I receive 

Reference to non-existent field 'dimord'.

Error in ft_sourceanalysis (line 788)
    if strcmp(data.dimord, 'chan_time')

while using 

cfg                   = [];
cfg.method            = 'lcmv';
cfg.grid              = source_model;
cfg.headmodel         = vol;
cfg.keepfilter        = 'yes';
cfg.grad              = dataica.grad;

lcmvsource            = ft_sourceanalysis(cfg, timelock);

And in timelock.dimord, the dimord exists as  'rpt_chan_time' which should be a valid input for the code. In addition if I just use strcmp(timelock.dimord, 'rpt_chan_time') the code runs fine on MATLAB so I am not entirely sure why ft_sourceanalysis thinks that this is a non-existant field. 

I am using MATLAB2015b with Neuromag resting state data for this analysis.

**Comment by schoffelen** [comment]
This is hard to address based on the description alone.
What happens if you do cfg.grad = timelock.grad? 

I.e. could it be that the grad-array in dataica is inconsistent with the grad-array that ft_sourceanalysis can work with?

**Comment by schoffelen** [comment]
No follow up from issue reporter. I close for now, please reopen if it can be constructively resolved, ideally involving the reporter of the issue.
