### ISSUE TITLE
Issues with compat folder when wrongly added to the search path

### ISSUE THREAD

**Issue by gllmflndn** [fieldtrip/fieldtrip#899]
Hi,

it has been brought to my attention that adding FieldTrip _with subfolders_ to the search path wreaks havoc on recent MATLAB versions as core functionalities such as `edit` or `open` stop working. The underlying cause is that the `contains` implementation is not complete and compatible. An a minima fix could be this:

```
Index: compat/matlablt2016b/contains.m
===================================================================
@@ -17,6 +17,10 @@
 if nargin<3
   str = 'IgnoreCase';
 end
+if exist('contains','builtin')
+    tf = builtin('contains',s, pattern, str, boolean);
+    return;
+end
 if ~strcmpi(str, 'ignorecase')
   error('incorrect third input argument, can only be ''IgnoreCase''');
 end

```

I know that FieldTrip's subfolders should not be added to the search path (same rule applies for SPM), that this is mentioned explicitly in the documentation:
```
% This is a compatibility function that should only be added to the path on
% MATLAB versions prior to 2016b.
```
and that FieldTrip displays a warning if this is detected but MATLAB crashes with its most basic functionalities as soon as the wrong folders are included and before FieldTrip being used (i.e. before any warning can be displayed). For example, using the MATLAB interface, just changing directory to `fieldtrip/compat/matlablt2016b/` and double-clicking on a file to open it will fail with error `PATTERN must be a string scalar or character vector`.

I am not sure that the comfort brought by using `contains` (and related methods of the `string` class) is currently worth the disruptions the required extra compatibility layer can create.

**Comment by robertoostenveld** [comment]
So you are saying that https://github.com/fieldtrip/fieldtrip/blob/71c87539a884265741b1742eef4f2d3835c39b20/ft_defaults.m#L363
does not work (in time)? Bummer.

The number of functions is relatively limited: 

```
mac011> cd /Users/roboos/matlab/fieldtrip/compat
mac011>  ls matlablt201*/*.m | wc -l
      16
```

and I suppose your solution would work for all of them, right? Should we try to make a generic solution, like `compat/matlablt2016b/contains.m` (and similar) doing the check like this

```
function varargout = compatfunction(varargin)

if exist(mfilename,'builtin')
  varargout{:} = builtin(mfilename, varargin{:})
else
  varargout = feval(mfilename, varargin{:})
end
```
where the actual drop-in replacement would go to `compat/matlablt2016b/private`?

**Comment by gllmflndn** [comment]
The issue here is that an error can take place before calling any FieldTrip function (where `checkIncorrectPath` would issue a warning). E.g.:
```
addpath(genpath('/Users/roboos/matlab/fieldtrip/'));
edit ft_defaults
```
Not all compatibility functions are builtin (e.g. `pad` is not) so this would not work all the time but it would already make things a bit more robust (what about checking `which('-all')`?). Overloaded is also already called automatically when the first argument is an object (e..g of the `string` class) so we do not have to worry about all use cases.

We could instead write complete implementations of these functions (whenever possible) so that they can also be submitted for inclusion into Octave (e.g. [isfolder](https://hg.savannah.gnu.org/hgweb/octave/rev/7c5956c45a29) #727).

**Comment by gllmflndn** [comment]
I came across another related issue, this time with the MATLAB Compiler. By default, everything inside the ``compat`` folder gets compiled and added to the MATLAB path. In particular, the ``narginchk`` function creates an issue with ``legend`` (same error than the one described [here](https://uk.mathworks.com/matlabcentral/answers/373117)).
A solution, that you might already use in the context of FieldTrip, is to remove all of the unnecessary directories according to the version of the MATLAB Compiler being used - I would prefer not to have to do that.

**Comment by gllmflndn** [comment]
I received another report where MATLAB became unusable after a user mistakenly added all subfolders to the MATLAB path:

```matlab

This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:
too many input arguments 
> In matlabrc (line 117) 
Warning: Initializing MATLAB Graphics failed.
This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:
too many input arguments 
> In hgrc (line 163)
  In matlabrc (line 123) 
Error using narginchk (line 10)
too many input arguments
Error in usejava (line 43)
narginchk(1,1);
Error in setInitialWorkingFolder (line 3)
    if ~(ismcc || isdeployed || feature('isdmlworker')) && usejava('jvm')
Error in matlabrc (line 195)
setInitialWorkingFolder();
```

Apparently even the ``Set Path`` button was not working any more due to ``narginchk``.

**Comment by robertoostenveld** [comment]
![](https://www.glasbergen.com/wp-content/gallery/cartoons/toon-1366-1.gif)

**Comment by robertoostenveld** [comment]
> I came across another related issue, this time with the MATLAB Compiler. By default, everything inside the `compat` folder gets compiled and added to the MATLAB path. In particular, the `narginchk` function creates an issue with `legend` (same error than the one described [here](https://uk.mathworks.com/matlabcentral/answers/373117)).
> A solution, that you might already use in the context of FieldTrip, is to remove all of the unnecessary directories according to the version of the MATLAB Compiler being used - I would prefer not to have to do that.

regarding compilation and paths, that is indeed not trivial. I have that in https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_compile_standalone.m, although I have not used it for quite some time.

**Comment by gllmflndn** [comment]
For a number of reasons, the compilation of SPM includes all subdirectories: https://github.com/spm/spm12/blob/r7487/config/spm_make_standalone.m#L111, leading to https://github.com/fieldtrip/fieldtrip/issues/899#issuecomment-464015241. I now pushed a change so that unnecessary directories from ``fieldtrip/compat`` are deleted prior to compilation according to the version of ``mcc``.

**Comment by robertoostenveld** [comment]
I have dealt with this in PR #960
