### ISSUE TITLE
implement support for the anyway_mrk format

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#903]
which is used to write markers for an existing dataset. The file looks like this

```
// AnyWave Marker File
New Marker	-1	544.781	0
New Marker	-1	545.68	0
New Marker	-1	547.921	0
New Marker	-1	548.661	0
New Marker	-1	550.267	0
New Marker	-1	551.378	0
```

functions affected: ft_filetype, ft_read_event, ...

**Comment by robertoostenveld** [comment]
see `fieldtrip/fileio/private/presentation_log.m` as an example

**Comment by schoffelen** [comment]
@raintwoto what is the status of this? Is there any progress to be expected on this front anytime soon? Otherwise, consider handing this over to someone who will be able to finish this. If not, please feel free to close this issue for the time being.
