### ISSUE TITLE
Non-existent 'functional' channel in  NIRS multi-channel tutorial

### ISSUE THREAD

**Issue by Horschig** [fieldtrip/fieldtrip#905]
we ran into an issue with the multichannel tutorial. When plotting the data, ft_multiplotER is configured with cfg.channel  = '* [functional]'; but there is no such channel in the data. Is this a residual from an earlier version in which the tutorial used Marc's super fancy function to separate systemic from functional effects? Or is a step missing there?

**Comment by Horschig** [comment]
I propose to either
1.  remove that step - why rename it to functional at all and not keep it as O2Hb
or 
2. also rename the data_func label to reflect this label renaming 

But I would really vore for 1)

What do you think @marcvanwanrooij

**Comment by schoffelen** [comment]
@Horschig feel free to proceed here in absence of @marcvanwanrooij input
Option 1 sounds reasonable.

**Comment by Horschig** [comment]
I think this has been resolved a while ago, at least I cannot find the respective lines back in the tutorial.
