### ISSUE TITLE
ft_nirs_referencechannelsubtraction should not remove data

### ISSUE THREAD

**Issue by Horschig** [fieldtrip/fieldtrip#906]
Currently, ft_nirs_referencechannelsubtraction removes data, whereas you might want to use the data for something like a 'blood-computer interface'

See also #732

**Comment by Horschig** [comment]
Think about restructuring that function to use ft_regressconfound instead (so basically a wrapper around ft_regressconfound, replicating what is written in http://www.fieldtriptoolbox.org/example/how_to_incorporate_head_movements_in_meg_analysis/)

Tagging @marcvanwanrooij FYI

**Comment by robertoostenveld** [comment]
This issue has not been worked on since the initial idea a few years back, hence I have closed it. Feel free to reopen.
