### ISSUE TITLE
nirs multichannel tutorial is setting bandpass filter type when using low pass filter

### ISSUE THREAD

**Issue by Horschig** [fieldtrip/fieldtrip#925]
When applying the lowpass filter further down in the tutorial, the code reads

```
cfg                 	= [];
cfg.lpfilter        	= 'yes';
cfg.lpfreq          	= 0.8;
cfg.bpfilttype        = 'fir';
data_lpf            	= ft_preprocessing(cfg, data_conc);
```

Obviously, the last cfg setting is not doing anything. @marcvanwanrooij should it have been a FIR lowpass-filter? If so, we should also change the highpass filter type to make it consistent. Otherwise, I propose to simply remove this line, because it works well with the default filter as well (in that case, we need to check whether the figures are still the same).

**Comment by robertoostenveld** [comment]
I have removed the line from the tutorial.
