### ISSUE TITLE
ft_connectivityanalysis give me an issues

### ISSUE THREAD

**Issue by pelagietemgoua** [fieldtrip/fieldtrip#942]
i run ft_connectivityanalysis.m script  with the following configuration :
[data, header] = edfread("s01.edf")
freq = 250
cfg             = [];
cfg.method      = 'plv';
stat = ft_connectivityanalysis(cfg, data)

and i get  the following error:
Error using ft_checkdata (line 529)
This function requires 'freqmvar', 'freq' or 'source' data as input, see ft_datatype_freq or ft_datatype_source.

Error in ft_connectivityanalysis (line 271)
    data = ft_checkdata(data, 'datatype', {'freqmvar' 'freq' 'source'});
need your help please

**Comment by schoffelen** [comment]
Please ask your question on the e-mail discussion list

**Comment by pelagietemgoua** [comment]
Please what is the e-mail discussion list? What can i do to use it?

**Comment by schoffelen** [comment]
http://www.fieldtriptoolbox.org/discussion_list/
