### ISSUE TITLE
FTP link error, trying to do download

### ISSUE THREAD

**Issue by ahamblen6608** [fieldtrip/fieldtrip#943]
Hi there - first time using fieldtrip, tried to follow the link to the ftp download and got an error: " 425 Security: Bad IP Connecting" - can anyone help me get around this to download the tool?

**Comment by robertoostenveld** [comment]
which specific URL are you using to download? It might be an intermittent problem, can you try again? If that still fails, please see http://www.fieldtriptoolbox.org/faq/i_am_having_problems_downloading_from_the_ftp_server/

**Comment by robertoostenveld** [comment]
since there has not been a recent response to this, I suppose it has been resolved
