### ISSUE TITLE
clean up neuromag layouts

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#946]
There are different versions with and without "MEG" in the channel names. The old ones NM306xxx are not used any more, since ft_read_header uses MNE-matlab, which always (as far as I know) includes the "MEG" part in the channel name. 

I will remove the NM306 versions. I will also rename the NM122 version to neuromag122.

**Comment by schoffelen** [comment]
OK, I have now also create helmet-outline type layouts for the different sets of channels + added the figures + updated the links in the webpage. Let's see how it renders in  a few minutes.

**Comment by robertoostenveld** [comment]
I have trimmed them with
```for file in neuromag*helmet* ; do convert -trim $file $file ; done```
so that they appear in a more consistent 200 pixel width with all others.

**Comment by schoffelen** [comment]
owja, da wilde ik nog vragen... 
merci

**Comment by schoffelen** [comment]
krijgen we er een leesbril bij?
