### ISSUE TITLE
Error using ft_append spike

### ISSUE THREAD

**Issue by koro30** [fieldtrip/fieldtrip#951]
Hi, 
I am trying to append LFP data (from a continous matlab file), with a spike data (from wave_clus),  into one large file to do some analysis. 
I tried many options but I always have the same error (Error using ft_appendspike (line 112)
could not find the trial information in the continuous data)
I add all the requiered info manually in order to read it but there is something missing I can't find.
Any help is welcome, thanks!

**Comment by schoffelen** [comment]
I'd recommend asking your question on the fieldtrip discussion list. Github issues aren't typically read by many people, a larger audience will be reached on the discussion list, which is both beneficial for the person raising the issue, and the people spending energy and time in trying to help out.
