### ISSUE TITLE
improve support for AnyWave ADES format

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#968]
Dear @bcolombet

I am working with @wittonc on the http://www.fieldtriptoolbox.org/tutorial/epilepsy/ where we want to use AnyWave for reviewing of virtual channel time series. For this it seems handy to have the possibility to export to the ADES format from within fieldtrip. 

This is how the code might look like (here not virtual channel, but a 151-channel CTF recording):

```
%%

cfg = [];
cfg.dataset = '/Volumes/128GB/data/Subject01.ds';
cfg.trl = [1 900 0];
cfg.demean = 'yes';
cfg.baselinewindow = [-Inf Inf];
cfg.channel = 'all';
data = ft_preprocessing(cfg);

%%

hdr = ft_fetch_header(data);
dat = ft_fetch_data(data);

%%

filename = [tempname, '.ades'];

ft_write_data(filename, dat, 'header', hdr, 'dataformat', 'anywave_ades');
```

and this is how the header would look like 

```
#ADES header file
samplingRate = 300
numberOfSamples = 900
Unit = CLOCK, s
Unit = EEG, V
Unit = MEGGRAD, T
Unit = REFGRAD, T
Unit = REFMAG, T
Unit = TRIGGER, unknown
STIM = unknown
SCLK01 = s
BG1 = T
BG2 = T
BG3 = T
BP1 = T
BP2 = T
BP3 = T
BQ1 = T
BQ2 = T
BQ3 = T
BR1 = T
BR2 = T
BR3 = T
G11 = T
G12 = T
G13 = T
G22 = T
G23 = T
P11 = T
P12 = T
P13 = T
P22 = T
P23 = T
Q11 = T
Q12 = T
Q13 = T
Q21 = T
Q22 = T
Q23 = T
R11 = T
R12 = T
R13 = T
R22 = T
R23 = T
MLC11 = T
MLC12 = T
MLC13 = T
MLC14 = T
MLC15 = T
...
...
```
as you can see, I am including all channel types in the output data. Would this work? Or would I have to collapse the different MEG sub-types into one?

**Comment by robertoostenveld** [comment]
![screen shot 2019-02-26 at 17 54 00](https://user-images.githubusercontent.com/899043/53430818-869e5080-39ef-11e9-81a8-de2e94dc1627.png)

or would I have to use types consistent with this?

**Comment by robertoostenveld** [comment]
sorry, I already realize one error. The channels should be shown like this

```
MLC11 = MEG
MLC12 = MEG
MLC13 = MEG
MLC14 = MEG
MLC15 = MEG
MLC21 = MEG
MLC22 = MEG
MLC23 = MEG
MLC24 = MEG
MLC31 = MEG
``` 

and not with the type.

**Comment by robertoostenveld** [comment]
with this script and only MEG channels it starts looking better.

```
%%

cfg = [];
cfg.dataset = '/Volumes/128GB/data/Subject01.ds';
cfg.trl = [1 30*300 0];
cfg.demean = 'yes';
cfg.baselinewindow = [-Inf Inf];
cfg.channel = 'MEG';
cfg.continuous = 'yes';
data = ft_preprocessing(cfg);

%%

hdr = ft_fetch_header(data);
dat = ft_fetch_data(data);

%%

filename = 'Subject01.ades';

ft_write_data(filename, 1e12 * dat, 'header', hdr, 'dataformat', 'anywave_ades');
```

Although I do not understand why I have to scale the data (in Tesla) with 1e12 to have it display reasonably in AnyWave.

**Comment by bcolombet** [comment]
Hello Robert
You don’t have to specify units unless special cases like when EEG are recorded in V.
AnyWave expets microV for Eeg seeg emg ecg  and T for MeG or Grad

You must however specify the Channel type or it will be considered EEG.
Example:
Q11 = meg
Or
Q11 = grad

Meg is magnometer Grad is gradiometer
For Grad unit is T/m

Replace Unknown by Other and it should work

One issue you may have is that AnyWave does not have RefGrad or RefMeg types but only Reference (which is in fact Megref)

I should Add refgrad shortly as I’ve already added Grad type....

Hope it will Help !
Cheers

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>



On Tue, Feb 26, 2019 at 5:54 PM +0100, "Robert Oostenveld" <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2019-02-26 at 17 54 00]<https://user-images.githubusercontent.com/899043/53430818-869e5080-39ef-11e9-81a8-de2e94dc1627.png>

or would I have to use types consistent with this?

**Comment by robertoostenveld** [comment]
if I write a MEG channel with a square wave that is either 0 or 1, without any other scaling and specifying in the header `Unit = MEG, T`, I get this

![screen shot 2019-02-26 at 18 18 13](https://user-images.githubusercontent.com/899043/53432553-024dcc80-39f3-11e9-843e-8beb3dee2410.png)

note the 1st channel, and at the bottom "MEG Levels" of 1 pP/cm. I did calibrate my screen, and this seems to be about a cm. Hence my confusion. The data (floating point values) and header suggest that this is 1 Tesla, not one pT. So should all MEG data be multiplied with 1e12?

**Comment by bcolombet** [comment]
No, values units must be in T.
AnyWave will convert in pT
Si if you store 1 it will be 1 T which is huge considering the display is expecting femto or pico T.

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>



On Tue, Feb 26, 2019 at 6:21 PM +0100, "Robert Oostenveld" <notifications@github.com<mailto:notifications@github.com>> wrote:


if I write a MEG channel with a square wave that is either 0 or 1, without any other scaling and specifying in the header Unit = MEG, T, I get this

[screen shot 2019-02-26 at 18 18 13]<https://user-images.githubusercontent.com/899043/53432553-024dcc80-39f3-11e9-843e-8beb3dee2410.png>

note the 1st channel, and at the bottom "MEG Levels" of 1 pP/cm. I did calibrate my screen, and this seems to be about a cm. Hence my confusion. The data (floating point values) and header suggest that this is 1 Tesla, not one pT. So should all MEG data be multiplied with 1e12?

**Comment by bcolombet** [comment]
I will have a look to the ADES code to check for an issue about MEG values when reading as soon as I’m back in Marseille
Cheers

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>



On Tue, Feb 26, 2019 at 6:21 PM +0100, "Robert Oostenveld" <notifications@github.com<mailto:notifications@github.com>> wrote:


if I write a MEG channel with a square wave that is either 0 or 1, without any other scaling and specifying in the header Unit = MEG, T, I get this

[screen shot 2019-02-26 at 18 18 13]<https://user-images.githubusercontent.com/899043/53432553-024dcc80-39f3-11e9-843e-8beb3dee2410.png>

note the 1st channel, and at the bottom "MEG Levels" of 1 pP/cm. I did calibrate my screen, and this seems to be about a cm. Hence my confusion. The data (floating point values) and header suggest that this is 1 Tesla, not one pT. So should all MEG data be multiplied with 1e12?

**Comment by bcolombet** [comment]
Also you dont have to add Unit = MEG, T
Just use channel1 = MEG

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>



On Tue, Feb 26, 2019 at 9:06 PM +0100, "COLOMBET Bruno" <bruno.colombet@univ-amu.fr<mailto:bruno.colombet@univ-amu.fr>> wrote:

I will have a look to the ADES code to check for an issue about MEG values when reading as soon as I’m back in Marseille
Cheers

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>



On Tue, Feb 26, 2019 at 6:21 PM +0100, "Robert Oostenveld" <notifications@github.com<mailto:notifications@github.com>> wrote:


if I write a MEG channel with a square wave that is either 0 or 1, without any other scaling and specifying in the header Unit = MEG, T, I get this

[screen shot 2019-02-26 at 18 18 13]<https://user-images.githubusercontent.com/899043/53432553-024dcc80-39f3-11e9-843e-8beb3dee2410.png>

note the 1st channel, and at the bottom "MEG Levels" of 1 pP/cm. I did calibrate my screen, and this seems to be about a cm. Hence my confusion. The data (floating point values) and header suggest that this is 1 Tesla, not one pT. So should all MEG data be multiplied with 1e12?

**Comment by robertoostenveld** [comment]
I have just merged #969 which includes the first implementation. There is probably room for improvement. Please have a look at the test script at https://github.com/fieldtrip/fieldtrip/blob/master/test/test_issue968.m which now contains a CTF151 section and a section with a simpler piece of simulated data. 

My experience is that scaling of SI units is needed to have the data display properly. The scaling now happens automatically in ft_write_data. It would be good if @bcolombet could check this when back in Marseille; I will leave this issue open to follow this up.

**Comment by robertoostenveld** [comment]
for reference, see also #903

**Comment by bcolombet** [comment]
I'm back at the lab and I'm currently checking the issue.
I've found an issue in the AnyWave code and fixed it.
However,  I've tried with simulated data using your test function 
        fieldtrip/test/test_issue968.m
      
and found that some values are not stored in V but still in micro V.

I've loaded the simulated.dat file in MATLAB and see:
![image](https://user-images.githubusercontent.com/5189643/53971232-c1456e80-40fc-11e9-8686-0cb2247b5706.png)

For MEG/Ref/Grad channel the values are in T and will be understood correctly.
But for EEG/SEEG/ECG values are in micro V despite the 1e-6 factor used...
And AnyWave will also apply a 1e6 factor as the units are defined as V. 

![image](https://user-images.githubusercontent.com/5189643/53971378-1aad9d80-40fd-11e9-96a3-99e14a8cc271.png)

Note also that refmag, megmag and megplanar are not recognized by AnyWave and considered as Other. So, you must adjust the View options in AnyWave to display Other channels.

Maybe you could modify the export code in FT to generate correct channel types for ADES format?

**Comment by robertoostenveld** [comment]
Could you share the matlab code to read the ADES format files in MATLAB? That will allow to check it with a round-trip, i.e. write from FT, read from FT and compare.

**Comment by bcolombet** [comment]
Hi,
I've created a gitlab repo for that purpose:  https://gitlab.thevirtualbrain.org/anywave/matlab_ades.git

**Comment by robertoostenveld** [comment]
Hi Bruno, I believe we have nailed all problems. The tutorial is now finished and Elaine has presented it at the SuSIE epilepsy conference. I will email you some details. Thanks!
