### ISSUE TITLE
Use strfind (or contains) instead of findstr

### ISSUE THREAD

**Issue by gllmflndn** [fieldtrip/fieldtrip#971]
`findstr` is not recommended in MATLAB and deprecated in Octave (a warning is now displayed in 5.1). it is used in a number of places in the FieldTrip codebase but a single replacement in `ft_hastoolbox` would already be a good start:
https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_hastoolbox.m#L586
Care has to be taken for each use case as `findstr` and `strfind` are not 100% exchangeable:
```
>> findstr('a','aba')    

ans =

     1     3

>> strfind('a','aba')

ans =

     []
```

**Comment by robertoostenveld** [comment]
I know... could you make concrete suggestions in a pull request?

**Comment by gllmflndn** [comment]
I just did for `ft_hastoolbox`; it is indeed a bit of a minefield as each call has to be checked to make sure behaviour won't change...
Interesting to see the CI running ;-)

**Comment by bmjstau** [comment]
While I agree with replacing findstr, using contains instead breaks compatibility to all Matlab versions before R2016b. An alternative would be to use  ~isempty(strfind()), as done [here](https://github.com/fieldtrip/fieldtrip/pull/744/commits/1092dac2618ce5fba3b4bc866b597eb574732cb6).

**Comment by robertoostenveld** [comment]
fieldtrip/compat/matlablt2016b contains a replacement `contains` function, which is automatically added to the path by `ft_defaults`. However, `ft_defaults` itself cannot yet rely on it.

**Comment by bmjstau** [comment]
Ah, perfect, thanks!

**Comment by robertoostenveld** [comment]
thank you for keeping an eye open on the changes to the code!
