### ISSUE TITLE
biosemi2ft: sampling frequency in dual-EEG

### ISSUE THREAD

**Issue by marzdtu** [fieldtrip/fieldtrip#974]
When using Biosemi in dual-EEG mode (i.e. using two amplifiers linked together), the amplifiers are set to a sampling rate of 2KHz. Biosemi2ft, however, recognizes, streams and saves the data (as stored in the header) as having 4 KHz, while the number of datapoints matches the 2 KHz sampling frequency of the amplifiers.

When using only one amplifier, the sampling frequency is stated correctly (i.e. at 2 KHz). Unfortunately, I cannot test what happens when using three or four amplifiers linked together.

**Comment by robertoostenveld** [comment]
it is not clear to me what needs to be done in the fieldtrip code to address this issue. I do not have access to a biosemi amplifier to test. Unless you contribute further insights here and/or code suggestions as a pull request, I cannot help you further.

best
Robert

**Comment by robertoostenveld** [comment]
Hi Marius, to follow up the interaction of last week: 

if you have insights to share, please add them to the https://github.com/fieldtrip/website/blob/master/development/realtime/biosemi.md page. Just click "edit" and send it as a pull request. 

I will close this specific issue, since I don't think that code will change.

**Comment by robertoostenveld** [comment]
mac011> mv ~/Downloads/biosemi2ft.exe bin/win64/biosemi2ft_2khz.exe 
mac011> git add bin/win64/biosemi2ft_2khz.exe 
mac011> git commit bin/win64/biosemi2ft_2khz.exe 
[master a8c3495e9] added interface for multi-EEG buisemi systems, see https://github.com/fieldtrip/website/pull/126
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 realtime/bin/win64/biosemi2ft_2khz.exe
