### ISSUE TITLE
Feature request: trialinfo as struct, not double

### ISSUE THREAD

**Issue by DanBenHa** [fieldtrip/fieldtrip#979]
Hi,

it's nice to have trial-related information in the trialinfo field. However, I think it would be useful to actually have some identifiers to the different columns in the data. This could be achieved by using a struct instead of a double matrix.

What's the dev team's stance on this idea?

Best,
Daniel

**Comment by schoffelen** [comment]
Hi Daniel, we are ahead of you in this: trialinfo can also be a table object.
Tables behave as matrices most of the time, and if purely numeric, can be used in much the same way as a matricial trialinfo. However, tables allow indeed for annotation (e.g. naming of the individual columns), and mixed representation (e.g. a mixture of textual and numeric information)

**Comment by schoffelen** [comment]
Can I therefore close this issue?

**Comment by DanBenHa** [comment]
Thanks, tables are even better ;)
Would I have to manually make trialinfo a table or is it also possible to change the trialfun of ft_definetrial to do that? Right now I just create a 3+ trl matrix which gets parsed into the trialinfo matrix.

**Comment by schoffelen** [comment]
I think not, but am not sure.
I'd convert manually once you have ran ft_preprocessing to read in and epoch the data

**Comment by DanBenHa** [comment]
OK, thanks.
