### ISSUE TITLE
eeglab2fieldtrip incomplete?

### ISSUE THREAD

**Issue by shadowfox87** [fieldtrip/fieldtrip#982]
Hello,

I'm using an EEG data structure and want to use the fieldtrip toolbox to perform the LCMV Beamformer algorithm as outlined in this tutorial: http://www.fieldtriptoolbox.org/tutorial/beamformer_lcmv/

I converted the EEG data to fieldtrip using:

`data=eeglab2fieldtrip(EEG,'preprocessing','none');`

Then, I tried to compute the covariance matrix using:

```
cfg                  = [];
cfg.covariance       = 'yes';
timelock             = ft_timelockanalysis(cfg, data);
```

Note, that in order to use ft_timelockanalysis function, the data has to be organized in a structure obtained from ft_preprocessing but that function is built for fieldtrip data and I had already sent 'preprocessing' as one of the arguments to eeglab2fieldtrip.

In any case, as soon as I call ft_timelockanalysis, I get the following error:

```
Reference to non-existent field 'dimord'.

Error in dimlength (line 74)
      elseif strcmp(data.(fld), 'rpt_pos')

Error in fixsampleinfo (line 49)
  ntrial = dimlength(data, 'rpt');

Error in ft_datatype_timelock (line 146)
      timelock = fixsampleinfo(timelock);

Error in ft_checkdata (line 270)
  data = ft_datatype_timelock(data, 'hassampleinfo', hassampleinfo);

Error in ft_timelockanalysis (line 101)
data = ft_checkdata(data, 'datatype', {'raw+comp', 'raw'}, 'feedback', 'yes', 'hassampleinfo', 'yes');
```
 
All of this works with the dataset included as part of the tutorial. I've tried to compare the structure of the two data sets and I've noticed that the data obtained from eeglab2fieldtrip is missing several fields. The data in these fields is already in the eeglab data but it wasn't added which is why the ft_timelockanalysis is failing since those fields don't exist.

**Comment by robertoostenveld** [comment]
I installed EEGLAB, loaded some data into EEGLAB to create the EEG structure, and did  

```
data = eeglab2fieldtrip(EEG,'preprocessing','none');

cfg                  = [];
cfg.covariance       = 'yes';
timelock             = ft_timelockanalysis(cfg, data);
```

I did not encounter any errors. Please check that you are using the correct version of eeglab2fieldtrip. For me it is 
```
>> which eeglab2fieldtrip
/Users/roboos/matlab/fieldtrip/external/eeglab/eeglab2fieldtrip.m
```
