### ISSUE TITLE
ft_prepare_leadfield does not check that openmeeg is in the path

### ISSUE THREAD

**Issue by pierremegevand** [fieldtrip/fieldtrip#985]
Dear Fieldtrip developers,

I just discovered a minor annoyance with FieldTrip: when calling `ft_prepare_leadfield` to compute a leadfield using OpenMEEG, the function does not check that the OpenMEEG toolbox has been added to the MATLAB path. If the function `ft_prepare_headmodel` is called earlier in the same MATLAB session, then that function adds the toolbox to the path (it's actually `ft_headmodel_openmeeg` that does it, on line 36). But `ft_prepare_leadfield` does not seem to have such a check. It might be worth adding it.

Thanks a lot,

Pierre

**Comment by robertoostenveld** [comment]
Hi @pierremegevand 

that sounds like a good suggestion. Can you propose a code change and send that as pull request? On http://www.fieldtriptoolbox.org/development/git/#tutorial you can find an explanation how to do that.

thanks
Robert

**Comment by pierremegevand** [comment]
Hi @robertoostenveld 

I've just proposed a code change (pull request #1040). Please let me know how it does.

Pierre

**Comment by schoffelen** [comment]
Thanks, PR merged.
