### ISSUE TITLE
error when initializing lf in leadfield_simbio?

### ISSUE THREAD

**Issue by pierremegevand** [fieldtrip/fieldtrip#986]
Dear FieldTrip developers,

I might have found a small error in the code for the function `leadfield_simbio`, on line 17. The code seems to initialize the variable lf and currently reads,

`lf = zeros(size(3*pos,1),size(vol.transfer,1));`

I wonder whether it should be

`lf = zeros(3*size(pos,1),size(vol.transfer,1));`

instead.

Thank you,

Pierre

**Comment by schoffelen** [comment]
I think you are right. Could you propose the fix through a PR?

**Comment by pierremegevand** [comment]
Hi @schoffelen ,

I've changed the code in pull request #1042. Please let me know if that's OK.

Pierre

**Comment by schoffelen** [comment]
Yes, I merged it. Thanks.
