### ISSUE TITLE
Correcting the CTF coordinate system for head motion

### ISSUE THREAD

**Issue by bmjstau** [fieldtrip/fieldtrip#989]
If I understand the chan- and coilori and –pos fields in the CTF header correctly, these express position and orientation in relation to the head-position measured when starting the MEG measurement. This seems to be slightly suboptimal to me: at least in my hands, subjects generally tend to move in a specific direction during the experiment, meaning that the alignment to the MRI later on will be off by a fixed amount. In addition, my subjects tend to move most during the beginning of the experiment, often even before the first trial is recorded. At least when head position is measured continuously during the experiment, I was wondering if pos and ori could not also be expressed in relation to the average head position during the analyzed trials.
 
I’ve written up a short function that does what I mean using ft_headcoordinates and ft_transform_geometry [on my GitHub](https://github.com/bmjstau/GradFixer/blob/master/fix_CTF_grad.m), which seems to move grating-induced gamma-responses into more sensible positions. Does something like this exist in FT already, and if not, should I send a pull request for a function like this and an optional call in ft_preprocessing?

(issue opened as per earlier e-mail with @robertoostenveld)

**Comment by schoffelen** [comment]
have you checked how this relates to functionality in the ft_headmovement function?

I think that one of the options in there is doing exactly what you describe.

**Comment by bmjstau** [comment]
You're completely correct - sorry, I missed that.

**Comment by schoffelen** [comment]
No worries. Keep up the good work! I hope that your implementation performs similar to mine

**Comment by robertoostenveld** [comment]
@bmjstau as you did not find this functionality, others might also not be aware of it. Could you please review the reference/help of the function and possibly documentation on the website? 

... I did a quick search on the website and only found http://www.fieldtriptoolbox.org/example/how_to_incorporate_head_movements_in_meg_analysis/ where it states "... implemented in the ft_headmovement ... not explained in further detail on this example page". If you want, please do a PR on https://github.com/fieldtrip/website.
