### ISSUE TITLE
error loading 3D scan using ft_read_headshape

### ISSUE THREAD

**Issue by xiaochenzheng** [fieldtrip/fieldtrip#992]
I was trying to read in the 3D scan for localizing electrodes (http://www.fieldtriptoolbox.org/tutorial/electrode/) and encountered the following error:

Error using refine (line 72)
invalid size of texture

Error in ft_read_headshape (line 957)
      [shape.pos, shape.tri, texture] = refine(shape.pos, shape.tri, 'banks', texture);

I had this problem with fieldtirp-20190224. With an earlier version (fieldtrip - 20170725) I had no problem.
I wonder whether something went wrong with refine.m.

Thanks in advance for fixing!

**Comment by simonhomoelle** [comment]
@xiaochenzheng Thank you for catching that. We identified the error and with an upcoming PR this should be fixed!

**Comment by robertoostenveld** [comment]
@xiaochenzheng the latest master branch should work
